#!/usr/bin/env python3
"""Generates the pinned Unicode 17 NFC tables used by L54."""

from pathlib import Path
import hashlib
import sys

EXPECTED = {
    "UnicodeData.txt": (2198209, "2e1efc1dcb59c575eedf5ccae60f95229f706ee6d031835247d843c11d96470c"),
    "CompositionExclusions.txt": (9007, "2f239196ef3b5b61db5cc476e9bd80f534d15aa1b74e1be1dea5d042a344c85f"),
    "DerivedNormalizationProps.txt": (1377582, "71fd6a206a2c0cdd41feb6b7f656aa31091db45e9cedc926985d718397f9e488"),
}


def values(items, width=16):
    lines = []
    for offset in range(0, len(items), width):
        lines.append("        " + ", ".join(str(item) for item in items[offset:offset + width]) + ",")
    return "\n".join(lines)


def main():
    if len(sys.argv) != 3:
        raise SystemExit("usage: generate-l54-unicode.py UCD_DIRECTORY OUTPUT")
    source = Path(sys.argv[1])
    output = Path(sys.argv[2])
    for name, (length, digest) in EXPECTED.items():
        data = (source / name).read_bytes()
        if len(data) != length or hashlib.sha256(data).hexdigest() != digest:
            raise SystemExit(f"Unicode authority mismatch: {name}")

    ccc = {}
    decompositions = {}
    for line in (source / "UnicodeData.txt").read_text(encoding="utf-8").splitlines():
        fields = line.split(";")
        codepoint = int(fields[0], 16)
        combining = int(fields[3])
        if combining:
            ccc[codepoint] = combining
        decomposition = fields[5]
        if decomposition and not decomposition.startswith("<"):
            decompositions[codepoint] = [int(item, 16) for item in decomposition.split()]

    exclusions = set()
    for raw in (source / "DerivedNormalizationProps.txt").read_text(encoding="utf-8").splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        field, prop = [item.strip() for item in line.split(";", 1)]
        if prop != "Full_Composition_Exclusion":
            continue
        if ".." in field:
            first, last = (int(item, 16) for item in field.split(".."))
            exclusions.update(range(first, last + 1))
        else:
            exclusions.add(int(field, 16))

    combining_data = [item for pair in sorted(ccc.items()) for item in pair]
    decomposition_index = []
    decomposition_data = []
    for codepoint, sequence in sorted(decompositions.items()):
        decomposition_index.extend((codepoint, len(decomposition_data), len(sequence)))
        decomposition_data.extend(sequence)
    composition_rows = []
    for composed, sequence in sorted(decompositions.items()):
        if composed in exclusions or len(sequence) != 2 or ccc.get(sequence[0], 0) != 0:
            continue
        composition_rows.append((sequence[0], sequence[1], composed))
    compositions = [item for row in sorted(composition_rows) for item in row]
    text = f"""// <auto-generated />
namespace HPD.Base;

internal static class BaseUnicode17NfcData
{{
    internal const string UnicodeVersion = "17.0.0";
    internal const string ReceiptChecksum = "b736a19402debe0fc09e419935d3be6077606b58996fe370cb3d53ec8f635d77";
    internal static readonly int[] CombiningClasses =
    [
{values(combining_data)}
    ];
    internal static readonly int[] DecompositionIndex =
    [
{values(decomposition_index)}
    ];
    internal static readonly int[] DecompositionData =
    [
{values(decomposition_data)}
    ];
    internal static readonly int[] Compositions =
    [
{values(compositions)}
    ];
}}
"""
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(text, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
