using System.Text;
using System.Text.Json.Nodes;

internal sealed class LspTypedGenerator(JsonObject root, string version, string commit, string hash)
{
    private const string Ns = "HPDOS.ToolHarnesses.Middleware.Protocol.Generated";
    private readonly Dictionary<string, JsonObject> _structures = root["structures"]!.AsArray().Select(x => x!.AsObject()).ToDictionary(x => x["name"]!.GetValue<string>());
    private readonly HashSet<string> _aliases = root["typeAliases"]!.AsArray().Select(x => x!["name"]!.GetValue<string>()).ToHashSet();
    private readonly HashSet<string> _enums = root["enumerations"]!.AsArray().Select(x => x!["name"]!.GetValue<string>()).ToHashSet();

    public Dictionary<string, string> Generate() => new(StringComparer.Ordinal)
    {
        ["LanguageProtocolModels.g.cs"] = Models(),
        ["LanguageProtocolDescriptors.g.cs"] = Descriptors(),
        ["LspJsonContext.g.cs"] = JsonContext()
    };

    private string Header() => $"// <auto-generated />\n// Language Server Protocol {version}; commit: {commit}\n// Meta-model SHA-256: {hash}\n#nullable enable\n\n";

    private string Models()
    {
        var b = new StringBuilder(Header()).AppendLine("using System.Text.Json;").AppendLine("using System.Text.Json.Serialization;").AppendLine().Append("namespace ").Append(Ns).AppendLine(";\n");
        b.AppendLine("public sealed partial class LspNoParams;");
        foreach (var node in root["enumerations"]!.AsArray().Select(x => x!.AsObject()).OrderBy(Name)) WriteEnum(b, node);
        foreach (var node in root["typeAliases"]!.AsArray().Select(x => x!.AsObject()).OrderBy(Name)) WriteAlias(b, node);
        foreach (var node in root["structures"]!.AsArray().Select(x => x!.AsObject()).OrderBy(Name)) WriteStructure(b, node);
        return b.ToString();
    }

    private void WriteEnum(StringBuilder b, JsonObject node)
    {
        var name = Id(Name(node)); var underlying = Type(node["type"]!.AsObject(), false);
        b.Append("[JsonConverter(typeof(").Append(name).AppendLine("JsonConverter))]").Append("public readonly partial record struct ").Append(name).Append('(').Append(underlying).AppendLine(" Value)").AppendLine("{");
        foreach (var value in node["values"]!.AsArray().Select(x => x!.AsObject()))
        {
            var raw = value["value"]!; var literal = underlying == "string" ? Quote(raw.GetValue<string>()) : raw.ToJsonString();
            var member = Id(value["name"]!.GetValue<string>()); if (member == "Value") member = "ValueKind";
            b.Append("    public static ").Append(name).Append(' ').Append(member).Append(" { get; } = new(").Append(literal).AppendLine(");");
        }
        b.Append("    public static implicit operator ").Append(name).Append('(').Append(underlying).AppendLine(" value) => new(value);")
         .Append("    public static implicit operator ").Append(underlying).Append('(').Append(name).AppendLine(" value) => value.Value;").AppendLine("}");
        b.Append("internal sealed class ").Append(name).Append("JsonConverter : JsonConverter<").Append(name).AppendLine(">").AppendLine("{")
         .Append("    public override ").Append(name).Append(" Read(ref Utf8JsonReader reader, Type type, JsonSerializerOptions options) => new(").Append(ReadExpression(underlying)).AppendLine(");")
         .Append("    public override void Write(Utf8JsonWriter writer, ").Append(name).Append(" value, JsonSerializerOptions options) => ").Append(WriteExpression(underlying)).AppendLine(";").AppendLine("}\n");
    }

    private void WriteAlias(StringBuilder b, JsonObject node)
    {
        var name = Id(Name(node));
        b.Append("[JsonConverter(typeof(").Append(name).AppendLine("JsonConverter))]").Append("public readonly partial record struct ").Append(name).AppendLine("(JsonElement Value);")
         .Append("internal sealed class ").Append(name).Append("JsonConverter : JsonConverter<").Append(name).AppendLine(">").AppendLine("{")
         .Append("    public override ").Append(name).AppendLine(" Read(ref Utf8JsonReader reader, Type type, JsonSerializerOptions options) => new(JsonElement.ParseValue(ref reader));")
         .Append("    public override void Write(Utf8JsonWriter writer, ").Append(name).AppendLine(" value, JsonSerializerOptions options) => value.Value.WriteTo(writer);").AppendLine("}\n");
    }

    private void WriteStructure(StringBuilder b, JsonObject node)
    {
        var name = Id(Name(node)); b.Append("public sealed partial class ").Append(name).AppendLine("\n{");
        foreach (var p in Flatten(name, []).Values.OrderBy(x => x["name"]!.GetValue<string>(), StringComparer.Ordinal))
        {
            var json = p["name"]!.GetValue<string>(); var optional = p["optional"]?.GetValue<bool>() == true; var type = Type(p["type"]!.AsObject(), optional);
            var property = Id(json); if (property == name) property += "Value";
            b.Append("    [JsonPropertyName(").Append(Quote(json)).AppendLine(")]").Append("    public ").Append(optional ? "" : "required ").Append(type).Append(' ').Append(property).AppendLine(" { get; init; }");
        }
        b.AppendLine("}\n");
    }

    private Dictionary<string, JsonObject> Flatten(string name, HashSet<string> seen)
    {
        if (!seen.Add(name)) return [];
        var result = new Dictionary<string, JsonObject>(StringComparer.Ordinal); var node = _structures[name];
        foreach (var group in new[] { "extends", "mixins" }) foreach (var parent in node[group]?.AsArray() ?? []) if (parent?["kind"]?.GetValue<string>() == "reference") foreach (var pair in Flatten(parent["name"]!.GetValue<string>(), seen)) result[pair.Key] = pair.Value;
        foreach (var p in node["properties"]!.AsArray().Select(x => x!.AsObject())) result[p["name"]!.GetValue<string>()] = p;
        return result;
    }

    private string Descriptors()
    {
        var b = new StringBuilder(Header()).AppendLine("using System.Text.Json;").AppendLine().Append("namespace ").Append(Ns).AppendLine(";\n")
         .AppendLine("public enum LspMessageDirection { ClientToServer, ServerToClient, Both }")
         .AppendLine("public sealed record LspRequestDescriptor<TParams, TResult>(string Method, LspMessageDirection Direction);")
         .AppendLine("public sealed record LspNotificationDescriptor<TParams>(string Method, LspMessageDirection Direction);")
         .AppendLine("public static class LanguageProtocolDescriptors\n{");
        foreach (var r in root["requests"]!.AsArray().Select(x => x!.AsObject()).OrderBy(x => x["method"]!.GetValue<string>()))
            b.Append("    public static LspRequestDescriptor<").Append(MessageType(r,"params")).Append(", ").Append(MessageType(r,"result")).Append("> ").Append(Id(r["typeName"]!.GetValue<string>())).Append(" { get; } = new(").Append(Quote(r["method"]!.GetValue<string>())).Append(", LspMessageDirection.").Append(Direction(r)).AppendLine(");");
        foreach (var n in root["notifications"]!.AsArray().Select(x => x!.AsObject()).OrderBy(x => x["method"]!.GetValue<string>()))
            b.Append("    public static LspNotificationDescriptor<").Append(MessageType(n,"params")).Append("> ").Append(Id(n["typeName"]!.GetValue<string>())).Append(" { get; } = new(").Append(Quote(n["method"]!.GetValue<string>())).Append(", LspMessageDirection.").Append(Direction(n)).AppendLine(");");
        return b.AppendLine("}").ToString();
    }

    private string JsonContext()
    {
        var types = _structures.Keys.Concat(_aliases).Concat(_enums).Select(Id).Where(x => x != "InitializeParams").Append("LspNoParams").Distinct().Order();
        var b = new StringBuilder(Header()).AppendLine("using System.Text.Json.Serialization;").AppendLine().Append("namespace ").Append(Ns).AppendLine(";\n").AppendLine("[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]");
        foreach (var type in types) b.Append("[JsonSerializable(typeof(").Append(type).AppendLine("))]");
        return b.AppendLine("public sealed partial class LspJsonContext : JsonSerializerContext;").ToString();
    }

    private string MessageType(JsonObject message, string property) => message[property] is JsonObject t ? Type(t, false) : "LspNoParams";
    private static string Direction(JsonObject m) => m["messageDirection"]!.GetValue<string>() switch { "clientToServer" => "ClientToServer", "serverToClient" => "ServerToClient", _ => "Both" };
    private string Type(JsonObject t, bool optional)
    {
        var value = t["kind"]!.GetValue<string>() switch
        {
            "base" => t["name"]!.GetValue<string>() switch { "string" or "URI" or "DocumentUri" or "RegExp" => "string", "boolean" => "bool", "integer" => "int", "uinteger" => "uint", "decimal" => "double", "null" => "JsonElement", _ => "JsonElement" },
            "reference" => Id(t["name"]!.GetValue<string>()),
            "array" => $"List<{Type(t["element"]!.AsObject(), false)}>",
            "map" => $"Dictionary<string, {Type(t["value"]!.AsObject(), false)}>",
            "stringLiteral" => "string",
            _ => "JsonElement"
        };
        return optional && value is not "string" && !value.EndsWith('>') && (value is "bool" or "int" or "uint" or "double" || _enums.Contains(value) || _aliases.Contains(value)) ? value + "?" : optional && value == "string" ? "string?" : optional && !value.EndsWith('?') ? value + "?" : value;
    }
    private static string ContextProperty(string type) => type.Replace("?", "").Replace("<", "").Replace(">", "").Replace(",", "").Replace(" ", "").Replace("string", "String").Replace("JsonElement", "JsonElement");
    private static string Name(JsonObject n) => n["name"]!.GetValue<string>();
    private static string Id(string value) { var s = new string(value.Select(c => char.IsLetterOrDigit(c) || c == '_' ? c : '_').ToArray()); if (s.Length == 0 || char.IsDigit(s[0])) s = "_" + s; return char.ToUpperInvariant(s[0]) + s[1..]; }
    private static string Quote(string value) => "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
    private static string ReadExpression(string type) => type switch { "string" => "reader.GetString() ?? throw new JsonException()", "int" => "reader.GetInt32()", "uint" => "reader.GetUInt32()", _ => "throw new JsonException()" };
    private static string WriteExpression(string type) => type switch { "string" => "writer.WriteStringValue(value.Value)", "int" => "writer.WriteNumberValue(value.Value)", "uint" => "writer.WriteNumberValue(value.Value)", _ => "throw new JsonException()" };
}
