using System.Security.Cryptography;
using System.Text;
using System.Text.Json.Nodes;

const string Commit = "8c26a839f86296448692b414cb35c0a8fbabe0e5";
const string Hash = "caae8df639a4248520a3f589fd72945365e9d8ebca5baf564161a515430d9d41";
var schema = ""; var output = ""; var verify = false;
for (var i = 0; i < args.Length; i++)
    switch (args[i]) { case "--schema": schema = args[++i]; break; case "--output": output = args[++i]; break; case "--verify": verify = true; break; default: throw new ArgumentException($"Unknown argument '{args[i]}'."); }
if (schema.Length == 0) schema = Path.Combine(AppContext.BaseDirectory, "Schema", "metaModel.json");
if (output.Length == 0) throw new ArgumentException("Required option --output <directory> was not supplied.");
var bytes = File.ReadAllBytes(schema);
var actual = Convert.ToHexString(SHA256.HashData(bytes)).ToLowerInvariant();
if (actual != Hash) throw new InvalidOperationException($"Pinned LSP meta-model checksum mismatch. Expected {Hash}, got {actual}.");
var root = JsonNode.Parse(bytes)!.AsObject();
var version = root["metaData"]!["version"]!.GetValue<string>();
var typed = new LspTypedGenerator(root, version, Commit, Hash).Generate();
var messages = root["requests"]!.AsArray().Concat(root["notifications"]!.AsArray())
    .Select(x => x!.AsObject()).OrderBy(x => x["method"]!.GetValue<string>(), StringComparer.Ordinal).ToArray();
string Header() => $"// <auto-generated />\n// Language Server Protocol {version}; commit: {Commit}\n// Meta-model SHA-256: {Hash}\n#nullable enable\n\n";
var inventory = new StringBuilder(Header()).AppendLine("namespace HPDOS.ToolHarnesses.Middleware.Protocol.Generated;\n")
    .AppendLine("public enum LspMessageKind { Request, Notification }")
    .AppendLine("public sealed record LspFeature(string Method, string TypeName, LspMessageKind Kind, string Direction, string? ClientCapability, string? ServerCapability);")
    .AppendLine("public static class LanguageProtocolFeatureInventory\n{\n    public static IReadOnlyList<LspFeature> All { get; } =\n    [");
foreach (var m in messages) inventory.Append("        new(").Append(Q(m, "method")).Append(", ").Append(Q(m, "typeName")).Append(", LspMessageKind.")
    .Append(root["requests"]!.AsArray().Any(x => ReferenceEquals(x, m)) ? "Request" : "Notification").Append(", ").Append(Q(m, "messageDirection")).Append(", ")
    .Append(Q(m, "clientCapability", true)).Append(", ").Append(Q(m, "serverCapability", true)).AppendLine("),");
inventory.AppendLine("    ];\n}");
var source = Header() + $"namespace HPDOS.ToolHarnesses.Middleware.Protocol.Generated;\n\npublic static class LanguageProtocolSource\n{{\n    public const string Repository = \"https://github.com/microsoft/language-server-protocol\";\n    public const string Commit = \"{Commit}\";\n    public const string Version = \"{version}\";\n    public const string MetaModelSha256 = \"{Hash}\";\n    public const int RequestCount = {root["requests"]!.AsArray().Count};\n    public const int NotificationCount = {root["notifications"]!.AsArray().Count};\n    public const int StructureCount = {root["structures"]!.AsArray().Count};\n}}\n";
var matrix = new StringBuilder("# Generated LSP feature matrix\n\nGenerated from the pinned canonical meta-model. Presence does not advertise or implement a feature.\n\n| Method | Kind | Direction | Client capability | Server capability | Runtime status |\n|---|---|---|---|---|---|\n");
foreach (var m in messages) matrix.Append("| `").Append(m["method"]!.GetValue<string>()).Append("` | ").Append(root["requests"]!.AsArray().Any(x => ReferenceEquals(x, m)) ? "request" : "notification").Append(" | ").Append(V(m,"messageDirection")).Append(" | ").Append(V(m,"clientCapability")).Append(" | ").Append(V(m,"serverCapability")).AppendLine(" | generated; runtime policy decides | ");
var outputs = new Dictionary<string,string>(typed, StringComparer.Ordinal) { ["LanguageProtocolFeatureInventory.g.cs"] = inventory.ToString(), ["LanguageProtocolSource.g.cs"] = source, ["LanguageProtocolFeatureMatrix.g.md"] = matrix.ToString() };
Directory.CreateDirectory(output);
foreach (var pair in outputs) { var path = Path.Combine(output, pair.Key); if (verify) { if (!File.Exists(path) || File.ReadAllText(path) != pair.Value) throw new InvalidOperationException($"Generated LSP output is stale: {pair.Key}"); } else File.WriteAllText(path, pair.Value, new UTF8Encoding(false)); }
Console.WriteLine($"{(verify ? "Verified" : "Generated")} {outputs.Count} LSP files from {actual}.");
static string V(JsonObject value, string name) => value[name]?.GetValue<string>() ?? "—";
static string Q(JsonObject value, string name, bool nullable = false) => value[name] is null && nullable ? "null" : "\"" + (value[name]?.GetValue<string>() ?? "").Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
