using System.Text.Json;
using System.Text.Json.Serialization;
using HPD.Agent;
using HPD.Agent.Audio;
using HPD.Agent.Audio.Output;
using HPD.Agent.Audio.Policies;
using HPD.Agent.ClientTools;
using HPD.Agent.Middleware;
using HPD.Agent.Planning;
using HPD.Agent.Providers;
using System.Collections.Immutable;
using Microsoft.Extensions.AI;

/// <summary>
/// JSON serialization context for HPD-Agent core types (AOT-compatible).
/// Does not include FFI-specific types - see HPDFFIJsonContext in HPD-Agent.FFI project.
/// </summary>
[JsonSourceGenerationOptions(
    WriteIndented = true, 
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    UnmappedMemberHandling = JsonUnmappedMemberHandling.Disallow
)]
// --- Framework-specific types ---
[JsonSerializable(typeof(ValidationErrorResponse))]
[JsonSerializable(typeof(ValidationError))]
[JsonSerializable(typeof(List<ValidationError>))]

// --- Common primitive and collection types for AI function return values ---
[JsonSerializable(typeof(string))]
[JsonSerializable(typeof(int))]
[JsonSerializable(typeof(long))]
[JsonSerializable(typeof(double))]
[JsonSerializable(typeof(float))]
[JsonSerializable(typeof(bool))]
[JsonSerializable(typeof(decimal))]
[JsonSerializable(typeof(Guid))]
[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(DateTimeOffset))]
[JsonSerializable(typeof(object))]
[JsonSerializable(typeof(JsonElement))]
[JsonSerializable(typeof(Dictionary<string, object>))]
[JsonSerializable(typeof(Dictionary<string, object?>))]
[JsonSerializable(typeof(Dictionary<string, JsonElement>))]
[JsonSerializable(typeof(Dictionary<string, string>))]
[JsonSerializable(typeof(IDictionary<string, object>))]
[JsonSerializable(typeof(IDictionary<string, object?>))]
[JsonSerializable(typeof(List<string>))]
[JsonSerializable(typeof(List<int>))]
[JsonSerializable(typeof(List<double>))]
[JsonSerializable(typeof(List<object>))]
[JsonSerializable(typeof(IReadOnlyList<string>))]

// --- JSON Node types for AOT compatibility ---
[JsonSerializable(typeof(System.Text.Json.Nodes.JsonNode))]
[JsonSerializable(typeof(System.Text.Json.Nodes.JsonObject))]
[JsonSerializable(typeof(System.Text.Json.Nodes.JsonArray))]
[JsonSerializable(typeof(System.Text.Json.Nodes.JsonValue))]

// --- Agent configuration types ---
[JsonSerializable(typeof(StoredAgent))]
[JsonSerializable(typeof(AgentConfig))]
[JsonSerializable(typeof(AgentMessageSource))]
[JsonSerializable(typeof(AgentMessageVisibility))]
[JsonSerializable(typeof(AgentMessagePersistence))]
[JsonSerializable(typeof(AudioConfig))]
[JsonSerializable(typeof(AudioInputMode))]
[JsonSerializable(typeof(AudioOutputMode))]
[JsonSerializable(typeof(AudioPolicySet))]
[JsonSerializable(typeof(InputMediaPolicy))]
[JsonSerializable(typeof(InputMediaHandlingMode))]
[JsonSerializable(typeof(InputMediaDisposition))]
[JsonSerializable(typeof(TraceCapturePolicy))]
[JsonSerializable(typeof(PrivacyPolicy))]
[JsonSerializable(typeof(ThreadProjectionPolicy))]
[JsonSerializable(typeof(AssistantOutputSynthesisMode))]
[JsonSerializable(typeof(AssistantAudioArtifactCapturePolicy))]
[JsonSerializable(typeof(TextToSpeechPacingOptions))]
[JsonSerializable(typeof(TextToSpeechFirstSegmentOptions))]
[JsonSerializable(typeof(TextToSpeechContinuationOptions))]
[JsonSerializable(typeof(TextToSpeechBoundaryOptions))]
[JsonSerializable(typeof(TextToSpeechFilteringOptions))]
[JsonSerializable(typeof(TextToSpeechPacingMode))]
[JsonSerializable(typeof(TextToSpeechEmojiPolicy))]
[JsonSerializable(typeof(ProgressiveTextToSpeechRouteMode))]
[JsonSerializable(typeof(PushTextInputAggregationMode))]
[JsonSerializable(typeof(AgentClientsConfig))]
[JsonSerializable(typeof(AgentProviderBackendProfile))]
[JsonSerializable(typeof(AgentProviderFamilyDefault))]
[JsonSerializable(typeof(ProviderReference))]
[JsonSerializable(typeof(ProviderAuthentication))]
[JsonSerializable(typeof(ApiKeyProviderAuthentication))]
[JsonSerializable(typeof(OAuthProviderAuthentication))]
[JsonSerializable(typeof(ExternalIdentityProviderAuthentication))]
[JsonSerializable(typeof(AnonymousProviderAuthentication))]
[JsonSerializable(typeof(ProviderAuthorizationChallenge))]
[JsonSerializable(typeof(BrowserAuthorizationChallenge))]
[JsonSerializable(typeof(DeviceAuthorizationChallenge))]
[JsonSerializable(typeof(ProviderAuthorizationResponse))]
[JsonSerializable(typeof(BrowserAuthorizationResponse))]
[JsonSerializable(typeof(DeviceAuthorizationPresentationResponse))]
[JsonSerializable(typeof(ProviderDeviceAuthorizationStatus))]
[JsonSerializable(typeof(ProviderAuthorizationStatus))]
[JsonSerializable(typeof(ProviderDisconnectResult))]
[JsonSerializable(typeof(ProviderRevocationResult))]
[JsonSerializable(typeof(ProviderClientConfig))]
[JsonSerializable(typeof(string))]
[JsonSerializable(typeof(CollapsingConfig))]
[JsonSerializable(typeof(CollapsingRunPolicy))]
[JsonSerializable(typeof(ContainerRecoveryHistoryMode))]
[JsonSerializable(typeof(HPD.Agent.ReasoningOptions))]
[JsonSerializable(typeof(HPD.Agent.ReasoningEffort))]
[JsonSerializable(typeof(HPD.Agent.ReasoningOutput))]

// --- ToolHarness and Middleware reference types (Config Serialization) ---
[JsonSerializable(typeof(ToolHarnessReference))]
[JsonSerializable(typeof(List<ToolHarnessReference>))]
[JsonSerializable(typeof(MiddlewareReference))]
[JsonSerializable(typeof(List<MiddlewareReference>))]

// --- Per-invocation run options (AgentRunConfig) ---
[JsonSerializable(typeof(AgentRunConfig))]
[JsonSerializable(typeof(AgentSecurityRunConfig))]
[JsonSerializable(typeof(AgentSandboxRunConfig))]
[JsonSerializable(typeof(AgentApprovalPolicy))]
[JsonSerializable(typeof(AgentSandboxPolicy))]
[JsonSerializable(typeof(AgentSandboxEscapePolicy))]
[JsonSerializable(typeof(HPD.Agent.Security.AgentSandboxConfiguration))]
[JsonSerializable(typeof(HPD.Agent.Security.AgentSandboxPathGrant))]
[JsonSerializable(typeof(HPD.Agent.Security.AgentSandboxPathAccess))]
[JsonSerializable(typeof(ThreadHistoryCompactionCheckpointEvent))]
[JsonSerializable(typeof(CompactionPointDescriptor))]
[JsonSerializable(typeof(CompactionPreservationDescriptor))]
[JsonSerializable(typeof(CompactionStrategyDescriptor))]
[JsonSerializable(typeof(CompactionRunPolicy))]
[JsonSerializable(typeof(ThreadContextUsage))]
[JsonSerializable(typeof(AudioRunConfig))]
[JsonSerializable(typeof(ChatClientConfig))]
[JsonSerializable(typeof(RealtimeClientConfig))]
[JsonSerializable(typeof(ImageGenerationClientConfig))]
[JsonSerializable(typeof(EmbeddingsClientConfig))]
[JsonSerializable(typeof(TextToSpeechClientConfig))]
[JsonSerializable(typeof(SpeechToTextClientConfig))]
[JsonSerializable(typeof(HostedFilesClientConfig))]
[JsonSerializable(typeof(VoiceActivityClientConfig))]
[JsonSerializable(typeof(EndOfTurnClientConfig))]
[JsonSerializable(typeof(RealtimeAudioFormatRunConfig))]
[JsonSerializable(typeof(RealtimeTranscriptionRunConfig))]
[JsonSerializable(typeof(Dictionary<string, bool>))]  // For PermissionOverrides

// --- HPD-Agent Typed Content Classes (Phase 1 - Typed Content) ---
[JsonSerializable(typeof(HPD.Agent.ImageContent))]
[JsonSerializable(typeof(HPD.Agent.AudioContent))]
[JsonSerializable(typeof(HPD.Agent.VideoContent))]
[JsonSerializable(typeof(HPD.Agent.DocumentContent))]
[JsonSerializable(typeof(LocalContentMetadata))]

// --- Conversation storage and serialization types ---
[JsonSerializable(typeof(BatchPermissionStateData))]
[JsonSerializable(typeof(CircuitBreakerStateData))]
[JsonSerializable(typeof(ContinuationPermissionStateData))]
[JsonSerializable(typeof(ErrorTrackingStateData))]
[JsonSerializable(typeof(ChatMessage), TypeInfoPropertyName = "MicrosoftExtensionsAIChatMessage")]
[JsonSerializable(typeof(IReadOnlyList<ChatMessage>), TypeInfoPropertyName = "IReadOnlyListMicrosoftExtensionsAIChatMessage")]
[JsonSerializable(typeof(CompactionTrigger))]
[JsonSerializable(typeof(TurnCountCompactionTrigger))]
[JsonSerializable(typeof(InputTokenCompactionTrigger))]
[JsonSerializable(typeof(ContextPercentageCompactionTrigger))]
[JsonSerializable(typeof(CompactionPoint))]
[JsonSerializable(typeof(CompactAtCurrentHead))]
[JsonSerializable(typeof(CompactAtMessage))]
[JsonSerializable(typeof(CompactAtTurn))]
[JsonSerializable(typeof(CompactionPreservation))]
[JsonSerializable(typeof(PreserveNoPreviousHistory))]
[JsonSerializable(typeof(PreservePreviousTurns))]
[JsonSerializable(typeof(PreservePreviousUserMessages))]
[JsonSerializable(typeof(PreviousHistoryLimit))]
[JsonSerializable(typeof(PreviousItemCountLimit))]
[JsonSerializable(typeof(PreviousTokenBudgetLimit))]
[JsonSerializable(typeof(CompactionStrategy))]
[JsonSerializable(typeof(RemovalCompaction))]
[JsonSerializable(typeof(SummarizingCompaction))]
[JsonSerializable(typeof(CompactionSpecification))]
[JsonSerializable(typeof(AutomaticCompactionPolicy))]
[JsonSerializable(typeof(ThreadForkCompaction))]
[JsonSerializable(typeof(InheritThreadForkCompaction))]
[JsonSerializable(typeof(DisableThreadForkCompaction))]
[JsonSerializable(typeof(ApplyThreadForkCompaction))]
[JsonSerializable(typeof(ThreadJournalCursor))]
[JsonSerializable(typeof(ThreadJournalReplaceResult))]
[JsonSerializable(typeof(PermissionPersistentStateData))]
[JsonSerializable(typeof(TotalErrorThresholdStateData))]
[JsonSerializable(typeof(PlanModePersistentStateData))]
[JsonSerializable(typeof(AgentPlanData))]
[JsonSerializable(typeof(PlanStepData))]
[JsonSerializable(typeof(ClientToolStateData))]
[JsonSerializable(typeof(ContainerMiddlewareState))]
[JsonSerializable(typeof(ContainerInstructionSet))]
[JsonSerializable(typeof(RecoveryInfo))]
[JsonSerializable(typeof(ImmutableHashSet<string>))]
[JsonSerializable(typeof(ImmutableDictionary<string, clientToolHarnessDefinition>), TypeInfoPropertyName = "ImmutableDictionaryStringClientToolHarnessDefinition")]
[JsonSerializable(typeof(ImmutableDictionary<string, ClientToolProviderToolBinding>), TypeInfoPropertyName = "ImmutableDictionaryStringClientToolProviderToolBinding")]
[JsonSerializable(typeof(ImmutableDictionary<string, ContextItem>), TypeInfoPropertyName = "ImmutableDictionaryStringContextItem")]
[JsonSerializable(typeof(ImmutableDictionary<string, ContainerInstructionSet>), TypeInfoPropertyName = "ImmutableDictionaryStringContainerInstructionSet")]
[JsonSerializable(typeof(ImmutableDictionary<string, RecoveryInfo>), TypeInfoPropertyName = "ImmutableDictionaryStringRecoveryInfo")]

// --- Client Tools types ---
[JsonSerializable(typeof(HPD.Agent.ClientTools.clientToolHarnessDefinition))]
[JsonSerializable(typeof(HPD.Agent.ClientTools.clientToolHarnessDefinition[]))]
[JsonSerializable(typeof(HPD.Agent.ClientTools.ClientToolDefinition))]
[JsonSerializable(typeof(HPD.Agent.ClientTools.ClientToolDefinition[]))]
[JsonSerializable(typeof(HPD.Agent.ClientTools.IToolResultContent))]
[JsonSerializable(typeof(IReadOnlyList<HPD.Agent.ClientTools.IToolResultContent>))]
[JsonSerializable(typeof(List<HPD.Agent.ClientTools.IToolResultContent>))]
[JsonSerializable(typeof(HPD.Agent.ClientTools.TextContent), TypeInfoPropertyName = "ClientToolsTextContent")]
[JsonSerializable(typeof(HPD.Agent.ClientTools.BinaryContent))]
[JsonSerializable(typeof(HPD.Agent.ClientTools.JsonContent))]
[JsonSerializable(typeof(HPD.Agent.ClientTools.ClientToolInvokeOutcomeKind))]
[JsonSerializable(typeof(HPD.Agent.ClientTools.ClientToolInvokeRequestEvent))]
[JsonSerializable(typeof(HPD.Agent.ClientTools.ClientToolInvokeOutcomeEvent))]
[JsonSerializable(typeof(HPD.Agent.ClientTools.ClientToolOperationOutcomeState))]
[JsonSerializable(typeof(HPD.Agent.ClientTools.ClientToolOperationOutcomeEvent))]
[JsonSerializable(typeof(HPD.Agent.ClientTools.ClientSkillDefinition))]
[JsonSerializable(typeof(HPD.Agent.ClientTools.ClientSkillDefinition[]))]
[JsonSerializable(typeof(HPD.Agent.ClientTools.ClientSkillReference))]
[JsonSerializable(typeof(HPD.Agent.ClientTools.ClientSkillReference[]))]
[JsonSerializable(typeof(HPD.Agent.ClientTools.ContextItem))]
[JsonSerializable(typeof(HPD.Agent.ClientTools.ContextItem[]))]
[JsonSerializable(typeof(HPD.Agent.ClientTools.AgentClientInput))]
[JsonSerializable(typeof(HPD.Agent.ClientTools.ClientAppProviderReference))]
[JsonSerializable(typeof(HPD.Agent.ClientTools.ClientAppProviderReference[]))]
[JsonSerializable(typeof(List<HPD.Agent.ClientTools.ClientAppProviderReference>))]
[JsonSerializable(typeof(HPD.Agent.ClientTools.ClientProviderSelector))]
[JsonSerializable(typeof(HPD.Agent.ClientTools.ClientToolHarnessSelector))]
[JsonSerializable(typeof(IReadOnlyList<HPD.Agent.ClientTools.ClientToolHarnessSelector>))]
[JsonSerializable(typeof(HPD.Agent.ClientTools.ClientAppProviderBindingPolicy))]
[JsonSerializable(typeof(HPD.Agent.ClientTools.ClientAppProviderDescriptor))]
[JsonSerializable(typeof(HPD.Agent.ClientTools.ClientToolProviderIdentity))]
[JsonSerializable(typeof(HPD.Agent.ClientTools.ClientToolProviderRuntimeIdentity))]
[JsonSerializable(typeof(HPD.Agent.ClientTools.ClientToolProviderContext))]
[JsonSerializable(typeof(HPD.Agent.ClientTools.ClientToolProviderReadiness))]
[JsonSerializable(typeof(HPD.Agent.ClientTools.ClientToolProviderConnectionState))]
[JsonSerializable(typeof(HPD.Agent.ClientTools.ClientToolProviderBindingLeaseStatus))]
[JsonSerializable(typeof(HPD.Agent.ClientTools.ClientToolProviderManifest))]
[JsonSerializable(typeof(HPD.Agent.ClientTools.ClientToolProviderSnapshot))]
[JsonSerializable(typeof(HPD.Agent.ClientTools.ClientToolProviderConnectionRegistration))]
[JsonSerializable(typeof(HPD.Agent.ClientTools.ClientToolProviderBindingScope))]
[JsonSerializable(typeof(HPD.Agent.ClientTools.ClientToolProviderBindingLease))]
[JsonSerializable(typeof(HPD.Agent.ClientTools.ClientToolProviderBindingResult))]
[JsonSerializable(typeof(HPD.Agent.ClientTools.ClientToolProviderQuery))]
[JsonSerializable(typeof(HPD.Agent.ClientTools.ClientToolProviderHelloMessage))]
[JsonSerializable(typeof(HPD.Agent.ClientTools.ClientToolProviderWelcomeMessage))]
[JsonSerializable(typeof(HPD.Agent.ClientTools.ClientToolProviderManifestMessage))]
[JsonSerializable(typeof(HPD.Agent.ClientTools.ClientToolProviderHeartbeatMessage))]
[JsonSerializable(typeof(HPD.Agent.ClientTools.ClientToolProviderReleaseMessage))]
[JsonSerializable(typeof(HPD.Agent.ClientTools.ClientToolProviderErrorMessage))]
[JsonSerializable(typeof(HPD.Agent.ClientTools.ClientToolProviderInvokeToolMessage))]
[JsonSerializable(typeof(HPD.Agent.ClientTools.ClientToolProviderInvokeOutcomeMessage))]
[JsonSerializable(typeof(HPD.Agent.ClientTools.ClientToolProviderOperationOutcomeMessage))]
[JsonSerializable(typeof(HPD.Agent.ClientTools.ClientToolError))]
[JsonSerializable(typeof(HPD.Agent.ClientTools.ClientToolProviderToolBinding))]
[JsonSerializable(typeof(HPD.Agent.ClientTools.ClientToolProviderInvocationRequest))]
[JsonSerializable(typeof(HPD.Agent.ClientTools.ClientToolProviderOperationDescriptor))]

// --- Background Responses types ---
[JsonSerializable(typeof(BackgroundResponsesConfig))]
[JsonSerializable(typeof(ThreadExecutionStartedEvent))]
[JsonSerializable(typeof(AgentRequestTerminatedEvent))]
[JsonSerializable(typeof(ThreadExecutionFinishedEvent))]
[JsonSerializable(typeof(ThreadExecutionError))]
[JsonSerializable(typeof(AgentInputResult))]
[JsonSerializable(typeof(AgentInputResult.Completed))]
[JsonSerializable(typeof(AgentInputResult.Steered))]
[JsonSerializable(typeof(AgentInputResult.Control))]
[JsonSerializable(typeof(AgentInputResult.AudioSession))]
[JsonSerializable(typeof(AudioSessionInputResult))]
[JsonSerializable(typeof(SubAgentInvocationStartedEvent))]
[JsonSerializable(typeof(SubAgentInvocationCompletedEvent))]
[JsonSerializable(typeof(SubAgentInvocationFailedEvent))]
[JsonSerializable(typeof(SubAgentInvocationCancelledEvent))]
[JsonSerializable(typeof(FunctionInvocationSnapshot))]
[JsonSerializable(typeof(ToolInvocationInfo))]

// --- Unified agent operations ---
[JsonSerializable(typeof(AgentOperationReceipt))]
[JsonSerializable(typeof(AgentOperationSnapshot))]
[JsonSerializable(typeof(AgentOperationTransition))]
[JsonSerializable(typeof(AgentOperationTransitionResult))]
[JsonSerializable(typeof(AgentOperationSourceKind))]
[JsonSerializable(typeof(AgentOperationProviderStatus))]
[JsonSerializable(typeof(AgentOperationObservationStatus))]
[JsonSerializable(typeof(AgentOperationKind))]
[JsonSerializable(typeof(AgentOperationCapabilities))]
[JsonSerializable(typeof(AgentExecutionAddress))]
[JsonSerializable(typeof(AgentOperationControl))]
[JsonSerializable(typeof(AgentOperationNotificationPolicy))]
[JsonSerializable(typeof(AgentOperationCompletion))]
[JsonSerializable(typeof(AgentOperationFailure))]
[JsonSerializable(typeof(AgentOperationRecoveryReference))]
[JsonSerializable(typeof(AgentOperationRegisteredEvent))]
[JsonSerializable(typeof(AgentOperationTransitionedEvent))]
[JsonSerializable(typeof(AgentOperationNotificationInputEvent))]
[JsonSerializable(typeof(AgentOperationNotification))]
[JsonSerializable(typeof(AgentOperationNotificationQueuedEvent))]
[JsonSerializable(typeof(AgentOperationNotificationDeliveredEvent))]
[JsonSerializable(typeof(AgentOperationNotificationSuppressedEvent))]
[JsonSerializable(typeof(AgentOperationRetentionPolicy))]
[JsonSerializable(typeof(AgentOperationTombstone))]
[JsonSerializable(typeof(AgentOperationTombstonedEvent))]
[JsonSerializable(typeof(AgentOperationTombstoneEvictedEvent))]
[JsonSerializable(typeof(AgentCapabilityRefreshStartedEvent))]
[JsonSerializable(typeof(AgentCapabilityRefreshPublishedEvent))]
[JsonSerializable(typeof(AgentCapabilityRefreshRejectedEvent))]
[JsonSerializable(typeof(AgentTurnCapabilitiesPinnedEvent))]
[JsonSerializable(typeof(AgentTurnCapabilityIdentity))]
[JsonSerializable(typeof(AgentCapabilitySourceRevision))]
[JsonSerializable(typeof(IReadOnlyList<AgentCapabilitySourceRevision>))]
[JsonSerializable(typeof(AgentCapabilityRefreshResult))]
[JsonSerializable(typeof(AgentShutdownOptions))]
[JsonSerializable(typeof(AgentRemoteOperationShutdownPolicy))]
[JsonSerializable(typeof(AgentLeaseLeakPolicy))]
[JsonSerializable(typeof(List<AgentOperationReceipt>))]

// --- Internal storage state types (nested classes) ---
// Note: Nested classes need full type paths for AOT
// These are internal implementation details but need serialization support

// --- Additional utility types for generic serialization ---
[JsonSerializable(typeof(object[]))]  // For dynamic object arrays in logging
[JsonSerializable(typeof(string[]))]  // For toolharness parameters that accept string arrays (e.g. glob patterns)

public partial class HPDJsonContext : JsonSerializerContext
{
}
