<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsAotCompatible>true</IsAotCompatible>
    <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
    <EnableSingleFileAnalyzer>true</EnableSingleFileAnalyzer>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\HPD-RealtimeMedia\src\HPD.Audio.WebRTC\HPD-Audio.WebRTC.csproj" />
    <ProjectReference Include="..\..\..\src\HPD-RealtimeMedia\src\HPD.Media.Rtcp.Feedback\HPD-Media.Rtcp.Feedback.csproj" />
    <ProjectReference Include="..\..\..\src\HPD-RealtimeMedia\src\HPD.Media.Rtcp\HPD-Media.Rtcp.csproj" />
    <ProjectReference Include="..\..\..\src\HPD-RealtimeMedia\src\HPD.Media.Rtp.Audio.Sdp\HPD-Media.Rtp.Audio.Sdp.csproj" />
    <ProjectReference Include="..\..\..\src\HPD-RealtimeMedia\src\HPD.Media.Rtp\HPD-Media.Rtp.csproj" />
    <ProjectReference Include="..\..\..\src\HPD-RealtimeMedia\src\HPD.Media.Sdp\HPD-Media.Sdp.csproj" />
    <ProjectReference Include="..\..\..\src\HPD-RealtimeMedia\src\HPD.Media.Srtp\HPD-Media.Srtp.csproj" />
    <ProjectReference Include="..\..\..\src\HPD-RealtimeMedia\src\HPD.Media.WebRTC\HPD-Media.WebRTC.csproj" />
  </ItemGroup>

</Project>
