<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><PublishAot>true</PublishAot><PublishTrimmed>true</PublishTrimmed></PropertyGroup>
  <ItemGroup><ProjectReference Include="../../src/HPD.Payments.Serialization/HPD.Payments.Serialization.csproj" /></ItemGroup>
</Project>
