import type { GatewayClientOperation, GatewaySchemaConstraint, GenerationPlan, JsonValue } from "./types.js";

const bannerPrefix = "// Generated by @hpd/gateway-client-generator 0.1.0. DO NOT EDIT.";
const referencePrefix = "#/components/schemas/";

export function render(plan: GenerationPlan): Readonly<Record<string, string>> {
  const names = schemaNames(plan.schemas);
  const banner = `${bannerPrefix}\n// source-sha256: ${plan.sourceSha256}\n// output-plan-sha256: ${plan.outputPlanSha256}\n\n`;
  return {
    "contract.ts": banner + renderContract(plan),
    "schemas.ts": banner + renderSchemas(plan, names),
    "operations.ts": banner + renderOperations(plan, names),
    "result.ts": banner + resultContract,
    "index.ts": banner + `export * from "./contract.js";\nexport * from "./schemas.js";\nexport * from "./operations.js";\nexport * from "./result.js";\n`,
    "snapshot.json": JSON.stringify({
      generatorVersion: "0.1.0",
      sourceSha256: plan.sourceSha256,
      openApiSha256: plan.openApiSha256,
      manifestSha256: plan.manifestSha256,
      outputPlanSha256: plan.outputPlanSha256,
    }, null, 2) + "\n",
  };
}

function renderContract(plan: GenerationPlan): string {
  const value = JSON.stringify(plan.operations, null, 2);
  return `export const gatewayOperations = ${value} as const;\n\nexport type GatewayOperationName = keyof typeof gatewayOperationsByName;\nexport const gatewayOperationsByName = Object.freeze(Object.fromEntries(gatewayOperations.map(value => [value.operation, value]))) as Readonly<Record<(typeof gatewayOperations)[number]["operation"], (typeof gatewayOperations)[number]>>;\n`;
}

function renderSchemas(plan: GenerationPlan, names: ReadonlyMap<string, string>): string {
  const brands = ["NamespaceId", "TargetNodeId", "RevisionId", "ValidationId", "OperationId", "CandidateId", "ContinuationToken", "DesiredStateToken", "IdempotencyKey", "CorrelationId"];
  let output = `declare const gatewayBrand: unique symbol;\nexport type GatewayBrand<T extends string> = string & { readonly [gatewayBrand]: T };\n`;
  for (const brand of brands) output += `export type Gateway${brand} = GatewayBrand<"${kebabBrand(brand)}">;\n`;
  output += `export type GatewayDesiredPrecondition = { readonly kind: "create-only" } | { readonly kind: "replace"; readonly token: GatewayDesiredStateToken };\n`;
  output += "\n";
  for (const [key, schema] of Object.entries(plan.schemas).sort(([a], [b]) => ordinal(a, b)))
    output += `export type ${names.get(key)!} = ${schemaType(schema, plan, names, `#/components/schemas/${key}`, new Set())};\n\n`;
  return output;
}

function renderOperations(plan: GenerationPlan, names: ReadonlyMap<string, string>): string {
  let output = `import type * as S from "./schemas.js";\nimport type { GatewayOperationResult } from "./result.js";\n\n`;
  for (const operation of plan.operations) {
    const name = pascal(operation.operation);
    const path = fields(operation, "path", names);
    const query = fields(operation, "query", names);
    const headers = fields(operation, "header", names);
    const body = operation.requestBody.schemaRef === null ? "" :
      `\n  readonly body${operation.requestBody.presence === "required" ? "" : "?"}: S.${refName(operation.requestBody.schemaRef, names)};`;
    output += `export interface ${name}Input {\n  readonly path: ${path};${query}${headers}${body}\n}\n`;
    const errors = operation.documentedErrors.join(" | ");
    output += `export type ${name}Result = GatewayOperationResult<S.${refName(operation.success.schemaRef, names)}, ${operation.success.status}, ${errors}>;\n\n`;
  }
  output += `export interface GatewayOperationTypes {\n`;
  for (const operation of plan.operations) output += `  readonly "${operation.operation}": { readonly input: ${pascal(operation.operation)}Input; readonly result: ${pascal(operation.operation)}Result };\n`;
  return output + `}\n`;
}

function fields(operation: GatewayClientOperation, location: "path" | "query" | "header", names: ReadonlyMap<string, string>): string {
  const values = operation.parameterConstraints.filter(value => value.location === location);
  if (values.length === 0) return location === "path" ? "Readonly<Record<never, never>>" : "";
  const members = values.map(value => `readonly ${propertyName(value.name)}${value.required || value.name === "If-Match" ? "" : "?"}: ${value.name === "If-Match" ? "S.GatewayDesiredPrecondition" : brandType(value.brand)}`).join("; ");
  const optional = values.some(value => value.required || value.name === "If-Match") ? "" : "?";
  return location === "path" ? `{ ${members} }` : `\n  readonly ${location === "header" ? "headers" : "query"}${optional}: { ${members} };`;
}

function schemaType(value: JsonValue, plan: GenerationPlan, names: ReadonlyMap<string, string>, schemaRef: string, visiting: Set<string>): string {
  const schema = asRecord(value);
  if (typeof schema.$ref === "string") {
    if (visiting.has(schema.$ref)) throw new Error(`Cyclic schema reference '${schema.$ref}'.`);
    return refName(schema.$ref, names);
  }
  const nullable = Array.isArray(schema.type) && schema.type.includes("null");
  const type = Array.isArray(schema.type) ? schema.type.find(value => value !== "null") : schema.type;
  let result: string;
  if (Array.isArray(schema.enum)) result = schema.enum.map(value => JSON.stringify(value)).join(" | ");
  else if (schema.const !== undefined) result = JSON.stringify(schema.const);
  else if (Array.isArray(schema.oneOf)) result = schema.oneOf.map(branch => schemaType(branch, plan, names, schemaRef, visiting)).join(" | ");
  else if (type === "string") result = constraintBrand(plan.schemaConstraints, schemaRef) ?? "string";
  else if (type === "integer" || type === "number") result = "number";
  else if (type === "boolean") result = "boolean";
  else if (type === "array") result = `readonly ${schemaType(schema.items!, plan, names, schemaRef, visiting)}[]`;
  else if (type === "object" || schema.properties !== undefined) result = objectType(schema, plan, names, schemaRef, visiting);
  else result = "unknown";
  return nullable ? `${result} | null` : result;
}

function objectType(schema: Readonly<Record<string, JsonValue>>, plan: GenerationPlan, names: ReadonlyMap<string, string>, schemaRef: string, visiting: Set<string>): string {
  const properties = schema.properties === undefined ? {} : asRecord(schema.properties);
  const required = new Set(Array.isArray(schema.required) ? schema.required as readonly string[] : []);
  const members = Object.entries(properties).sort(([a], [b]) => ordinal(a, b)).map(([key, child]) => {
    const pointer = `/properties/${key.replaceAll("~", "~0").replaceAll("/", "~1")}`;
    const brand = plan.schemaConstraints.find(value => value.schemaRef === schemaRef && value.propertyPointer === pointer && value.appliesTo === "value")?.brand;
    const type = brand && brand !== "none" ? schemaBrandType(brand) : schemaType(child, plan, names, schemaRef, visiting);
    return `readonly ${propertyName(key)}${required.has(key) ? "" : "?"}: ${type}`;
  });
  return `{ ${members.join("; ")} }`;
}

function schemaNames(schemas: Readonly<Record<string, JsonValue>>): ReadonlyMap<string, string> {
  const result = new Map<string, string>();
  const used = new Set<string>();
  for (const key of Object.keys(schemas).sort(ordinal)) {
    const candidate = pascal(key.replace(/^HPD_Gateway_(?:Admin|Abstractions|Effective|Management|Status)_/u, ""));
    if (!candidate || used.has(candidate)) throw new Error(`Schema name collision for '${key}'.`);
    used.add(candidate); result.set(key, candidate);
  }
  return result;
}

function refName(reference: string, names: ReadonlyMap<string, string>): string {
  if (!reference.startsWith(referencePrefix)) throw new Error(`Unsupported reference '${reference}'.`);
  const name = names.get(reference.slice(referencePrefix.length));
  if (!name) throw new Error(`Unresolved reference '${reference}'.`);
  return name;
}

function constraintBrand(constraints: readonly GatewaySchemaConstraint[], ref: string): string | undefined {
  const value = constraints.find(item => item.schemaRef === ref && item.propertyPointer === "" && item.appliesTo === "value");
  return value?.brand === "none" ? undefined : value?.brand === undefined ? undefined : schemaBrandType(value.brand);
}
function brandType(brand: string): string { return brand === "none" ? "string" : `S.Gateway${pascal(brand)}`; }
function schemaBrandType(brand: string): string { return brand === "none" ? "string" : `Gateway${pascal(brand)}`; }
function kebabBrand(value: string): string { return value.replace(/[A-Z]/gu, (c, i) => `${i ? "-" : ""}${c.toLowerCase()}`); }
function pascal(value: string): string { return value.split(/[^A-Za-z0-9]+/u).filter(Boolean).map(part => part[0]!.toUpperCase() + part.slice(1)).join(""); }
function propertyName(value: string): string { const name = value === "X-Correlation-ID" ? "correlationId" : value === "Idempotency-Key" ? "idempotencyKey" : value === "If-Match" ? "desiredPrecondition" : value; return /^[A-Za-z_$][\w$]*$/u.test(name) ? name : JSON.stringify(name); }
function asRecord(value: JsonValue): Readonly<Record<string, JsonValue>> { if (value === null || typeof value !== "object" || Array.isArray(value)) throw new Error("Schema must be an object."); return value as Readonly<Record<string, JsonValue>>; }
function ordinal(a: string, b: string): number { return a < b ? -1 : a > b ? 1 : 0; }

const resultContract = `export type GatewayResponseHeaders = Readonly<Record<string, string>>;\nexport type GatewayProtocolReason = "unexpected-status" | "unexpected-media-type" | "malformed-json" | "response-too-large" | "schema-mismatch" | "error-envelope-invalid";\nexport type GatewaySuccess<T, S extends 200 | 201 | 202> = { readonly ok: true; readonly status: S; readonly value: T; readonly correlationId?: import("./schemas.js").GatewayCorrelationId; readonly headers: GatewayResponseHeaders };\nexport type GatewayHttpFailure<S extends number> = { readonly ok: false; readonly kind: "http"; readonly status: S; readonly error: import("./schemas.js").GatewayAdminError; readonly correlationId?: import("./schemas.js").GatewayCorrelationId; readonly headers: GatewayResponseHeaders };\nexport type GatewayProtocolFailure = { readonly ok: false; readonly kind: "protocol"; readonly reason: GatewayProtocolReason; readonly actualStatus: number | null; readonly mediaType: string | null; readonly correlationId?: import("./schemas.js").GatewayCorrelationId; readonly headers: GatewayResponseHeaders };\nexport type GatewayTransportFailure = { readonly ok: false; readonly kind: "transport"; readonly reason: "network-failure"; readonly correlationId?: import("./schemas.js").GatewayCorrelationId };\nexport type GatewayCanceledFailure = { readonly ok: false; readonly kind: "canceled"; readonly reason: "caller-canceled"; readonly correlationId?: import("./schemas.js").GatewayCorrelationId };\nexport type GatewayFailure<S extends number> = GatewayHttpFailure<S> | GatewayProtocolFailure | GatewayTransportFailure | GatewayCanceledFailure;\nexport type GatewayOperationResult<T, S extends 200 | 201 | 202, E extends number> = GatewaySuccess<T, S> | GatewayFailure<E>;\n`;
