using HPD.Agent.SourceGenerator.SourceGeneration;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace HPD.Agent.LiveAudio.Contracts.Tests;

public sealed class GraphExecutableFactoryCatalogSourceGeneratorTests
{
    [Fact]
    public void Local_declarations_emit_contributions_and_internal_sorted_golden_evidence()
    {
        var (result, compilation) = Run(Preamble + """
            [HpdGraphExecutableFactory("source", 2)] public sealed class Source { }
            [HpdGraphExecutableFactory("sink", 1)] public sealed class Sink { }
            """);
        Assert.DoesNotContain(result.Diagnostics, x => x.Severity == DiagnosticSeverity.Error);
        Assert.Equal(3, result.GeneratedTrees.Length);
        var evidence = Evidence(result);
        Assert.Equal("""
            // <auto-generated/>
            #nullable enable
            namespace HPD.Agent.Audio.Graph.Generated;

            internal static class GraphExecutableFactoryCatalogEvidenceV1
            {
                internal const string CatalogFingerprintHex = "2382ca4a34e8a72c653bda8883080acd84ede0c07e7cf3f50846d1f9afd57e9e";
                internal static readonly string[] OrderedDeclarations =
                [
                    "sink\0graph-root:Sink@1\01",
                    "source\0graph-root:Source@2\02",
                ];
                internal static readonly string[] FactoryIdentityHex =
                [
                    "28220a02c7d71032a1940b2a86463910",
                    "48d1c4d9322126384d31760e8e6dd433",
                ];
            }
            """, evidence.TrimEnd());
        Assert.DoesNotContain("public ", evidence, StringComparison.Ordinal);
        Assert.DoesNotContain(compilation.GetDiagnostics(), x => x.Severity == DiagnosticSeverity.Error);
    }

    [Fact]
    public void Class_multiplicity_and_cross_target_forms_are_rejected()
    {
        AssertInvalid(Preamble + """
            [HpdGraphExecutableFactory("a", 1), HpdGraphExecutableFactory("b", 1)] public sealed class F { }
            """);
        AssertInvalid(Preamble + """
            [HpdGraphExecutableFactory(typeof(F), "a", 1)] public sealed class F { }
            """);
    }

    [Fact]
    public void Manual_local_assembly_forms_are_rejected()
    {
        AssertInvalid(AssemblySource("[assembly: HpdGraphExecutableFactory(typeof(F), \"a\", 1)]"));
        AssertInvalid(AssemblySource("[assembly: HpdGraphExecutableFactory(\"a\", 1)]"));
    }

    [Theory]
    [InlineData("")]
    [InlineData("has space")]
    [InlineData("é")]
    public void Invalid_node_keys_are_rejected(string key) => AssertInvalid(Preamble +
        $"[HpdGraphExecutableFactory({SymbolDisplay.FormatLiteral(key, true)}, 1)] public sealed class F {{ }}");

    [Fact]
    public void Revision_bounds_duplicates_and_maximum_are_exact()
    {
        AssertInvalid(Preamble + "[HpdGraphExecutableFactory(\"a\", 0)] public sealed class F { }");
        AssertInvalid(Preamble + """
            [HpdGraphExecutableFactory("a", 1)] public sealed class F { }
            [HpdGraphExecutableFactory("a", 2)] public sealed class G { }
            """);
        AssertValid(Many(64));
        AssertInvalid(Many(65));
        AssertValid(Preamble + $"[HpdGraphExecutableFactory(\"{new string('a', 64)}\", 1)] public sealed class Edge {{ }}");
        AssertInvalid(Preamble + $"[HpdGraphExecutableFactory(\"{new string('a', 65)}\", 1)] public sealed class Edge {{ }}");
    }

    [Fact]
    public void Non_nfc_or_overlong_implementation_identity_is_rejected()
    {
        AssertInvalid(Preamble + "[HpdGraphExecutableFactory(\"a\", 1)] public sealed class Te\u0301st { }");
        AssertInvalid(Preamble + $"[HpdGraphExecutableFactory(\"a\", 1)] public sealed class {new string('X', 500)} {{ }}");
    }

    [Theory]
    [InlineData("public abstract class F")]
    [InlineData("public static class F")]
    [InlineData("public class F<T>")]
    [InlineData("file class F")]
    public void Abstract_static_open_or_file_local_implementations_are_rejected(string declaration) =>
        AssertInvalid(Preamble + $"[HpdGraphExecutableFactory(\"a\", 1)] {declaration} {{ }}");

    [Fact]
    public void Inaccessible_or_open_containing_types_are_rejected()
    {
        AssertInvalid(Preamble + """
            internal class Outer { [HpdGraphExecutableFactory("a", 1)] private sealed class F { } }
            """);
        AssertInvalid(Preamble + """
            public class Outer<T> { [HpdGraphExecutableFactory("a", 1)] public sealed class F { } }
            """);
        AssertValid(Preamble + """
            internal class Outer { [HpdGraphExecutableFactory("a", 1)] internal sealed class F { } }
            """);
    }

    [Fact]
    public void Referenced_generated_contributions_join_each_application_root()
    {
        var leaf = CompileLeaf();
        var (result, compilation) = Run(Preamble +
            "[HpdGraphExecutableFactory(\"root\", 2)] public sealed class Root { }", [leaf]);
        var evidence = Evidence(result);
        Assert.Contains("leaf", evidence, StringComparison.Ordinal);
        Assert.Contains("root", evidence, StringComparison.Ordinal);
        Assert.DoesNotContain(compilation.GetDiagnostics(), x => x.Severity == DiagnosticSeverity.Error);
    }

    [Fact]
    public void Referenced_malformed_nonowning_and_short_form_contributions_are_rejected()
    {
        AssertInvalid(Preamble, [CompileManualLeaf("[assembly: HpdGraphExecutableFactory(\"leaf\", 1)]")]);
        AssertInvalid(Preamble, [CompileManualLeaf("[assembly: HpdGraphExecutableFactory(typeof(string), \"leaf\", 1)]")]);
    }

    [Fact]
    public void Incremental_rerun_is_byte_deterministic_and_generated_code_has_no_runtime_discovery()
    {
        var source = Preamble + "[HpdGraphExecutableFactory(\"a\", 1)] internal sealed class F { }";
        var first = Run(source).Result.GeneratedTrees.Select(x => x.GetText().ToString()).Order().ToArray();
        var second = Run(source).Result.GeneratedTrees.Select(x => x.GetText().ToString()).Order().ToArray();
        Assert.Equal(first, second);
        var joined = string.Join("\n", first);
        Assert.DoesNotContain("System.Reflection", joined, StringComparison.Ordinal);
        Assert.DoesNotContain("dynamic", joined, StringComparison.Ordinal);
        Assert.DoesNotContain("ModuleInitializer", joined, StringComparison.Ordinal);
        Assert.DoesNotContain("GetType", joined, StringComparison.Ordinal);
        Assert.DoesNotContain("Activator", joined, StringComparison.Ordinal);
    }

    [Fact]
    public void Public_attribute_has_exact_metadata_only_shape()
    {
        var type = typeof(HPD.Agent.Audio.Graph.HpdGraphExecutableFactoryAttribute);
        var usage = Assert.Single(type.GetCustomAttributes(typeof(AttributeUsageAttribute), false).Cast<AttributeUsageAttribute>());
        Assert.Equal(AttributeTargets.Class | AttributeTargets.Assembly, usage.ValidOn);
        Assert.True(usage.AllowMultiple); Assert.False(usage.Inherited);
        Assert.Equal(2, type.GetConstructors().Length);
        Assert.Equal([typeof(string), typeof(uint)], type.GetConstructors().Single(x => x.GetParameters().Length == 2)
            .GetParameters().Select(x => x.ParameterType).ToArray());
        Assert.Equal([typeof(Type), typeof(string), typeof(uint)], type.GetConstructors().Single(x => x.GetParameters().Length == 3)
            .GetParameters().Select(x => x.ParameterType).ToArray());
        Assert.Equal(["ImplementationRevision", "ImplementationType", "NodeKey"],
            type.GetProperties(System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Instance |
                System.Reflection.BindingFlags.DeclaredOnly).Select(x => x.Name).Order().ToArray());
        Assert.DoesNotContain(type.GetMethods(System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Instance |
            System.Reflection.BindingFlags.DeclaredOnly), x => !x.IsSpecialName);
        Assert.Equal(typeof(Type), type.GetProperty("ImplementationType")!.PropertyType);
        Assert.Equal(typeof(string), type.GetProperty("NodeKey")!.PropertyType);
        Assert.Equal(typeof(uint), type.GetProperty("ImplementationRevision")!.PropertyType);
        Assert.Equal(System.Reflection.NullabilityState.Nullable,
            new System.Reflection.NullabilityInfoContext().Create(type.GetProperty("ImplementationType")!).ReadState);
    }

    private static void AssertValid(string source)
    { var (result, compilation) = Run(source); Assert.DoesNotContain(result.Diagnostics, x => x.Severity == DiagnosticSeverity.Error); Assert.DoesNotContain(compilation.GetDiagnostics(), x => x.Severity == DiagnosticSeverity.Error); }
    private static void AssertInvalid(string source, IEnumerable<MetadataReference>? extras = null)
    { var (result, _) = Run(source, extras); Assert.Contains(result.Diagnostics, x => x.Id == "HPDA006" && x.Severity == DiagnosticSeverity.Error); Assert.DoesNotContain(result.GeneratedTrees, x => x.FilePath.EndsWith("GraphExecutableFactoryCatalogEvidenceV1.g.cs", StringComparison.Ordinal)); }

    private static (GeneratorDriverRunResult Result, Compilation Compilation) Run(string source,
        IEnumerable<MetadataReference>? extras = null)
    {
        var compilation = CSharpCompilation.Create("graph-root",
            [CSharpSyntaxTree.ParseText(source, new CSharpParseOptions(LanguageVersion.Latest))],
            PlatformReferences().Concat(extras ?? []), new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));
        GeneratorDriver driver = CSharpGeneratorDriver.Create(
            [new GraphExecutableFactoryCatalogSourceGenerator().AsSourceGenerator()],
            parseOptions: new CSharpParseOptions(LanguageVersion.Latest));
        driver = driver.RunGeneratorsAndUpdateCompilation(compilation, out var updated, out _);
        return (driver.GetRunResult(), updated);
    }

    private static MetadataReference CompileLeaf()
    {
        var (result, compilation) = Run(Preamble +
            "[HpdGraphExecutableFactory(\"leaf\", 1)] public sealed class Leaf { }");
        Assert.DoesNotContain(result.Diagnostics, x => x.Severity == DiagnosticSeverity.Error);
        using var stream = new MemoryStream(); var emitted = compilation.Emit(stream);
        Assert.True(emitted.Success, string.Join(global::System.Environment.NewLine, emitted.Diagnostics));
        return MetadataReference.CreateFromImage(stream.ToArray());
    }

    private static MetadataReference CompileManualLeaf(string assemblyAttribute)
    {
        var source = AssemblySource(assemblyAttribute);
        var compilation = CSharpCompilation.Create("manual-leaf",
            [CSharpSyntaxTree.ParseText(source, new CSharpParseOptions(LanguageVersion.Latest))], PlatformReferences(),
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));
        using var stream = new MemoryStream(); var emitted = compilation.Emit(stream);
        Assert.True(emitted.Success, string.Join(global::System.Environment.NewLine, emitted.Diagnostics));
        return MetadataReference.CreateFromImage(stream.ToArray());
    }

    private static string Evidence(GeneratorDriverRunResult result) => Assert.Single(result.GeneratedTrees,
        x => x.FilePath.EndsWith("GraphExecutableFactoryCatalogEvidenceV1.g.cs", StringComparison.Ordinal)).GetText().ToString();
    private static string Many(int count) => Preamble + string.Join(global::System.Environment.NewLine,
        Enumerable.Range(0, count).Select(i => $"[HpdGraphExecutableFactory(\"n{i:00}\", 1)] public sealed class F{i:00} {{ }}"));
    private static IEnumerable<MetadataReference> PlatformReferences() =>
        ((string?)AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES"))!.Split(Path.PathSeparator)
            .Select(path => MetadataReference.CreateFromFile(path));
    private static string AssemblySource(string attribute) => $$"""
        using System;
        using HPD.Agent.Audio.Graph;
        {{attribute}}
        namespace HPD.Agent.Audio.Graph
        {
            [AttributeUsage(AttributeTargets.Class | AttributeTargets.Assembly, AllowMultiple=true, Inherited=false)]
            public sealed class HpdGraphExecutableFactoryAttribute : Attribute
            {
                public HpdGraphExecutableFactoryAttribute(string nodeKey, uint revision) { }
                public HpdGraphExecutableFactoryAttribute(Type type, string nodeKey, uint revision) { }
            }
        }
        public sealed class F { }
        """;

    private const string Preamble = """
        using System;
        using HPD.Agent.Audio.Graph;
        namespace HPD.Agent.Audio.Graph
        {
            [AttributeUsage(AttributeTargets.Class | AttributeTargets.Assembly, AllowMultiple=true, Inherited=false)]
            public sealed class HpdGraphExecutableFactoryAttribute : Attribute
            {
                public HpdGraphExecutableFactoryAttribute(string nodeKey, uint revision) { }
                public HpdGraphExecutableFactoryAttribute(Type type, string nodeKey, uint revision) { }
            }
        }
        """;
}
