using HPD.Agent.Audio.Runtime.Providers;
using HPD.Agent.Authority;

namespace HPD.Agent.LiveAudio.Contracts.Tests;

public sealed class ProviderAdjacentOwnerPortsV1Tests
{
    [Fact] public void All_seven_adjacent_owners_have_exact_supply_and_consume_kinds(){var f=Fixture();var port=new InMemoryProviderAdjacentOwnerPortV1(f.Plan,32);foreach(var x in Cases())Assert.IsType<ProviderAdjacentPortResultV1.Accepted>(port.Exchange(Message(f,x.Direction,x.Kind,x.Owner)));}
    [Fact] public void Wrong_owner_kind_pair_is_constructor_rejected(){var f=Fixture();Assert.Throws<ArgumentException>(()=>new ProviderAdjacentMessageV1(OperationId.Create(),ProviderAdjacentDirectionV1.SuppliedByProvider,ProviderAdjacentKindV1.OutputCandidate,OwnerSliceId.S4,f.Plan.ParticipantId,f.Plan.Generation,f.Authority,new JournalPositionV1(f.Session,1),Hash(1)));}
    [Fact] public void Adjacent_evidence_cannot_replace_provider_authority(){var f=Fixture();var stale=ProviderGenerationId.Create();var authority=ExpectedAuthorityVectorV1.Create(f.Session,[new AuthorityAxisValueV1.Provider(stale),new AuthorityAxisValueV1.Route(f.Plan.RouteGeneration)]);Assert.Throws<ArgumentException>(()=>new ProviderAdjacentMessageV1(OperationId.Create(),ProviderAdjacentDirectionV1.ConsumedByProvider,ProviderAdjacentKindV1.EndpointDecision,OwnerSliceId.S4,f.Plan.ParticipantId,f.Plan.Generation,authority,new JournalPositionV1(f.Session,1),Hash(2)));}
    [Fact] public void Retry_is_exact_and_changed_message_is_contradictory(){var f=Fixture();var port=new InMemoryProviderAdjacentOwnerPortV1(f.Plan,4);var message=Message(f,ProviderAdjacentDirectionV1.SuppliedByProvider,ProviderAdjacentKindV1.TranscriptEvidence,OwnerSliceId.S4);Assert.IsType<ProviderAdjacentPortResultV1.Accepted>(port.Exchange(message));Assert.IsType<ProviderAdjacentPortResultV1.Duplicate>(port.Exchange(message));var changed=new ProviderAdjacentMessageV1(message.OperationId,message.Direction,message.Kind,message.AdjacentOwner,message.ParticipantId,message.ProviderGeneration,message.Authority,message.SourcePosition,Hash(9));Assert.Equal("provider-adjacent-operation-contradiction",Assert.IsType<ProviderAdjacentPortResultV1.Rejected>(port.Exchange(changed)).SafeCode.ToString());}
    [Fact] public void Port_is_bounded_without_dropping_prior_evidence(){var f=Fixture();var state=new ProviderAdjacentPortStateV1(f.Plan);state=Assert.IsType<ProviderAdjacentPortResultV1.Accepted>(ProviderAdjacentOwnerReducerV1.Apply(state,Message(f,ProviderAdjacentDirectionV1.SuppliedByProvider,ProviderAdjacentKindV1.ProviderHealth,OwnerSliceId.S8),1)).State;var rejected=Assert.IsType<ProviderAdjacentPortResultV1.Rejected>(ProviderAdjacentOwnerReducerV1.Apply(state,Message(f,ProviderAdjacentDirectionV1.ConsumedByProvider,ProviderAdjacentKindV1.RouteAuthorization,OwnerSliceId.S8),1));Assert.Equal("provider-adjacent-capacity-refused",rejected.SafeCode.ToString());Assert.Single(rejected.State.Messages);}
    private static IEnumerable<(ProviderAdjacentDirectionV1 Direction,ProviderAdjacentKindV1 Kind,OwnerSliceId Owner)> Cases(){yield return(ProviderAdjacentDirectionV1.SuppliedByProvider,ProviderAdjacentKindV1.ParticipantReadiness,OwnerSliceId.S1);yield return(ProviderAdjacentDirectionV1.ConsumedByProvider,ProviderAdjacentKindV1.LifecycleAdmission,OwnerSliceId.S1);yield return(ProviderAdjacentDirectionV1.SuppliedByProvider,ProviderAdjacentKindV1.MediaObservation,OwnerSliceId.S2);yield return(ProviderAdjacentDirectionV1.ConsumedByProvider,ProviderAdjacentKindV1.MediaLease,OwnerSliceId.S2);yield return(ProviderAdjacentDirectionV1.SuppliedByProvider,ProviderAdjacentKindV1.ActivityEvidence,OwnerSliceId.S3);yield return(ProviderAdjacentDirectionV1.ConsumedByProvider,ProviderAdjacentKindV1.PromotedActivity,OwnerSliceId.S3);yield return(ProviderAdjacentDirectionV1.SuppliedByProvider,ProviderAdjacentKindV1.TranscriptEvidence,OwnerSliceId.S4);yield return(ProviderAdjacentDirectionV1.ConsumedByProvider,ProviderAdjacentKindV1.EndpointDecision,OwnerSliceId.S4);yield return(ProviderAdjacentDirectionV1.SuppliedByProvider,ProviderAdjacentKindV1.OutputCandidate,OwnerSliceId.S6);yield return(ProviderAdjacentDirectionV1.ConsumedByProvider,ProviderAdjacentKindV1.PlayoutReceipt,OwnerSliceId.S6);yield return(ProviderAdjacentDirectionV1.SuppliedByProvider,ProviderAdjacentKindV1.ToolProposal,OwnerSliceId.S7);yield return(ProviderAdjacentDirectionV1.ConsumedByProvider,ProviderAdjacentKindV1.ToolDisposition,OwnerSliceId.S7);yield return(ProviderAdjacentDirectionV1.SuppliedByProvider,ProviderAdjacentKindV1.ProviderHealth,OwnerSliceId.S8);yield return(ProviderAdjacentDirectionV1.ConsumedByProvider,ProviderAdjacentKindV1.RouteAuthorization,OwnerSliceId.S8);}
    private static ProviderAdjacentMessageV1 Message((ProviderParticipantPlanV1 Plan,ExpectedAuthorityVectorV1 Authority,SessionAuthorityStampV1 Session) f,ProviderAdjacentDirectionV1 d,ProviderAdjacentKindV1 k,OwnerSliceId o)=>new(OperationId.Create(),d,k,o,f.Plan.ParticipantId,f.Plan.Generation,f.Authority,new JournalPositionV1(f.Session,1),Hash((byte)k));
    private static (ProviderParticipantPlanV1 Plan,ExpectedAuthorityVectorV1 Authority,SessionAuthorityStampV1 Session) Fixture(){var s=new SessionAuthorityStampV1(RuntimeGenerationId.Create(),LiveSessionId.Create());var p=ProviderGenerationId.Create();var r=RouteGenerationId.Create();var a=ExpectedAuthorityVectorV1.Create(s,[new AuthorityAxisValueV1.Provider(p),new AuthorityAxisValueV1.Route(r)]);return(new ProviderParticipantPlanV1(ParticipantId.Create(),ProviderId.Create(),p,r,a,Hash(20),2),a,s);}
    private static Hash256 Hash(byte b)=>Hash256.Compute(new[]{b});
}
