using HPD.Agent.Audio.Runtime.Providers;
using HPD.Agent.Audio.Runtime.Routing;
using HPD.Agent.Audio.Runtime.Tools;
using HPD.Agent.Authority;

namespace HPD.Agent.LiveAudio.Contracts.Tests;

public sealed class RouteCutoverCoordinatorV1Tests
{
    [Fact] public void Authorized_prepared_provider_commits_cutover(){var f=Fixture();Assert.IsType<RouteCutoverResultV1.Committed>(RouteCutoverCoordinatorV1.Commit(OperationId.Create(),f.Evidence));}
    [Fact] public void Provider_identity_and_generation_are_authenticated(){var f=Fixture();var wrong=new ProviderParticipantPlanV1(f.Plan.ParticipantId,ProviderId.Create(),f.Plan.Generation,f.Plan.RouteGeneration,f.Plan.Authority,f.Plan.CatalogFingerprint,1);var r=RouteCutoverCoordinatorV1.Commit(OperationId.Create(),f.Evidence with{Provider=f.Evidence.Provider with{Plan=wrong}});Assert.Equal("route-provider-evidence-mismatch",Assert.IsType<RouteCutoverResultV1.Rejected>(r).SafeCode.ToString());}
    [Fact] public void Unauthorized_preparation_cannot_cut_over(){var f=Fixture();var p=new RoutePreparationStateV1(f.Evidence.Preparation.Route,new(2,RoutePreparationPhaseV1.OwnerClaimed,OwnerSliceId.S5));Assert.Equal("route-cutover-not-authorized",Assert.IsType<RouteCutoverResultV1.Rejected>(RouteCutoverCoordinatorV1.Commit(OperationId.Create(),f.Evidence with{Preparation=p})).SafeCode.ToString());}
    [Fact] public void Authenticated_cutover_enables_composite_tool_resume(){var f=Fixture();var route=Assert.IsType<RouteCutoverResultV1.Committed>(RouteCutoverCoordinatorV1.Commit(OperationId.Create(),f.Evidence)).Receipt;var tool=Projected(f.Authority,f.Output,f.Tool);var resumed=Assert.IsType<ToolTransactionResultV1.Applied>(ToolCompositeResumeV1.Resume(tool,OperationId.Create(),route,32));Assert.Equal(ToolTransactionPhaseV1.ToolContinuationAuthorized,resumed.State.Snapshot.Phase);}
    [Fact] public void Resume_rejects_stale_route_without_advancing(){var f=Fixture();var route=Assert.IsType<RouteCutoverResultV1.Committed>(RouteCutoverCoordinatorV1.Commit(OperationId.Create(),f.Evidence)).Receipt;var other=RouteGenerationId.Create();var authority=ExpectedAuthorityVectorV1.Create(f.Authority.Session,[new AuthorityAxisValueV1.Output(f.Output),new AuthorityAxisValueV1.Tool(f.Tool),new AuthorityAxisValueV1.Route(other),new AuthorityAxisValueV1.Provider(f.Plan.Generation)]);var tool=Projected(authority,f.Output,f.Tool);var rejected=Assert.IsType<ToolTransactionResultV1.Rejected>(ToolCompositeResumeV1.Resume(tool,OperationId.Create(),route,32));Assert.Equal("tool-route-authority-mismatch",rejected.SafeCode.ToString());Assert.Equal(ToolTransactionPhaseV1.ToolResultProjected,rejected.State.Snapshot.Phase);}
    private static (RouteCutoverEvidenceV1 Evidence,ProviderParticipantPlanV1 Plan,ExpectedAuthorityVectorV1 Authority,OutputGenerationId Output,ToolGenerationId Tool) Fixture(){var s=new SessionAuthorityStampV1(RuntimeGenerationId.Create(),LiveSessionId.Create());var pg=ProviderGenerationId.Create();var rg=RouteGenerationId.Create();var og=OutputGenerationId.Create();var tg=ToolGenerationId.Create();var a=ExpectedAuthorityVectorV1.Create(s,[new AuthorityAxisValueV1.Output(og),new AuthorityAxisValueV1.Tool(tg),new AuthorityAxisValueV1.Route(rg),new AuthorityAxisValueV1.Provider(pg)]);var route=new CompiledRouteV1(OperationId.Create(),ProviderId.Create(),rg,a,Hash(1),Hash(2));var prep=new RoutePreparationStateV1(route,new(3,RoutePreparationPhaseV1.CutoverAuthorized,OwnerSliceId.S5));var plan=new ProviderParticipantPlanV1(ParticipantId.Create(),route.ProviderId,pg,rg,a,Hash(1),1);return(new(prep,new(2,ProviderParticipantPhaseV1.Effective,plan,0,null),new JournalPositionV1(s,4)),plan,a,og,tg);}
    private static ToolTransactionStateV1 Projected(ExpectedAuthorityVectorV1 a,OutputGenerationId o,ToolGenerationId t){var state=ToolTransactionSupervisorV1.Create(new(OperationId.Create(),t,o,a,new MonotonicStampV1(ClockDomainId.Create(),BootId.Create(),100),true));foreach(var p in new[]{ToolTransactionPhaseV1.ToolControlRecorded,ToolTransactionPhaseV1.ToolArgumentsFinalized,ToolTransactionPhaseV1.ToolApprovalDecided,ToolTransactionPhaseV1.ToolDispositionChosen,ToolTransactionPhaseV1.ToolOwnerClaimed,ToolTransactionPhaseV1.ToolDispatchAuthorized,ToolTransactionPhaseV1.ToolEntryIntentRecorded,ToolTransactionPhaseV1.ToolExternalBoundaryEntered})state=A(state,new ToolTransactionCommandV1.Advance(OperationId.Create(),state.Snapshot.Revision,p,1));state=A(state,new ToolTransactionCommandV1.AdmitEffectEvidence(OperationId.Create(),8,true));state=A(state,new ToolTransactionCommandV1.Advance(OperationId.Create(),9,ToolTransactionPhaseV1.ToolResultFinalized,1));return A(state,new ToolTransactionCommandV1.Advance(OperationId.Create(),10,ToolTransactionPhaseV1.ToolResultProjected,1));}
    private static ToolTransactionStateV1 A(ToolTransactionStateV1 s,ToolTransactionCommandV1 c)=>Assert.IsType<ToolTransactionResultV1.Applied>(ToolTransactionSupervisorV1.Apply(s,c,32)).State;
    private static Hash256 Hash(byte b)=>Hash256.Compute(new[]{b});
}
