using HPD.Agent.Audio.Runtime.Replay;
using HPD.Agent.Audio.Runtime.Transports;
using HPD.Agent.Authority;

namespace HPD.Agent.LiveAudio.Contracts.Tests;

public sealed class TransportRecordingReplayV1Tests
{
    [Fact] public async Task Copy_is_reserved_before_recorder_escape(){var f=new Fixture();var effect=new RecordingEffect();var result=Assert.IsType<TransportRecordingResultV1.Materialized>(await TransportRecordingCoordinatorV1.RecordAsync(PrivacyCopyLifecycleV1.Create(),f.Reservation(0),0,effect,8,32));Assert.True(effect.SawReservedIntent);Assert.Single(result.Privacy.Copies);}
    [Fact] public async Task Ambiguous_recording_retains_open_copy_obligation(){var f=new Fixture();var result=Assert.IsType<TransportRecordingResultV1.OutcomeUnknown>(await TransportRecordingCoordinatorV1.RecordAsync(PrivacyCopyLifecycleV1.Create(),f.Reservation(0),0,new RecordingEffect(true),8,32));Assert.Single(result.Privacy.Copies);Assert.Null(result.Privacy.Copies.Values.Single().Evidence);}
    [Fact] public async Task Exact_retry_does_not_repeat_recorder_escape(){var f=new Fixture();var effect=new RecordingEffect();var reservation=f.Reservation(0);var first=Assert.IsType<TransportRecordingResultV1.Materialized>(await TransportRecordingCoordinatorV1.RecordAsync(PrivacyCopyLifecycleV1.Create(),reservation,0,effect,8,32));var retry=Assert.IsType<TransportRecordingResultV1.Duplicate>(await TransportRecordingCoordinatorV1.RecordAsync(first.Privacy,reservation,0,effect,8,32));Assert.Equal(1,effect.CallCount);Assert.Equal(first.ReservationReceipt,retry.ReservationReceipt);}
    [Fact] public async Task Replay_requires_the_exact_registered_copy_and_is_read_only(){var f=new Fixture();var recorded=Assert.IsType<TransportRecordingResultV1.Materialized>(await TransportRecordingCoordinatorV1.RecordAsync(PrivacyCopyLifecycleV1.Create(),f.Reservation(0),0,new RecordingEffect(),8,32));await f.SeedAsync();var before=await f.HeadAsync();var replay=Assert.IsType<TransportReplayResultV1.Compiled>(await TransportReplayCoordinatorV1.CompileAsync(recorded.Privacy,recorded.Privacy.Copies.Keys.Single(),new AuthorityJournalReplaySourceV1(f.Journal),f.Session));Assert.Single(replay.Compilation.Facts);Assert.Equal(before,await f.HeadAsync());Assert.DoesNotContain(typeof(IAuthorityReplaySourceV1).GetMethods(),x=>x.Name.Contains("Append",StringComparison.Ordinal));}
    [Fact] public async Task Unknown_copy_cannot_authorize_replay(){var f=new Fixture();Assert.IsType<TransportReplayResultV1.Unauthorized>(await TransportReplayCoordinatorV1.CompileAsync(PrivacyCopyLifecycleV1.Create(),CopyId.Create(),new AuthorityJournalReplaySourceV1(f.Journal),f.Session));}
    [Fact] public async Task Held_copy_cannot_authorize_replay(){var f=new Fixture();var recorded=Assert.IsType<TransportRecordingResultV1.Materialized>(await TransportRecordingCoordinatorV1.RecordAsync(PrivacyCopyLifecycleV1.Create(),f.Reservation(0),0,new RecordingEffect(),8,32));var copy=recorded.Privacy.Copies.Keys.Single();var held=Assert.IsType<PrivacyCopyResultV1.Applied>(PrivacyCopyLifecycleV1.Apply(recorded.Privacy,new PrivacyCopyCommandV1.SetHold(OperationId.Create(),1,copy,true),8,32)).State;Assert.IsType<TransportReplayResultV1.Unauthorized>(await TransportReplayCoordinatorV1.CompileAsync(held,copy,new AuthorityJournalReplaySourceV1(f.Journal),f.Session));}
    private sealed class RecordingEffect(bool unknown=false):ITransportRecordingEffectPortV1{internal bool SawReservedIntent{get;private set;}internal int CallCount{get;private set;}public ValueTask<TransportRecordingEffectResultV1> RecordAsync(CopyReservationV1 reservation,CancellationToken cancellationToken){CallCount++;SawReservedIntent=reservation.ExpectedInventoryFrontier==0;return ValueTask.FromResult<TransportRecordingEffectResultV1>(unknown?new TransportRecordingEffectResultV1.OutcomeUnknown(new BoundedAscii("record-outcome-unknown")):new TransportRecordingEffectResultV1.Materialized(Hash256.Compute(new byte[]{1})));}}
    private sealed class Fixture{internal readonly SessionAuthorityStampV1 Session=new(RuntimeGenerationId.Create(),LiveSessionId.Create());internal readonly InMemoryAuthorityJournalV1 Journal;internal Fixture()=>Journal=new(new AuthorityPayloadAdmissionRegistryV1([new SessionAuthorityStampPayloadRegistrationV1()]),()=>new UtcInstant(1),new(16,128,1_000_000));internal CopyReservationV1 Reservation(ulong frontier){var p=new JournalPositionV1(Session,1);return new(CopyId.Create(),new(p,p),CustodianDescriptorId.Create(),[],DataClassificationV1.Confidential,PurposeId.Create(),AudienceId.Create(),new([new BoundedAscii("us")],false),AuthorizationId.Create(),new(new UtcInstant(1),new UtcInstant(2),RetentionBasisV1.Purpose),ExpectedAuthorityVectorV1.Create(Session,[]),OperationId.Create(),frontier);}internal async Task SeedAsync(){var payload=SessionAuthorityStampV1Codec.Encode(new(RuntimeGenerationId.Create(),LiveSessionId.Create()));var registration=new SessionAuthorityStampPayloadRegistrationV1();var proposal=new ProposedAuthorityFactV1(JournalFactId.Create(),null,registration.Owner,registration.Schema,payload,AuthorityPayloadHashV1.Compute(registration.SchemaToken,registration.Schema,payload),new CorrelationEnvelopeV1(TenantId.Create(),operationId:OperationId.Create()),new UtcInstant(1));Assert.IsType<AppendAuthorityResultV1.Committed>(await Journal.AppendAsync(new(Session,0,[],[proposal],4096)));}internal async Task<long> HeadAsync()=>Assert.IsType<ReadAuthorityRangeResultV1.Batch>(await Journal.ReadAsync(new(Session,0,long.MaxValue,16,65536))).SnapshotThrough;}
}
