using HPD.Agent.Audio;
using HPD.Agent.Audio.Media;
using HPD.Agent.Audio.Policies;
using HPD.Agent.Audio.Runtime.Transports;
using HPD.Agent.Audio.Transports;
using HPD.Agent.Authority;

namespace HPD.Agent.LiveAudio.Contracts.Tests;

public sealed class TransportCoordinatorV1Tests
{
    [Fact] public async Task Finite_content_adapter_migrates_through_S11_lifecycle(){await using var adapter=new ContentInputTransportAdapter(new TransportAdapterId("finite-1"),new AudioSessionId("audio-1"),new InputContentRef{Id=new InputContentId("input-1"),Kind=InputContentKind.Audio,SourceKind=InputContentSourceKind.MetadataOnly,MediaType="audio/wav"},new AudioPolicySet());var state=State(TransportProfileV1.FiniteContent);var port=new FiniteManualTransportAdapterPortV1(adapter);state=await A(state,new TransportLifecycleCommandV1.Bind(OperationId.Create(),0),port);state=await A(state,new TransportLifecycleCommandV1.Start(OperationId.Create(),1),port);Assert.Equal(TransportAdapterState.Active,adapter.State);state=await A(state,new TransportLifecycleCommandV1.Stop(OperationId.Create(),2),port);Assert.Equal(TransportLifecycleV1.Stopped,state.Snapshot.Lifecycle);}
    [Fact] public async Task Manual_adapter_uses_the_same_generation_fenced_coordinator(){var effects=new ScriptedEffectPort();var state=State(TransportProfileV1.Manual);state=await A(state,new TransportLifecycleCommandV1.Bind(OperationId.Create(),0),effects);state=await A(state,new TransportLifecycleCommandV1.Start(OperationId.Create(),1),effects);Assert.Equal(1,effects.Starts);}
    [Fact] public async Task Adapter_unknown_outcome_preserves_lifecycle(){var effects=new ScriptedEffectPort{Unknown=true};var state=State(TransportProfileV1.Manual);state=await A(state,new TransportLifecycleCommandV1.Bind(OperationId.Create(),0),effects);var result=Assert.IsType<TransportCoordinatorResultV1.OutcomeUnknown>(await TransportCoordinatorV1.ApplyAsync(state,new TransportLifecycleCommandV1.Start(OperationId.Create(),1),effects,8));Assert.Equal(TransportLifecycleV1.Bound,result.State.Snapshot.Lifecycle);}
    [Fact] public async Task Retry_is_exact_and_changed_reuse_conflicts(){var effects=new ScriptedEffectPort();var state=State(TransportProfileV1.Manual);var command=new TransportLifecycleCommandV1.Bind(OperationId.Create(),0);var applied=Assert.IsType<TransportCoordinatorResultV1.Applied>(await TransportCoordinatorV1.ApplyAsync(state,command,effects,8));Assert.IsType<TransportCoordinatorResultV1.Duplicate>(await TransportCoordinatorV1.ApplyAsync(applied.State,command,effects,8));Assert.IsType<TransportCoordinatorResultV1.Rejected>(await TransportCoordinatorV1.ApplyAsync(applied.State,new TransportLifecycleCommandV1.Start(command.OperationId,1),effects,8));}
    [Fact] public void Transport_generation_must_match_the_S11_axis(){var s=new SessionAuthorityStampV1(RuntimeGenerationId.Create(),LiveSessionId.Create());var g=TransportGenerationId.Create();var a=ExpectedAuthorityVectorV1.Create(s,[new AuthorityAxisValueV1.Transport(TransportGenerationId.Create())]);Assert.Throws<ArgumentException>(()=>new TransportPlanV1(OperationId.Create(),TransportProfileV1.Manual,g,a));}
    private static TransportCoordinatorStateV1 State(TransportProfileV1 profile){var s=new SessionAuthorityStampV1(RuntimeGenerationId.Create(),LiveSessionId.Create());var g=TransportGenerationId.Create();var a=ExpectedAuthorityVectorV1.Create(s,[new AuthorityAxisValueV1.Transport(g)]);return TransportCoordinatorV1.Create(new(OperationId.Create(),profile,g,a));}
    private static async Task<TransportCoordinatorStateV1> A(TransportCoordinatorStateV1 s,TransportLifecycleCommandV1 c,ITransportLifecycleEffectPortV1 p)=>Assert.IsType<TransportCoordinatorResultV1.Applied>(await TransportCoordinatorV1.ApplyAsync(s,c,p,8)).State;
    private sealed class ScriptedEffectPort:ITransportLifecycleEffectPortV1{public bool Unknown{get;set;}public int Starts{get;private set;}public ValueTask<TransportAdapterEffectResultV1> ApplyAsync(TransportLifecycleCommandV1 command,CancellationToken cancellationToken){cancellationToken.ThrowIfCancellationRequested();if(Unknown&&command is TransportLifecycleCommandV1.Start)return ValueTask.FromResult<TransportAdapterEffectResultV1>(new TransportAdapterEffectResultV1.OutcomeUnknown(new BoundedAscii("transport-adapter-outcome-unknown")));if(command is TransportLifecycleCommandV1.Start)Starts++;return ValueTask.FromResult<TransportAdapterEffectResultV1>(new TransportAdapterEffectResultV1.Completed());}}
}
