<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>false</IsTestProject>
    <OutputType>Exe</OutputType>
    <NoWarn>$(NoWarn);CA1308;CA1515</NoWarn>
  </PropertyGroup>
  <ItemGroup><ProjectReference Include="../../src/HPD.Payments.Contracts/HPD.Payments.Contracts.csproj" /></ItemGroup>
</Project>
