import type { GeneratedFile, GenerationPlan, PlannedCollection, PlannedField, RecordOperation } from "./types.js";
import { inputType, outputType } from "./type-map.js";
import { stringLiteral } from "./names.js";

export function renderGeneratedFiles(plan: GenerationPlan): GeneratedFile[] {
  return [
    { path: "index.ts", content: withBanner(plan, renderIndex()) },
    { path: "types.ts", content: withBanner(plan, renderTypes(plan)) },
    { path: "query.ts", content: withBanner(plan, renderQuery(plan)) },
    { path: "metadata.ts", content: withBanner(plan, renderMetadata(plan)) },
    { path: "client.ts", content: withBanner(plan, renderClient(plan)) }
  ];
}

function withBanner(plan: GenerationPlan, content: string): string {
  const banner = plan.config.banner ?? "Generated by @hpd/base-client-generator. Do not edit by hand.";
  return `// ${banner}\n\n${content.trim()}\n`;
}

function renderIndex(): string {
  return `
export * from "./types.js";
export * from "./query.js";
export * from "./metadata.js";
export * from "./client.js";
`;
}

function renderTypes(plan: GenerationPlan): string {
  const collections = plan.collections.map(collection => renderCollectionTypes(collection)).join("\n\n");
  return `
import type { CollectionClient, RecordEnvelope, RecordPage, DeleteResult } from "@hpd/base-client";

export type RecordId = string;
export type RevisionToken = string;
export type IsoDateTimeString = string;
export type DecimalString = string;
export type JsonValue =
  | null
  | string
  | number
  | boolean
  | JsonValue[]
  | { [key: string]: JsonValue };

${collections}
`;
}

function renderCollectionTypes(collection: PlannedCollection): string {
  const outputFields = collection.fields.filter(field => field.outputVisible);
  const fields = outputFields.map(field => `  ${optionalProperty(field, false)}: ${outputType(field)};`).join("\n") || "  [key: string]: never;";
  const createFields = collection.fields.filter(field => writableInCreate(field));
  const patchFields = collection.fields.filter(field => writable(field));
  const fieldUnion = union(outputFields.map(field => field.propertyName));
  const comparableUnion = union(outputFields.filter(field => field.comparable && field.scalar).map(field => field.propertyName));
  const stringUnion = union(outputFields.filter(field => field.baseType === "string" && field.scalar).map(field => field.propertyName));
  return `
export interface ${collection.typeName} extends Record<string, unknown> {
${fields}
}

export type ${collection.typeName}Create = {
${renderInputFields(createFields, "create")}
};

export type ${collection.typeName}Patch = {
${renderInputFields(patchFields, "patch")}
};

export type ${collection.typeName}Replace = ${collection.typeName}Create;
export type ${collection.typeName}FieldPath = ${fieldUnion};
export type ${collection.typeName}ComparableFieldPath = ${comparableUnion};
export type ${collection.typeName}StringFieldPath = ${stringUnion};
export type ${collection.typeName}Envelope = RecordEnvelope<${collection.typeName}>;
export type ${collection.typeName}Page = RecordPage<${collection.typeName}>;
export type ${collection.typeName}DeleteResult = DeleteResult<${collection.typeName}>;
export type ${collection.typeName}GenericCollection = CollectionClient<${collection.typeName}>;
`;
}

function renderInputFields(fields: PlannedField[], mode: "create" | "patch"): string {
  if (fields.length === 0) return "  [key: string]: never;";
  return fields.map(field => {
    const optional = mode === "patch" || !field.required || field.generatedOnCreate || field.hasDefault ? "?" : "";
    return `  ${JSON.stringify(field.propertyName)}${optional}: ${inputType(field)};`;
  }).join("\n");
}

function renderQuery(plan: GenerationPlan): string {
  const aliases = plan.collections.map(collection => `
export type ${collection.typeName}QueryHelpers = TypedQueryHelpers<${collection.typeName}FieldPath, ${collection.typeName}ComparableFieldPath, ${collection.typeName}StringFieldPath, ${collection.queryFeatures.filter}, ${collection.queryFeatures.sort}>;
export type ${collection.typeName}QueryInput = TypedRecordQueryInput<${collection.typeName}FieldPath, ${collection.queryFeatures.filter}, ${collection.queryFeatures.sort}, ${collection.queryFeatures.select}, ${collection.queryFeatures.include}>;
export const ${collection.propertyName}Q = typedQ<${collection.typeName}FieldPath, ${collection.typeName}ComparableFieldPath, ${collection.typeName}StringFieldPath, ${collection.queryFeatures.filter}, ${collection.queryFeatures.sort}>();
`).join("\n");
  return `
import { q as baseQ } from "@hpd/base-client";
import type { FilterExpression, QueryCountMode, QueryInclude, QueryPage, QuerySort, QueryValueInput } from "@hpd/base-client";
import type { ${plan.collections.map(collection => `${collection.typeName}ComparableFieldPath, ${collection.typeName}FieldPath, ${collection.typeName}StringFieldPath`).join(", ")} } from "./types.js";

export type TypedQueryHelpers<
  TField extends string,
  TComparable extends TField,
  TString extends TField,
  TFilter extends boolean = true,
  TSort extends boolean = true
> =
  (TFilter extends true ? {
  eq(field: TField, value: QueryValueInput): FilterExpression;
  neq(field: TField, value: QueryValueInput): FilterExpression;
  lt(field: TComparable, value: QueryValueInput): FilterExpression;
  lte(field: TComparable, value: QueryValueInput): FilterExpression;
  gt(field: TComparable, value: QueryValueInput): FilterExpression;
  gte(field: TComparable, value: QueryValueInput): FilterExpression;
  contains(field: TString, value: QueryValueInput): FilterExpression;
  startsWith(field: TString, value: string): FilterExpression;
  endsWith(field: TString, value: string): FilterExpression;
  in(field: TField, values: QueryValueInput[]): FilterExpression;
  between(field: TComparable, min: QueryValueInput, max: QueryValueInput): FilterExpression;
  isNull(field: TField): FilterExpression;
  isDefined(field: TField): FilterExpression;
  and(...children: FilterExpression[]): FilterExpression;
  or(...children: FilterExpression[]): FilterExpression;
  not(child: FilterExpression): FilterExpression;
  } : {}) &
  (TSort extends true ? {
  sortAsc(field: TField): QuerySort;
  sortDesc(field: TField): QuerySort;
  } : {});

export type TypedRecordQueryInput<
  TField extends string,
  TFilter extends boolean = true,
  TSort extends boolean = true,
  TSelect extends boolean = true,
  TInclude extends boolean = true
> =
  (TFilter extends true ? {
    where?: FilterExpression | ((q: TypedQueryHelpers<TField, Extract<TField, string>, Extract<TField, string>, TFilter, TSort>) => FilterExpression);
    filter?: FilterExpression | ((q: TypedQueryHelpers<TField, Extract<TField, string>, Extract<TField, string>, TFilter, TSort>) => FilterExpression);
  } : {}) &
  (TSort extends true ? {
    sort?: QuerySort | QuerySort[];
  } : {}) &
  (TSelect extends true ? {
    select?: TField[];
  } : {}) &
  (TInclude extends true ? {
    include?: QueryInclude | QueryInclude[];
  } : {}) & {
  page?: QueryPage;
  count?: QueryCountMode;
  requestDependencyToken?: boolean;
  dependencyToken?: boolean;
};

export function typedQ<TField extends string, TComparable extends TField, TString extends TField, TFilter extends boolean = true, TSort extends boolean = true>(): TypedQueryHelpers<TField, TComparable, TString, TFilter, TSort> {
  return baseQ as unknown as TypedQueryHelpers<TField, TComparable, TString, TFilter, TSort>;
}

${aliases}
`;
}

function renderMetadata(plan: GenerationPlan): string {
  const collectionEntries = plan.collections.map(collection => `    ${stringLiteral(collection.id)}: {
      id: ${stringLiteral(collection.id)},
      propertyName: ${stringLiteral(collection.propertyName)},
      operations: ${JSON.stringify(collection.availableOperations)},
      routes: ${JSON.stringify(collection.routes)}
    }`).join(",\n");
  return `
export const baseGeneratedMetadata = {
  snapshotVersion: "1",
  contractVersion: ${stringLiteral(plan.snapshot.manifest.contractVersion ?? plan.snapshot.schema.contractVersion ?? "1.0")},
  collections: {
${collectionEntries}
  }
} as const;

export type BaseGeneratedMetadata = typeof baseGeneratedMetadata;
export type KnownCollectionId = keyof BaseGeneratedMetadata["collections"];
export type GeneratedCollectionMetadata<TId extends KnownCollectionId> = BaseGeneratedMetadata["collections"][TId];
`;
}

function renderClient(plan: GenerationPlan): string {
  const imports = plan.collections.flatMap(collection => [
    collection.typeName,
    `${collection.typeName}Create`,
    `${collection.typeName}FieldPath`,
    `${collection.typeName}Patch`,
    `${collection.typeName}Replace`
  ]).join(", ");
  const queryImports = plan.collections.map(collection => `${collection.typeName}QueryInput`).join(", ");
  const interfaces = plan.collections.map(collection => renderCollectionInterface(plan, collection)).join("\n\n");
  const collectionMap = plan.config.emitExactCollectionsMap ? plan.collections.map(collection => `  readonly ${stringLiteral(collection.id)}: ${collection.typeName}CollectionClient;`).join("\n") : "";
  const properties = plan.collections.map(collection => `  readonly ${collection.propertyName}: ${collection.typeName}CollectionClient;`).join("\n");
  const overloads = plan.collections.map(collection => `  collection(id: ${stringLiteral(collection.id)}): ${collection.typeName}CollectionClient;`).join("\n");
  const functionOverloads = plan.collections.map(collection => `  function collection(id: ${stringLiteral(collection.id)}): ${collection.typeName}CollectionClient;`).join("\n");
  const vars = plan.collections.map(collection => `  const ${collection.variableName} = create${collection.typeName}Collection(base.collection<${collection.typeName}>(${stringLiteral(collection.id)}));`).join("\n");
  const returns = plan.collections.map(collection => `    ${collection.propertyName},`).join("\n");
  const exactReturns = plan.collections.map(collection => `      case ${stringLiteral(collection.id)}: return ${collection.variableName};`).join("\n");
  const mapEntries = plan.config.emitExactCollectionsMap ? plan.collections.map(collection => `      ${stringLiteral(collection.id)}: ${collection.variableName}`).join(",\n") : "";
  const factories = plan.collections.map(collection => renderCollectionFactory(plan, collection)).join("\n\n");
  const collectionsInterface = plan.config.emitExactCollectionsMap ? `
export interface GeneratedCollections {
${collectionMap}
}

export type KnownGeneratedCollection = GeneratedCollections[KnownCollectionId];
` : `
export type GeneratedCollections = never;
export type KnownGeneratedCollection = never;
`;
  const collectionsProperty = plan.config.emitExactCollectionsMap ? "  readonly collections: GeneratedCollections;" : "";
  const collectionsReturn = plan.config.emitExactCollectionsMap ? `    collections: {
${mapEntries}
    },` : "";
  return `
import type {
  BaseResult,
  CollectionClient,
  CollectionDefinition,
  CollectionOperation,
  CreateOptions,
  DeleteOptions,
  DeleteResult,
  HpdBaseClient,
  ListRequestOptions,
  MutationOptions,
  RecordEnvelope,
  RecordPage,
  RequestOptions,
  SupportsOptions
} from "@hpd/base-client";
import { baseGeneratedMetadata } from "./metadata.js";
import type { GeneratedCollectionMetadata, KnownCollectionId } from "./metadata.js";
import type { ${queryImports} } from "./query.js";
import type { ${imports} } from "./types.js";

${interfaces}

${collectionsInterface}

export interface ${plan.config.clientName} {
  readonly $base: HpdBaseClient;
  readonly $metadata: typeof baseGeneratedMetadata;
${collectionsProperty}
${properties}
${overloads}
  collection(id: string): CollectionClient;
}

export function createGeneratedBaseClient(base: HpdBaseClient): ${plan.config.clientName} {
${vars}

${functionOverloads}
  function collection(id: string): CollectionClient;
  function collection(id: string): unknown {
    switch (id) {
${exactReturns}
      default: return base.collection(id);
    }
  }

  return {
    $base: base,
    $metadata: baseGeneratedMetadata,
${collectionsReturn}
${returns}
    collection
  };
}

function unsupportedMethod(operation: string): never {
  throw new Error(\`HPD.BASE collection operation "\${operation}" is not supported by this generated snapshot.\`);
}

${factories}
`;
}

function renderCollectionInterface(plan: GenerationPlan, collection: PlannedCollection): string {
  return `
export interface ${collection.typeName}CollectionClient {
  readonly id: ${stringLiteral(collection.id)};
  readonly $generic: CollectionClient<${collection.typeName}>;
  readonly $metadata: GeneratedCollectionMetadata<${stringLiteral(collection.id)}>;
${collection.operations.map(operation => renderMethodSignatures(plan, collection, operation)).join("\n")}
  definition(options?: RequestOptions): Promise<CollectionDefinition>;
${plan.config.emitResultMethods ? "  definitionResult(options?: RequestOptions): Promise<BaseResult<CollectionDefinition>>;" : ""}
  supports(operation: CollectionOperation, options?: SupportsOptions): boolean | undefined;
}`;
}

function renderMethodSignatures(plan: GenerationPlan, collection: PlannedCollection, operation: RecordOperation): string {
  const t = collection.typeName;
  const resultMethods = plan.config.emitResultMethods;
  switch (operation) {
    case "list": return `  list(query?: ${t}QueryInput, options?: ListRequestOptions): Promise<RecordPage<${t}>>;${resultMethods ? `\n  listResult(query?: ${t}QueryInput, options?: ListRequestOptions): Promise<BaseResult<RecordPage<${t}>>>;` : ""}`;
    case "query": return `  query(query?: ${t}QueryInput, options?: RequestOptions): Promise<RecordPage<${t}>>;${resultMethods ? `\n  queryResult(query?: ${t}QueryInput, options?: RequestOptions): Promise<BaseResult<RecordPage<${t}>>>;` : ""}`;
    case "get": return `  get(id: string, options?: RequestOptions): Promise<RecordEnvelope<${t}>>;
${resultMethods ? `  getResult(id: string, options?: RequestOptions): Promise<BaseResult<RecordEnvelope<${t}>>>;` : ""}`;
    case "create": return `  create(input: ${t}Create, options?: CreateOptions): Promise<RecordEnvelope<${t}>>;
${resultMethods ? `  createResult(input: ${t}Create, options?: CreateOptions): Promise<BaseResult<RecordEnvelope<${t}>>>;` : ""}`;
    case "patch": return `  patch(id: string, input: ${t}Patch, options?: MutationOptions): Promise<RecordEnvelope<${t}>>;
${resultMethods ? `  patchResult(id: string, input: ${t}Patch, options?: MutationOptions): Promise<BaseResult<RecordEnvelope<${t}>>>;` : ""}`;
    case "replace": return `  replace(id: string, input: ${t}Replace, options?: MutationOptions): Promise<RecordEnvelope<${t}>>;
${resultMethods ? `  replaceResult(id: string, input: ${t}Replace, options?: MutationOptions): Promise<BaseResult<RecordEnvelope<${t}>>>;` : ""}`;
    case "delete": return `  delete(id: string, options?: DeleteOptions): Promise<DeleteResult<${t}>>;
${resultMethods ? `  deleteResult(id: string, options?: DeleteOptions): Promise<BaseResult<DeleteResult<${t}>>>;` : ""}`;
  }
}

function renderCollectionFactory(plan: GenerationPlan, collection: PlannedCollection): string {
  const methods = collection.operations.map(operation => renderMethodImplementation(plan, collection, operation)).filter(Boolean).join(",\n");
  const definitionResult = plan.config.emitResultMethods ? "    definitionResult: options => generic.definitionResult(options),\n" : "";
  return `
function create${collection.typeName}Collection(generic: CollectionClient<${collection.typeName}>): ${collection.typeName}CollectionClient {
  return {
    id: ${stringLiteral(collection.id)},
    $generic: generic,
    $metadata: baseGeneratedMetadata.collections[${stringLiteral(collection.id)}],
${methods ? `${methods},` : ""}
    definition: options => generic.definition(options),
${definitionResult}    supports: (operation, options) => generic.supports(operation, options)
  };
}`;
}

function renderMethodImplementation(plan: GenerationPlan, collection: PlannedCollection, operation: RecordOperation): string {
  if (!collection.availableOperations.includes(operation)) return renderUnsupportedMethodImplementation(plan, operation);
  const resultMethods = plan.config.emitResultMethods;
  switch (operation) {
    case "list": return resultMethods ? `    list: (query, options) => generic.list(query as never, options),
    listResult: (query, options) => generic.listResult(query as never, options)` : "    list: (query, options) => generic.list(query as never, options)";
    case "query": return resultMethods ? `    query: (query, options) => generic.query(query as never, options),
    queryResult: (query, options) => generic.queryResult(query as never, options)` : "    query: (query, options) => generic.query(query as never, options)";
    case "get": return resultMethods ? `    get: (id, options) => generic.get(id, options),
    getResult: (id, options) => generic.getResult(id, options)` : "    get: (id, options) => generic.get(id, options)";
    case "create": return resultMethods ? `    create: (input, options) => generic.create(input, options),
    createResult: (input, options) => generic.createResult(input, options)` : "    create: (input, options) => generic.create(input, options)";
    case "patch": return resultMethods ? `    patch: (id, input, options) => generic.patch(id, input, options),
    patchResult: (id, input, options) => generic.patchResult(id, input, options)` : "    patch: (id, input, options) => generic.patch(id, input, options)";
    case "replace": return resultMethods ? `    replace: (id, input, options) => generic.replace(id, input, options),
    replaceResult: (id, input, options) => generic.replaceResult(id, input, options)` : "    replace: (id, input, options) => generic.replace(id, input, options)";
    case "delete": return resultMethods ? `    delete: (id, options) => generic.delete(id, options),
    deleteResult: (id, options) => generic.deleteResult(id, options)` : "    delete: (id, options) => generic.delete(id, options)";
  }
}

function renderUnsupportedMethodImplementation(plan: GenerationPlan, operation: RecordOperation): string {
  const thrower = `unsupportedMethod(${stringLiteral(operation)})`;
  const resultMethod = `${operation}Result`;
  switch (operation) {
    case "list": return `    list: () => ${thrower}${plan.config.emitResultMethods ? `,\n    ${resultMethod}: () => ${thrower}` : ""}`;
    case "query": return `    query: () => ${thrower}${plan.config.emitResultMethods ? `,\n    ${resultMethod}: () => ${thrower}` : ""}`;
    case "get": return `    get: () => ${thrower}${plan.config.emitResultMethods ? `,\n    ${resultMethod}: () => ${thrower}` : ""}`;
    case "create": return `    create: () => ${thrower}${plan.config.emitResultMethods ? `,\n    ${resultMethod}: () => ${thrower}` : ""}`;
    case "patch": return `    patch: () => ${thrower}${plan.config.emitResultMethods ? `,\n    ${resultMethod}: () => ${thrower}` : ""}`;
    case "replace": return `    replace: () => ${thrower}${plan.config.emitResultMethods ? `,\n    ${resultMethod}: () => ${thrower}` : ""}`;
    case "delete": return `    delete: () => ${thrower}${plan.config.emitResultMethods ? `,\n    ${resultMethod}: () => ${thrower}` : ""}`;
  }
}

function optionalProperty(field: PlannedField, input: boolean): string {
  const optional = !field.required || input ? "?" : "";
  return `${JSON.stringify(field.propertyName)}${optional}`;
}

function writable(field: PlannedField): boolean {
  return field.updateWritable;
}

function writableInCreate(field: PlannedField): boolean {
  return field.createWritable;
}

function union(values: string[]): string {
  return values.length === 0 ? "never" : values.map(value => stringLiteral(value)).join(" | ");
}
