using System.Collections.Immutable;
using HPD.Payments.Analyzers;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Diagnostics;

var tests = new (string Name, Action Run)[]
{
    ("stable diagnostic catalog and OWN mapping", StableCatalog),
    ("positive and negative fixtures", PositiveAndNegative),
    ("duplicate discriminator", DuplicateDiscriminator),
    ("alias generic closure exception generated", ContextCoverage),
    ("bounded code fixes", BoundedFixes),
    ("analyzer does not certify behavior", NeverCertifies),
};
foreach (var test in tests) { test.Run(); Console.WriteLine($"PASS {test.Name}"); }

static void StableCatalog()
{
    var ids = new PaymentsSemanticAnalyzer().SupportedDiagnostics.Select(d => d.Id).ToArray();
    Equal(string.Join(',', Enumerable.Range(1, 12).Select(i => $"HPDPA{i:000}")), string.Join(',', ids), "stable IDs");
    True(ids.Distinct(StringComparer.Ordinal).Count() == 12, "unique IDs");
}

static void PositiveAndNegative()
{
    const string bad = """
using System; using System.Diagnostics.CodeAnalysis; using System.Reflection;
sealed class DiscriminatorAttribute : Attribute { public DiscriminatorAttribute(string x) {} }
[Discriminator(nameof(Bad))] sealed class Bad {
 [SuppressMessage("x","y")] public void MutateAuthority() { Environment.GetEnvironmentVariable("TENANT"); Activator.CreateInstance(typeof(Bad)); Claim("x"); ClaimAll(); Return(rented); var x = new System.Collections.Concurrent.ConcurrentDictionary<int,int>(); var y = 1 switch { 1 => 2 }; }
 static byte[] rented = []; static void Return(byte[] x) {}
 static void Claim(string x) {} static void ClaimAll() {}
 public Span<byte> Borrowed() => Span<byte>.Empty;
 public PaymentResult Result() => default;
}
readonly struct PaymentResult {}
""";
    var ids = Analyze(bad).Select(d => d.Id).Distinct().Order().ToArray();
    foreach (var id in Enumerable.Range(1, 12).Select(i => $"HPDPA{i:000}")) True(ids.Contains(id), "missing " + id);
    Equal(0, Analyze("sealed class Safe { int Map(int x) => x switch { 0 => 1, _ => 2 }; }").Length, "negative fixture");
}

static void DuplicateDiscriminator()
{
    const string source = "using System; sealed class DiscriminatorAttribute:Attribute { public DiscriminatorAttribute(string x){} } [Discriminator(\"wire-a\")] class A{} [Discriminator(\"wire-a\")] class B{}";
    Equal(1, Analyze(source).Count(d => d.Id == "HPDPA002"), "duplicate");
}

static void ContextCoverage()
{
    const string source = """
using System; using Alias = System.Activator;
// <auto-generated/>
sealed class G<T> { public Span<T> Escape() => Span<T>.Empty; public object Closure() { Func<object> f = () => Alias.CreateInstance(typeof(G<T>))!; try { return f(); } catch { throw; } } }
""";
    var ids = Analyze(source).Select(d => d.Id).ToArray();
    True(ids.Contains("HPDPA004"), "generic borrowed escape");
    True(ids.Contains("HPDPA007"), "alias/closure/exception/generated activation");
}

static void BoundedFixes()
{
    Equal(3, PaymentsCodeFixCatalog.FixableDiagnosticIds.Length, "bounded count");
    True(PaymentsCodeFixCatalog.GetRecipe("HPDPA012") is null, "suppression has no automatic fix");
    True(PaymentsCodeFixCatalog.GetRecipe("HPDPA003")!.Contains("explicit parameter", StringComparison.Ordinal), "ambient recipe");
}

static void NeverCertifies()
{
    var text = string.Join(' ', new PaymentsSemanticAnalyzer().SupportedDiagnostics.Select(d => d.Description));
    True(text.Contains("Runtime conformance", StringComparison.Ordinal), "runtime caveat");
    True(!typeof(PaymentsSemanticAnalyzer).Assembly.GetTypes().Any(t => t.Name.Contains("Certificate", StringComparison.Ordinal)), "no certificate emitter");
}

static ImmutableArray<Diagnostic> Analyze(string source)
{
    var compilation = CSharpCompilation.Create("Fixture", [CSharpSyntaxTree.ParseText(source, new CSharpParseOptions(LanguageVersion.Preview))],
        AppDomain.CurrentDomain.GetAssemblies().Where(a => !a.IsDynamic && !string.IsNullOrEmpty(a.Location)).Select(a => MetadataReference.CreateFromFile(a.Location)),
        new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));
    return compilation.WithAnalyzers([new PaymentsSemanticAnalyzer()]).GetAnalyzerDiagnosticsAsync().GetAwaiter().GetResult();
}

static void Equal<T>(T expected, T actual, string name) where T : notnull { if (!EqualityComparer<T>.Default.Equals(expected, actual)) throw new InvalidOperationException($"{name}: expected {expected}, actual {actual}"); }
static void True(bool condition, string name) { if (!condition) throw new InvalidOperationException(name); }
