<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsAotCompatible>true</IsAotCompatible>
    <AssemblyName>hpd-applevz</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../HPD-Execution.AppleVirtualization.DevKit/HPD-Execution.AppleVirtualization.DevKit.csproj" />
    <ProjectReference Include="../HPD-Execution.Contracts/HPD-Execution.Contracts.csproj" />
  </ItemGroup>
</Project>
