using HPD.Base;

namespace HPD.Auth.Base;

internal static class AuthRecoveryCodesReplaceRequestFactory
{
    internal static AuthRecoveryCodesReplaceV1 Create(
        Guid tenantId,
        Guid userId,
        RevisionToken expectedUserRevision,
        IReadOnlyList<AuthRecoveryPriorSlotV1> priorCodes,
        IReadOnlyList<AuthRecoveryNewSlotV1> newCodes,
        string securityStamp,
        string concurrencyStamp,
        DateTimeOffset operationTime)
    {
        ArgumentNullException.ThrowIfNull(priorCodes);
        ArgumentNullException.ThrowIfNull(newCodes);
        if (priorCodes.Count != 64 || newCodes.Count != 64)
            throw new ArgumentException("Recovery-code replacement requires exactly 64 canonical slots.");
        return new AuthRecoveryCodesReplaceV1
        {
            New00 = newCodes[0],
            New01 = newCodes[1],
            New02 = newCodes[2],
            New03 = newCodes[3],
            New04 = newCodes[4],
            New05 = newCodes[5],
            New06 = newCodes[6],
            New07 = newCodes[7],
            New08 = newCodes[8],
            New09 = newCodes[9],
            New10 = newCodes[10],
            New11 = newCodes[11],
            New12 = newCodes[12],
            New13 = newCodes[13],
            New14 = newCodes[14],
            New15 = newCodes[15],
            New16 = newCodes[16],
            New17 = newCodes[17],
            New18 = newCodes[18],
            New19 = newCodes[19],
            New20 = newCodes[20],
            New21 = newCodes[21],
            New22 = newCodes[22],
            New23 = newCodes[23],
            New24 = newCodes[24],
            New25 = newCodes[25],
            New26 = newCodes[26],
            New27 = newCodes[27],
            New28 = newCodes[28],
            New29 = newCodes[29],
            New30 = newCodes[30],
            New31 = newCodes[31],
            New32 = newCodes[32],
            New33 = newCodes[33],
            New34 = newCodes[34],
            New35 = newCodes[35],
            New36 = newCodes[36],
            New37 = newCodes[37],
            New38 = newCodes[38],
            New39 = newCodes[39],
            New40 = newCodes[40],
            New41 = newCodes[41],
            New42 = newCodes[42],
            New43 = newCodes[43],
            New44 = newCodes[44],
            New45 = newCodes[45],
            New46 = newCodes[46],
            New47 = newCodes[47],
            New48 = newCodes[48],
            New49 = newCodes[49],
            New50 = newCodes[50],
            New51 = newCodes[51],
            New52 = newCodes[52],
            New53 = newCodes[53],
            New54 = newCodes[54],
            New55 = newCodes[55],
            New56 = newCodes[56],
            New57 = newCodes[57],
            New58 = newCodes[58],
            New59 = newCodes[59],
            New60 = newCodes[60],
            New61 = newCodes[61],
            New62 = newCodes[62],
            New63 = newCodes[63],
            Prior00 = priorCodes[0],
            Prior01 = priorCodes[1],
            Prior02 = priorCodes[2],
            Prior03 = priorCodes[3],
            Prior04 = priorCodes[4],
            Prior05 = priorCodes[5],
            Prior06 = priorCodes[6],
            Prior07 = priorCodes[7],
            Prior08 = priorCodes[8],
            Prior09 = priorCodes[9],
            Prior10 = priorCodes[10],
            Prior11 = priorCodes[11],
            Prior12 = priorCodes[12],
            Prior13 = priorCodes[13],
            Prior14 = priorCodes[14],
            Prior15 = priorCodes[15],
            Prior16 = priorCodes[16],
            Prior17 = priorCodes[17],
            Prior18 = priorCodes[18],
            Prior19 = priorCodes[19],
            Prior20 = priorCodes[20],
            Prior21 = priorCodes[21],
            Prior22 = priorCodes[22],
            Prior23 = priorCodes[23],
            Prior24 = priorCodes[24],
            Prior25 = priorCodes[25],
            Prior26 = priorCodes[26],
            Prior27 = priorCodes[27],
            Prior28 = priorCodes[28],
            Prior29 = priorCodes[29],
            Prior30 = priorCodes[30],
            Prior31 = priorCodes[31],
            Prior32 = priorCodes[32],
            Prior33 = priorCodes[33],
            Prior34 = priorCodes[34],
            Prior35 = priorCodes[35],
            Prior36 = priorCodes[36],
            Prior37 = priorCodes[37],
            Prior38 = priorCodes[38],
            Prior39 = priorCodes[39],
            Prior40 = priorCodes[40],
            Prior41 = priorCodes[41],
            Prior42 = priorCodes[42],
            Prior43 = priorCodes[43],
            Prior44 = priorCodes[44],
            Prior45 = priorCodes[45],
            Prior46 = priorCodes[46],
            Prior47 = priorCodes[47],
            Prior48 = priorCodes[48],
            Prior49 = priorCodes[49],
            Prior50 = priorCodes[50],
            Prior51 = priorCodes[51],
            Prior52 = priorCodes[52],
            Prior53 = priorCodes[53],
            Prior54 = priorCodes[54],
            Prior55 = priorCodes[55],
            Prior56 = priorCodes[56],
            Prior57 = priorCodes[57],
            Prior58 = priorCodes[58],
            Prior59 = priorCodes[59],
            Prior60 = priorCodes[60],
            Prior61 = priorCodes[61],
            Prior62 = priorCodes[62],
            Prior63 = priorCodes[63],
            TenantId = tenantId,
            UserId = userId,
            ExpectedUserRevision = expectedUserRevision,
            PriorCount = priorCodes.Count(static slot => slot.Active),
            NewCount = newCodes.Count(static slot => slot.Active),
            SecurityStamp = securityStamp,
            ConcurrencyStamp = concurrencyStamp,
            OperationTime = operationTime,
        };
    }
}
