<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Rhodium.Primitives\Rhodium.Primitives.csproj" />
    <ProjectReference Include="..\Rhodium.Unsafe\Rhodium.Unsafe.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Rhodium.Kernel" />
    <InternalsVisibleTo Include="Rhodium.Tensor.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Numerics.Tensors" Version="9.0.0" />
  </ItemGroup>

</Project>
