using System.Formats.Cbor;
using HPD.Agent.Authority;
namespace HPD.Agent.Audio.Authority;

internal sealed record LiveAudioRuntimePlanV1
{
 internal LiveAudioRuntimePlanV1(LiveAudioPlanId planId,Hash256 planHash,uint compilerVersion,Hash256 providerCatalogHash,IEnumerable<ParticipantDescriptorV1> participants,LoweredConstraintSetV1 constraints,IEnumerable<CapacityChargeTemplateV1> chargeTemplates,Hash256 applicabilityManifestHash,SchemaReferenceV1 privacyPolicyReference,Hash256 supportManifestReference)
 {ArgumentNullException.ThrowIfNull(participants);ArgumentNullException.ThrowIfNull(chargeTemplates);var p=participants.ToArray();var c=chargeTemplates.ToArray();if(!planId.IsValid||!Valid(planHash)||!Valid(providerCatalogHash)||p.Length>256||!ParticipantsStrict(p)||constraints is null||c.Length>256||!ChargesStrict(c)||!Valid(applicabilityManifestHash)||!privacyPolicyReference.IsValid||!Valid(supportManifestReference))throw new ArgumentException("Invalid live audio runtime plan.");PlanId=planId;PlanHash=planHash;CompilerVersion=compilerVersion;ProviderCatalogHash=providerCatalogHash;Participants=Array.AsReadOnly(p);Constraints=constraints;ChargeTemplates=Array.AsReadOnly(c);ApplicabilityManifestHash=applicabilityManifestHash;PrivacyPolicyReference=privacyPolicyReference;SupportManifestReference=supportManifestReference;}
 internal LiveAudioPlanId PlanId{get;}internal Hash256 PlanHash{get;}internal uint CompilerVersion{get;}internal Hash256 ProviderCatalogHash{get;}internal IReadOnlyList<ParticipantDescriptorV1> Participants{get;}internal LoweredConstraintSetV1 Constraints{get;}internal IReadOnlyList<CapacityChargeTemplateV1> ChargeTemplates{get;}internal Hash256 ApplicabilityManifestHash{get;}internal SchemaReferenceV1 PrivacyPolicyReference{get;}internal Hash256 SupportManifestReference{get;}
 private static bool Valid(Hash256 h){Span<byte>b=stackalloc byte[32];return h.TryWriteBytes(b);}private static bool ParticipantsStrict(ParticipantDescriptorV1[]a){Span<byte>x=stackalloc byte[16];Span<byte>y=stackalloc byte[16];for(var i=1;i<a.Length;i++){a[i-1].ParticipantId.TryWriteBytes(x);a[i].ParticipantId.TryWriteBytes(y);if(x.SequenceCompareTo(y)>=0)return false;}return true;}private static bool ChargesStrict(CapacityChargeTemplateV1[]a){for(var i=1;i<a.Length;i++)if(a[i-1].DimensionId>=a[i].DimensionId)return false;return true;}
}

internal static class LiveAudioRuntimePlanCodecsV1
{
 internal const string SchemaId="hpd.live-audio-runtime-plan.v1";
 internal static byte[] Encode(LiveAudioRuntimePlanV1 v){ArgumentNullException.ThrowIfNull(v);var w=W();w.WriteStartMap(10);T(w,1);Id(w,v.PlanId.TryWriteBytes);T(w,2);Hash(w,v.PlanHash);T(w,3);w.WriteUInt64(v.CompilerVersion);T(w,4);Hash(w,v.ProviderCatalogHash);T(w,5);w.WriteStartArray(v.Participants.Count);foreach(var p in v.Participants)Participant(w,p);w.WriteEndArray();T(w,6);Constraints(w,v.Constraints);T(w,7);w.WriteStartArray(v.ChargeTemplates.Count);foreach(var c in v.ChargeTemplates)Charge(w,c);w.WriteEndArray();T(w,8);Hash(w,v.ApplicabilityManifestHash);T(w,9);w.WriteEncodedValue(AuthorityEnvelopePrimitiveCodecsV1.Encode(v.PrivacyPolicyReference));T(w,10);Hash(w,v.SupportManifestReference);w.WriteEndMap();return w.Encode();}
 internal static bool TryDecode(ReadOnlyMemory<byte>b,out LiveAudioRuntimePlanV1? v){v=null;try{var r=new CborReader(b,CborConformanceMode.Ctap2Canonical,false);if(r.ReadStartMap()!=10)return false;N(r,1);var id=LiveAudioPlanId.FromValue(ReadId(r));N(r,2);var plan=ReadHash(r);N(r,3);var compiler=checked((uint)r.ReadUInt64());N(r,4);var catalog=ReadHash(r);N(r,5);var pn=r.ReadStartArray();if(pn is null or<0 or>256)return false;var ps=new ParticipantDescriptorV1[pn.Value];for(var i=0;i<ps.Length;i++)ps[i]=ReadParticipant(r);r.ReadEndArray();N(r,6);var constraints=ReadConstraints(r);N(r,7);var cn=r.ReadStartArray();if(cn is null or<0 or>256)return false;var cs=new CapacityChargeTemplateV1[cn.Value];for(var i=0;i<cs.Length;i++)cs[i]=ReadCharge(r);r.ReadEndArray();N(r,8);var applicability=ReadHash(r);N(r,9);if(!AuthorityEnvelopePrimitiveCodecsV1.TryDecodeSchemaReference(r.ReadEncodedValue(),out var policy))return false;N(r,10);var support=ReadHash(r);r.ReadEndMap();var x=new LiveAudioRuntimePlanV1(id,plan,compiler,catalog,ps,constraints,cs,applicability,policy,support);if(r.BytesRemaining!=0||!Encode(x).AsSpan().SequenceEqual(b.Span))return false;v=x;return true;}catch(Exception e)when(e is CborContentException or InvalidOperationException or ArgumentException or OverflowException){return false;}}
 internal static Hash256 ComputeHash(LiveAudioRuntimePlanV1 v)=>AuthorityIntegrityHashV1.Compute(SchemaId,1,0,Encode(v));
 private static void Participant(CborWriter w,ParticipantDescriptorV1 p){w.WriteStartMap(5);T(w,1);Id(w,p.ParticipantId.TryWriteBytes);T(w,2);w.WriteUInt64((ushort)p.Owner);T(w,3);w.WriteEncodedValue(AuthorityEnvelopePrimitiveCodecsV1.Encode(p.DescriptorSchema));T(w,4);w.WriteStartArray(p.Dependencies.Count);foreach(var x in p.Dependencies)Id(w,x.TryWriteBytes);w.WriteEndArray();T(w,5);Hash(w,p.DescriptorHash);w.WriteEndMap();}
 private static ParticipantDescriptorV1 ReadParticipant(CborReader r){if(r.ReadStartMap()!=5)throw B();N(r,1);var id=ParticipantId.FromValue(ReadId(r));N(r,2);var owner=checked((OwnerSliceId)r.ReadUInt64());N(r,3);if(!AuthorityEnvelopePrimitiveCodecsV1.TryDecodeSchemaReference(r.ReadEncodedValue(),out var schema))throw B();N(r,4);var n=r.ReadStartArray();if(n is null or<0 or>256)throw B();var d=new ParticipantId[n.Value];for(var i=0;i<d.Length;i++)d[i]=ParticipantId.FromValue(ReadId(r));r.ReadEndArray();N(r,5);var hash=ReadHash(r);r.ReadEndMap();return new(id,owner,schema,d,hash);}
 private static void Constraints(CborWriter w,LoweredConstraintSetV1 c){w.WriteStartMap(3);T(w,1);w.WriteEncodedValue(AuthorityEnvelopePrimitiveCodecsV1.Encode(c.Schema));T(w,2);w.WriteByteString(c.Bytes);T(w,3);Hash(w,c.Hash);w.WriteEndMap();}
 private static LoweredConstraintSetV1 ReadConstraints(CborReader r){if(r.ReadStartMap()!=3)throw B();N(r,1);if(!AuthorityEnvelopePrimitiveCodecsV1.TryDecodeSchemaReference(r.ReadEncodedValue(),out var schema))throw B();N(r,2);var bytes=r.ReadByteString();if(bytes.Length>65_536)throw B();N(r,3);var hash=ReadHash(r);r.ReadEndMap();return new(schema,bytes,hash);}
 private static void Charge(CborWriter w,CapacityChargeTemplateV1 c){w.WriteStartMap(4);T(w,1);w.WriteUInt64(c.DimensionId);T(w,2);w.WriteUInt64((ushort)c.ScopeKind);T(w,3);w.WriteInt64(c.MaximumAmount);T(w,4);Id(w,c.Purpose.TryWriteBytes);w.WriteEndMap();}
 private static CapacityChargeTemplateV1 ReadCharge(CborReader r){if(r.ReadStartMap()!=4)throw B();N(r,1);var dimension=checked((ushort)r.ReadUInt64());N(r,2);var scope=checked((CapacityScopeKindV1)r.ReadUInt64());N(r,3);var amount=r.ReadInt64();N(r,4);var purpose=CapacityPurposeId.FromValue(ReadId(r));r.ReadEndMap();return new(dimension,scope,amount,purpose);}
 private delegate bool WriteId(Span<byte>b);private static void Id(CborWriter w,WriteId f){Span<byte>b=stackalloc byte[16];if(!f(b))throw new ArgumentException();w.WriteByteString(b);}private static StableId128 ReadId(CborReader r){Span<byte>b=stackalloc byte[16];if(!r.TryReadByteString(b,out var n)||n!=16)throw B();return StableId128.FromBytes(b);}private static void Hash(CborWriter w,Hash256 h){Span<byte>b=stackalloc byte[32];if(!h.TryWriteBytes(b))throw new ArgumentException();w.WriteByteString(b);}private static Hash256 ReadHash(CborReader r){Span<byte>b=stackalloc byte[32];if(!r.TryReadByteString(b,out var n)||n!=32)throw B();return Hash256.FromBytes(b);}private static CborWriter W()=>new(CborConformanceMode.Ctap2Canonical);private static void T(CborWriter w,ulong n)=>w.WriteUInt64(n);private static void N(CborReader r,ulong n){if(r.ReadUInt64()!=n)throw B();}private static CborContentException B()=>new("Invalid live audio runtime plan encoding.");
}
