using Microsoft.AspNetCore.Routing;
using Microsoft.Extensions.DependencyInjection;

namespace HPD.Agent.Bots.AspNetCore.EndpointMapping;

/// <summary>
/// Convenience extension for mapping all registered adapters at once.
/// </summary>
public static class BotEndpointRouteBuilderExtensions
{
    /// <summary>
    /// Maps every adapter registered in the assembly via <see cref="HpdBotAttribute"/>
    /// to its default webhook path.
    /// </summary>
    /// <remarks>
    /// Equivalent to calling <c>MapXxxWebhook()</c> for each adapter individually.
    /// Uses the assembly-scoped <c>BotRegistry.All</c> array generated by the
    /// source generator — zero reflection after startup.
    /// </remarks>
    /// <example>
    /// <code>
    /// // Map all adapters at their default paths:
    /// app.MapHPDBots();
    ///
    /// // Or map individually with custom paths:
    /// app.MapSlackWebhook("/webhooks/slack");
    /// app.MapTeamsWebhook("/webhooks/teams");
    /// </code>
    /// </example>
    public static IEndpointRouteBuilder MapHPDBots(this IEndpointRouteBuilder app)
    {
        // BotRegistry.All is generated by the source generator at compile time.
        // This method is a no-op if no adapters are registered in the calling assembly.
        // Each adapter's MapEndpoint delegate calls the generated MapXxxWebhook() extension.
        foreach (var registration in GetRegistrations(app))
        {
            registration.MapEndpoint(app, registration.DefaultPath);
        }

        return app;
    }

    // Returns BotRegistry.All from the calling assembly via the generated type.
    // Resolved via a partial method so the generator can inject the right assembly reference.
    private static IEnumerable<BotRegistration> GetRegistrations(IEndpointRouteBuilder app)
    {
        // The generator emits BotRegistry in namespace HPD.Agent.Bots.Generated.
        // We resolve it here by convention. If none are registered, returns empty.
        return app.ServiceProvider
            .GetServices<IBotRegistryProvider>()
            .SelectMany(provider => provider.GetAll());
    }
}
