using System.Formats.Cbor;
using System.Security.Cryptography;
using System.Text;

namespace HPD.Agent.Authority;

internal static class GlobalParticipantAllocatorCodecsV1
{
    internal const int MaximumOuterBytes=8192, MaximumBodyBytes=7168, MaximumProofPathBytes=4096;
    internal static byte[] CreateEmptyProofPath(){var absent=Encoding.UTF8.GetBytes("hpd-s1-global-participant-absent-leaf-v1\0");var node=Encoding.UTF8.GetBytes("hpd-s1-global-participant-owner-node-v1\0");var current=SHA256.HashData(absent);var path=new byte[4096];for(var depth=1;depth<=128;depth++){current.CopyTo(path,(depth-1)*32);var p=new byte[node.Length+65];node.CopyTo(p,0);p[node.Length]=(byte)depth;current.CopyTo(p,node.Length+1);current.CopyTo(p,node.Length+33);current=SHA256.HashData(p);}return path;}
    internal static Hash256 EmptyIndexRoot(){var path=CreateEmptyProofPath();var node=Encoding.UTF8.GetBytes("hpd-s1-global-participant-owner-node-v1\0");var current=path.AsSpan(0,32).ToArray();for(var depth=1;depth<=128;depth++){var sibling=path.AsSpan((depth-1)*32,32);var p=new byte[node.Length+65];node.CopyTo(p,0);p[node.Length]=(byte)depth;current.CopyTo(p,node.Length+1);sibling.CopyTo(p.AsSpan(node.Length+33));current=SHA256.HashData(p);}return Hash256.FromBytes(current);}
    internal static bool VerifyProof(ParticipantId participantId,ushort state,ParticipantIdOwnerEvidenceV1? owner,Hash256 root,ReadOnlySpan<byte> path){if(path.Length!=4096)return false;Span<byte> id=stackalloc byte[16];if(!participantId.TryWriteBytes(id))return false;byte[] current;if(state==1){current=SHA256.HashData(Encoding.UTF8.GetBytes("hpd-s1-global-participant-absent-leaf-v1\0"));}else if(state==2&&owner is not null){var evidence=Encode(owner);var domain=Encoding.UTF8.GetBytes("hpd-s1-global-participant-owner-leaf-v1\0");var p=new byte[domain.Length+16+evidence.Length];domain.CopyTo(p,0);id.CopyTo(p.AsSpan(domain.Length));evidence.CopyTo(p,domain.Length+16);current=SHA256.HashData(p);}else return false;var node=Encoding.UTF8.GetBytes("hpd-s1-global-participant-owner-node-v1\0");for(var depth=1;depth<=128;depth++){var sibling=path.Slice((depth-1)*32,32);var p=new byte[node.Length+65];node.CopyTo(p,0);p[node.Length]=(byte)depth;var bit=(id[15-((depth-1)/8)]>>((depth-1)%8))&1;if(bit==0){current.CopyTo(p,node.Length+1);sibling.CopyTo(p.AsSpan(node.Length+33));}else{sibling.CopyTo(p.AsSpan(node.Length+1));current.CopyTo(p,node.Length+33);}current=SHA256.HashData(p);}Span<byte> expected=stackalloc byte[32];return root.TryWriteBytes(expected)&&current.AsSpan().SequenceEqual(expected);}
    internal static bool IsExactEmptyProof(Hash256 root,ReadOnlySpan<byte> path){if(path.Length!=4096||!path.SequenceEqual(CreateEmptyProofPath()))return false;Span<byte>b=stackalloc byte[32];return root.TryWriteBytes(b)&&b.SequenceEqual(HashBytes(EmptyIndexRoot()));}
    private static byte[] HashBytes(Hash256 value){var b=new byte[32];return value.TryWriteBytes(b)?b:Array.Empty<byte>();}
    internal const string OuterSchemaId="hpd.authority-payload-global-participant-claim-record.v1";
    internal static byte[] Encode(GlobalParticipantClaimRecordV1 v){var w=W(3);T(w,1);SessionAuthorityStampV1Codec.Write(w,v.SourceSession);T(w,2);AuthorityVectorCodecsV1.WriteVector(w,v.SourceExpectedAuthority);T(w,3);w.WriteByteString(v.BodyBytes);var encoded=F(w,MaximumOuterBytes);if(encoded.Length-v.BodyBytes.Length>1024)throw X();return encoded;}
    internal static bool TryDecodeOuter(ReadOnlyMemory<byte>b,out GlobalParticipantClaimRecordV1? v){v=null;if(b.Length>MaximumOuterBytes||!PrecheckOuterBody(b))return false;try{var r=R(b);S(r,3);N(r,1);var s=SessionAuthorityStampV1Codec.Read(r);N(r,2);var a=AuthorityVectorCodecsV1.ReadVector(r);N(r,3);var bodyBuffer=new byte[MaximumBodyBytes];if(!r.TryReadByteString(bodyBuffer,out var bodyLength))throw X();var body=bodyBuffer.AsSpan(0,bodyLength).ToArray();r.ReadEndMap();if(r.BytesRemaining!=0||body.Length is <1 or >MaximumBodyBytes||b.Length-body.Length>1024)return false;v=new(s,a,body);return b.Span.SequenceEqual(Encode(v));}catch(Exception e)when(Bad(e)){return false;}}
    internal static byte[] Encode(GlobalParticipantClaimRecordBodyV1 v){var w=W(8);T(w,1);Id(w,v.OperationId);T(w,2);Source(w,v.Source);T(w,3);Id(w,v.ParticipantId);T(w,4);Opt(w,v.PriorHead,Head);T(w,5);Proof(w,v.OwnerProof);T(w,6);Outcome(w,v.Outcome);T(w,7);Position(w,v.AssignedPosition);T(w,8);w.WriteEncodedValue(MonotonicStampV1Codec.Encode(v.ObservedAt));return F(w,MaximumBodyBytes);}
    internal static byte[] Encode(GlobalParticipantAuthorityPositionV1 v){var w=W(2);T(w,1);Id(w,v.JournalId);T(w,2);w.WriteUInt64(v.Sequence);return F(w,128);}
    internal static byte[] Encode(GlobalParticipantAuthorityHeadV1 v){var w=W(2);T(w,1);Position(w,v.Position);T(w,2);Hash(w,v.RecordHash);return F(w,256);}
    internal static byte[] Encode(GlobalParticipantAllocationSourceV1 v){var w=W(4);T(w,1);Id(w,v.LiveSessionId);T(w,2);AuthorityPositionCodecsV1.Write(w,v.SourceFactPosition);T(w,3);Hash(w,v.SourceOuterIntegrityHash);T(w,4);Hash(w,v.SourceBodyHash);return F(w,1024);}
    internal static byte[] Encode(ParticipantIdOwnerEvidenceV1 v){var w=W(5);T(w,1);Id(w,v.ParticipantId);T(w,2);Id(w,v.LiveSessionId);T(w,3);Id(w,v.OperationId);T(w,4);Hash(w,v.SourceFingerprint);T(w,5);Head(w,v.ClaimHead);return F(w,1024);}
    internal static byte[] Encode(ParticipantIdOwnerProofV1 v){var w=W(7);T(w,1);Id(w,v.ParticipantId);T(w,2);Opt(w,v.Head,Head);T(w,3);w.WriteUInt64(v.State);T(w,4);Opt(w,v.Owner,Evidence);T(w,5);Hash(w,v.IndexRoot);T(w,6);w.WriteByteString(v.ProofPathBytes);T(w,7);w.WriteUInt64(v.RecordCount);return F(w,8192);}
    internal static byte[] Encode(ParticipantIdClaimOutcomeV1 v){ValidateOutcome(v);var w=W(3);T(w,1);w.WriteUInt64(v.Kind);T(w,2);Opt(w,v.ExistingOwnerPosition,Position);T(w,3);OptAscii(w,v.SafeCode);return F(w,2048);}
    internal static bool IsCanonical<T>(ReadOnlyMemory<byte>b,int max,Func<CborReader,T> read,Func<T,byte[]> encode,out T? value)where T:class{value=null;if(b.Length>max)return false;try{var r=R(b);var x=read(r);if(r.BytesRemaining!=0||!b.Span.SequenceEqual(encode(x)))return false;value=x;return true;}catch(Exception e)when(Bad(e)){return false;}}
    internal static bool TryDecodeBody(ReadOnlyMemory<byte>b,out GlobalParticipantClaimRecordBodyV1? v){v=null;return PrecheckBodyProof(b)&&IsCanonical(b,MaximumBodyBytes,ReadBody,Encode,out v);}
    internal static bool TryDecodeProof(ReadOnlyMemory<byte>b,out ParticipantIdOwnerProofV1? v){v=null;return PrecheckProof(b)&&IsCanonical(b,8192,ReadProof,Encode,out v);}
    internal static bool TryDecodeOutcome(ReadOnlyMemory<byte>b,out ParticipantIdClaimOutcomeV1? v)=>IsCanonical(b,2048,ReadOutcome,Encode,out v);
    internal static bool TryDecodeSource(ReadOnlyMemory<byte>b,out GlobalParticipantAllocationSourceV1? v)=>IsCanonical(b,1024,ReadSource,Encode,out v);
    internal static bool TryDecodeEvidence(ReadOnlyMemory<byte>b,out ParticipantIdOwnerEvidenceV1? v)=>IsCanonical(b,1024,ReadEvidence,Encode,out v);
    internal static bool TryDecodePosition(ReadOnlyMemory<byte>b,out GlobalParticipantAuthorityPositionV1 v)=>TryCanonicalValue(b,128,ReadPosition,Encode,out v);
    internal static bool TryDecodeHead(ReadOnlyMemory<byte>b,out GlobalParticipantAuthorityHeadV1 v)=>TryCanonicalValue(b,256,ReadHead,Encode,out v);
    private static bool TryCanonicalValue<T>(ReadOnlyMemory<byte>b,int max,Func<CborReader,T> read,Func<T,byte[]> encode,out T value){value=default!;if(b.Length>max)return false;try{var r=R(b);var x=read(r);if(r.BytesRemaining!=0||!b.Span.SequenceEqual(encode(x)))return false;value=x;return true;}catch(Exception e)when(Bad(e)){return false;}}
    private static GlobalParticipantClaimRecordBodyV1 ReadBody(CborReader r){S(r,8);N(r,1);var op=OperationId.FromValue(Stable(r));N(r,2);var src=ReadSource(r);N(r,3);var pid=ParticipantId.FromValue(Stable(r));N(r,4);var prior=ReadOpt(r,ReadHead);N(r,5);var proof=ReadProof(r);N(r,6);var outcome=ReadOutcome(r);N(r,7);var pos=ReadPosition(r);N(r,8);if(!MonotonicStampV1Codec.TryDecode(r.ReadEncodedValue(),out var stamp))throw X();r.ReadEndMap();return new(op,src,pid,prior,proof,outcome,pos,stamp);}
    private static GlobalParticipantAllocationSourceV1 ReadSource(CborReader r){S(r,4);N(r,1);var live=LiveSessionId.FromValue(Stable(r));N(r,2);var p=AuthorityPositionCodecsV1.ReadJournal(r);N(r,3);var oh=ReadHash(r);N(r,4);var bh=ReadHash(r);r.ReadEndMap();return new(live,p,oh,bh);}
    private static ParticipantIdOwnerProofV1 ReadProof(CborReader r){S(r,7);N(r,1);var pid=ParticipantId.FromValue(Stable(r));N(r,2);var head=ReadOpt(r,ReadHead);N(r,3);var state=checked((ushort)r.ReadUInt64());N(r,4);var owner=ReadOpt(r,ReadEvidence);N(r,5);var root=ReadHash(r);N(r,6);var path=new byte[MaximumProofPathBytes];if(!r.TryReadByteString(path,out var pathLength)||pathLength!=MaximumProofPathBytes)throw X();N(r,7);var count=r.ReadUInt64();r.ReadEndMap();return new(pid,head,state,owner,root,path,count);}
    private static ParticipantIdOwnerEvidenceV1 ReadEvidence(CborReader r){S(r,5);N(r,1);var p=ParticipantId.FromValue(Stable(r));N(r,2);var l=LiveSessionId.FromValue(Stable(r));N(r,3);var o=OperationId.FromValue(Stable(r));N(r,4);var f=ReadHash(r);N(r,5);var h=ReadHead(r);r.ReadEndMap();return new(p,l,o,f,h);}
    private static ParticipantIdClaimOutcomeV1 ReadOutcome(CborReader r){S(r,3);N(r,1);var k=checked((ushort)r.ReadUInt64());N(r,2);var p=ReadOptValue(r,ReadPosition);N(r,3);var c=ReadOptAscii(r);r.ReadEndMap();var v=new ParticipantIdClaimOutcomeV1(k,p,c);ValidateOutcome(v);return v;}
    private static void ValidateOutcome(ParticipantIdClaimOutcomeV1 v){if(v.Kind is <1 or >3)throw X();if(v.Kind==1&&(v.ExistingOwnerPosition is not null||v.SafeCode is not null))throw X();if(v.Kind==2&&(v.ExistingOwnerPosition is null||v.SafeCode?.ToString()!="participant-id-owned"))throw X();if(v.Kind==3&&v.ExistingOwnerPosition is not null)throw X();}
    private static void Source(CborWriter w,GlobalParticipantAllocationSourceV1 v)=>w.WriteEncodedValue(Encode(v)); private static void Evidence(CborWriter w,ParticipantIdOwnerEvidenceV1 v)=>w.WriteEncodedValue(Encode(v)); private static void Proof(CborWriter w,ParticipantIdOwnerProofV1 v)=>w.WriteEncodedValue(Encode(v)); private static void Outcome(CborWriter w,ParticipantIdClaimOutcomeV1 v)=>w.WriteEncodedValue(Encode(v));
    internal static void Position(CborWriter w,GlobalParticipantAuthorityPositionV1 v){if(!v.IsValid)throw X();w.WriteStartMap(2);T(w,1);Id(w,v.JournalId);T(w,2);w.WriteUInt64(v.Sequence);w.WriteEndMap();} private static GlobalParticipantAuthorityPositionV1 ReadPosition(CborReader r){S(r,2);N(r,1);var j=GlobalParticipantAllocatorJournalId.FromValue(Stable(r));N(r,2);var s=r.ReadUInt64();r.ReadEndMap();return new(j,s);}
    internal static void Head(CborWriter w,GlobalParticipantAuthorityHeadV1 v){w.WriteStartMap(2);T(w,1);Position(w,v.Position);T(w,2);Hash(w,v.RecordHash);w.WriteEndMap();} private static GlobalParticipantAuthorityHeadV1 ReadHead(CborReader r){S(r,2);N(r,1);var p=ReadPosition(r);N(r,2);var h=ReadHash(r);r.ReadEndMap();return new(p,h);}
    private static void Opt<TValue>(CborWriter w,TValue? v,Action<CborWriter,TValue> write)where TValue:class{w.WriteStartMap(v is null?1:2);T(w,1);w.WriteUInt64(v is null?0UL:1UL);if(v is not null){T(w,2);write(w,v);}w.WriteEndMap();} private static void Opt(CborWriter w,GlobalParticipantAuthorityHeadV1? v,Action<CborWriter,GlobalParticipantAuthorityHeadV1> write)=>OptValue(w,v,write); private static void Opt(CborWriter w,GlobalParticipantAuthorityPositionV1? v,Action<CborWriter,GlobalParticipantAuthorityPositionV1> write)=>OptValue(w,v,write);
    private static void OptValue<TValue>(CborWriter w,TValue? v,Action<CborWriter,TValue> write)where TValue:struct{w.WriteStartMap(v is null?1:2);T(w,1);w.WriteUInt64(v is null?0UL:1UL);if(v is{}x){T(w,2);write(w,x);}w.WriteEndMap();} private static TValue? ReadOptValue<TValue>(CborReader r,Func<CborReader,TValue> read)where TValue:struct{var n=r.ReadStartMap();N(r,1);var k=r.ReadUInt64();if(n==1&&k==0){r.ReadEndMap();return null;}if(n!=2||k!=1)throw X();N(r,2);var v=read(r);r.ReadEndMap();return v;} private static TValue? ReadOpt<TValue>(CborReader r,Func<CborReader,TValue> read)where TValue:class{var n=r.ReadStartMap();N(r,1);var k=r.ReadUInt64();if(n==1&&k==0){r.ReadEndMap();return null;}if(n!=2||k!=1)throw X();N(r,2);var v=read(r);r.ReadEndMap();return v;} private static GlobalParticipantAuthorityHeadV1? ReadOpt(CborReader r,Func<CborReader,GlobalParticipantAuthorityHeadV1> read)=>ReadOptValue(r,read);
    private static void OptAscii(CborWriter w,BoundedAscii? v){w.WriteStartMap(v is null?1:2);T(w,1);w.WriteUInt64(v is null?0UL:1UL);if(v is{}x){T(w,2);BoundedAsciiCodec.Write(w,x);}w.WriteEndMap();}private static BoundedAscii? ReadOptAscii(CborReader r){var n=r.ReadStartMap();N(r,1);var k=r.ReadUInt64();if(n==1&&k==0){r.ReadEndMap();return null;}if(n!=2||k!=1)throw X();N(r,2);var v=BoundedAsciiCodec.Read(r);r.ReadEndMap();if(v.ToString().Length>64)throw X();return v;}
    private static void Id(CborWriter w,OperationId v){Span<byte>b=stackalloc byte[16];if(!v.TryWriteBytes(b))throw X();w.WriteByteString(b);}private static void Id(CborWriter w,ParticipantId v){Span<byte>b=stackalloc byte[16];if(!v.TryWriteBytes(b))throw X();w.WriteByteString(b);}private static void Id(CborWriter w,LiveSessionId v){Span<byte>b=stackalloc byte[16];if(!v.TryWriteBytes(b))throw X();w.WriteByteString(b);}private static void Id(CborWriter w,GlobalParticipantAllocatorJournalId v){Span<byte>b=stackalloc byte[16];if(!v.TryWriteBytes(b))throw X();w.WriteByteString(b);} private static StableId128 Stable(CborReader r){Span<byte>b=stackalloc byte[16];if(!r.TryReadByteString(b,out var n)||n!=16)throw X();return StableId128.FromBytes(b);}private static void Hash(CborWriter w,Hash256 v){Span<byte>b=stackalloc byte[32];if(!v.TryWriteBytes(b))throw X();w.WriteByteString(b);}private static Hash256 ReadHash(CborReader r){Span<byte>b=stackalloc byte[32];if(!r.TryReadByteString(b,out var n)||n!=32)throw X();return Hash256.FromBytes(b);}
    private static bool PrecheckOuterBody(ReadOnlyMemory<byte>b){try{var r=R(b);S(r,3);N(r,1);r.SkipValue();N(r,2);r.SkipValue();N(r,3);return DeclaredBstr(b.Span,b.Length-r.BytesRemaining,1,MaximumBodyBytes);}catch{return false;}}
    private static bool PrecheckProof(ReadOnlyMemory<byte>b){try{var r=R(b);S(r,7);for(ulong tag=1;tag<=5;tag++){N(r,tag);r.SkipValue();}N(r,6);return DeclaredBstr(b.Span,b.Length-r.BytesRemaining,MaximumProofPathBytes,MaximumProofPathBytes);}catch{return false;}}
    private static bool PrecheckBodyProof(ReadOnlyMemory<byte>b){try{var r=R(b);S(r,8);for(ulong tag=1;tag<=4;tag++){N(r,tag);r.SkipValue();}N(r,5);S(r,7);for(ulong tag=1;tag<=5;tag++){N(r,tag);r.SkipValue();}N(r,6);return DeclaredBstr(b.Span,b.Length-r.BytesRemaining,MaximumProofPathBytes,MaximumProofPathBytes);}catch{return false;}}
    private static bool DeclaredBstr(ReadOnlySpan<byte>s,int o,int min,int max){if((uint)o>=(uint)s.Length||(s[o]>>5)!=2)return false;var ai=s[o]&31;ulong n;if(ai<24)n=(ulong)ai;else if(ai==24&&o+2<=s.Length)n=s[o+1];else if(ai==25&&o+3<=s.Length)n=System.Buffers.Binary.BinaryPrimitives.ReadUInt16BigEndian(s.Slice(o+1,2));else if(ai==26&&o+5<=s.Length)n=System.Buffers.Binary.BinaryPrimitives.ReadUInt32BigEndian(s.Slice(o+1,4));else if(ai==27&&o+9<=s.Length)n=System.Buffers.Binary.BinaryPrimitives.ReadUInt64BigEndian(s.Slice(o+1,8));else return false;return n>=(ulong)min&&n<=(ulong)max;}
    private static CborWriter W(int n){var w=new CborWriter(CborConformanceMode.Ctap2Canonical);w.WriteStartMap(n);return w;}private static byte[] F(CborWriter w,int max){w.WriteEndMap();var b=w.Encode();if(b.Length>max)throw X();return b;}private static CborReader R(ReadOnlyMemory<byte>b)=>new(b,CborConformanceMode.Ctap2Canonical,false);private static void T(CborWriter w,ulong t)=>w.WriteUInt64(t);private static void S(CborReader r,int n){if(r.ReadStartMap()!=n)throw X();}private static void N(CborReader r,ulong t){if(r.ReadUInt64()!=t)throw X();}private static CborContentException X()=>new("Invalid global participant wire value.");private static bool Bad(Exception e)=>e is CborContentException or InvalidOperationException or ArgumentException or OverflowException;
}
