using System.Formats.Cbor;
namespace HPD.Agent.Authority;

internal sealed record QualificationCellV1
{
 internal QualificationCellV1(TfmId tfm,RidId rid,SurfaceId surfaceId,SchemaVersionV1 surfaceVersion,EnvironmentProfileId environmentProfileId,QualificationDeclarationV1 declaration,uint expectedStatus,EvidenceReferenceV1? buildEvidence,EvidenceReferenceV1? executionEvidence,bool nativeExecution,EmulationKindV1 emulation,IEnumerable<LimitationId> limitations)
 {ArgumentNullException.ThrowIfNull(limitations);var a=limitations.ToArray();if(!Enum.IsDefined(tfm)||!Enum.IsDefined(rid)||!surfaceId.IsValid||surfaceVersion is null||!environmentProfileId.IsValid||!Enum.IsDefined(declaration)||!Enum.IsDefined(emulation)||a.Length>256||a.Any(x=>!x.IsValid)||!Strict(a))throw new ArgumentException("Invalid qualification cell.");Tfm=tfm;Rid=rid;SurfaceId=surfaceId;SurfaceVersion=surfaceVersion;EnvironmentProfileId=environmentProfileId;Declaration=declaration;ExpectedStatus=expectedStatus;BuildEvidence=buildEvidence;ExecutionEvidence=executionEvidence;NativeExecution=nativeExecution;Emulation=emulation;Limitations=Array.AsReadOnly(a);}
 internal TfmId Tfm{get;}internal RidId Rid{get;}internal SurfaceId SurfaceId{get;}internal SchemaVersionV1 SurfaceVersion{get;}internal EnvironmentProfileId EnvironmentProfileId{get;}internal QualificationDeclarationV1 Declaration{get;}internal uint ExpectedStatus{get;}internal EvidenceReferenceV1? BuildEvidence{get;}internal EvidenceReferenceV1? ExecutionEvidence{get;}internal bool NativeExecution{get;}internal EmulationKindV1 Emulation{get;}internal IReadOnlyList<LimitationId> Limitations{get;}
 private static bool Strict(LimitationId[]a){Span<byte>x=stackalloc byte[16];Span<byte>y=stackalloc byte[16];for(var i=1;i<a.Length;i++){a[i-1].TryWriteBytes(x);a[i].TryWriteBytes(y);if(x.SequenceCompareTo(y)>=0)return false;}return true;}
}

internal static class QualificationCellCodecsV1
{
 internal const string SchemaId="hpd.qualification-cell.v1";
 internal static byte[] Encode(QualificationCellV1 v){ArgumentNullException.ThrowIfNull(v);var w=W();w.WriteStartMap(12);T(w,1);w.WriteUInt64((ushort)v.Tfm);T(w,2);w.WriteUInt64((ushort)v.Rid);T(w,3);Id(w,v.SurfaceId.TryWriteBytes);T(w,4);Version(w,v.SurfaceVersion);T(w,5);Id(w,v.EnvironmentProfileId.TryWriteBytes);T(w,6);w.WriteUInt64((ushort)v.Declaration);T(w,7);w.WriteUInt64(v.ExpectedStatus);T(w,8);EvidenceOption(w,v.BuildEvidence);T(w,9);EvidenceOption(w,v.ExecutionEvidence);T(w,10);w.WriteBoolean(v.NativeExecution);T(w,11);w.WriteUInt64((ushort)v.Emulation);T(w,12);w.WriteStartArray(v.Limitations.Count);foreach(var x in v.Limitations)Id(w,x.TryWriteBytes);w.WriteEndArray();w.WriteEndMap();return w.Encode();}
 internal static bool TryDecode(ReadOnlyMemory<byte>b,out QualificationCellV1? v){v=null;try{var r=new CborReader(b,CborConformanceMode.Ctap2Canonical,false);if(r.ReadStartMap()!=12)return false;N(r,1);var tfm=checked((TfmId)r.ReadUInt64());N(r,2);var rid=checked((RidId)r.ReadUInt64());N(r,3);var surface=SurfaceId.FromValue(ReadId(r));N(r,4);var version=ReadVersion(r);N(r,5);var environment=EnvironmentProfileId.FromValue(ReadId(r));N(r,6);var declaration=checked((QualificationDeclarationV1)r.ReadUInt64());N(r,7);var status=checked((uint)r.ReadUInt64());N(r,8);var build=ReadEvidenceOption(r);N(r,9);var execution=ReadEvidenceOption(r);N(r,10);var native=r.ReadBoolean();N(r,11);var emulation=checked((EmulationKindV1)r.ReadUInt64());N(r,12);var n=r.ReadStartArray();if(n is null or<0 or>256)return false;var limitations=new LimitationId[n.Value];for(var i=0;i<limitations.Length;i++)limitations[i]=LimitationId.FromValue(ReadId(r));r.ReadEndArray();r.ReadEndMap();var x=new QualificationCellV1(tfm,rid,surface,version,environment,declaration,status,build,execution,native,emulation,limitations);if(r.BytesRemaining!=0||!Encode(x).AsSpan().SequenceEqual(b.Span))return false;v=x;return true;}catch(Exception e)when(e is CborContentException or InvalidOperationException or ArgumentException or OverflowException){return false;}}
 internal static Hash256 ComputeHash(QualificationCellV1 v)=>AuthorityIntegrityHashV1.Compute(SchemaId,1,0,Encode(v));
 private static void Version(CborWriter w,SchemaVersionV1 v){w.WriteStartMap(2);T(w,1);w.WriteUInt64(v.Major);T(w,2);w.WriteUInt64(v.Minor);w.WriteEndMap();}private static SchemaVersionV1 ReadVersion(CborReader r){if(r.ReadStartMap()!=2)throw B();N(r,1);var a=checked((ushort)r.ReadUInt64());N(r,2);var b=checked((ushort)r.ReadUInt64());r.ReadEndMap();return new(a,b);}
 private static void EvidenceOption(CborWriter w,EvidenceReferenceV1? v){w.WriteStartArray(v is null?1:2);w.WriteUInt64(v is null?0UL:1UL);if(v is not null)Evidence(w,v);w.WriteEndArray();}private static EvidenceReferenceV1? ReadEvidenceOption(CborReader r){var n=r.ReadStartArray();if(n==1&&r.ReadUInt64()==0){r.ReadEndArray();return null;}if(n!=2||r.ReadUInt64()!=1)throw B();var v=ReadEvidence(r);r.ReadEndArray();return v;}
 private static void Evidence(CborWriter w,EvidenceReferenceV1 v){w.WriteStartMap(4);T(w,1);Id(w,v.ContentId.TryWriteBytes);T(w,2);Hash(w,v.Sha256);T(w,3);w.WriteUInt64(v.ByteLength);T(w,4);BoundedAsciiCodec.Write(w,v.MediaType);w.WriteEndMap();}private static EvidenceReferenceV1 ReadEvidence(CborReader r){if(r.ReadStartMap()!=4)throw B();N(r,1);var id=ContentId.FromValue(ReadId(r));N(r,2);var h=ReadHash(r);N(r,3);var l=r.ReadUInt64();N(r,4);var m=BoundedAsciiCodec.Read(r);r.ReadEndMap();return new(id,h,l,m);}
 private delegate bool WriteId(Span<byte>b);private static void Id(CborWriter w,WriteId f){Span<byte>b=stackalloc byte[16];if(!f(b))throw new ArgumentException();w.WriteByteString(b);}private static StableId128 ReadId(CborReader r){Span<byte>b=stackalloc byte[16];if(!r.TryReadByteString(b,out var n)||n!=16)throw B();return StableId128.FromBytes(b);}private static void Hash(CborWriter w,Hash256 h){Span<byte>b=stackalloc byte[32];if(!h.TryWriteBytes(b))throw new ArgumentException();w.WriteByteString(b);}private static Hash256 ReadHash(CborReader r){Span<byte>b=stackalloc byte[32];if(!r.TryReadByteString(b,out var n)||n!=32)throw B();return Hash256.FromBytes(b);}
 private static CborWriter W()=>new(CborConformanceMode.Ctap2Canonical);private static void T(CborWriter w,ulong n)=>w.WriteUInt64(n);private static void N(CborReader r,ulong n){if(r.ReadUInt64()!=n)throw B();}private static CborContentException B()=>new("Invalid qualification cell encoding.");
}
