<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>HPD.Payments.Connectors.Simulator</AssemblyName>
    <RootNamespace>HPD.Payments.Connectors_Simulator</RootNamespace>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../HPD.Payments.Primitives/HPD.Payments.Primitives.csproj" />
    <ProjectReference Include="../HPD.Payments.Contracts/HPD.Payments.Contracts.csproj" />
    <ProjectReference Include="../HPD.Payments.Supporting/HPD.Payments.Supporting.csproj" />
    <ProjectReference Include="../HPD.Payments.Runtime/HPD.Payments.Runtime.csproj" />
  </ItemGroup>
</Project>
