using System.Buffers.Binary;
using HPD.Agent.Authority;

namespace HPD.Agent.Audio.Authority;

internal sealed class FileGlobalParticipantAllocatorDurableBackendV1 : IGlobalParticipantAllocatorDurableClaimPortV1, IGlobalParticipantAllocatorReconciliationPortV1, IGlobalParticipantAllocatorDurableSnapshotPortV1, IAsyncDisposable
{
    private const int MaximumFrameBytes = 8304;
    internal sealed class State
    {
        private readonly byte[][][] _records=new byte[256][][]; private int _recordCount;
        internal State(IEnumerable<ReadOnlyMemory<byte>> records, IEnumerable<KeyValuePair<JournalFactId,int>> facts, GlobalParticipantAuthorityHeadV1? head, Hash256 indexRoot, ulong totalBytes, Hash256 lastFrameHash, ulong committedLength, ulong generation, int activeSlot, BoundedAscii? quarantine) { Facts=new Dictionary<JournalFactId,int>(65536);Owners=new Dictionary<ParticipantId,ParticipantIdOwnerEvidenceV1>(65536);foreach(var record in records){EnsureNextRecordCapacity();PublishRecord(record.ToArray());}foreach(var x in facts)Facts.Add(x.Key,x.Value);foreach(var x in Facts){var bytes=RecordAt(x.Value);if(!GlobalParticipantAllocatorCodecsV1.TryDecodeOuter(bytes,out var outer)||outer is null||!GlobalParticipantAllocatorCodecsV1.TryDecodeBody(outer.BodyBytes.ToArray(),out var body)||body is null)continue;var transition=GlobalParticipantAllocatorFoldV1.EvaluateTransition(body.OwnerProof.Owner,body.Outcome);if(!transition.InsertOwnerAfterHash)continue;var fingerprint=GlobalParticipantAllocatorFactIdsV1.SourceFingerprint(body.Source);Owners.Add(body.ParticipantId,new(body.ParticipantId,body.Source.LiveSessionId,body.OperationId,fingerprint,HeadFor(x.Key,bytes)));}OwnerCount=Owners.Count;Head=head;IndexRoot=indexRoot;TotalBytes=totalBytes;LastFrameHash=lastFrameHash;CommittedLength=committedLength;Generation=generation;ActiveSlot=activeSlot;Quarantine=quarantine; }
        internal int RecordCount=>_recordCount; internal int AllocatedRecordChunkCount=>(_recordCount+255)/256; internal IEnumerable<ReadOnlyMemory<byte>> Records { get { for(var i=0;i<_recordCount;i++)yield return _records[i>>8][i&255]; } }
        internal ReadOnlyMemory<byte> RecordAt(int index)=>index>=0&&index<_recordCount?_records[index>>8][index&255]:throw new ArgumentOutOfRangeException(nameof(index));
        internal void EnsureNextRecordCapacity(){if(_recordCount>=65536)throw new InvalidOperationException("Record capacity exhausted.");var chunk=_recordCount>>8;if(_records[chunk] is null)_records[chunk]=new byte[256][];}
        internal void PublishRecord(byte[] exactOwnedBytes){_records[_recordCount>>8][_recordCount&255]=exactOwnedBytes;_recordCount++;}
        internal Dictionary<JournalFactId,int> Facts { get; } internal Dictionary<ParticipantId,ParticipantIdOwnerEvidenceV1> Owners { get; } internal int OwnerCount; internal GlobalParticipantAuthorityHeadV1? Head; internal Hash256 IndexRoot; internal ulong TotalBytes; internal Hash256 LastFrameHash; internal ulong CommittedLength; internal ulong Generation; internal int ActiveSlot; internal BoundedAscii? Quarantine;
    }
    internal abstract record OpenResultV1
    {
        private OpenResultV1() { }
        internal sealed record Opened(FileGlobalParticipantAllocatorDurableBackendV1 Backend) : OpenResultV1;
        internal sealed record Quarantined(BoundedAscii SafeCode) : OpenResultV1;
        internal sealed record StoreUnavailable(BoundedAscii SafeCode) : OpenResultV1;
        internal sealed record OutcomeUnknown(GlobalParticipantAllocatorJournalId JournalId, BoundedAscii SafeCode) : OpenResultV1;
        internal sealed record RealmFenced(ulong CurrentFenceEpoch) : OpenResultV1;
    }
    internal sealed record Frame(ulong Epoch, ulong Sequence, JournalFactId FactId, ReadOnlyMemory<byte> Record, Hash256 PriorFrameHash, Hash256 FrameHash);
    internal sealed class ManagedTestingTransport
    {
        private static readonly object RegistryGate = new(); private static readonly Dictionary<string, ManagedTestingTransport> Registry = new(StringComparer.Ordinal); private readonly object _gate = new(); private readonly Dictionary<string, byte[]> _volatile = new(StringComparer.Ordinal), _durable = new(StringComparer.Ordinal); private readonly Dictionary<string, int> _volatileLength = new(StringComparer.Ordinal), _durableLength = new(StringComparer.Ordinal), _dirtyStart = new(StringComparer.Ordinal); private readonly Dictionary<string, string> _pendingRenameSource = new(StringComparer.Ordinal); private readonly HashSet<string> _volatileLinks = new(StringComparer.Ordinal), _durableLinks = new(StringComparer.Ordinal); private int _custody, _handles;
        private ManagedTestingTransport(string root) => ExactNormalizedRoot = root;
        internal string ExactNormalizedRoot { get; }
        internal static ManagedTestingTransport CreateForTesting(string exactNormalizedRoot) { var root = Normalize(exactNormalizedRoot); lock (RegistryGate) { if (Registry.ContainsKey(root)) throw new InvalidOperationException("Testing volume already exists."); var volume = new ManagedTestingTransport(root); Registry.Add(root, volume); return volume; } }
        internal static ManagedTestingTransport GetForTesting(string exactNormalizedRoot) { var root = Normalize(exactNormalizedRoot); lock (RegistryGate) return Registry.TryGetValue(root, out var volume) ? volume : throw new InvalidOperationException("Testing volume does not exist."); }
        internal static void ResetForTesting(string exactNormalizedRoot) { var root = Normalize(exactNormalizedRoot); lock (RegistryGate) { if (!Registry.TryGetValue(root, out var volume)) throw new InvalidOperationException("Testing volume does not exist."); lock (volume._gate) { if (volume._custody != 0 || volume._handles != 0) throw new InvalidOperationException("Testing volume is active."); Registry.Remove(root); } } }
        internal void AcquireCustody() { lock (_gate) { if (_custody != 0) throw new IOException("Testing custody conflict."); _custody = 1; } }
        internal void ReleaseCustody() { lock (_gate) { if (_custody == 0) throw new InvalidOperationException("No testing custody."); _custody = 0; } }
        internal void OpenHandle() { lock (_gate) _handles++; }
        internal void CloseHandle() { lock (_gate) { if (_handles == 0) throw new InvalidOperationException("No testing handle."); _handles--; } }
        internal void WriteVolatile(string name, ReadOnlySpan<byte> bytes) { ValidateName(name); lock (_gate) { _volatile[name] = bytes.ToArray(); _volatileLength[name] = bytes.Length; _dirtyStart[name] = 0; _volatileLinks.Add(name); } }
        internal bool ExistsVolatile(string name) { ValidateName(name); lock (_gate) return _volatileLinks.Contains(name); }
        internal byte[] ReadVolatileOwned(string name) { ValidateName(name); lock (_gate) return _volatileLinks.Contains(name) && _volatile.TryGetValue(name, out var bytes) ? bytes.AsSpan(0, _volatileLength[name]).ToArray() : throw new IOException("Entry absent."); }
        internal byte[] ReadVolatileRangeOwned(string name, long offset, int maximumBytes) { ValidateName(name); if (offset < 0 || maximumBytes < 0) throw new ArgumentOutOfRangeException(); lock (_gate) { if (!_volatileLinks.Contains(name) || !_volatile.TryGetValue(name, out var bytes)) throw new IOException("Entry absent."); var length = _volatileLength[name]; if (offset >= length) return Array.Empty<byte>(); var count = (int)Math.Min(maximumBytes, length - offset); return bytes.AsSpan(checked((int)offset), count).ToArray(); } }
        internal void PwriteVolatile(string name, long offset, ReadOnlySpan<byte> bytes) { ValidateName(name); if (offset < 0) throw new ArgumentOutOfRangeException(nameof(offset)); lock (_gate) { if (!_volatileLinks.Contains(name) || !_volatile.TryGetValue(name, out var current) || offset + bytes.Length > 544210944) throw new IOException("Entry absent or bound exceeded."); var start = checked((int)offset); var length = checked((int)Math.Max(_volatileLength[name], offset + bytes.Length)); if (length > current.Length) { var capacity = Math.Max(length, Math.Min(544210944, Math.Max(256, current.Length * 2))); Array.Resize(ref current, capacity); } _volatile[name] = current; _volatileLength[name] = length; _dirtyStart[name] = _dirtyStart.TryGetValue(name, out var dirty) ? Math.Min(dirty, start) : start; bytes.CopyTo(current.AsSpan(start)); } }
        internal void TruncateVolatile(string name, long length) { ValidateName(name); if (length < 0 || length > 544210944) throw new ArgumentOutOfRangeException(nameof(length)); lock (_gate) { if (!_volatileLinks.Contains(name) || !_volatile.TryGetValue(name, out var current)) throw new IOException("Entry absent."); var old = _volatileLength[name]; if (length > current.Length) Array.Resize(ref current, checked((int)length)); _volatile[name] = current; _volatileLength[name] = checked((int)length); _dirtyStart[name] = Math.Min(old, checked((int)length)); } }
        internal void UnlinkVolatile(string name) { ValidateName(name); lock (_gate) { _volatileLinks.Remove(name); _volatile.Remove(name); _volatileLength.Remove(name); _dirtyStart.Remove(name); } }
        internal void FileFlush(string name) { ValidateName(name); lock (_gate) { if (!_volatileLinks.Contains(name) || !_volatile.TryGetValue(name, out var bytes)) throw new IOException("Entry absent."); var length = _volatileLength[name]; var start = _dirtyStart.TryGetValue(name, out var dirty) ? dirty : length; if (!_durable.TryGetValue(name, out var durable) || durable.Length < length) { var capacity = Math.Max(length, Math.Min(544210944, Math.Max(256, durable?.Length * 2 ?? 0))); Array.Resize(ref durable, capacity); } _durable[name] = durable!; if (start < length) bytes.AsSpan(start, length - start).CopyTo(durable.AsSpan(start)); _durableLength[name] = length; _dirtyStart.Remove(name); } }
        internal void RenameVolatile(string from, string to, bool replace) { ValidateName(from); ValidateName(to); lock (_gate) { if (!_volatileLinks.Contains(from)) throw new IOException("Source absent."); if (!replace && _volatileLinks.Contains(to)) throw new IOException("Target exists."); _volatileLinks.Remove(from); _volatileLinks.Remove(to); _volatileLinks.Add(to); _volatile[to] = _volatile[from]; _volatile.Remove(from); _volatileLength[to] = _volatileLength[from]; _volatileLength.Remove(from); if (_dirtyStart.Remove(from, out var dirty)) _dirtyStart[to] = dirty; _pendingRenameSource[to] = from; } }
        internal void DirectoryFlush() { lock (_gate) { foreach (var pair in _pendingRenameSource) { if (!_durable.TryGetValue(pair.Value, out var image)) throw new IOException("Renamed entry has no durable image."); var length = _durableLength[pair.Value]; _durable[pair.Key] = image.AsSpan(0, length).ToArray(); _durableLength[pair.Key] = length; } _durableLinks.Clear(); foreach (var name in _volatileLinks) { if (!_durable.ContainsKey(name)) throw new IOException("Linked entry has no durable image."); _durableLinks.Add(name); } foreach (var name in _durable.Keys.Where(name => !_durableLinks.Contains(name)).ToArray()) { _durable.Remove(name); _durableLength.Remove(name); } _pendingRenameSource.Clear(); } }
        internal void Crash() { lock (_gate) { _volatile.Clear(); _volatileLength.Clear(); _dirtyStart.Clear(); _pendingRenameSource.Clear(); _volatileLinks.Clear(); foreach (var name in _durableLinks) { _volatileLinks.Add(name); var length = _durableLength[name]; _volatile[name] = _durable[name].AsSpan(0, length).ToArray(); _volatileLength[name] = length; } } }
        internal void CorruptDurableByte(string name, long offset, byte xorMask) { ValidateName(name); lock (_gate) { if (!_durableLinks.Contains(name) || !_durable.TryGetValue(name, out var bytes) || offset < 0 || offset >= bytes.LongLength) throw new ArgumentOutOfRangeException(nameof(offset)); bytes[checked((int)offset)] ^= xorMask; } }
        internal void TruncateDurable(string name, long length) { ValidateName(name); if (length < 0 || length > 544210944) throw new ArgumentOutOfRangeException(nameof(length)); lock (_gate) { if (!_durableLinks.Contains(name) || !_durable.TryGetValue(name, out var bytes) || length > _durableLength[name]) throw new ArgumentOutOfRangeException(nameof(length)); _durableLength[name] = checked((int)length); } }
        internal void AppendDurable(string name, ReadOnlySpan<byte> bytes) { ValidateName(name); lock (_gate) { if (!_durableLinks.Contains(name) || !_durable.TryGetValue(name, out var current) || _durableLength[name] + bytes.Length > 544210944) throw new ArgumentOutOfRangeException(nameof(bytes)); var old = _durableLength[name]; var length = old + bytes.Length; if (current.Length < length) Array.Resize(ref current, length); bytes.CopyTo(current.AsSpan(old)); _durable[name] = current; _durableLength[name] = length; } }
        internal byte[] ReadDurableOwned(string name) { ValidateName(name); lock (_gate) return _durableLinks.Contains(name) && _durable.TryGetValue(name, out var bytes) ? bytes.AsSpan(0, _durableLength[name]).ToArray() : throw new IOException("Entry absent."); }
        private static string Normalize(string root) { if (string.IsNullOrWhiteSpace(root) || !Path.IsPathFullyQualified(root)) throw new ArgumentException("Exact normalized root required.", nameof(root)); var normalized = Path.GetFullPath(root); if (!StringComparer.Ordinal.Equals(root, normalized)) throw new ArgumentException("Exact normalized root required.", nameof(root)); return normalized; }
        private static void ValidateName(string name) { if (name is "store.id" or "realm.manifest" or "authority.log" or "committed.head" or "realm.lock") return; if (name.StartsWith(".store.id.create.", StringComparison.Ordinal) || name.StartsWith(".authority.log.create.", StringComparison.Ordinal) || name.StartsWith(".committed.head.create.", StringComparison.Ordinal) || name.StartsWith(".realm.manifest.publish.", StringComparison.Ordinal)) return; throw new ArgumentException("Unrecognized testing entry.", nameof(name)); }
    }
    internal sealed class PinnedPageSource : IGlobalParticipantAllocatorPageSourceV1
    {
        private readonly GlobalParticipantAllocatorJournalId _journal; private readonly GlobalParticipantAuthorityHeadV1? _head; private readonly Hash256 _root; private readonly ReadOnlyMemory<byte>[] _records; private readonly ulong _bytes; private readonly int[] _starts, _counts; private readonly Hash256?[] _previous;
        internal PinnedPageSource(GlobalParticipantAllocatorJournalId journal, GlobalParticipantAuthorityHeadV1? head, Hash256 root, IEnumerable<ReadOnlyMemory<byte>> records, ulong bytes) { _journal = journal; _head = head; _root = root; _records = records.ToArray(); _bytes = bytes; var starts = new List<int>(); var counts = new List<int>(); for (var start = 0; start < _records.Length;) { var count = 0; var size = 2; while (start + count < _records.Length && count < 256 && size + 4 + _records[start + count].Length <= 64000) { size += 4 + _records[start + count].Length; count++; } starts.Add(start); counts.Add(count); start += count; } if (starts.Count == 0) { starts.Add(0); counts.Add(0); } _starts = starts.ToArray(); _counts = counts.ToArray(); _previous = new Hash256?[_starts.Length]; }
        ValueTask<ReadOnlyMemory<byte>?> IGlobalParticipantAllocatorPageSourceV1.ReadPageAsync(GlobalParticipantAllocatorJournalId journalId, ushort ordinal, CancellationToken token)
        { token.ThrowIfCancellationRequested(); if (journalId != _journal || ordinal == 0 || ordinal > _starts.Length) return ValueTask.FromResult<ReadOnlyMemory<byte>?>(null); return ValueTask.FromResult<ReadOnlyMemory<byte>?>(Encode(ordinal - 1)); }
        private byte[] Encode(int index) { lock (_previous) { for (var i = 1; i <= index; i++) if (_previous[i] is null) { var prior = EncodeCore(i - 1); GlobalParticipantPageCodecV1.TryDecode(prior, out var page); _previous[i] = GlobalParticipantPageCodecV1.ComputePageHash(page!); } return EncodeCore(index); } }
        private byte[] EncodeCore(int index) { var group = new ReadOnlyMemory<byte>[_counts[index]]; Array.Copy(_records, _starts[index], group, 0, group.Length); var field = GlobalParticipantPageCodecV1.EncodeRecordsField(group); var page = new GlobalParticipantPageV1(_journal, _head, _root, (ushort)(index + 1), _previous[index], field, (ushort)(index == _starts.Length - 1 ? 1 : 0), (ushort)_starts.Length, (ulong)_records.Length, _bytes); return GlobalParticipantPageCodecV1.Encode(page); }
    }

    private readonly string _root; private readonly FileGlobalParticipantAllocatorRealmStoreV1.RootCustody _custody; private readonly GlobalParticipantAllocatorRealmLeaseV1 _lease; private readonly Func<BoundedAscii, ValueTask>? _fault; private readonly SemaphoreSlim _gate = new(1, 1); private readonly object _disposeGate = new(); private State _state; private int _disposed; private Task? _disposeTask;
    internal ulong RetainedCanonicalBytes=>_state.TotalBytes;internal ulong RetainedRecordCount=>(ulong)_state.RecordCount;internal int AllocatedRecordChunkCount=>_state.AllocatedRecordChunkCount;internal int RetainedFactCount=>_state.Facts.Count;internal int RetainedOwnerCount=>_state.OwnerCount;internal long RetainedSparseBytes=>checked(256L+Math.Max(0,_state.OwnerCount*2-1)*64L+_state.OwnerCount*224L);internal long PeakAdditionalWorkingBytes=>8388608;internal long ConservativeResidentUpperBoundBytes=>checked((long)_state.TotalBytes+2072L+_state.AllocatedRecordChunkCount*2072L+_state.RecordCount*32L+3670016L+81789120L+2097152L+8388608L);
    private FileGlobalParticipantAllocatorDurableBackendV1(string root, GlobalParticipantAllocatorRealmLeaseV1 lease, Func<BoundedAscii, ValueTask>? fault, State state) { _root = root; _custody = (FileGlobalParticipantAllocatorRealmStoreV1.RootCustody)lease.Custody; _lease = lease; _fault = fault; _state = state; }
    internal static ValueTask<OpenResultV1> OpenAsync(string rootPath, GlobalParticipantAllocatorRealmLeaseV1 realmLease, CancellationToken cancellationToken) { cancellationToken.ThrowIfCancellationRequested(); ArgumentNullException.ThrowIfNull(realmLease); if (!Path.IsPathFullyQualified(rootPath)) throw new ArgumentException("Absolute root required.",nameof(rootPath));var root=Path.GetFullPath(rootPath);if(realmLease.Custody is not FileGlobalParticipantAllocatorRealmStoreV1.RootCustody custody)throw new ArgumentException("Realm custody does not match root.",nameof(realmLease));bool matches;try{matches=custody.MatchesRootIdentity(root);}catch(ObjectDisposedException){return ValueTask.FromResult<OpenResultV1>(new OpenResultV1.RealmFenced(realmLease.Manifest.FenceEpoch));}if(!matches)throw new ArgumentException("Realm custody does not match root.",nameof(realmLease));if(!realmLease.TryAcquireUse(out var use))return ValueTask.FromResult<OpenResultV1>(new OpenResultV1.RealmFenced(realmLease.Manifest.FenceEpoch));using(use)return OpenStreaming(root,realmLease,null,cancellationToken);}
    internal static ValueTask<OpenResultV1> OpenForTestingAsync(string rootPath, GlobalParticipantAllocatorRealmLeaseV1 realmLease, Func<BoundedAscii, ValueTask> stageFault, CancellationToken cancellationToken) { cancellationToken.ThrowIfCancellationRequested();ArgumentNullException.ThrowIfNull(realmLease);ArgumentNullException.ThrowIfNull(stageFault);if(!Path.IsPathFullyQualified(rootPath))throw new ArgumentException("Absolute root required.",nameof(rootPath));var root=Path.GetFullPath(rootPath);if(realmLease.Custody is not FileGlobalParticipantAllocatorRealmStoreV1.RootCustody custody)throw new ArgumentException("Realm custody does not match root.",nameof(realmLease));bool matches;try{matches=custody.MatchesRootIdentity(root);}catch(ObjectDisposedException){return ValueTask.FromResult<OpenResultV1>(new OpenResultV1.RealmFenced(realmLease.Manifest.FenceEpoch));}if(!matches)throw new ArgumentException("Realm custody does not match root.",nameof(realmLease));if(!realmLease.TryAcquireUse(out var use))return ValueTask.FromResult<OpenResultV1>(new OpenResultV1.RealmFenced(realmLease.Manifest.FenceEpoch));using(use){var volume = ManagedTestingTransport.GetForTesting(root); volume.OpenHandle(); try { var result=OpenStreaming(root,realmLease,stageFault,cancellationToken);if(result.IsCompletedSuccessfully&&result.Result is not OpenResultV1.Opened)volume.CloseHandle();return result; } catch { volume.CloseHandle(); throw; }} }
    private static ValueTask<OpenResultV1> OpenStreaming(string root, GlobalParticipantAllocatorRealmLeaseV1 lease, Func<BoundedAscii, ValueTask>? fault, CancellationToken token)
    { try{return OpenStreamingCore(root,lease,fault,token);}catch(Exception exception) when(exception is InvalidDataException or OverflowException or ArgumentException){var state=new State(Array.Empty<ReadOnlyMemory<byte>>(),Array.Empty<KeyValuePair<JournalFactId,int>>(),null,GlobalParticipantAllocatorCodecsV1.EmptyIndexRoot(),0,default,0,1,0,new BoundedAscii("durable-state-invalid"));return ValueTask.FromResult<OpenResultV1>(new OpenResultV1.Quarantined(new("durable-state-invalid")));}catch(IOException){return ValueTask.FromResult<OpenResultV1>(new OpenResultV1.StoreUnavailable(new("store-unavailable")));} }
    private static ValueTask<OpenResultV1> OpenStreamingCore(string root, GlobalParticipantAllocatorRealmLeaseV1 lease, Func<BoundedAscii, ValueTask>? fault, CancellationToken token)
    {
        token.ThrowIfCancellationRequested();
        var custody = (FileGlobalParticipantAllocatorRealmStoreV1.RootCustody)lease.Custody;
        var anchor = custody.ReadChildBounded("committed.head", 0, 400);
        var logLength = FindChildLength(custody, "authority.log", 544210944);
        if (!RecoverAnchorBytes(anchor, lease.Manifest.JournalId, lease.Manifest.FenceEpoch, logLength, out var committed, out var generation, out var activeSlot, out var allowTail, out var anchorCount, out var anchorTotal, out var anchorHeadSequence, out var anchorHeadHash, out var anchorRoot, out var anchorLast) || committed > logLength) throw new InvalidDataException("Durable anchor invalid.");
        if (logLength > committed && !allowTail) throw new InvalidDataException("Durable suffix is unexplained.");

        var records = new List<ReadOnlyMemory<byte>>(checked((int)anchorCount));
        var facts = new Dictionary<JournalFactId, int>(65536);
        var recoveryFold=GlobalParticipantAllocatorFoldV1.Create(lease.Manifest.JournalId); GlobalParticipantAuthorityHeadV1? recoveryHead=null;
        Hash256 last = default; ulong offset = 0;
        while (offset < committed)
        {
            var header = custody.ReadChildBounded("authority.log", checked((long)offset), 80);
            if (header.Length != 80 || !header.AsSpan(0, 8).SequenceEqual("HPDGPA03"u8)) throw new InvalidDataException("Durable frame header invalid.");
            var length = BinaryPrimitives.ReadUInt32BigEndian(header.AsSpan(8, 4)); var recordLength = BinaryPrimitives.ReadUInt32BigEndian(header.AsSpan(44, 4));
            if (length != 112 + recordLength || recordLength is 0 or > 8192 || offset + length > committed) throw new InvalidDataException("Durable frame length invalid.");
            var tail = custody.ReadChildBounded("authority.log", checked((long)offset + 80), checked((int)recordLength + 32)); if (tail.Length != recordLength + 32) throw new InvalidDataException("Durable frame truncated.");
            using var encoded = new MemoryStream(checked((int)length)); encoded.Write(header); encoded.Write(tail); encoded.Position = 0;
            if (!TryReadFrame(encoded, out var frame) || frame.Epoch > lease.Manifest.FenceEpoch || frame.Sequence != (ulong)records.Count + 1 || frame.PriorFrameHash != last) throw new InvalidDataException("Durable frame authentication invalid.");
            var result=recoveryFold.Apply(frame.Record);if(result is not GlobalParticipantAllocatorFoldApplyResultV1.Accepted accepted)throw new InvalidDataException("Durable replay invalid.");
            var owned = (ReadOnlyMemory<byte>)frame.Record.ToArray(); records.Add(owned); facts.Add(frame.FactId, records.Count - 1); recoveryHead=accepted.Head;last = frame.FrameHash; offset += length;
        }
        var completed=((GlobalParticipantAllocatorFoldResultV1.Current)recoveryFold.Complete()).Snapshot;var replayRoot=completed.IndexRoot;
        if (anchorCount != (ulong)records.Count || anchorTotal != completed.TotalCanonicalRecordBytes || anchorHeadSequence != (completed.Head?.Position.Sequence ?? 0) || anchorHeadHash != (completed.Head?.RecordHash ?? default) || anchorRoot != replayRoot || anchorLast != last) throw new InvalidDataException($"Durable anchor tuple invalid count={anchorCount}/{records.Count} total={anchorTotal}/{completed.TotalCanonicalRecordBytes} headSeq={anchorHeadSequence}/{completed.Head?.Position.Sequence ?? 0} headHash={anchorHeadHash==(completed.Head?.RecordHash??default)} root={anchorRoot==replayRoot} last={anchorLast==last}");
        try { fault?.Invoke(new("before-anchor-adoption-flush")).AsTask().GetAwaiter().GetResult(); }
        catch(IOException) { return ValueTask.FromResult<OpenResultV1>(new OpenResultV1.StoreUnavailable(new("store-unavailable"))); }
        try { custody.FlushChild("committed.head"); fault?.Invoke(new("after-anchor-adoption-flush")).AsTask().GetAwaiter().GetResult(); }
        catch(IOException) { return ValueTask.FromResult<OpenResultV1>(new OpenResultV1.OutcomeUnknown(lease.Manifest.JournalId,new("durability-unknown"))); }
        if(logLength>committed)
        {
            try
            {
                fault?.Invoke(new("recovery-before-tail-truncate")).AsTask().GetAwaiter().GetResult();
                custody.TruncateChild("authority.log",checked((long)committed));
                fault?.Invoke(new("recovery-after-tail-truncate-before-flush")).AsTask().GetAwaiter().GetResult();
                custody.FlushChild("authority.log");
                fault?.Invoke(new("recovery-after-tail-flush")).AsTask().GetAwaiter().GetResult();
            }
            catch(IOException) { return ValueTask.FromResult<OpenResultV1>(new OpenResultV1.OutcomeUnknown(lease.Manifest.JournalId,new("durability-unknown"))); }
        }
        return ValueTask.FromResult<OpenResultV1>(new OpenResultV1.Opened(new FileGlobalParticipantAllocatorDurableBackendV1(root, lease, fault, new(records, facts, completed.Head, replayRoot, completed.TotalCanonicalRecordBytes, last, committed, generation, activeSlot, null))));
    }
    private static ulong FindChildLength(FileGlobalParticipantAllocatorRealmStoreV1.RootCustody custody, string name, ulong maximum)
    { ulong offset = 0; const int chunk = 65536; while (offset <= maximum) { var request = (int)Math.Min((ulong)chunk, maximum - offset + 1); var bytes = custody.ReadChildBounded(name, checked((long)offset), request); offset += (ulong)bytes.Length; if (bytes.Length < request) return offset; } throw new IOException("Child bound exceeded."); }


    async ValueTask<GlobalParticipantAllocatorDurableClaimResultV1> IGlobalParticipantAllocatorDurableClaimPortV1.ClaimAsync(GlobalParticipantAllocatorDurableClaimRequestV1 request, CancellationToken token)
    {
        ArgumentNullException.ThrowIfNull(request); if (!request.RealmLease.TryAcquireUse(out var use)) return new GlobalParticipantAllocatorDurableClaimResultV1.RealmFenced(_lease.Manifest.FenceEpoch); using (use)
        {
            token.ThrowIfCancellationRequested(); await _gate.WaitAsync(token); try
            {
                if (_disposed != 0) return new GlobalParticipantAllocatorDurableClaimResultV1.StoreUnavailable(new("store-unavailable")); if (request.RealmLease != _lease || !ManifestMatchesLease()) return new GlobalParticipantAllocatorDurableClaimResultV1.RealmFenced(CurrentEpoch()); if (_state.Quarantine is { } q) return new GlobalParticipantAllocatorDurableClaimResultV1.Quarantined(q); if (_state.Facts.TryGetValue(request.FactId, out var oldIndex)){var oldBytes=_state.RecordAt(oldIndex);var oldHead=HeadFor(request.FactId,oldBytes);return oldBytes.Span.SequenceEqual(request.ExactCanonicalRecordBytes.Span) ? new GlobalParticipantAllocatorDurableClaimResultV1.AlreadyCommitted(oldHead,(ulong)oldIndex+1,oldBytes) : new GlobalParticipantAllocatorDurableClaimResultV1.ContradictoryDuplicate(request.FactId, new("fact-id-bytes-conflict"));} if (request.ExpectedHead != _state.Head) return new GlobalParticipantAllocatorDurableClaimResultV1.HeadConflict(_state.Head);
                if(!TryEvaluateCandidate(request,out var committedHead,out var nextRoot,out var insertedOwner,out var invalidCode))return new GlobalParticipantAllocatorDurableClaimResultV1.InvalidRecord(invalidCode);var committedSequence=(ulong)_state.RecordCount+1;
                byte[] bytes,frame,projected;Hash256 nextLast;ulong nextLength,nextGeneration;int nextSlot;bool insertsOwner;var mutationStage=0;
                try { bytes=request.ExactCanonicalRecordBytes.ToArray();frame=EncodeFrame(_lease.Manifest.FenceEpoch,committedSequence,request.FactId,bytes,_state.LastFrameHash);insertsOwner=insertedOwner is not null;nextLast=Hash256.FromBytes(frame.AsSpan(frame.Length-32));nextLength=checked(_state.CommittedLength+(ulong)frame.Length);nextGeneration=checked(_state.Generation+1);nextSlot=1-_state.ActiveSlot;_state.EnsureNextRecordCapacity();projected=ProjectedAnchor(_lease.Manifest.JournalId,_lease.Manifest.FenceEpoch,nextGeneration,nextLength,checked((ulong)_state.RecordCount+1),checked(_state.TotalBytes+(ulong)bytes.Length),committedHead,nextRoot,nextLast);await Fault("before-frame-write"); } catch (Exception exception) when (exception is IOException or UnauthorizedAccessException or OverflowException or OutOfMemoryException) { return new GlobalParticipantAllocatorDurableClaimResultV1.StoreUnavailable(new("prewrite-capacity-unavailable")); }
                try { mutationStage=1;if (_fault is not null) { var volume = ManagedTestingTransport.GetForTesting(_root); await Fault("during-frame-write"); volume.PwriteVolatile("authority.log", (long)_state.CommittedLength, frame.AsSpan(0, 80)); volume.FileFlush("authority.log"); volume.PwriteVolatile("authority.log", (long)_state.CommittedLength + 80, frame.AsSpan(80)); volume.FileFlush("authority.log"); } else { await Fault("during-frame-write"); _custody.WriteChildExact("authority.log", (long)_state.CommittedLength, frame.AsSpan(0, 80), true); _custody.WriteChildExact("authority.log", (long)_state.CommittedLength + 80, frame.AsSpan(80), true); } mutationStage=2;await Fault("after-frame-flush-before-anchor");await Fault("during-inactive-anchor-write");WriteAnchor(projected,nextSlot);mutationStage=3;_state.Head=committedHead;_state.IndexRoot=nextRoot;_state.TotalBytes+=(ulong)bytes.Length;_state.LastFrameHash=nextLast;_state.CommittedLength=nextLength;_state.Generation=nextGeneration;_state.ActiveSlot=nextSlot;_state.PublishRecord(bytes);if(insertedOwner is not null){_state.OwnerCount++;_state.Owners.Add(insertedOwner.ParticipantId,insertedOwner);}_state.Facts.Add(request.FactId,_state.RecordCount-1); await Fault("after-anchor-flush-before-ack"); return new GlobalParticipantAllocatorDurableClaimResultV1.Committed(committedHead, committedSequence, bytes); } catch (Exception exception) when (exception is IOException or UnauthorizedAccessException) { return new GlobalParticipantAllocatorDurableClaimResultV1.OutcomeUnknown(request.FactId, new(mutationStage==3?"acknowledgement-lost":mutationStage==1?"operation-interrupted":"durability-unknown")); }
            }
            finally { _gate.Release(); }
        }
    }
    async ValueTask<GlobalParticipantAllocatorReconcileResultV1> IGlobalParticipantAllocatorReconciliationPortV1.ReconcileAsync(GlobalParticipantAllocatorReconcileRequestV1 request, CancellationToken token) { ArgumentNullException.ThrowIfNull(request); if (!request.RealmLease.TryAcquireUse(out var use)) return new GlobalParticipantAllocatorReconcileResultV1.RealmFenced(_lease.Manifest.FenceEpoch); using (use) { await _gate.WaitAsync(token); try { if (_disposed != 0 || request.RealmLease != _lease || !ManifestMatchesLease()) return new GlobalParticipantAllocatorReconcileResultV1.RealmFenced(CurrentEpoch()); if (_state.Quarantine is { } q) return new GlobalParticipantAllocatorReconcileResultV1.Quarantined(q); if(!_state.Facts.TryGetValue(request.FactId,out var index))return new GlobalParticipantAllocatorReconcileResultV1.NotFound();var bytes=_state.RecordAt(index);return new GlobalParticipantAllocatorReconcileResultV1.Committed(HeadFor(request.FactId,bytes),(ulong)index+1,bytes); } finally { _gate.Release(); } } }
    async ValueTask<GlobalParticipantAllocatorDurableSnapshotResultV1> IGlobalParticipantAllocatorDurableSnapshotPortV1.ReadAsync(GlobalParticipantAllocatorDurableSnapshotRequestV1 request, CancellationToken token) { ArgumentNullException.ThrowIfNull(request); if (!request.RealmLease.TryAcquireUse(out var use)) return new GlobalParticipantAllocatorDurableSnapshotResultV1.RealmFenced(_lease.Manifest.FenceEpoch); using (use) { await _gate.WaitAsync(token); try { if (_disposed != 0 || request.RealmLease != _lease || !ManifestMatchesLease()) return new GlobalParticipantAllocatorDurableSnapshotResultV1.RealmFenced(CurrentEpoch()); if (_state.Quarantine is { } q) return new GlobalParticipantAllocatorDurableSnapshotResultV1.Quarantined(q); return new GlobalParticipantAllocatorDurableSnapshotResultV1.Current(new(_lease.Manifest.JournalId, _state.Head, (ulong)_state.RecordCount, _state.TotalBytes, _state.Records.Select(x => (ReadOnlyMemory<byte>)x.ToArray()).ToArray())); } finally { _gate.Release(); } } }
    internal async ValueTask<IGlobalParticipantAllocatorPageSourceV1> CreatePinnedPageSourceAsync(GlobalParticipantAllocatorDurableSnapshotRequestV1 request, CancellationToken token) { ArgumentNullException.ThrowIfNull(request); if (!request.RealmLease.TryAcquireUse(out var use)) throw new InvalidOperationException("Realm fenced."); using (use) { await _gate.WaitAsync(token); try { if (_disposed != 0 || request.RealmLease != _lease || !ManifestMatchesLease() || _state.Quarantine is not null) throw new InvalidOperationException("Snapshot unavailable."); var captured = _state; return new PinnedPageSource(_lease.Manifest.JournalId, captured.Head, captured.IndexRoot, captured.Records, captured.TotalBytes); } finally { _gate.Release(); } } }
    private async ValueTask Fault(string s) { if (_fault is null) return; try { await _fault(new(s)); } catch (Exception exception) { throw new IOException("Injected storage-stage failure.", exception); } }
    private byte[] ReadChild(string name) => _custody.ReadChildBounded(name, 0, 8192);
    private ulong CurrentEpoch() { try { var b = ReadChild("realm.manifest"); return b.Length == 127 ? BinaryPrimitives.ReadUInt64BigEndian(b.AsSpan(47, 8)) : _lease.Manifest.FenceEpoch; } catch { return _lease.Manifest.FenceEpoch; } }
    private bool ManifestMatchesLease() { try { var b = ReadChild("realm.manifest"); if (b.Length != 127 || !b.AsSpan(0, 29).SequenceEqual("hpd-s1-gpa-realm-manifest-v1\0"u8)) return false; Span<byte> journal = stackalloc byte[16], store = stackalloc byte[32], hash = stackalloc byte[32]; _lease.Manifest.JournalId.TryWriteBytes(journal); _lease.Manifest.StoreIdentity.TryWriteBytes(store); _lease.Manifest.ManifestHash.TryWriteBytes(hash); return b.AsSpan(29, 16).SequenceEqual(journal) && BinaryPrimitives.ReadUInt16BigEndian(b.AsSpan(45, 2)) == 1 && BinaryPrimitives.ReadUInt64BigEndian(b.AsSpan(47, 8)) == _lease.Manifest.FenceEpoch && b.AsSpan(55, 32).SequenceEqual(store) && BinaryPrimitives.ReadInt64BigEndian(b.AsSpan(87, 8)) == _lease.Manifest.CreatedAt.NanosecondsSinceUnixEpoch && b.AsSpan(95, 32).SequenceEqual(hash); } catch { return false; } }
    private bool TryEvaluateCandidate(GlobalParticipantAllocatorDurableClaimRequestV1 request,out GlobalParticipantAuthorityHeadV1 head,out Hash256 root,out ParticipantIdOwnerEvidenceV1? inserted,out BoundedAscii code){head=default;root=_state.IndexRoot;inserted=null;code=new("head-invalid");var bytes=request.ExactCanonicalRecordBytes;if(!GlobalParticipantAllocatorCodecsV1.TryDecodeOuter(bytes,out var outer)||outer is null||!GlobalParticipantAllocatorCodecsV1.TryDecodeBody(outer.BodyBytes.ToArray(),out var body)||body is null){code=new("record-wire-invalid");return false;}var fingerprint=GlobalParticipantAllocatorFactIdsV1.SourceFingerprint(body.Source);var fact=GlobalParticipantAllocatorFactIdsV1.Fact(outer.SourceSession.LiveSessionId,body.OperationId,fingerprint);if(fact!=request.FactId){code=new("fact-id-mismatch");return false;}var participant=GlobalParticipantAllocatorFactIdsV1.Participant(outer.SourceSession.LiveSessionId,body.OperationId,fingerprint);if(participant!=body.ParticipantId){code=new("participant-id-mismatch");return false;}if(body.AssignedPosition.JournalId!=_lease.Manifest.JournalId||body.AssignedPosition.Sequence!=(ulong)_state.RecordCount+1||body.PriorHead!=_state.Head)return false;var proof=body.OwnerProof;var owner=_state.Owners.TryGetValue(body.ParticipantId,out var retained)?retained:null;if(proof.Head!=_state.Head||proof.IndexRoot!=_state.IndexRoot||proof.RecordCount!=(ulong)_state.RecordCount||proof.State!=(owner is null?1:2)||!OwnerEqual(proof.Owner,owner)||!GlobalParticipantAllocatorCodecsV1.VerifyProof(body.ParticipantId,proof.State,proof.Owner,proof.IndexRoot,proof.ProofPathBytes))return false;var transition=GlobalParticipantAllocatorFoldV1.EvaluateTransition(owner,body.Outcome);if(body.Source.LiveSessionId!=outer.SourceSession.LiveSessionId||body.Source.SourceFactPosition.Session!=outer.SourceSession||!transition.Valid)return false;var hash=GlobalParticipantAllocatorFactIdsV1.RecordHash(body.AssignedPosition,_state.Head,fact,outer.SourceSession,outer.SourceExpectedAuthority,outer.BodyBytes);head=new(body.AssignedPosition,hash);if(transition.InsertOwnerAfterHash){inserted=new(body.ParticipantId,body.Source.LiveSessionId,body.OperationId,fingerprint,head);root=SparseIndex.ApplyOwner(body.ParticipantId,inserted,proof.ProofPathBytes);}return true;}
    private static bool OwnerEqual(ParticipantIdOwnerEvidenceV1? x,ParticipantIdOwnerEvidenceV1? y)=>x is null?y is null:y is not null&&GlobalParticipantAllocatorCodecsV1.Encode(x).AsSpan().SequenceEqual(GlobalParticipantAllocatorCodecsV1.Encode(y));
    private static Hash256 Root(GlobalParticipantAllocatorJournalId journal, IEnumerable<ReadOnlyMemory<byte>> records) { var fold = GlobalParticipantAllocatorFoldV1.Create(journal); foreach (var record in records) if (fold.Apply(record) is GlobalParticipantAllocatorFoldApplyResultV1.InvalidHistory) return default; return ((GlobalParticipantAllocatorFoldResultV1.Current)fold.Complete()).Snapshot.IndexRoot; }
    private static GlobalParticipantAuthorityHeadV1 HeadFor(JournalFactId fact,ReadOnlyMemory<byte> bytes){if(!GlobalParticipantAllocatorCodecsV1.TryDecodeOuter(bytes,out var outer)||outer is null||!GlobalParticipantAllocatorCodecsV1.TryDecodeBody(outer.BodyBytes.ToArray(),out var body)||body is null)throw new InvalidOperationException("Retained canonical record invalid.");var hash=GlobalParticipantAllocatorFactIdsV1.RecordHash(body.AssignedPosition,body.PriorHead,fact,outer.SourceSession,outer.SourceExpectedAuthority,outer.BodyBytes);return new(body.AssignedPosition,hash);}
    internal static byte[] EmptyAnchor(GlobalParticipantAllocatorJournalId journal) { var fold = GlobalParticipantAllocatorFoldV1.Create(journal); var current = (GlobalParticipantAllocatorFoldResultV1.Current)fold.Complete(); var state = new State(Array.Empty<ReadOnlyMemory<byte>>(), new Dictionary<JournalFactId,int>(), null, current.Snapshot.IndexRoot, 0, default, 0, 1, 0, null); return AnchorSlot(state, journal, 1); }
    private static byte[] EncodeFrame(ulong epoch, ulong seq, JournalFactId fact, byte[] record, Hash256 prior) { var b = new byte[112 + record.Length]; "HPDGPA03"u8.CopyTo(b); BinaryPrimitives.WriteUInt32BigEndian(b.AsSpan(8), checked((uint)b.Length)); BinaryPrimitives.WriteUInt64BigEndian(b.AsSpan(12), epoch); BinaryPrimitives.WriteUInt64BigEndian(b.AsSpan(20), seq); fact.TryWriteBytes(b.AsSpan(28, 16)); BinaryPrimitives.WriteUInt32BigEndian(b.AsSpan(44), checked((uint)record.Length)); prior.TryWriteBytes(b.AsSpan(48, 32)); record.CopyTo(b, 80); var pre = new byte["hpd-s1-gpa-log-frame-v3\0"u8.Length + 80 + record.Length]; "hpd-s1-gpa-log-frame-v3\0"u8.CopyTo(pre); b.AsSpan(0, 80 + record.Length).CopyTo(pre.AsSpan("hpd-s1-gpa-log-frame-v3\0"u8.Length)); Hash256.Compute(pre).TryWriteBytes(b.AsSpan(80 + record.Length)); return b; }
    private static bool TryReadFrame(Stream s, out Frame frame) { frame = null!; Span<byte> h = stackalloc byte[80]; if (s.Read(h) == 0) return false; if (s.Position < 80 || !h[..8].SequenceEqual("HPDGPA03"u8)) return false; var length = BinaryPrimitives.ReadUInt32BigEndian(h[8..]); var recordLength = BinaryPrimitives.ReadUInt32BigEndian(h[44..]); if (length != 112 + recordLength || recordLength is 0 or > 8192) return false; var tail = new byte[recordLength + 32]; s.ReadExactly(tail); var fact = JournalFactId.FromValue(StableId128.FromBytes(h[28..44])); var sequence = BinaryPrimitives.ReadUInt64BigEndian(h[20..]); var prior = sequence == 1 && h[48..80].SequenceEqual(new byte[32]) ? default : Hash256.FromBytes(h[48..80]); var epoch = BinaryPrimitives.ReadUInt64BigEndian(h[12..]); var record = tail.AsSpan(0, (int)recordLength).ToArray(); var expected = EncodeFrame(epoch, sequence, fact, record, prior); if (!expected.AsSpan(expected.Length - 32).SequenceEqual(tail.AsSpan((int)recordLength))) return false; var hash = Hash256.FromBytes(tail.AsSpan((int)recordLength)); frame = new(epoch, sequence, fact, record, prior, hash); return true; }
    private static byte[] AnchorSlot(State s, GlobalParticipantAllocatorJournalId journal, ulong epoch) { var b = new byte[200]; "HPDANC01"u8.CopyTo(b); BinaryPrimitives.WriteUInt64BigEndian(b.AsSpan(8), s.Generation); BinaryPrimitives.WriteUInt64BigEndian(b.AsSpan(16), s.CommittedLength); BinaryPrimitives.WriteUInt64BigEndian(b.AsSpan(24), epoch); BinaryPrimitives.WriteUInt64BigEndian(b.AsSpan(32), (ulong)s.RecordCount); BinaryPrimitives.WriteUInt64BigEndian(b.AsSpan(40), s.TotalBytes); journal.TryWriteBytes(b.AsSpan(48, 16)); if (s.Head is { } h) { BinaryPrimitives.WriteUInt64BigEndian(b.AsSpan(64), h.Position.Sequence); h.RecordHash.TryWriteBytes(b.AsSpan(72, 32)); } s.IndexRoot.TryWriteBytes(b.AsSpan(104, 32)); s.LastFrameHash.TryWriteBytes(b.AsSpan(136, 32)); var pre = new byte["hpd-s1-gpa-commit-anchor-v1\0"u8.Length + 168]; "hpd-s1-gpa-commit-anchor-v1\0"u8.CopyTo(pre); b.AsSpan(0, 168).CopyTo(pre.AsSpan("hpd-s1-gpa-commit-anchor-v1\0"u8.Length)); Hash256.Compute(pre).TryWriteBytes(b.AsSpan(168)); return b; }
    private static byte[] ReadNativeChild(int rootFd, string name, int maximum) { var fd = FileGlobalParticipantAllocatorRealmStoreV1.LinuxNative.openat(rootFd, name, FileGlobalParticipantAllocatorRealmStoreV1.LinuxNative.O_RDONLY | FileGlobalParticipantAllocatorRealmStoreV1.LinuxNative.O_CLOEXEC | FileGlobalParticipantAllocatorRealmStoreV1.LinuxNative.O_NOFOLLOW, 0); if (fd < 0) throw new IOException("Required child open failed."); try { using var stream = new FileStream(new Microsoft.Win32.SafeHandles.SafeFileHandle((IntPtr)fd, false), FileAccess.Read, 4096, false); if (stream.Length < 0 || stream.Length > maximum) throw new IOException("Child length invalid."); var bytes = new byte[stream.Length]; stream.ReadExactly(bytes); return bytes; } finally { FileGlobalParticipantAllocatorRealmStoreV1.LinuxNative.close(fd); } }
    private static bool RecoverAnchorBytes(byte[] bytes, GlobalParticipantAllocatorJournalId journal, ulong epoch, ulong logLength, out ulong committed, out ulong generation, out int activeSlot, out bool allowTail, out ulong count, out ulong total, out ulong headSequence, out Hash256 headHash, out Hash256 root, out Hash256 last) { committed = 0; generation = 0; activeSlot = 0; allowTail = false; count = total = headSequence = 0; headHash = root = last = default; if (bytes.Length != 400 || epoch == 0) return false; Span<byte> journalBytes = stackalloc byte[16]; journal.TryWriteBytes(journalBytes); var valid = new bool[2]; var lengths = new ulong[2]; var generations = new ulong[2]; for (var i = 0; i < 2; i++) { var slot = bytes.AsSpan(i * 200, 200); if (!slot[..8].SequenceEqual("HPDANC01"u8) || !slot.Slice(48, 16).SequenceEqual(journalBytes)) continue; var fence = BinaryPrimitives.ReadUInt64BigEndian(slot[24..]); if (fence is 0 || fence > epoch) continue; var pre = new byte["hpd-s1-gpa-commit-anchor-v1\0"u8.Length + 168]; "hpd-s1-gpa-commit-anchor-v1\0"u8.CopyTo(pre); slot[..168].CopyTo(pre.AsSpan("hpd-s1-gpa-commit-anchor-v1\0"u8.Length)); var checksum = new byte[32]; Hash256.Compute(pre).TryWriteBytes(checksum); if (!checksum.AsSpan().SequenceEqual(slot[168..200])) continue; generations[i] = BinaryPrimitives.ReadUInt64BigEndian(slot[8..]); lengths[i] = BinaryPrimitives.ReadUInt64BigEndian(slot[16..]); if (generations[i] is 0 or ulong.MaxValue) continue; valid[i] = true; } if (!valid[0] && !valid[1]) return false; if (valid[0] && valid[1] && generations[0] == generations[1] && !bytes.AsSpan(0, 200).SequenceEqual(bytes.AsSpan(200, 200))) return false; activeSlot = valid[0] && valid[1] ? (generations[1] > generations[0] ? 1 : 0) : (valid[0] ? 0 : 1); var chosen = bytes.AsSpan(activeSlot * 200, 200); committed = lengths[activeSlot]; generation = generations[activeSlot]; allowTail = valid[0] && valid[1]; if (!allowTail && logLength != committed) return false; count = BinaryPrimitives.ReadUInt64BigEndian(chosen[32..]); total = BinaryPrimitives.ReadUInt64BigEndian(chosen[40..]); headSequence = BinaryPrimitives.ReadUInt64BigEndian(chosen[64..]); headHash = headSequence == 0 ? default : Hash256.FromBytes(chosen[72..104]); root = Hash256.FromBytes(chosen[104..136]); last = committed == 0 ? default : Hash256.FromBytes(chosen[136..168]); return true; }
    private void WriteAnchor(State s, GlobalParticipantAllocatorJournalId journal, ulong epoch) { var slot = AnchorSlot(s, journal, epoch); if (_fault is not null) { var volume = ManagedTestingTransport.GetForTesting(_root); volume.PwriteVolatile("committed.head", s.ActiveSlot * 200L, slot); _fault(new("after-anchor-write-before-flush")).AsTask().GetAwaiter().GetResult(); volume.FileFlush("committed.head"); var verify = volume.ReadVolatileOwned("committed.head").AsSpan(s.ActiveSlot * 200, 200); if (!verify.SequenceEqual(slot)) throw new IOException("Anchor reread verification failed."); return; } _custody.WriteChildExact("committed.head", s.ActiveSlot * 200L, slot, true); _custody.FlushChild("committed.head"); var bytes = _custody.ReadChildBounded("committed.head", s.ActiveSlot * 200L, 200); if (!bytes.AsSpan().SequenceEqual(slot)) throw new IOException("Anchor reread verification failed."); }
    private static byte[] ProjectedAnchor(GlobalParticipantAllocatorJournalId journal,ulong epoch,ulong generation,ulong committedLength,ulong count,ulong total,GlobalParticipantAuthorityHeadV1? head,Hash256 root,Hash256 last){var b=new byte[200];"HPDANC01"u8.CopyTo(b);BinaryPrimitives.WriteUInt64BigEndian(b.AsSpan(8),generation);BinaryPrimitives.WriteUInt64BigEndian(b.AsSpan(16),committedLength);BinaryPrimitives.WriteUInt64BigEndian(b.AsSpan(24),epoch);BinaryPrimitives.WriteUInt64BigEndian(b.AsSpan(32),count);BinaryPrimitives.WriteUInt64BigEndian(b.AsSpan(40),total);journal.TryWriteBytes(b.AsSpan(48,16));if(head is{}h){BinaryPrimitives.WriteUInt64BigEndian(b.AsSpan(64),h.Position.Sequence);h.RecordHash.TryWriteBytes(b.AsSpan(72,32));}root.TryWriteBytes(b.AsSpan(104,32));last.TryWriteBytes(b.AsSpan(136,32));var pre=new byte["hpd-s1-gpa-commit-anchor-v1\0"u8.Length+168];"hpd-s1-gpa-commit-anchor-v1\0"u8.CopyTo(pre);b.AsSpan(0,168).CopyTo(pre.AsSpan("hpd-s1-gpa-commit-anchor-v1\0"u8.Length));Hash256.Compute(pre).TryWriteBytes(b.AsSpan(168));return b;}
    private void WriteAnchor(byte[] slot,int slotIndex){if(_fault is not null){var volume=ManagedTestingTransport.GetForTesting(_root);volume.PwriteVolatile("committed.head",slotIndex*200L,slot);_fault(new("after-anchor-write-before-flush")).AsTask().GetAwaiter().GetResult();volume.FileFlush("committed.head");var verify=volume.ReadVolatileRangeOwned("committed.head",slotIndex*200L,200);if(!verify.AsSpan().SequenceEqual(slot))throw new IOException("Anchor reread verification failed.");return;}_custody.WriteChildExact("committed.head",slotIndex*200L,slot,true);_custody.FlushChild("committed.head");var bytes=_custody.ReadChildBounded("committed.head",slotIndex*200L,200);if(!bytes.AsSpan().SequenceEqual(slot))throw new IOException("Anchor reread verification failed.");}
    internal ValueTask DisposeAsync() { lock (_disposeGate) return new ValueTask(_disposeTask ??= DisposeCoreAsync()); }
    private async Task DisposeCoreAsync() { Interlocked.Exchange(ref _disposed, 1); await _gate.WaitAsync(); try { if (_fault is not null) ManagedTestingTransport.GetForTesting(_root).CloseHandle(); } finally { _gate.Release(); } }
    ValueTask IAsyncDisposable.DisposeAsync() => DisposeAsync();
}
