namespace HPD.Agent.Authority;

internal sealed record GraphParticipantBindingRequestV2
{
    internal GraphParticipantBindingRequestV2(GraphParticipantReservationResultV2.Applied appliedReservation, GraphParticipantReservationFoldV2.AppliedReservation authenticatedReservation, GraphParticipantBindingPlanEvidenceV2 bindingEvidence, CorrelationEnvelopeV1 correlation, MonotonicStampV1 bindingObservedAt, UtcInstant observedAt, ulong maximumSessionRecords, ulong maximumSessionCanonicalBytes)
    {
        AppliedReservation = appliedReservation ?? throw new ArgumentNullException(nameof(appliedReservation));
        AuthenticatedReservation = authenticatedReservation ?? throw new ArgumentNullException(nameof(authenticatedReservation));
        BindingEvidence = bindingEvidence ?? throw new ArgumentNullException(nameof(bindingEvidence));
        if (!correlation.IsValid || !bindingObservedAt.IsValid || maximumSessionRecords is 0 or > 65_536 || maximumSessionCanonicalBytes is 0 or > 536_870_912) throw new ArgumentException("Invalid binding request.");
        if (bindingEvidence.ExpiresAt is CapacityGrantExpiryV1.At expiresAt && expiresAt.Value.CompareTo(bindingObservedAt) != ClockComparison.Later) throw new ArgumentException("The capacity grant is expired or belongs to an incomparable clock.");
        if (appliedReservation.CommandPosition != authenticatedReservation.Command.Position || appliedReservation.FactPosition != authenticatedReservation.Fact.Position || !appliedReservation.ExactCanonicalFactBytes.Span.SequenceEqual(authenticatedReservation.Fact.PayloadMemory.Span) || appliedReservation.ParticipantId != authenticatedReservation.Reservation.ParticipantId || bindingEvidence.PreGrantPlan.ReservationCommandPosition != authenticatedReservation.Command.Position || bindingEvidence.PreGrantPlan.ReservationFactPosition != authenticatedReservation.Fact.Position || bindingEvidence.PreGrantPlan.ParticipantId != appliedReservation.ParticipantId || correlation.OperationId != bindingEvidence.PreGrantPlan.OperationId) throw new ArgumentException("Reservation authority does not match binding evidence.");
        AppliedReservation = appliedReservation; AuthenticatedReservation = authenticatedReservation; BindingEvidence = bindingEvidence; Correlation = correlation; BindingObservedAt = bindingObservedAt; ObservedAt = observedAt; MaximumSessionRecords = maximumSessionRecords; MaximumSessionCanonicalBytes = maximumSessionCanonicalBytes;
    }
    internal GraphParticipantReservationResultV2.Applied AppliedReservation { get; }
    internal GraphParticipantReservationFoldV2.AppliedReservation AuthenticatedReservation { get; }
    internal GraphParticipantBindingPlanEvidenceV2 BindingEvidence { get; }
    internal CorrelationEnvelopeV1 Correlation { get; }
    internal MonotonicStampV1 BindingObservedAt { get; }
    internal UtcInstant ObservedAt { get; }
    internal ulong MaximumSessionRecords { get; }
    internal ulong MaximumSessionCanonicalBytes { get; }
}

internal abstract record GraphParticipantBindingResultV2
{
    private GraphParticipantBindingResultV2() { }
    internal sealed record Bound : GraphParticipantBindingResultV2 { private readonly byte[] _bytes; internal Bound(JournalPositionV1 commandPosition, JournalPositionV1 factPosition, ReadOnlyMemory<byte> exactCanonicalFactBytes, GraphParticipantBindingV1 binding, CapacityGrantBindingProofV1 capacityGrantProof) { if (!commandPosition.IsValid || !factPosition.IsValid || commandPosition.Session != factPosition.Session || factPosition.Sequence <= commandPosition.Sequence || exactCanonicalFactBytes.IsEmpty) throw new ArgumentException("Invalid bound result."); CommandPosition = commandPosition; FactPosition = factPosition; _bytes = exactCanonicalFactBytes.ToArray(); Binding = binding ?? throw new ArgumentNullException(nameof(binding)); CapacityGrantProof = capacityGrantProof ?? throw new ArgumentNullException(nameof(capacityGrantProof)); } internal JournalPositionV1 CommandPosition { get; } internal JournalPositionV1 FactPosition { get; } internal ReadOnlyMemory<byte> ExactCanonicalFactBytes => _bytes.ToArray(); internal GraphParticipantBindingV1 Binding { get; } internal CapacityGrantBindingProofV1 CapacityGrantProof { get; } }
    internal sealed record AlreadyBound : GraphParticipantBindingResultV2 { private readonly byte[] _bytes; internal AlreadyBound(JournalPositionV1 commandPosition, JournalPositionV1 factPosition, ReadOnlyMemory<byte> exactCanonicalFactBytes, GraphParticipantBindingV1 binding, CapacityGrantBindingProofV1 capacityGrantProof) { if (!commandPosition.IsValid || !factPosition.IsValid || commandPosition.Session != factPosition.Session || factPosition.Sequence <= commandPosition.Sequence || exactCanonicalFactBytes.IsEmpty) throw new ArgumentException("Invalid bound result."); CommandPosition = commandPosition; FactPosition = factPosition; _bytes = exactCanonicalFactBytes.ToArray(); Binding = binding ?? throw new ArgumentNullException(nameof(binding)); CapacityGrantProof = capacityGrantProof ?? throw new ArgumentNullException(nameof(capacityGrantProof)); } internal JournalPositionV1 CommandPosition { get; } internal JournalPositionV1 FactPosition { get; } internal ReadOnlyMemory<byte> ExactCanonicalFactBytes => _bytes.ToArray(); internal GraphParticipantBindingV1 Binding { get; } internal CapacityGrantBindingProofV1 CapacityGrantProof { get; } }
    internal sealed record Rejected : GraphParticipantBindingResultV2 { private readonly byte[] _bytes; internal Rejected(JournalPositionV1 commandPosition, JournalPositionV1 factPosition, BoundedAscii safeCode, ReadOnlyMemory<byte> exactCanonicalFactBytes) { if (!commandPosition.IsValid || !factPosition.IsValid || commandPosition.Session != factPosition.Session || factPosition.Sequence <= commandPosition.Sequence || !safeCode.IsValid || exactCanonicalFactBytes.IsEmpty) throw new ArgumentException("Invalid rejected result."); CommandPosition = commandPosition; FactPosition = factPosition; SafeCode = safeCode; _bytes = exactCanonicalFactBytes.ToArray(); } internal JournalPositionV1 CommandPosition { get; } internal JournalPositionV1 FactPosition { get; } internal BoundedAscii SafeCode { get; } internal ReadOnlyMemory<byte> ExactCanonicalFactBytes => _bytes.ToArray(); }
    internal sealed record RetryRequired(BoundedAscii SafeCode) : GraphParticipantBindingResultV2; internal sealed record StoreUnavailable(BoundedAscii SafeCode) : GraphParticipantBindingResultV2; internal sealed record OutcomeUnknown(JournalFactId FactId, BoundedAscii SafeCode) : GraphParticipantBindingResultV2; internal sealed record RealmFenced(ulong CurrentFenceEpoch) : GraphParticipantBindingResultV2; internal sealed record Quarantined(BoundedAscii SafeCode) : GraphParticipantBindingResultV2;
}

internal sealed class GraphParticipantBindingCoordinatorV2
{
    private const int MaximumReplayPasses = 10, MaximumAppendCalls = 6, MaximumPhaseAttempts = 3;
    private readonly IAuthorityJournalV1 _s1Journal, _s2Journal;
    private readonly IGlobalParticipantAllocatorDurableSnapshotPortV1 _allocatorSnapshots;
    private readonly GlobalParticipantAllocatorRealmLeaseV1 _allocatorLease;
    internal GraphParticipantBindingCoordinatorV2(IAuthorityJournalV1 s1Journal, IAuthorityJournalV1 s2Journal, IGlobalParticipantAllocatorDurableSnapshotPortV1 allocatorSnapshots, GlobalParticipantAllocatorRealmLeaseV1 allocatorLease) { _s1Journal = s1Journal ?? throw new ArgumentNullException(nameof(s1Journal)); _s2Journal = s2Journal ?? throw new ArgumentNullException(nameof(s2Journal)); _allocatorSnapshots = allocatorSnapshots ?? throw new ArgumentNullException(nameof(allocatorSnapshots)); _allocatorLease = allocatorLease ?? throw new ArgumentNullException(nameof(allocatorLease)); }

    internal async ValueTask<GraphParticipantBindingResultV2> BindAsync(GraphParticipantBindingRequestV2 request, CancellationToken cancellationToken)
    {
        cancellationToken.ThrowIfCancellationRequested(); ArgumentNullException.ThrowIfNull(request);
        var totalReplayPasses = 0; var totalAppendCalls = 0; var initial = await ReadS1Async(request, cancellationToken).ConfigureAwait(false); totalReplayPasses++;
        if (initial.Result is not null) return initial.Result; var existing = ToTerminal(initial.Fold!, request.BindingEvidence.PreGrantPlan.OperationId, true); if (existing is not null) return existing;
        var s1 = AuthenticateS1Async(request, initial.Fold!); if (s1 is not null) return s1;
        var s2 = await AuthenticateS2Async(request, cancellationToken).ConfigureAwait(false); if (s2.Result is not null) return s2.Result;
        var CoverageValidated = s2.Proof is not null; if (!CoverageValidated) return Quarantine("capacity-history-invalid");
        var allocator = await AuthenticateAllocatorAsync(request, cancellationToken).ConfigureAwait(false); var SourceValidated = allocator is null; if (!SourceValidated) return allocator!;
        if (request.BindingEvidence.TopologyFingerprint != request.BindingEvidence.Topology.Fingerprint || request.BindingEvidence.ExecutableFingerprint != request.BindingEvidence.ExecutablePlan.Fingerprint) return Quarantine("binding-plan-invalid");
        var preCommand = await ReadS1Async(request, cancellationToken).ConfigureAwait(false); totalReplayPasses++;
        if (preCommand.Result is not null) return preCommand.Result;
        var preCommandTerminal = ToTerminal(preCommand.Fold!, request.BindingEvidence.PreGrantPlan.OperationId, true); if (preCommandTerminal is not null) return preCommandTerminal;
        var preCommandAuthentication = AuthenticateS1Async(request, preCommand.Fold!); if (preCommandAuthentication is not null) return preCommandAuthentication;
        initial = preCommand;
        AuthorityFactEnvelopeV1? commandDurable = null;
        for (var commandAttempt = 0; commandAttempt < MaximumPhaseAttempts; commandAttempt++)
        {
            cancellationToken.ThrowIfCancellationRequested();
            var proposal = BuildCommandProposal(request, s2.Proof!);
            if (totalAppendCalls >= MaximumAppendCalls) return new GraphParticipantBindingResultV2.OutcomeUnknown(proposal.FactId, new("binding-outcome-unknown"));
            AppendAuthorityResultV1 append;
            try { totalAppendCalls++; append = await _s1Journal.AppendAsync(new(request.AuthenticatedReservation.Command.Position.Session, initial.Through, [], [proposal], 1_048_576), cancellationToken).ConfigureAwait(false); }
            catch (OperationCanceledException) when (cancellationToken.IsCancellationRequested) { append = new AppendAuthorityResultV1.OutcomeUnknown(request.BindingEvidence.PreGrantPlan.OperationId); }
            catch { append = new AppendAuthorityResultV1.OutcomeUnknown(request.BindingEvidence.PreGrantPlan.OperationId); }
            if (append is AppendAuthorityResultV1.Committed c && c.Envelopes.Count == 1 && EnvelopeMatches(c.Envelopes[0], proposal)) { commandDurable = c.Envelopes[0]; break; }
            if (append is AppendAuthorityResultV1.AlreadyCommitted a && a.Envelopes.Count == 1 && EnvelopeMatches(a.Envelopes[0], proposal)) { commandDurable = a.Envelopes[0]; break; }
            if (append is AppendAuthorityResultV1.UnknownSchema or AppendAuthorityResultV1.InvalidPayload or AppendAuthorityResultV1.ContradictoryDuplicate or AppendAuthorityResultV1.ThreadConflict) return Quarantine("binding-contradiction");
            if (append is AppendAuthorityResultV1.CapacityRefused) return new GraphParticipantBindingResultV2.StoreUnavailable(new("journal-capacity-refused"));
            if (append is AppendAuthorityResultV1.StoreUnavailable) return new GraphParticipantBindingResultV2.StoreUnavailable(new("authority-store-unavailable"));
            var reconciled = await ReconcileAsync(request, CancellationToken.None).ConfigureAwait(false); totalReplayPasses++;
            if (reconciled.Fold?.Query(request.BindingEvidence.PreGrantPlan.OperationId) is GraphParticipantBindingFoldQueryResultV2.CommandOnly found && EnvelopeMatches(found.Command, proposal)) { commandDurable = found.Command; break; }
            if (cancellationToken.IsCancellationRequested) return new GraphParticipantBindingResultV2.OutcomeUnknown(proposal.FactId, new("binding-outcome-unknown"));
            initial = reconciled;
        }
        if (commandDurable is null) return new GraphParticipantBindingResultV2.RetryRequired(new("binding-predecessor-conflict"));
        var elected = await ReadS1Async(request, CancellationToken.None).ConfigureAwait(false); totalReplayPasses++; var election = elected.Fold!.Elect(request.BindingEvidence.PreGrantPlan.OperationId); BoundedAscii? rejection = election is GraphParticipantBindingElectionResultV2.Leader ? null : new BoundedAscii(election is GraphParticipantBindingElectionResultV2.PredecessorConflict ? "binding-predecessor-conflict" : "participant-binding-already-applied");
        for (var factAttempt = 0; factAttempt < MaximumPhaseAttempts; factAttempt++)
        {
            var factProposal = BuildFactProposal(request, commandDurable, s2.Proof!, rejection);
            if (totalAppendCalls >= MaximumAppendCalls || totalReplayPasses >= MaximumReplayPasses) return new GraphParticipantBindingResultV2.OutcomeUnknown(factProposal.FactId, new("binding-outcome-unknown"));
            AppendAuthorityResultV1 append;
            try { totalAppendCalls++; append = await _s1Journal.AppendAsync(new(commandDurable.Position.Session, elected.Through, [], [factProposal], 1_048_576), cancellationToken).ConfigureAwait(false); }
            catch (OperationCanceledException) when (cancellationToken.IsCancellationRequested) { append = new AppendAuthorityResultV1.OutcomeUnknown(request.BindingEvidence.PreGrantPlan.OperationId); }
            catch { append = new AppendAuthorityResultV1.OutcomeUnknown(request.BindingEvidence.PreGrantPlan.OperationId); }
            if (append is AppendAuthorityResultV1.Committed c && (c.Envelopes.Count != 1 || !EnvelopeMatches(c.Envelopes[0], factProposal))) return Quarantine("binding-contradiction");
            if (append is AppendAuthorityResultV1.AlreadyCommitted a && (a.Envelopes.Count != 1 || !EnvelopeMatches(a.Envelopes[0], factProposal))) return Quarantine("binding-contradiction");
            if (append is AppendAuthorityResultV1.Committed or AppendAuthorityResultV1.AlreadyCommitted) { var terminal = await ReadS1Async(request, CancellationToken.None).ConfigureAwait(false); return ToTerminal(terminal.Fold!, request.BindingEvidence.PreGrantPlan.OperationId, false) ?? Quarantine("binding-outcome-unknown"); }
            if (append is AppendAuthorityResultV1.UnknownSchema or AppendAuthorityResultV1.InvalidPayload or AppendAuthorityResultV1.ContradictoryDuplicate or AppendAuthorityResultV1.ThreadConflict) return Quarantine("binding-contradiction");
            if (append is AppendAuthorityResultV1.CapacityRefused) return new GraphParticipantBindingResultV2.StoreUnavailable(new("journal-capacity-refused"));
            if (append is AppendAuthorityResultV1.StoreUnavailable) return new GraphParticipantBindingResultV2.StoreUnavailable(new("authority-store-unavailable"));
            var reconciled = await ReconcileAsync(request, CancellationToken.None).ConfigureAwait(false); totalReplayPasses++;
            var terminalResult = ToTerminal(reconciled.Fold!, request.BindingEvidence.PreGrantPlan.OperationId, false); if (terminalResult is not null) return terminalResult;
            if (cancellationToken.IsCancellationRequested) return new GraphParticipantBindingResultV2.OutcomeUnknown(factProposal.FactId, new("binding-outcome-unknown"));
            elected = reconciled;
        }
        return new GraphParticipantBindingResultV2.OutcomeUnknown(GraphParticipantBindingFactIdsV1.BindingFact(commandDurable.Position), new("binding-outcome-unknown"));
    }

    private GraphParticipantBindingResultV2? AuthenticateS1Async(GraphParticipantBindingRequestV2 request, GraphParticipantBindingFoldV2 fold)
    {
        var ReservationCommandV2 = request.AuthenticatedReservation.Command;
        var ReservationFactV2 = request.AuthenticatedReservation.Fact;
        var operation = request.BindingEvidence.PreGrantPlan.OperationId;
        var replayed = fold.Query(operation) switch
        {
            GraphParticipantBindingFoldQueryResultV2.ReservationOnly x => x.Reservation,
            GraphParticipantBindingFoldQueryResultV2.CommandOnly x => x.Reservation,
            _ => null
        };
        if (replayed is null || replayed.Command.Position != ReservationCommandV2.Position || replayed.Fact.Position != ReservationFactV2.Position || !replayed.Command.PayloadMemory.Span.SequenceEqual(ReservationCommandV2.PayloadMemory.Span) || !replayed.Fact.PayloadMemory.Span.SequenceEqual(ReservationFactV2.PayloadMemory.Span) || replayed.Reservation.ParticipantId != request.AuthenticatedReservation.Reservation.ParticipantId || replayed.Reservation.ParticipantFactoryKey != request.AuthenticatedReservation.Reservation.ParticipantFactoryKey || !replayed.Reservation.OrderedTopologyNodeKeys.SequenceEqual(request.AuthenticatedReservation.Reservation.OrderedTopologyNodeKeys)) return Quarantine("reservation-history-invalid");
        if (!GraphParticipantReservationCodecsV2.TryDecodeReservationCommand(ReservationCommandV2.PayloadMemory, out var commandOuter) || commandOuter is null || !GraphParticipantReservationCodecsV2.TryDecodeReservationCommandBody(commandOuter.BodyBytes.ToArray(), out var commandBody) || commandBody is null || !GraphParticipantReservationCodecsV2.TryDecodeReservationFact(ReservationFactV2.PayloadMemory, out var factOuter) || factOuter is null || !GraphParticipantReservationCodecsV2.TryDecodeReservationFactBody(factOuter.BodyBytes.ToArray(), out var factBody) || factBody is null) return Quarantine("reservation-history-invalid");
        if (ReservationCommandV2.Position != request.AppliedReservation.CommandPosition || ReservationFactV2.Position != request.AppliedReservation.FactPosition || !ReservationFactV2.PayloadMemory.Span.SequenceEqual(request.AppliedReservation.ExactCanonicalFactBytes.Span) || request.AuthenticatedReservation.Reservation.ParticipantId != request.AppliedReservation.ParticipantId || operation != request.Correlation.OperationId || ReservationCommandV2.Correlation != request.Correlation || ReservationFactV2.Correlation != request.Correlation || commandOuter.Session != ReservationCommandV2.Position.Session || factOuter.Session != commandOuter.Session || commandOuter.ExpectedAuthority != factOuter.ExpectedAuthority || commandBody.OperationId != operation || factBody.OperationId != operation || factBody.CommandPosition != ReservationCommandV2.Position || factBody.Outcome != 1 || factBody.Reservation is null || factBody.Reservation.ParticipantId != request.AuthenticatedReservation.Reservation.ParticipantId || factBody.Reservation.ParticipantFactoryKey != request.AuthenticatedReservation.Reservation.ParticipantFactoryKey || !factBody.Reservation.OrderedTopologyNodeKeys.SequenceEqual(request.AuthenticatedReservation.Reservation.OrderedTopologyNodeKeys) || factBody.RuntimeGeneration != commandBody.RuntimeGeneration || factBody.GraphGeneration != commandBody.GraphGeneration || factBody.ParticipantPlanFingerprint != commandBody.ParticipantPlanFingerprint || factBody.AllocationCarrierFingerprint != commandBody.AllocationCarrierFingerprint || request.BindingEvidence.PreGrantPlan.GraphGeneration != commandBody.GraphGeneration || request.BindingEvidence.PreGrantPlan.ParticipantPlanFingerprint != commandBody.ParticipantPlanFingerprint || request.BindingEvidence.PreGrantPlan.AllocationFingerprint != commandBody.AllocationCarrierFingerprint || request.BindingEvidence.PreGrantPlan.FactoryKey != commandBody.ParticipantFactoryKey || !request.BindingEvidence.PreGrantPlan.OrderedNodeKeys.SequenceEqual(commandBody.OrderedTopologyNodeKeys)) return Quarantine("reservation-history-invalid");
        return null;
    }
    private async ValueTask<(GraphParticipantBindingFoldV2? Fold, long Through, GraphParticipantBindingResultV2? Result)> ReadS1Async(GraphParticipantBindingRequestV2 request, CancellationToken token)
    { var fold = GraphParticipantBindingFoldV2.Create(request.AuthenticatedReservation.Command.Position.Session); long cursor = 0; long? through = null; ulong count = 0, total = 0; ulong pageCalls = 0; while ((through is null || cursor < through) && pageCalls < request.MaximumSessionRecords) { pageCalls++; ReadAuthorityRangeResultV1 read; try { read = await _s1Journal.ReadAsync(new(request.AuthenticatedReservation.Command.Position.Session, cursor, through ?? long.MaxValue, 256, 1_048_576), token).ConfigureAwait(false); } catch (OperationCanceledException) when (token.IsCancellationRequested) { throw; } catch { return (null, 0, new GraphParticipantBindingResultV2.StoreUnavailable(new("authority-store-unavailable"))); } if (read is not ReadAuthorityRangeResultV1.Batch batch || batch.AfterExclusive != cursor || through is not null && batch.SnapshotThrough != through) return (null, 0, new GraphParticipantBindingResultV2.StoreUnavailable(new("authority-store-unavailable"))); through ??= batch.SnapshotThrough; foreach (var envelope in batch.Facts) { count++; total += (ulong)AuthorityCanonicalCborV1.GetEnvelopeEncodedLength(envelope); if (count > request.MaximumSessionRecords || total > request.MaximumSessionCanonicalBytes || fold.Apply(envelope) is GraphParticipantBindingFoldApplyResultV2.InvalidHistory) return (null, 0, Quarantine("reservation-history-invalid")); cursor = envelope.Position.Sequence; } if (!batch.HasMore) break; } if (through is null || cursor != through) return (null, 0, new GraphParticipantBindingResultV2.StoreUnavailable(new("authority-store-unavailable"))); if (fold.Complete() is GraphParticipantBindingFoldCompleteResultV2.InvalidHistory) return (null, 0, Quarantine("reservation-history-invalid")); return (fold, through.Value, null); }
    private async ValueTask<(CapacityGrantBindingProofV1? Proof, GraphParticipantBindingResultV2? Result)> AuthenticateS2Async(GraphParticipantBindingRequestV2 request, CancellationToken token)
    { CapacityGrantSnapshotAtResultV1 read; try { read = await CapacityGrantSnapshotReaderV1.ReadAtAsync(_s2Journal, request.BindingEvidence.PreGrantPlan.Request.Authority.Session, request.BindingEvidence.GrantId, request.BindingEvidence.CurrentFact, token).ConfigureAwait(false); } catch (OperationCanceledException) when (token.IsCancellationRequested) { throw; } catch { return (null, new GraphParticipantBindingResultV2.StoreUnavailable(new("authority-store-unavailable"))); } if (read is CapacityGrantSnapshotAtResultV1.OutcomeUnknown unknown && unknown.SafeCode.ToString() is "capacity-history-read-failed" or "capacity-history-snapshot-drift") return (null, new GraphParticipantBindingResultV2.StoreUnavailable(new("authority-store-unavailable"))); if (read is not CapacityGrantSnapshotAtResultV1.Exact exact) return (null, Quarantine("capacity-history-invalid")); if (exact.Grant.GrantId != request.BindingEvidence.GrantId || exact.Grant.GrantedAt != request.BindingEvidence.GrantedAt || exact.Grant.CurrentFact != request.BindingEvidence.CurrentFact || exact.Grant.ExpiresAt != request.BindingEvidence.ExpiresAt || exact.Grant.ExpiresAt is CapacityGrantExpiryV1.At expiresAt && expiresAt.Value.CompareTo(request.BindingObservedAt) != ClockComparison.Later || !GraphParticipantCapacityPlanCompilerV2.GrantMatches(request.BindingEvidence.PreGrantPlan, exact.Grant, request.BindingEvidence.PreGrantPlan.Request.Authority.Session, request.BindingEvidence.CurrentFact, out var projection, out var coverage) || !projection.SequenceEqual(request.BindingEvidence.CanonicalProjection) || coverage != request.BindingEvidence.CoverageHashV2) return (null, Quarantine("capacity-history-invalid")); var RequiredChargeCount = checked((ushort)request.BindingEvidence.PreGrantPlan.Request.Charges.Count); return (new(request.BindingEvidence.GrantId, request.BindingEvidence.GrantedAt, request.BindingEvidence.CurrentFact, RequiredChargeCount, coverage), null); }
    private async ValueTask<GraphParticipantBindingResultV2?> AuthenticateAllocatorAsync(GraphParticipantBindingRequestV2 request, CancellationToken token)
    {
        GlobalParticipantAllocatorDurableSnapshotResultV1 read;
        try { read = await _allocatorSnapshots.ReadAsync(new(_allocatorLease), token).ConfigureAwait(false); }
        catch (OperationCanceledException) when (token.IsCancellationRequested) { throw; }
        catch { return new GraphParticipantBindingResultV2.StoreUnavailable(new("authority-store-unavailable")); }
        if (read is GlobalParticipantAllocatorDurableSnapshotResultV1.RealmFenced fenced) return new GraphParticipantBindingResultV2.RealmFenced(fenced.CurrentFenceEpoch);
        if (read is not GlobalParticipantAllocatorDurableSnapshotResultV1.Current current) return Quarantine("allocator-snapshot-invalid");
        var snapshot = current.Snapshot;
        if (snapshot.JournalId != _allocatorLease.Manifest.JournalId || snapshot.RecordCount != (ulong)snapshot.ExactCanonicalRecords.Count) return Quarantine("allocator-snapshot-invalid");
        var fold = new GlobalParticipantAllocatorFoldAccumulatorV1(snapshot.JournalId);
        foreach (var exactRecord in snapshot.ExactCanonicalRecords)
            if (fold.Apply(exactRecord) is GlobalParticipantAllocatorFoldApplyResultV1.InvalidHistory) return Quarantine("allocator-snapshot-invalid");
        if (fold.Complete() is not GlobalParticipantAllocatorFoldResultV1.Current completed || completed.Snapshot.Head != snapshot.Head || completed.Snapshot.RecordCount != snapshot.RecordCount || completed.Snapshot.TotalCanonicalRecordBytes != snapshot.TotalCanonicalRecordBytes) return Quarantine("allocator-snapshot-invalid");
        if (!GraphParticipantReservationCodecsV2.TryDecodeReservationCommand(request.AuthenticatedReservation.Command.PayloadMemory, out var outer) || outer is null || !GraphParticipantReservationCodecsV2.TryDecodeReservationCommandBody(outer.BodyBytes.ToArray(), out var body) || body is null) return Quarantine("allocator-snapshot-invalid");
        var source = new GlobalParticipantAllocationSourceV1(outer.Session.LiveSessionId, request.AuthenticatedReservation.Command.Position, request.AuthenticatedReservation.Command.PayloadHash, Hash256.Compute(outer.BodyBytes));
        var SourceCommandPosition = source.SourceFactPosition; var SourcePayloadHash = source.SourceOuterIntegrityHash; var SourceBodyFingerprint = source.SourceBodyHash;
        var sourceFingerprint = GlobalParticipantAllocatorFactIdsV1.SourceFingerprint(source);
        var proof = completed.Snapshot.Query(request.AppliedReservation.ParticipantId);
        var owner = proof.Owner;
        if (SourceCommandPosition != request.AuthenticatedReservation.Command.Position || SourcePayloadHash != request.AuthenticatedReservation.Command.PayloadHash || SourceBodyFingerprint != Hash256.Compute(outer.BodyBytes) || proof.State != 2 || owner is null || owner.ParticipantId != request.AppliedReservation.ParticipantId || owner.LiveSessionId != outer.Session.LiveSessionId || owner.OperationId != body.OperationId || owner.SourceFingerprint != sourceFingerprint || owner.ClaimHead.Position.JournalId != snapshot.JournalId || snapshot.Head is not { } head || owner.ClaimHead.Position.Sequence > head.Position.Sequence) return Quarantine("allocator-snapshot-invalid");
        return null;
    }
    private ProposedAuthorityFactV1 BuildCommandProposal(GraphParticipantBindingRequestV2 request, CapacityGrantBindingProofV1 proof) { if (!GraphParticipantReservationCodecsV2.TryDecodeReservationCommand(request.AuthenticatedReservation.Command.PayloadMemory, out var reservationOuter) || reservationOuter is null) throw new InvalidOperationException("Authenticated reservation command could not be decoded."); var body = new GraphParticipantBindingCommandBodyV1(request.BindingEvidence.PreGrantPlan.OperationId, request.AuthenticatedReservation.Fact.Position, null, request.BindingEvidence.PreGrantPlan.GraphGeneration, request.AuthenticatedReservation.Command.Position.Session.RuntimeGenerationId, request.BindingEvidence.PreGrantPlan.ParticipantPlanFingerprint, request.BindingEvidence.TopologyFingerprint, request.BindingEvidence.ExecutableFingerprint, proof, request.BindingObservedAt); var bb = GraphParticipantBindingCodecsV1.Encode(body); var outer = new GraphParticipantBindingCommandV1(request.AuthenticatedReservation.Command.Position.Session, reservationOuter.ExpectedAuthority, bb); var payload = GraphParticipantBindingCodecsV1.Encode(outer); var reg = GraphParticipantBindingPayloadRegistrationsV1.BindingCommand; return new(GraphParticipantBindingFactIdsV1.BindingCommand(request.AuthenticatedReservation.Command.Position.Session, body.OperationId), null, OwnerSliceId.S1, reg.Schema, payload, AuthorityPayloadHashV1.Compute(reg.SchemaToken, reg.Schema, payload), request.Correlation, request.ObservedAt); }
    private ProposedAuthorityFactV1 BuildFactProposal(GraphParticipantBindingRequestV2 request, AuthorityFactEnvelopeV1 command, CapacityGrantBindingProofV1 proof, BoundedAscii? rejection) { if (!GraphParticipantReservationCodecsV2.TryDecodeReservationCommand(request.AuthenticatedReservation.Command.PayloadMemory, out var reservationOuter) || reservationOuter is null) throw new InvalidOperationException("Authenticated reservation command could not be decoded."); var binding = rejection is null ? new GraphParticipantBindingV1(request.AppliedReservation.ParticipantId, request.AuthenticatedReservation.Reservation.ParticipantFactoryKey, request.AuthenticatedReservation.Reservation.OrderedTopologyNodeKeys) : null; var body = new GraphParticipantBindingFactBodyV1(request.BindingEvidence.PreGrantPlan.OperationId, command.Position, request.AuthenticatedReservation.Fact.Position, null, rejection is null ? (ushort)1 : (ushort)2, request.BindingEvidence.PreGrantPlan.GraphGeneration, command.Position.Session.RuntimeGenerationId, request.BindingEvidence.PreGrantPlan.ParticipantPlanFingerprint, request.BindingEvidence.TopologyFingerprint, request.BindingEvidence.ExecutableFingerprint, binding, rejection is null ? proof : null, rejection, request.BindingObservedAt); var bb = GraphParticipantBindingCodecsV1.Encode(body); var outer = new GraphParticipantBindingFactV1(command.Position.Session, reservationOuter.ExpectedAuthority, bb); var payload = GraphParticipantBindingCodecsV1.Encode(outer); var reg = GraphParticipantBindingPayloadRegistrationsV1.BindingFact; return new(GraphParticipantBindingFactIdsV1.BindingFact(command.Position), null, OwnerSliceId.S1, reg.Schema, payload, AuthorityPayloadHashV1.Compute(reg.SchemaToken, reg.Schema, payload), request.Correlation, request.ObservedAt); }
    private ValueTask<(GraphParticipantBindingFoldV2? Fold, long Through, GraphParticipantBindingResultV2? Result)> ReconcileAsync(GraphParticipantBindingRequestV2 request, CancellationToken token) => ReadS1Async(request, CancellationToken.None);
    private GraphParticipantBindingResultV2? ToTerminal(GraphParticipantBindingFoldV2 fold, OperationId operation, bool existing) { return fold.Query(operation) switch { GraphParticipantBindingFoldQueryResultV2.Bound x when existing => new GraphParticipantBindingResultV2.AlreadyBound(x.Command.Position, x.Fact.Position, x.Fact.PayloadMemory, x.Binding, x.CapacityGrantProof), GraphParticipantBindingFoldQueryResultV2.Bound x => new GraphParticipantBindingResultV2.Bound(x.Command.Position, x.Fact.Position, x.Fact.PayloadMemory, x.Binding, x.CapacityGrantProof), GraphParticipantBindingFoldQueryResultV2.Rejected x => new GraphParticipantBindingResultV2.Rejected(x.Command.Position, x.Fact.Position, x.SafeCode, x.Fact.PayloadMemory), _ => null }; }
    private static bool EnvelopeMatches(AuthorityFactEnvelopeV1 envelope, ProposedAuthorityFactV1 proposal) => envelope.FactId == proposal.FactId && envelope.PayloadHash == proposal.PayloadHash && envelope.PayloadMemory.Span.SequenceEqual(proposal.PayloadMemory.Span);
    private static GraphParticipantBindingResultV2.Quarantined Quarantine(string code) => new(new BoundedAscii(code));
}
