using System.Security.Cryptography;
using System.Text;

namespace HPD.Base;

internal sealed class DefaultBaseSubjectRetirementRuntime(
    IRecordStoreRegistry stores,
    BaseSubjectContractRegistry contracts,
    IBasePolicyOrchestrator policy,
    BaseOpaqueTokenProtector tokens,
    TimeProvider timeProvider) : IBaseSubjectRetirementRuntime
{
    private const string FixedAcknowledgementGrant="base.subjectRetirement.acknowledge";
    private readonly BaseSubjectRetirementEvidenceCodec _codec=new(tokens,timeProvider);

    public async ValueTask<bool> AuthorizeGenerationAsync(BaseSession session,BaseInstalledSubjectRetirementConsumer installed,CancellationToken cancellationToken)
    {
        if(!AudienceAllows(installed.Definition.Audience,session.Principal))return false;
        BaseGeneratedSubjectRegistration? contract=contracts.Find(installed.Lifecycle.Definition.ContractId,installed.Lifecycle.Definition.ContractVersion);
        if(contract is null)return false;
        OperationContext operation=session.Operation(BaseOperationKind.SubjectRetirementAcknowledge,installed.Definition.ConsumerId);
        var resource=new CollectionDefinition{Id=installed.Definition.ConsumerId,Name=installed.Definition.ConsumerId,Kind=BaseCollectionKinds.Custom,SchemaMode=SchemaMode.Strict,UnknownFields=UnknownFieldPolicy.Reject,System=true,SystemOwnerModuleId=installed.Definition.OwningModuleId};
        OperationResult<BasePolicyEvaluation> authorization=await policy.EvaluateWriteAsync(new(){Principal=session.Principal,Operation=operation,Collection=resource,ResourceKind=PolicyResourceKind.SubjectLifecycle},cancellationToken).ConfigureAwait(false);
        if(!BaseSystemCollectionGate.HasExactSubjectLifecycleGrant(authorization,installed.Definition.AcknowledgementGrantId,installed.Definition.OwningModuleId,installed.Definition.ConsumerId,contract.Definition.Id,contract.Definition.Version,session.Principal,operation))return false;
        OperationContext fixedOperation=session.Operation(BaseOperationKind.SubjectRetirementAcknowledge,FixedAcknowledgementGrant);
        OperationResult<BasePolicyEvaluation> fixedAuthorization=await policy.EvaluateWriteAsync(new(){Principal=session.Principal,Operation=fixedOperation,Collection=resource,ResourceKind=PolicyResourceKind.SubjectLifecycle},cancellationToken).ConfigureAwait(false);
        return BaseSystemCollectionGate.HasExactSubjectLifecycleGrant(fixedAuthorization,FixedAcknowledgementGrant,installed.Definition.OwningModuleId,FixedAcknowledgementGrant,contract.Definition.Id,contract.Definition.Version,session.Principal,fixedOperation);
    }

    public ValueTask<BaseResult<BaseSubjectAdvisoryLifecycleDelivery<TSubject>>> IssueAdvisoryAsync<TSubject>(BaseSession session,BaseInstalledSubjectRetirementConsumer installed,BaseSubjectLifecycleDelivery<TSubject> delivery,CancellationToken cancellationToken)
    {
        if(installed.Definition.Participation!=BaseSubjectRetirementParticipation.AdvisoryAcknowledgement)return ValueTask.FromResult<BaseResult<BaseSubjectAdvisoryLifecycleDelivery<TSubject>>>(Failure<BaseSubjectAdvisoryLifecycleDelivery<TSubject>>(OperationStatus.ValidationFailed,BaseSubjectRetirementErrorCodes.ContractInvalid,ErrorCategory.Validation));
        BaseSubjectLifecycleFact fact=delivery.Fact.Fact;BaseOwnedSubjectScopeEvidence scope=Scope(session,installed);
        DateTimeOffset issued=timeProvider.GetUtcNow();DateTimeOffset expires=issued+TimeSpan.FromDays(30);
        var payload=Payload(installed,fact,null,issued,expires);byte[] token=_codec.Protect(payload,BaseSubjectRetirementEvidenceCodec.Binding(session.ApplicationId,installed,scope));BaseMutationRequestIdentity identity=Identity(installed,token);
        return ValueTask.FromResult<BaseResult<BaseSubjectAdvisoryLifecycleDelivery<TSubject>>>(new BaseSuccess<BaseSubjectAdvisoryLifecycleDelivery<TSubject>>(new(){Lifecycle=delivery,Acknowledgement=new(token),AcknowledgementIdentity=identity},OperationStatus.Ok,null,null,null,null));
    }

    public async ValueTask<BaseResult<BaseSubjectRequiredLifecycleDelivery<TSubject>>> IssueRequiredAsync<TSubject>(BaseSession session,BaseInstalledSubjectRetirementConsumer installed,BaseSubjectLifecycleDelivery<TSubject> delivery,CancellationToken cancellationToken)
    {
        if(installed.Definition.Participation!=BaseSubjectRetirementParticipation.RequiredBeforePurge)return Failure<BaseSubjectRequiredLifecycleDelivery<TSubject>>(OperationStatus.ValidationFailed,BaseSubjectRetirementErrorCodes.ContractInvalid,ErrorCategory.Validation);
        BaseSubjectLifecycleFact fact=delivery.Fact.Fact;if(fact.Transitioned?.CurrentState!=BaseSubjectLifecycleState.Tombstoned)return Failure<BaseSubjectRequiredLifecycleDelivery<TSubject>>(OperationStatus.ValidationFailed,BaseSubjectRetirementErrorCodes.ContractInvalid,ErrorCategory.Validation);
        BaseGeneratedSubjectRegistration? contract=contracts.Find(fact.ContractId,fact.ContractVersion);if(contract is null||stores.GetStoreForCollection(contract.Definition.ValidationPlan.PrivateCollectionId) is not IBaseSubjectRetirementStore store)return Failure<BaseSubjectRequiredLifecycleDelivery<TSubject>>(OperationStatus.CapabilityUnavailable,BaseSubjectRetirementErrorCodes.ProviderContractInvalid,ErrorCategory.Capability);
        BaseOwnedSubjectScopeEvidence scope=Scope(session,installed);OperationResult<BaseSubjectRetirementInspection> read=await store.InspectAsync(new(){ContractId=fact.ContractId,ContractVersion=fact.ContractVersion,SubjectId=fact.SubjectId,AuthorityEpoch=fact.AuthorityEpoch,Incarnation=fact.Incarnation,ScopeAuthority=new(){Mode=BaseSubjectScopeQueryMode.ExactScope,ExactScope=scope,InstalledAuthorityDigest=contract.Checksum},IncludeTerminalSummary=false,MaximumResultBytes=installed.Definition.Limits.MaximumReceiptBytes,DeadlineUtc=timeProvider.GetUtcNow()+installed.Definition.Limits.AcknowledgementTimeout},cancellationToken).ConfigureAwait(false);
        if(!read.IsSuccess()||read.Value?.CurrentBarrier is not { } barrier)return Failure<BaseSubjectRequiredLifecycleDelivery<TSubject>>(read.Status,read.Error?.Code??BaseSubjectRetirementErrorCodes.ProviderContractInvalid,read.Error?.Category??ErrorCategory.Store);
        if(barrier.TombstoneSequence!=fact.SubjectSequence)return Failure<BaseSubjectRequiredLifecycleDelivery<TSubject>>(OperationStatus.Conflict,"base.subjectRetirement.barrierConflict",ErrorCategory.Conflict);
        DateTimeOffset issued=timeProvider.GetUtcNow();DateTimeOffset expires=barrier.DeadlineUtc<issued.AddDays(30)?barrier.DeadlineUtc:issued.AddDays(30);var expectation=new BaseSubjectRequiredBarrierExpectation{Generation=barrier.Generation,Checksum=barrier.BarrierChecksum};
        var payload=Payload(installed,fact,expectation,issued,expires);byte[] token=_codec.Protect(payload,BaseSubjectRetirementEvidenceCodec.Binding(session.ApplicationId,installed,scope));BaseMutationRequestIdentity identity=Identity(installed,token);
        return new BaseSuccess<BaseSubjectRequiredLifecycleDelivery<TSubject>>(new(){Lifecycle=delivery,Acknowledgement=new(token),AcknowledgementIdentity=identity},OperationStatus.Ok,null,null,null,null);
    }

    public async ValueTask<BaseResult<BaseSubjectAcknowledgementResult>> AcknowledgeAsync(BaseSession session,BaseInstalledSubjectRetirementConsumer installed,ReadOnlyMemory<byte> evidence,BaseSubjectRetirementParticipation participation,BaseSubjectAcknowledgementDisposition disposition,BaseMutationRequestIdentity identity,CancellationToken cancellationToken)
    {
        if(installed.Definition.Participation!=participation||!Enum.IsDefined(disposition)||!AudienceAllows(installed.Definition.Audience,session.Principal))return Failure<BaseSubjectAcknowledgementResult>(OperationStatus.PolicyDenied,BaseSubjectRetirementErrorCodes.Unauthorized,ErrorCategory.Authorization);
        BaseGeneratedSubjectRegistration? contract=contracts.Find(installed.Lifecycle.Definition.ContractId,installed.Lifecycle.Definition.ContractVersion);if(contract is null)return Failure<BaseSubjectAcknowledgementResult>(OperationStatus.CapabilityUnavailable,BaseSubjectRetirementErrorCodes.ProviderContractInvalid,ErrorCategory.Capability);
        BaseOwnedSubjectScopeEvidence scope=Scope(session,installed);byte[] binding=BaseSubjectRetirementEvidenceCodec.Binding(session.ApplicationId,installed,scope);
        if(!_codec.TryRead(evidence.Span,participation,binding,contract.Definition.SubjectIdKind,out BaseSubjectRetirementEvidencePayload? payload)||payload is null||payload.ConsumerId!=installed.Definition.ConsumerId||payload.ConsumerVersion!=installed.Definition.ConsumerVersion||payload.ConsumerChecksum!=installed.Checksum||!IdentityMatches(identity,installed,evidence.Span))return Failure<BaseSubjectAcknowledgementResult>(OperationStatus.ValidationFailed,BaseSubjectRetirementErrorCodes.ContractInvalid,ErrorCategory.Validation);
        OperationContext operation=session.Operation(BaseOperationKind.SubjectRetirementAcknowledge,installed.Definition.ConsumerId);var resource=new CollectionDefinition{Id=installed.Definition.ConsumerId,Name=installed.Definition.ConsumerId,Kind=BaseCollectionKinds.Custom,SchemaMode=SchemaMode.Strict,UnknownFields=UnknownFieldPolicy.Reject,System=true,SystemOwnerModuleId=installed.Definition.OwningModuleId};
        OperationResult<BasePolicyEvaluation> authorization=await policy.EvaluateWriteAsync(new(){Principal=session.Principal,Operation=operation,Collection=resource,ResourceKind=PolicyResourceKind.SubjectLifecycle},cancellationToken).ConfigureAwait(false);
        if(!BaseSystemCollectionGate.HasExactSubjectLifecycleGrant(authorization,installed.Definition.AcknowledgementGrantId,installed.Definition.OwningModuleId,installed.Definition.ConsumerId,payload.ContractId,payload.ContractVersion,session.Principal,operation))return Failure<BaseSubjectAcknowledgementResult>(OperationStatus.PolicyDenied,BaseSubjectRetirementErrorCodes.Unauthorized,ErrorCategory.Authorization);
        OperationContext fixedOperation=session.Operation(BaseOperationKind.SubjectRetirementAcknowledge,FixedAcknowledgementGrant);OperationResult<BasePolicyEvaluation> fixedAuthorization=await policy.EvaluateWriteAsync(new(){Principal=session.Principal,Operation=fixedOperation,Collection=resource,ResourceKind=PolicyResourceKind.SubjectLifecycle},cancellationToken).ConfigureAwait(false);
        if(!BaseSystemCollectionGate.HasExactSubjectLifecycleGrant(fixedAuthorization,FixedAcknowledgementGrant,installed.Definition.OwningModuleId,FixedAcknowledgementGrant,payload.ContractId,payload.ContractVersion,session.Principal,fixedOperation))return Failure<BaseSubjectAcknowledgementResult>(OperationStatus.PolicyDenied,BaseSubjectRetirementErrorCodes.Unauthorized,ErrorCategory.Authorization);
        if(stores.GetStoreForCollection(contract.Definition.ValidationPlan.PrivateCollectionId) is not IBaseSubjectRetirementStore store)return Failure<BaseSubjectAcknowledgementResult>(OperationStatus.CapabilityUnavailable,BaseSubjectRetirementErrorCodes.ProviderContractInvalid,ErrorCategory.Capability);
        BaseInstalledSubjectRetirementPolicy? retirementPolicy=(session.Services.GetService(typeof(BaseSubjectRetirementRegistry)) as BaseSubjectRetirementRegistry)?.FindPolicy(payload.ContractId,payload.ContractVersion);
        var acknowledgement=new BaseSubjectLifecycleAcknowledgement{ConsumerId=payload.ConsumerId,ConsumerVersion=payload.ConsumerVersion,ConsumerChecksum=installed.Lifecycle.Checksum,ContractId=payload.ContractId,ContractVersion=payload.ContractVersion,SubjectId=payload.SubjectId,AuthorityEpoch=payload.AuthorityEpoch,Incarnation=payload.Incarnation,ThroughSubjectSequence=payload.ThroughSequence,Disposition=disposition,Participation=participation,RequiredBarrier=payload.Barrier,Identity=identity};
        var processor=new BaseSubjectRetirementAcknowledgementProcessor(new(){Acknowledgement=acknowledgement,Scope=scope,RetirementConsumerChecksum=installed.Checksum,RetirementPolicyChecksum=retirementPolicy?.Definition.PolicyChecksum??new string('0',64),ObservedAtUtc=timeProvider.GetUtcNow(),DeadlineUtc=timeProvider.GetUtcNow()+installed.Definition.Limits.AcknowledgementTimeout});
        RecordMutationExecutionResult execution=await store.ExecuteAsync(processor,new(){AcquisitionTimeout=installed.Definition.Limits.AcknowledgementTimeout,TransactionTimeout=installed.Definition.Limits.AcknowledgementTimeout,CommitCompletionTimeout=installed.Definition.Limits.AcknowledgementTimeout,AtomicRequest=new(){Identity=identity,StructuralDigest=SHA256.HashData(evidence.Span),ExpiresAt=timeProvider.GetUtcNow().AddDays(30),MaxReceiptBytes=installed.Definition.Limits.MaximumReceiptBytes}},cancellationToken).ConfigureAwait(false);
        if(execution.Outcome==RecordMutationExecutionOutcome.Committed&&processor.Result is not null)return new BaseSuccess<BaseSubjectAcknowledgementResult>(processor.Result,processor.Result.Outcome==BaseSubjectRetirementMutationOutcome.Duplicate?OperationStatus.Ok:OperationStatus.Updated,null,null,null,null);
        BaseError? error=execution.Error??execution.Processing?.Error;return Failure<BaseSubjectAcknowledgementResult>(execution.Outcome==RecordMutationExecutionOutcome.Indeterminate?OperationStatus.StoreError:OperationStatus.Conflict,error?.Code??BaseSubjectRetirementErrorCodes.ProviderContractInvalid,error?.Category??ErrorCategory.Store);
    }

    public async ValueTask<BaseResult<BaseSubjectRetirementPage>> ReadBarriersAsync(BaseSession session,string contractId,int contractVersion,BaseSubjectRetirementBarrierState? state,BaseSubjectRetirementCursor? after,int take,CancellationToken cancellationToken)
    {
        BaseGeneratedSubjectRegistration? contract=contracts.Find(contractId,contractVersion);if(contract is null)return Failure<BaseSubjectRetirementPage>(OperationStatus.NotFound,BaseSubjectRetirementErrorCodes.Unauthorized,ErrorCategory.NotFound);
        OperationContext operation=session.Operation(BaseOperationKind.SubjectRetirementInspect,"base.subjectRetirement.barriers.query");if(!await AuthorizedAsync(session,contract,"base.subjectRetirement.barrier.inspect",operation,false,cancellationToken).ConfigureAwait(false))return Failure<BaseSubjectRetirementPage>(OperationStatus.NotFound,BaseSubjectRetirementErrorCodes.Unauthorized,ErrorCategory.NotFound);bool allScopes=session.Principal.SubjectKind is AccessSubjectKind.Admin or AccessSubjectKind.System;if(allScopes&&!await AuthorizedAsync(session,contract,"base.subjectRetirement.scope.all",session.Operation(BaseOperationKind.SubjectRetirementInspect,"base.subjectRetirement.scope.all"),false,cancellationToken).ConfigureAwait(false))return Failure<BaseSubjectRetirementPage>(OperationStatus.NotFound,BaseSubjectRetirementErrorCodes.Unauthorized,ErrorCategory.NotFound);
        if(take is <1 or >256)return Failure<BaseSubjectRetirementPage>(OperationStatus.ValidationFailed,BaseSubjectRetirementErrorCodes.ContractInvalid,ErrorCategory.Validation);
        IRecordStore raw=stores.GetStoreForCollection(contract.Definition.ValidationPlan.PrivateCollectionId)??throw new InvalidOperationException(BaseSubjectRetirementErrorCodes.ProviderContractInvalid);if(raw is not IBaseSubjectRetirementStore store||raw is not IBaseSubjectLifecycleStore lifecycleStore)return Failure<BaseSubjectRetirementPage>(OperationStatus.CapabilityUnavailable,BaseSubjectRetirementErrorCodes.ProviderContractInvalid,ErrorCategory.Capability);
        BaseOwnedSubjectScopeEvidence? scope=allScopes?null:Scope(session,contract,operation);BaseSubjectLifecycleInspectionAuthority? installedInspection=allScopes?(session.Services.GetService(typeof(BaseSubjectLifecycleInspectionAuthorityRegistry)) as BaseSubjectLifecycleInspectionAuthorityRegistry)?.Find(contractId,contractVersion):null;if(allScopes&&installedInspection is null)return Failure<BaseSubjectRetirementPage>(OperationStatus.CapabilityUnavailable,BaseSubjectRetirementErrorCodes.ProviderContractInvalid,ErrorCategory.Capability);string authorityDigest=installedInspection?.Digest??contract.Checksum;var scopeAuthority=new BaseSubjectScopeQueryAuthority{Mode=allScopes?BaseSubjectScopeQueryMode.AllAuthorizedScopes:BaseSubjectScopeQueryMode.ExactScope,ExactScope=scope,InstalledAuthorityDigest=authorityDigest};OperationResult<BaseSubjectLifecycleProviderInspection> authority=await lifecycleStore.InspectAsync(new(){ContractId=contractId,ContractVersion=contractVersion,ConsumerId=null,ScopeAuthority=scopeAuthority,SubjectId=null,IncludeTerminalReceipt=false,MaximumResultBytes=4096,DeadlineUtc=timeProvider.GetUtcNow().AddSeconds(5)},cancellationToken).ConfigureAwait(false);if(!authority.IsSuccess()||authority.Value is null)return Failure<BaseSubjectRetirementPage>(authority.Status,authority.Error?.Code??BaseSubjectRetirementErrorCodes.ProviderContractInvalid,authority.Error?.Category??ErrorCategory.Store);
        byte[] binding=CursorBinding(session.ApplicationId,contract,state,scope,authority.Value.StoreInstanceId,authority.Value.RestoreEpoch);BaseSubjectRetirementBarrierKey? providerAfter=null;
        if(after is not null&&!TryReadCursor(after,binding,contract.Definition.SubjectIdKind,out providerAfter))return Failure<BaseSubjectRetirementPage>(OperationStatus.ValidationFailed,BaseSubjectRetirementErrorCodes.CursorInvalid,ErrorCategory.Validation);
        OperationResult<BaseSubjectRetirementBarrierPage> result=await store.ReadBarriersAsync(new(){ApplicationId=session.ApplicationId,ContractId=contractId,ContractVersion=contractVersion,ScopeAuthority=scopeAuthority,State=state,After=providerAfter,Take=take,MaximumResultBytes=1_048_576,DeadlineUtc=timeProvider.GetUtcNow().AddSeconds(30)},cancellationToken).ConfigureAwait(false);
        if(!result.IsSuccess()||result.Value is null)return Failure<BaseSubjectRetirementPage>(result.Status,result.Error?.Code??BaseSubjectRetirementErrorCodes.ProviderContractInvalid,result.Error?.Category??ErrorCategory.Store);
        BaseSubjectRetirementCursor? next=result.Value.Next is null?null:ProtectCursor(result.Value.Next,binding);
        return new BaseSuccess<BaseSubjectRetirementPage>(new(){Barriers=[..result.Value.Barriers.Select(static row=>row.Barrier)],Next=next,CapturedBarrierGeneration=result.Value.CapturedBarrierGeneration},OperationStatus.Ok,null,null,null,null);
    }

    private BaseSubjectRetirementCursor ProtectCursor(BaseSubjectRetirementBarrierKey key,ReadOnlySpan<byte> binding)
    {
        using var stream=new MemoryStream();using var writer=new BinaryWriter(stream,Encoding.UTF8,true);writer.Write((byte)key.ScopeKind);writer.Write(key.ScopeIndexDigest);Write(writer,key.ContractId);writer.Write(key.ContractVersion);Write(writer,key.SubjectId.Value);writer.Write(key.AuthorityEpoch.ToArray());writer.Write(key.Incarnation.ToArray());writer.Flush();
        return new(Encoding.ASCII.GetBytes(tokens.Protect("hpd.base.subject-retirement.cursor.v1",1,stream.ToArray(),binding)));
    }
    private bool TryReadCursor(BaseSubjectRetirementCursor cursor,ReadOnlySpan<byte> binding,BaseSubjectIdKind idKind,out BaseSubjectRetirementBarrierKey? key)
    {
        key=null;BaseOpaqueTokenResult value=tokens.Unprotect("hpd.base.subject-retirement.cursor.v1",1,Encoding.ASCII.GetString(cursor.ToArray()),65,2048,binding);if(value.Status!=BaseOpaqueTokenStatus.Valid||value.Plaintext is null)return false;
        try{using var stream=new MemoryStream(value.Plaintext,false);using var reader=new BinaryReader(stream,Encoding.UTF8,true);var kind=(BaseSubjectScopeKind)reader.ReadByte();byte[] digest=reader.ReadBytes(32);string contractId=Read(reader);int version=reader.ReadInt32();BaseSubjectId subjectId=BaseSubjectId.Create(Read(reader),idKind);var epoch=new BaseSubjectAuthorityEpoch(reader.ReadBytes(16));var incarnation=new BaseSubjectIncarnation(reader.ReadBytes(24));if(stream.Position!=stream.Length||digest.Length!=32||!Enum.IsDefined(kind))return false;key=new(){ScopeKind=kind,ScopeIndexDigest=digest,ContractId=contractId,ContractVersion=version,SubjectId=subjectId,AuthorityEpoch=epoch,Incarnation=incarnation};return true;}catch{return false;}
    }
    private static byte[] CursorBinding(string applicationId,BaseGeneratedSubjectRegistration contract,BaseSubjectRetirementBarrierState? state,BaseOwnedSubjectScopeEvidence? scope,string storeInstanceId,long restoreEpoch)=>SHA256.HashData(Encoding.UTF8.GetBytes($"base.subjectRetirement.cursor.binding.v1\0{applicationId}\0{contract.Definition.Id}\0{contract.Definition.Version}\0{contract.Checksum}\0{(scope is null?-1:(int)scope.Kind)}\0{scope?.Value}\0{(state is null?-1:(int)state.Value)}\0{storeInstanceId}\0{restoreEpoch}"));
    private static void Write(BinaryWriter writer,string value){byte[] bytes=Encoding.UTF8.GetBytes(value);writer.Write(bytes.Length);writer.Write(bytes);}
    private static string Read(BinaryReader reader){int length=reader.ReadInt32();if(length is <1 or >512)throw new FormatException();byte[] bytes=reader.ReadBytes(length);if(bytes.Length!=length)throw new EndOfStreamException();return Encoding.UTF8.GetString(bytes);}

    public async ValueTask<BaseResult<BaseSubjectRetirementInspection>> InspectAsync(BaseSession session,BaseSubjectRetirementInspectionRequest request,CancellationToken cancellationToken)
    {
        BaseGeneratedSubjectRegistration? contract=contracts.Find(request.ContractId,request.ContractVersion);if(contract is null)return Failure<BaseSubjectRetirementInspection>(OperationStatus.NotFound,BaseSubjectRetirementErrorCodes.Unauthorized,ErrorCategory.NotFound);OperationContext operation=session.Operation(BaseOperationKind.SubjectRetirementInspect,"base.subjectRetirement.barrier.inspect");if(!await AuthorizedAsync(session,contract,"base.subjectRetirement.barrier.inspect",operation,false,cancellationToken).ConfigureAwait(false))return Failure<BaseSubjectRetirementInspection>(OperationStatus.NotFound,BaseSubjectRetirementErrorCodes.Unauthorized,ErrorCategory.NotFound);if(stores.GetStoreForCollection(contract.Definition.ValidationPlan.PrivateCollectionId) is not IBaseSubjectRetirementStore store)return Failure<BaseSubjectRetirementInspection>(OperationStatus.CapabilityUnavailable,BaseSubjectRetirementErrorCodes.ProviderContractInvalid,ErrorCategory.Capability);BaseOwnedSubjectScopeEvidence scope=Scope(session,contract,operation);OperationResult<BaseSubjectRetirementInspection> result=await store.InspectAsync(request with{ScopeAuthority=new(){Mode=BaseSubjectScopeQueryMode.ExactScope,ExactScope=scope,InstalledAuthorityDigest=contract.Checksum}},cancellationToken).ConfigureAwait(false);return Result(result);
    }

    public async ValueTask<BaseResult<BaseSubjectRetirementTimeoutResult>> TimeoutAsync(BaseSession session,BaseSubjectRetirementTimeoutRequest request,CancellationToken cancellationToken)
    {
        BaseGeneratedSubjectRegistration? contract=contracts.Find(request.ContractId,request.ContractVersion);BaseSubjectRetirementRegistry? registry=session.Services.GetService(typeof(BaseSubjectRetirementRegistry)) as BaseSubjectRetirementRegistry;BaseInstalledSubjectRetirementPolicy? installed=registry?.FindPolicy(request.ContractId,request.ContractVersion);if(contract is null||installed is null)return Failure<BaseSubjectRetirementTimeoutResult>(OperationStatus.NotFound,BaseSubjectRetirementErrorCodes.Unauthorized,ErrorCategory.NotFound);OperationContext operation=session.Operation(BaseOperationKind.SubjectRetirementTimeout,"base.subjectRetirement.timeout.process");if(!await AuthorizedAsync(session,contract,"base.subjectRetirement.timeout.process",operation,true,cancellationToken).ConfigureAwait(false))return Failure<BaseSubjectRetirementTimeoutResult>(OperationStatus.NotFound,BaseSubjectRetirementErrorCodes.Unauthorized,ErrorCategory.NotFound);if(stores.GetStoreForCollection(contract.Definition.ValidationPlan.PrivateCollectionId) is not IBaseSubjectRetirementStore store)return Failure<BaseSubjectRetirementTimeoutResult>(OperationStatus.CapabilityUnavailable,BaseSubjectRetirementErrorCodes.ProviderContractInvalid,ErrorCategory.Capability);BaseOwnedSubjectScopeEvidence scope=Scope(session,contract,operation);var processor=new BaseSubjectRetirementTimeoutProcessor(new(){Request=request,Scope=scope,RetirementPolicyChecksum=installed.Definition.PolicyChecksum,ObservedAtUtc=timeProvider.GetUtcNow()});RecordMutationExecutionResult execution=await ExecuteAsync(store,processor,request.Identity,Canonical(request),cancellationToken).ConfigureAwait(false);return Execution(execution,processor.Result);
    }

    public async ValueTask<BaseResult<BaseSubjectRetirementOverrideResult>> OverrideAsync(BaseSession session,BaseSubjectRetirementOverrideRequest request,CancellationToken cancellationToken)
    {
        BaseGeneratedSubjectRegistration? contract=contracts.Find(request.ContractId,request.ContractVersion);BaseSubjectRetirementRegistry? registry=session.Services.GetService(typeof(BaseSubjectRetirementRegistry)) as BaseSubjectRetirementRegistry;BaseInstalledSubjectRetirementPolicy? installed=registry?.FindPolicy(request.ContractId,request.ContractVersion);if(contract is null||installed is null)return Failure<BaseSubjectRetirementOverrideResult>(OperationStatus.NotFound,BaseSubjectRetirementErrorCodes.Unauthorized,ErrorCategory.NotFound);OperationContext operation=session.Operation(BaseOperationKind.SubjectRetirementOverride,"base.subjectRetirement.override");if(!await AuthorizedAsync(session,contract,"base.subjectRetirement.override",operation,true,cancellationToken).ConfigureAwait(false))return Failure<BaseSubjectRetirementOverrideResult>(OperationStatus.NotFound,BaseSubjectRetirementErrorCodes.Unauthorized,ErrorCategory.NotFound);if(stores.GetStoreForCollection(contract.Definition.ValidationPlan.PrivateCollectionId) is not IBaseSubjectRetirementStore store)return Failure<BaseSubjectRetirementOverrideResult>(OperationStatus.CapabilityUnavailable,BaseSubjectRetirementErrorCodes.ProviderContractInvalid,ErrorCategory.Capability);BaseOwnedSubjectScopeEvidence scope=Scope(session,contract,operation);var processor=new BaseSubjectRetirementOverrideProcessor(new(){Request=request,Scope=scope,RetirementPolicyChecksum=installed.Definition.PolicyChecksum,ObservedAtUtc=timeProvider.GetUtcNow()});RecordMutationExecutionResult execution=await ExecuteAsync(store,processor,request.Identity,Canonical(request),cancellationToken).ConfigureAwait(false);return Execution(execution,processor.Result);
    }

    public async ValueTask<BaseResult<BaseSubjectFinalPurgeResult>> PurgeAsync(BaseSession session,BaseSubjectFinalPurgeRequest request,CancellationToken cancellationToken)
    {
        BaseGeneratedSubjectRegistration? contract=contracts.Find(request.ContractId,request.ContractVersion);BaseSubjectRetirementRegistry? registry=session.Services.GetService(typeof(BaseSubjectRetirementRegistry)) as BaseSubjectRetirementRegistry;BaseInstalledSubjectRetirementPolicy? installed=registry?.FindPolicy(request.ContractId,request.ContractVersion);if(contract is null||installed is null)return Failure<BaseSubjectFinalPurgeResult>(OperationStatus.NotFound,BaseSubjectRetirementErrorCodes.Unauthorized,ErrorCategory.NotFound);OperationContext operation=session.Operation(BaseOperationKind.SubjectRetirementPurge,"base.subjectRetirement.purge");if(!await AuthorizedAsync(session,contract,"base.subjectRetirement.purge",operation,true,cancellationToken).ConfigureAwait(false))return Failure<BaseSubjectFinalPurgeResult>(OperationStatus.NotFound,BaseSubjectRetirementErrorCodes.Unauthorized,ErrorCategory.NotFound);if(!await AuthorizedSourceAsync(session,contract,operation,cancellationToken).ConfigureAwait(false))return Failure<BaseSubjectFinalPurgeResult>(OperationStatus.NotFound,BaseSubjectRetirementErrorCodes.Unauthorized,ErrorCategory.NotFound);if(stores.GetStoreForCollection(contract.Definition.ValidationPlan.PrivateCollectionId) is not IBaseSubjectRetirementStore store)return Failure<BaseSubjectFinalPurgeResult>(OperationStatus.CapabilityUnavailable,BaseSubjectRetirementErrorCodes.ProviderContractInvalid,ErrorCategory.Capability);BaseOwnedSubjectScopeEvidence scope=Scope(session,contract,operation);var processor=new BaseSubjectRetirementPurgeProcessor(new(){Request=request,Scope=scope,ContractChecksum=contract.Checksum,RetirementPolicyChecksum=installed.Definition.PolicyChecksum,MinimumTombstoneAge=installed.Definition.PurgeRetention.MinimumTombstoneAge,ObservedAtUtc=timeProvider.GetUtcNow(),Operation=operation});RecordMutationExecutionResult execution=await ExecuteAsync(store,processor,request.Identity,Canonical(request),cancellationToken).ConfigureAwait(false);return Execution(execution,processor.Result);
    }

    public async ValueTask<BaseResult<BaseSubjectRetirementConsumerRemovalResult>> RemoveConsumerAsync(BaseSession session,BaseSubjectRetirementConsumerRemovalRequest request,CancellationToken cancellationToken)
    {
        BaseGeneratedSubjectRegistration? contract=contracts.Find(request.ContractId,request.ContractVersion);BaseSubjectRetirementRegistry? registry=session.Services.GetService(typeof(BaseSubjectRetirementRegistry)) as BaseSubjectRetirementRegistry;BaseInstalledSubjectRetirementPolicy? policyDefinition=registry?.FindPolicy(request.ContractId,request.ContractVersion);BaseInstalledSubjectRetirementConsumer? consumer=registry?.FindConsumer(request.ConsumerId,request.ConsumerVersion);
        if(contract is null||policyDefinition is null||consumer is null||consumer.Checksum!=request.ExpectedConsumerChecksum||BaseSubjectRetirementRegistry.AcceptedSetChecksum(policyDefinition.Definition.AcceptedConsumers)!=request.ExpectedAcceptedSetChecksum)return Failure<BaseSubjectRetirementConsumerRemovalResult>(OperationStatus.Conflict,BaseSubjectRetirementErrorCodes.RegistrationConflict,ErrorCategory.Conflict);
        OperationContext operation=session.Operation(BaseOperationKind.SubjectRetirementConsumerRemoval,"base.subjectRetirement.consumerRemoval");if(!await AuthorizedAsync(session,contract,"base.subjectRetirement.consumerRemoval",operation,true,cancellationToken).ConfigureAwait(false))return Failure<BaseSubjectRetirementConsumerRemovalResult>(OperationStatus.NotFound,BaseSubjectRetirementErrorCodes.Unauthorized,ErrorCategory.NotFound);
        IRecordStore raw=stores.GetStoreForCollection(contract.Definition.ValidationPlan.PrivateCollectionId)??throw new InvalidOperationException(BaseSubjectRetirementErrorCodes.ProviderContractInvalid);if(raw is not IBaseSubjectAuthorityMaintenanceStore maintenance||raw is not IBaseSubjectLifecycleStore lifecycleStore)return Failure<BaseSubjectRetirementConsumerRemovalResult>(OperationStatus.CapabilityUnavailable,BaseSubjectRetirementErrorCodes.ProviderContractInvalid,ErrorCategory.Capability);
        BaseSubjectLifecycleInspectionAuthority? inspectionAuthority=(session.Services.GetService(typeof(BaseSubjectLifecycleInspectionAuthorityRegistry)) as BaseSubjectLifecycleInspectionAuthorityRegistry)?.Find(request.ContractId,request.ContractVersion);if(inspectionAuthority is null)return Failure<BaseSubjectRetirementConsumerRemovalResult>(OperationStatus.CapabilityUnavailable,BaseSubjectRetirementErrorCodes.ProviderContractInvalid,ErrorCategory.Capability);
        OperationResult<BaseSubjectLifecycleProviderInspection> inspection=await lifecycleStore.InspectAsync(new(){ContractId=request.ContractId,ContractVersion=request.ContractVersion,ConsumerId=request.ConsumerId,ScopeAuthority=new(){Mode=BaseSubjectScopeQueryMode.AllAuthorizedScopes,ExactScope=null,InstalledAuthorityDigest=inspectionAuthority.Digest},SubjectId=null,IncludeTerminalReceipt=false,MaximumResultBytes=1_048_576,DeadlineUtc=timeProvider.GetUtcNow().AddSeconds(30)},cancellationToken).ConfigureAwait(false);if(!inspection.IsSuccess()||inspection.Value is null)return Failure<BaseSubjectRetirementConsumerRemovalResult>(inspection.Status,inspection.Error?.Code??BaseSubjectRetirementErrorCodes.ProviderContractInvalid,inspection.Error?.Category??ErrorCategory.Store);
        BaseSubjectLifecycleConsumerInspection? projection=inspection.Value.Consumers.SingleOrDefault(value=>value.ConsumerId==request.ConsumerId&&value.ConsumerVersion==request.ConsumerVersion);if(projection is null)return Failure<BaseSubjectRetirementConsumerRemovalResult>(OperationStatus.Conflict,BaseSubjectRetirementErrorCodes.RegistrationConflict,ErrorCategory.Conflict);
        long schemaGeneration=1;if(raw is IBaseSchemaStore schema){BaseLogicalSchema? logicalSchema=session.Services.GetService(typeof(BaseLogicalSchema)) as BaseLogicalSchema;if(logicalSchema is null)return Failure<BaseSubjectRetirementConsumerRemovalResult>(OperationStatus.CapabilityUnavailable,BaseSubjectRetirementErrorCodes.ProviderContractInvalid,ErrorCategory.Capability);OperationResult<BaseSchemaObservedState> observed=await schema.InspectSchemaAsync(new(){ApplicationId=session.ApplicationId,ExpectedLogicalChecksum=logicalSchema.CanonicalChecksum,Visibility=VisibilityLevel.Admin,InspectionTimeout=TimeSpan.FromSeconds(5)},cancellationToken).ConfigureAwait(false);if(!observed.IsSuccess()||observed.Value is null)return Failure<BaseSubjectRetirementConsumerRemovalResult>(observed.Status,BaseSubjectRetirementErrorCodes.ProviderContractInvalid,ErrorCategory.Store);schemaGeneration=observed.Value.Generation;}
        byte[] lifecycleChecksum=SHA256.HashData(Encoding.UTF8.GetBytes($"base.subjectLifecycle.removeConsumer.v1\0{request.ContractId}\0{request.ContractVersion}\0{request.ConsumerId}\0{request.ConsumerVersion}\0{projection.ProjectionGeneration}"));byte[] retirementChecksum=SHA256.HashData(Encoding.UTF8.GetBytes($"base.subjectRetirement.removeConsumer.v1\0{request.ExpectedConsumerChecksum}\0{request.ExpectedAcceptedSetChecksum}\0{request.ExpectedGraphGeneration}"));
        var execution=new BaseSubjectAuthorityMaintenanceExecutionRequest{Lifecycle=new(){Kind=BaseSubjectLifecycleMaintenanceKind.RemoveConsumer,ContractId=request.ContractId,ContractVersion=request.ContractVersion,ConsumerId=request.ConsumerId,ConsumerVersion=request.ConsumerVersion,Scope=null,RetainedFrom=null,ExpectedDeliveryEpoch=inspection.Value.DeliveryEpoch,ExpectedProjectionGeneration=projection.ProjectionGeneration,PlanChecksum=lifecycleChecksum},Retirement=new(){Kind=BaseSubjectRetirementMaintenanceKind.RemoveConsumer,ScopeAuthority=new(){Mode=BaseSubjectScopeQueryMode.AllAuthorizedScopes,ExactScope=null,InstalledAuthorityDigest=policyDefinition.Definition.PolicyChecksum},ExpectedGraphGeneration=request.ExpectedGraphGeneration,ExpectedBarrierControlGeneration=inspection.Value.RetirementControlGeneration,PlanChecksum=retirementChecksum},Identity=request.Identity,CombinedPlanChecksum=new byte[32],ExpectedStoreGeneration=schemaGeneration,ExpectedSchemaGeneration=schemaGeneration,ExpectedRestoreEpoch=inspection.Value.RestoreEpoch,ExpectedScopeProtectionGeneration=inspection.Value.ScopeProtectionGeneration,ExpectedScopeProtectionKeyId=inspection.Value.ScopeProtectionKeyId,ReplacementScopeProtectionKeyId=null,PageSize=256,OperationTimeout=TimeSpan.FromMinutes(30),CommitCompletionTimeout=TimeSpan.FromMinutes(5)};execution=execution with{CombinedPlanChecksum=BaseSubjectAuthorityMaintenanceProcessor.PlanChecksum(execution)};var processor=new BaseSubjectAuthorityMaintenanceProcessor();RecordMutationExecutionResult result=await maintenance.ExecuteMaintenanceAsync(processor,execution,cancellationToken).ConfigureAwait(false);if(result.Outcome!=RecordMutationExecutionOutcome.Committed||processor.LifecycleResult is null)return Failure<BaseSubjectRetirementConsumerRemovalResult>(result.Outcome==RecordMutationExecutionOutcome.Indeterminate?OperationStatus.StoreError:OperationStatus.Conflict,result.Error?.Code??result.Processing?.Error?.Code??BaseSubjectRetirementErrorCodes.ProviderContractInvalid,result.Error?.Category??result.Processing?.Error?.Category??ErrorCategory.Store);
        string published=BaseSubjectRetirementRegistry.AcceptedSetChecksum(policyDefinition.Definition.AcceptedConsumers.Where(value=>value.ConsumerId!=request.ConsumerId||value.ConsumerVersion!=request.ConsumerVersion));return new BaseSuccess<BaseSubjectRetirementConsumerRemovalResult>(new(){Outcome=BaseSubjectRetirementMutationOutcome.Applied,PublishedGraphGeneration=checked(request.ExpectedGraphGeneration+1),AcceptedConsumerSetChecksum=published,ExaminedBarriers=checked((int)(processor.RetirementResult?.ExaminedCount??0)),ResolvedBarriers=checked((int)(processor.RetirementResult?.ChangedCount??0))},OperationStatus.Updated,null,null,null,null);
    }

    private async ValueTask<bool> AuthorizedAsync(BaseSession session,BaseGeneratedSubjectRegistration contract,string grantId,OperationContext operation,bool write,CancellationToken token)
    {
        if(session.Principal.SubjectKind is not(AccessSubjectKind.Admin or AccessSubjectKind.System))return false;var resource=new CollectionDefinition{Id=grantId,Name=grantId,Kind=BaseCollectionKinds.Custom,SchemaMode=SchemaMode.Strict,UnknownFields=UnknownFieldPolicy.Reject,System=true,SystemOwnerModuleId=contract.Definition.OwningModuleId};OperationResult<BasePolicyEvaluation> result=write?await policy.EvaluateWriteAsync(new(){Principal=session.Principal,Operation=operation,Collection=resource,ResourceKind=PolicyResourceKind.SubjectLifecycle},token).ConfigureAwait(false):await policy.EvaluateReadAsync(new(){Principal=session.Principal,Operation=operation,Collection=resource,ResourceKind=PolicyResourceKind.SubjectLifecycle},token).ConfigureAwait(false);return BaseSystemCollectionGate.HasExactSubjectLifecycleGrant(result,grantId,contract.Definition.OwningModuleId,grantId,contract.Definition.Id,contract.Definition.Version,session.Principal,operation);
    }
    private async ValueTask<bool> AuthorizedSourceAsync(BaseSession session,BaseGeneratedSubjectRegistration contract,OperationContext operation,CancellationToken token)
    {
        string sourceGrant=$"{contract.Definition.Id}.retirement.purge.source";var resource=new CollectionDefinition{Id=contract.Definition.ValidationPlan.PrivateCollectionId,Name=contract.Definition.ValidationPlan.PrivateCollectionId,Kind=BaseCollectionKinds.Custom,SchemaMode=SchemaMode.Strict,UnknownFields=UnknownFieldPolicy.Reject,System=true,SystemOwnerModuleId=contract.Definition.OwningModuleId};OperationResult<BasePolicyEvaluation> result=await policy.EvaluateWriteAsync(new(){Principal=session.Principal,Operation=operation with{CollectionId=contract.Definition.ValidationPlan.PrivateCollectionId},Collection=resource,ResourceKind=PolicyResourceKind.Record},token).ConfigureAwait(false);return BaseSystemCollectionGate.HasExactModuleSourceGrant(result,sourceGrant,contract.Definition.OwningModuleId,session.Principal,operation with{CollectionId=contract.Definition.ValidationPlan.PrivateCollectionId},contract.Definition.ValidationPlan.PrivateCollectionId);
    }
    private static BaseOwnedSubjectScopeEvidence Scope(BaseSession session,BaseGeneratedSubjectRegistration contract,OperationContext operation)=>new(){Kind=contract.Definition.Scope,Value=contract.Definition.Scope switch{BaseSubjectScopeKind.Global=>null,BaseSubjectScopeKind.Tenant=>operation.TenantId??session.Principal.CurrentTenantId,BaseSubjectScopeKind.Project=>operation.ProjectId,_=>null}};
    private async ValueTask<RecordMutationExecutionResult> ExecuteAsync(IBaseSubjectRetirementStore store,IAtomicMutationProcessor processor,BaseMutationRequestIdentity identity,byte[] bytes,CancellationToken token)=>await store.ExecuteAsync(processor,new(){AcquisitionTimeout=TimeSpan.FromSeconds(5),TransactionTimeout=TimeSpan.FromSeconds(30),CommitCompletionTimeout=TimeSpan.FromSeconds(30),AtomicRequest=new(){Identity=identity,StructuralDigest=SHA256.HashData(bytes),ExpiresAt=timeProvider.GetUtcNow().AddDays(30),MaxReceiptBytes=1_048_576}},token).ConfigureAwait(false);
    private static byte[] Canonical(BaseSubjectRetirementTimeoutRequest value)=>Encoding.UTF8.GetBytes($"timeout\0{value.ContractId}\0{value.ContractVersion}\0{value.SubjectId.Value}\0{value.AuthorityEpoch.ToBase64Url()}\0{value.Incarnation.ToBase64Url()}\0{value.ExpectedBarrierGeneration}\0{value.ExpectedBarrierChecksum}");
    private static byte[] Canonical(BaseSubjectRetirementOverrideRequest value)=>Encoding.UTF8.GetBytes($"override\0{value.ContractId}\0{value.ContractVersion}\0{value.SubjectId.Value}\0{value.AuthorityEpoch.ToBase64Url()}\0{value.Incarnation.ToBase64Url()}\0{value.ExpectedTombstoneSequence}\0{value.ExpectedBarrierGeneration}\0{value.ExpectedBarrierChecksum}\0{value.Intent}\0{value.ChangeReference}");
    private static byte[] Canonical(BaseSubjectFinalPurgeRequest value)=>Encoding.UTF8.GetBytes($"purge\0{value.ContractId}\0{value.ContractVersion}\0{value.SubjectId.Value}\0{value.AuthorityEpoch.ToBase64Url()}\0{value.Incarnation.ToBase64Url()}\0{value.ExpectedTombstoneSequence}\0{value.ExpectedPrivateRevision.Value}\0{value.ExpectedBarrierGeneration}\0{value.ExpectedBarrierChecksum}");
    private static BaseResult<T> Result<T>(OperationResult<T> result)=>result.IsSuccess()&&result.Value is not null?new BaseSuccess<T>(result.Value,OperationStatus.Ok,null,null,null,null):Failure<T>(result.Status,result.Error?.Code??BaseSubjectRetirementErrorCodes.ProviderContractInvalid,result.Error?.Category??ErrorCategory.Store);
    private static BaseResult<T> Execution<T>(RecordMutationExecutionResult execution,T? value) where T:class=>execution.Outcome==RecordMutationExecutionOutcome.Committed&&value is not null?new BaseSuccess<T>(value,execution.RequestDisposition==BaseMutationRequestDisposition.Duplicate?OperationStatus.Ok:OperationStatus.Updated,null,null,null,null):Failure<T>(execution.Outcome==RecordMutationExecutionOutcome.Indeterminate?OperationStatus.StoreError:OperationStatus.Conflict,execution.Error?.Code??execution.Processing?.Error?.Code??BaseSubjectRetirementErrorCodes.ProviderContractInvalid,execution.Error?.Category??execution.Processing?.Error?.Category??ErrorCategory.Store);

    private static BaseSubjectRetirementEvidencePayload Payload(BaseInstalledSubjectRetirementConsumer installed,BaseSubjectLifecycleFact fact,BaseSubjectRequiredBarrierExpectation? barrier,DateTimeOffset issued,DateTimeOffset expires)=>new(installed.Definition.Participation,installed.Definition.ConsumerId,installed.Definition.ConsumerVersion,installed.Checksum,fact.ContractId,fact.ContractVersion,fact.SubjectId,fact.AuthorityEpoch,fact.Incarnation,fact.SubjectSequence,barrier,issued,expires);
    private static BaseMutationRequestIdentity Identity(BaseInstalledSubjectRetirementConsumer installed,ReadOnlySpan<byte> token){byte[] digest=SHA256.HashData(token);return BaseMutationRequestIdentity.Create($"subject-retirement:{installed.Definition.ConsumerId}","subjectRetirement.acknowledge",Convert.ToHexStringLower(digest),BaseMutationRequestFingerprint.Create(digest));}
    private static bool IdentityMatches(BaseMutationRequestIdentity identity,BaseInstalledSubjectRetirementConsumer installed,ReadOnlySpan<byte> token){BaseMutationRequestIdentity expected=Identity(installed,token);return identity==expected;}
    private static BaseOwnedSubjectScopeEvidence Scope(BaseSession session,BaseInstalledSubjectRetirementConsumer installed){BaseGeneratedSubjectRegistration? contract=(session.Services.GetService(typeof(BaseSubjectContractRegistry)) as BaseSubjectContractRegistry)?.Find(installed.Lifecycle.Definition.ContractId,installed.Lifecycle.Definition.ContractVersion);OperationContext operation=session.Operation(BaseOperationKind.SubjectRetirementAcknowledge,installed.Definition.ConsumerId);return new(){Kind=contract?.Definition.Scope??throw new InvalidOperationException(BaseSubjectRetirementErrorCodes.ContractInvalid),Value=contract.Definition.Scope switch{BaseSubjectScopeKind.Global=>null,BaseSubjectScopeKind.Tenant=>operation.TenantId??session.Principal.CurrentTenantId,BaseSubjectScopeKind.Project=>operation.ProjectId,_=>null}};}
    private static bool AudienceAllows(BaseSubjectLifecycleConsumerAudience audience,PrincipalContext principal)=>principal.SubjectKind==AccessSubjectKind.System||audience==BaseSubjectLifecycleConsumerAudience.Service&&principal.SubjectKind==AccessSubjectKind.ServicePrincipal;
    private static BaseFailure<T> Failure<T>(OperationStatus status,string code,ErrorCategory category)=>new(status,new BaseError{Code=code,Message="The subject retirement operation failed.",Category=category},null,null);
}
