using System.Security.Cryptography;
using System.Text;
using System.Collections.Immutable;
using System.Diagnostics;

namespace HPD.Base;

internal sealed class DefaultBaseSubjectRetirementRuntime(
    IRecordStoreRegistry stores,
    BaseSubjectContractRegistry contracts,
    IBasePolicyOrchestrator policy,
    BaseOpaqueTokenProtector tokens,
    TimeProvider timeProvider,
    BaseSubjectRetirementOperationalState operationalState,
    BaseSubjectRetirementControlDispatcher retirementControls) : IBaseSubjectRetirementRuntime, IAsyncDisposable, IDisposable
{
    private const string FixedAcknowledgementGrant = "base.subjectRetirement.acknowledge";
    private readonly BaseSubjectRetirementEvidenceCodec _codec = new(tokens, timeProvider);
    private readonly BaseSubjectLifecycleTokenCodec _lifecycleCodec = new(tokens, timeProvider);
    private readonly BaseSubjectScopeProtector _scopes = new(tokens);
    private readonly SemaphoreSlim _providerSlots = new(64, 64);
    private static readonly TimeSpan ShutdownDrainTimeout = TimeSpan.FromSeconds(30);

    public async ValueTask<bool> AuthorizeGenerationAsync(BaseSession session, BaseInstalledSubjectRetirementConsumer installed, CancellationToken cancellationToken)
        => (await AuthorizeAcknowledgementAsync(session, installed, cancellationToken).ConfigureAwait(false)) is not null;

    private async ValueTask<byte[]?> AuthorizeAcknowledgementAsync(BaseSession session, BaseInstalledSubjectRetirementConsumer installed, CancellationToken cancellationToken)
    {
        if (!AudienceAllows(installed.Definition.Audience, session.Principal)) return null;
        BaseGeneratedSubjectRegistration? contract = contracts.Find(installed.Lifecycle.Definition.ContractId, installed.Lifecycle.Definition.ContractVersion);
        if (contract is null) return null;
        OperationContext operation = session.Operation(BaseOperationKind.SubjectRetirementAcknowledge, installed.Definition.ConsumerId);
        BaseOwnedSubjectScopeEvidence scope = Scope(session, installed); if (scope.Kind != BaseSubjectScopeKind.Global && string.IsNullOrEmpty(scope.Value)) return null;
        var resource = new CollectionDefinition { Id = installed.Definition.ConsumerId, Name = installed.Definition.ConsumerId, Kind = BaseCollectionKinds.Custom, SchemaMode = SchemaMode.Strict, UnknownFields = UnknownFieldPolicy.Reject, System = true, SystemOwnerModuleId = installed.Definition.OwningModuleId };
        OperationResult<BasePolicyEvaluation> authorization = await policy.EvaluateWriteAsync(new() { Principal = session.Principal, Operation = operation, Collection = resource, ResourceKind = PolicyResourceKind.SubjectLifecycle }, cancellationToken).ConfigureAwait(false);
        if (!BaseSystemCollectionGate.HasExactSubjectLifecycleGrant(authorization, installed.Definition.AcknowledgementGrantId, installed.Definition.OwningModuleId, installed.Definition.ConsumerId, contract.Definition.Id, contract.Definition.Version, session.Principal, operation) || authorization.Value?.Authority is null) return null;
        OperationContext fixedOperation = session.Operation(BaseOperationKind.SubjectRetirementAcknowledge, FixedAcknowledgementGrant);
        OperationResult<BasePolicyEvaluation> fixedAuthorization = await policy.EvaluateWriteAsync(new() { Principal = session.Principal, Operation = fixedOperation, Collection = resource, ResourceKind = PolicyResourceKind.SubjectLifecycle }, cancellationToken).ConfigureAwait(false);
        if (!BaseSystemCollectionGate.HasExactSubjectLifecycleGrant(fixedAuthorization, FixedAcknowledgementGrant, installed.Definition.OwningModuleId, FixedAcknowledgementGrant, contract.Definition.Id, contract.Definition.Version, session.Principal, fixedOperation) || fixedAuthorization.Value?.Authority is null) return null;
        byte[] first = authorization.Value.Authority.Checksum.ToArray(); byte[] second = fixedAuthorization.Value.Authority.Checksum.ToArray(); byte[] combined = new byte[first.Length + second.Length]; first.CopyTo(combined, 0); second.CopyTo(combined, first.Length); return SHA256.HashData(combined);
    }

    public async ValueTask<BaseResult<BaseSubjectAdvisoryLifecycleDelivery<TSubject>>> IssueAdvisoryAsync<TSubject>(BaseSession session, BaseInstalledSubjectRetirementConsumer installed, BaseSubjectLifecycleDelivery<TSubject> delivery, CancellationToken cancellationToken)
    {
        if (installed.Definition.Participation != BaseSubjectRetirementParticipation.AdvisoryAcknowledgement) return Failure<BaseSubjectAdvisoryLifecycleDelivery<TSubject>>(OperationStatus.ValidationFailed, BaseSubjectRetirementErrorCodes.ContractInvalid, ErrorCategory.Validation);
        byte[]? grantDigest = await AuthorizeAcknowledgementAsync(session, installed, cancellationToken).ConfigureAwait(false); if (grantDigest is null) return Failure<BaseSubjectAdvisoryLifecycleDelivery<TSubject>>(OperationStatus.PolicyDenied, BaseSubjectRetirementErrorCodes.Unauthorized, ErrorCategory.Authorization);
        BaseSubjectLifecycleFact fact = delivery.Fact.Fact; BaseOwnedSubjectScopeEvidence scope = Scope(session, installed); BaseGeneratedSubjectRegistration? contract = contracts.Find(fact.ContractId, fact.ContractVersion); if (contract is null || !TryDeliveryAuthority(session, installed, delivery, contract, scope, out BaseSubjectLifecycleTokenPayload? authority) || authority is null) return Failure<BaseSubjectAdvisoryLifecycleDelivery<TSubject>>(OperationStatus.ValidationFailed, BaseSubjectRetirementErrorCodes.ContractInvalid, ErrorCategory.Validation);
        DateTimeOffset issued = timeProvider.GetUtcNow(); DateTimeOffset expires = checked(issued + installed.Lifecycle.Definition.Limits.MaximumCheckpointLag);
        var payload = Payload(installed, fact, null, issued, expires, grantDigest, contract.Checksum, authority); byte[] token = _codec.Protect(payload, BaseSubjectRetirementEvidenceCodec.Binding(session.ApplicationId, installed, scope)); BaseMutationRequestIdentity identity = Identity(installed, token);
        return new BaseSuccess<BaseSubjectAdvisoryLifecycleDelivery<TSubject>>(new() { Lifecycle = delivery, Acknowledgement = new(token), AcknowledgementIdentity = identity }, OperationStatus.Ok, null, null, null, null);
    }

    public async ValueTask<BaseResult<BaseSubjectRequiredLifecycleDelivery<TSubject>>> IssueRequiredAsync<TSubject>(BaseSession session, BaseInstalledSubjectRetirementConsumer installed, BaseSubjectLifecycleDelivery<TSubject> delivery, CancellationToken cancellationToken)
    {
        if (installed.Definition.Participation != BaseSubjectRetirementParticipation.RequiredBeforePurge) return Failure<BaseSubjectRequiredLifecycleDelivery<TSubject>>(OperationStatus.ValidationFailed, BaseSubjectRetirementErrorCodes.ContractInvalid, ErrorCategory.Validation);
        byte[]? grantDigest = await AuthorizeAcknowledgementAsync(session, installed, cancellationToken).ConfigureAwait(false); if (grantDigest is null) return Failure<BaseSubjectRequiredLifecycleDelivery<TSubject>>(OperationStatus.PolicyDenied, BaseSubjectRetirementErrorCodes.Unauthorized, ErrorCategory.Authorization);
        BaseSubjectLifecycleFact fact = delivery.Fact.Fact; if (fact.Transitioned?.CurrentState != BaseSubjectLifecycleState.Tombstoned) return Failure<BaseSubjectRequiredLifecycleDelivery<TSubject>>(OperationStatus.ValidationFailed, BaseSubjectRetirementErrorCodes.ContractInvalid, ErrorCategory.Validation);
        BaseGeneratedSubjectRegistration? contract = contracts.Find(fact.ContractId, fact.ContractVersion); if (contract is null || stores.GetStoreForCollection(contract.Definition.ValidationPlan.PrivateCollectionId) is not IBaseSubjectRetirementStore store) return Failure<BaseSubjectRequiredLifecycleDelivery<TSubject>>(OperationStatus.CapabilityUnavailable, BaseSubjectRetirementErrorCodes.ProviderContractInvalid, ErrorCategory.Capability);
        BaseOwnedSubjectScopeEvidence scope = Scope(session, installed); if (!TryDeliveryAuthority(session, installed, delivery, contract, scope, out BaseSubjectLifecycleTokenPayload? authority) || authority is null) return Failure<BaseSubjectRequiredLifecycleDelivery<TSubject>>(OperationStatus.ValidationFailed, BaseSubjectRetirementErrorCodes.ContractInvalid, ErrorCategory.Validation);
        var inspectionRequest = new BaseSubjectRetirementInspectionRequest { ContractId = fact.ContractId, ContractVersion = fact.ContractVersion, SubjectId = fact.SubjectId, AuthorityEpoch = fact.AuthorityEpoch, Incarnation = fact.Incarnation, ScopeAuthority = new() { Mode = BaseSubjectScopeQueryMode.ExactScope, ExactScope = scope, InstalledAuthorityDigest = contract.Checksum }, IncludeTerminalSummary = false, MaximumResultBytes = installed.Definition.Limits.MaximumReceiptBytes, DeadlineUtc = timeProvider.GetUtcNow() + installed.Definition.Limits.AcknowledgementTimeout };
        OperationResult<BaseSubjectRetirementInspection> read; try { read = await InvokeProviderAsync(token => store.InspectAsync(inspectionRequest, token), installed.Definition.Limits.AcknowledgementTimeout, cancellationToken).ConfigureAwait(false); } catch (TimeoutException) { return Failure<BaseSubjectRequiredLifecycleDelivery<TSubject>>(OperationStatus.StoreError, BaseSubjectRetirementErrorCodes.Timeout, ErrorCategory.Store); }
        if (!read.IsSuccess() || read.Value?.CurrentBarrier is not { } barrier) return Failure<BaseSubjectRequiredLifecycleDelivery<TSubject>>(read.Status, read.Error?.Code ?? BaseSubjectRetirementErrorCodes.ProviderContractInvalid, read.Error?.Category ?? ErrorCategory.Store);
        if (!ValidateInspection(read.Value, inspectionRequest, scope)) return Failure<BaseSubjectRequiredLifecycleDelivery<TSubject>>(OperationStatus.CapabilityUnavailable, BaseSubjectRetirementErrorCodes.ProviderContractInvalid, ErrorCategory.Capability);
        if (barrier.TombstoneSequence != fact.SubjectSequence) return Failure<BaseSubjectRequiredLifecycleDelivery<TSubject>>(OperationStatus.Conflict, BaseSubjectRetirementErrorCodes.BarrierPending, ErrorCategory.Conflict);
        DateTimeOffset issued = timeProvider.GetUtcNow();
        DateTimeOffset expires = RequiredEvidenceExpiry(issued, installed.Lifecycle.Definition.Limits.MaximumCheckpointLag, barrier.DeadlineUtc);
        var expectation = new BaseSubjectRequiredBarrierExpectation { Generation = barrier.Generation, Checksum = barrier.BarrierChecksum };
        var payload = Payload(installed, fact, expectation, issued, expires, grantDigest, contract.Checksum, authority); byte[] token = _codec.Protect(payload, BaseSubjectRetirementEvidenceCodec.Binding(session.ApplicationId, installed, scope)); BaseMutationRequestIdentity identity = Identity(installed, token);
        return new BaseSuccess<BaseSubjectRequiredLifecycleDelivery<TSubject>>(new() { Lifecycle = delivery, Acknowledgement = new(token), AcknowledgementIdentity = identity }, OperationStatus.Ok, null, null, null, null);
    }

    public async ValueTask<BaseResult<BaseSubjectAcknowledgementResult>> AcknowledgeAsync(BaseSession session, BaseInstalledSubjectRetirementConsumer installed, ReadOnlyMemory<byte> evidence, BaseSubjectRetirementParticipation participation, BaseSubjectAcknowledgementDisposition disposition, BaseMutationRequestIdentity identity, BaseActivationGuard? activationGuard, CancellationToken cancellationToken)
    {
        if (installed.Definition.Participation != participation || !Enum.IsDefined(disposition) || !AudienceAllows(installed.Definition.Audience, session.Principal)) return Failure<BaseSubjectAcknowledgementResult>(OperationStatus.PolicyDenied, BaseSubjectRetirementErrorCodes.Unauthorized, ErrorCategory.Authorization);
        BaseGeneratedSubjectRegistration? contract = contracts.Find(installed.Lifecycle.Definition.ContractId, installed.Lifecycle.Definition.ContractVersion); if (contract is null) return Failure<BaseSubjectAcknowledgementResult>(OperationStatus.CapabilityUnavailable, BaseSubjectRetirementErrorCodes.ProviderContractInvalid, ErrorCategory.Capability);
        BaseOwnedSubjectScopeEvidence scope = Scope(session, installed); byte[] binding = BaseSubjectRetirementEvidenceCodec.Binding(session.ApplicationId, installed, scope);
        if (!_codec.TryRead(evidence.Span, participation, binding, contract.Definition.SubjectIdKind, out BaseSubjectRetirementEvidencePayload? payload) || payload is null || payload.ConsumerId != installed.Definition.ConsumerId || payload.ConsumerVersion != installed.Definition.ConsumerVersion || payload.ConsumerChecksum != installed.Checksum || payload.ContractChecksum != contract.Checksum || (payload.AllowedDispositions & (1 << (int)disposition)) == 0 || !IdentityMatches(identity, installed, evidence.Span)) return Failure<BaseSubjectAcknowledgementResult>(OperationStatus.ValidationFailed, BaseSubjectRetirementErrorCodes.ContractInvalid, ErrorCategory.Validation);
        OperationContext operation = session.Operation(BaseOperationKind.SubjectRetirementAcknowledge, installed.Definition.ConsumerId); var resource = new CollectionDefinition { Id = installed.Definition.ConsumerId, Name = installed.Definition.ConsumerId, Kind = BaseCollectionKinds.Custom, SchemaMode = SchemaMode.Strict, UnknownFields = UnknownFieldPolicy.Reject, System = true, SystemOwnerModuleId = installed.Definition.OwningModuleId };
        OperationResult<BasePolicyEvaluation> authorization = await policy.EvaluateWriteAsync(new() { Principal = session.Principal, Operation = operation, Collection = resource, ResourceKind = PolicyResourceKind.SubjectLifecycle }, cancellationToken).ConfigureAwait(false);
        if (!BaseSystemCollectionGate.HasExactSubjectLifecycleGrant(authorization, installed.Definition.AcknowledgementGrantId, installed.Definition.OwningModuleId, installed.Definition.ConsumerId, payload.ContractId, payload.ContractVersion, session.Principal, operation)) return Failure<BaseSubjectAcknowledgementResult>(OperationStatus.PolicyDenied, BaseSubjectRetirementErrorCodes.Unauthorized, ErrorCategory.Authorization);
        OperationContext fixedOperation = session.Operation(BaseOperationKind.SubjectRetirementAcknowledge, FixedAcknowledgementGrant); OperationResult<BasePolicyEvaluation> fixedAuthorization = await policy.EvaluateWriteAsync(new() { Principal = session.Principal, Operation = fixedOperation, Collection = resource, ResourceKind = PolicyResourceKind.SubjectLifecycle }, cancellationToken).ConfigureAwait(false);
        if (!BaseSystemCollectionGate.HasExactSubjectLifecycleGrant(fixedAuthorization, FixedAcknowledgementGrant, installed.Definition.OwningModuleId, FixedAcknowledgementGrant, payload.ContractId, payload.ContractVersion, session.Principal, fixedOperation) || authorization.Value?.Authority is null || fixedAuthorization.Value?.Authority is null) return Failure<BaseSubjectAcknowledgementResult>(OperationStatus.PolicyDenied, BaseSubjectRetirementErrorCodes.Unauthorized, ErrorCategory.Authorization); byte[] currentGrantDigest = CombinedAuthorityDigest(authorization.Value.Authority, fixedAuthorization.Value.Authority); if (!CryptographicOperations.FixedTimeEquals(currentGrantDigest, payload.GrantAuthorityDigest)) return Failure<BaseSubjectAcknowledgementResult>(OperationStatus.PolicyDenied, BaseSubjectRetirementErrorCodes.Unauthorized, ErrorCategory.Authorization);
        IRecordStore? rawStore = stores.GetStoreForCollection(contract.Definition.ValidationPlan.PrivateCollectionId); if (rawStore is not IBaseSubjectRetirementStore store || rawStore is not IBaseSubjectLifecycleStore lifecycleStore) return Failure<BaseSubjectAcknowledgementResult>(OperationStatus.CapabilityUnavailable, BaseSubjectRetirementErrorCodes.ProviderContractInvalid, ErrorCategory.Capability);
        OperationResult<BaseSubjectLifecycleProviderInspection> lifecycleAuthority; try { lifecycleAuthority = await InvokeProviderAsync(token => lifecycleStore.InspectAsync(new() { ContractId = payload.ContractId, ContractVersion = payload.ContractVersion, ConsumerId = payload.ConsumerId, ScopeAuthority = new() { Mode = BaseSubjectScopeQueryMode.ExactScope, ExactScope = scope, InstalledAuthorityDigest = installed.Lifecycle.Checksum }, SubjectId = payload.SubjectId, IncludeTerminalReceipt = false, MaximumResultBytes = 4096, DeadlineUtc = timeProvider.GetUtcNow().Add(installed.Definition.Limits.AcknowledgementTimeout) }, token), installed.Definition.Limits.AcknowledgementTimeout, cancellationToken).ConfigureAwait(false); } catch (TimeoutException) { return Failure<BaseSubjectAcknowledgementResult>(OperationStatus.StoreError, BaseSubjectRetirementErrorCodes.Timeout, ErrorCategory.Store); }
        BaseSubjectLifecycleConsumerInspection? currentConsumer = lifecycleAuthority.Value?.Consumers.SingleOrDefault(value => value.ConsumerId == payload.ConsumerId && value.ConsumerVersion == payload.ConsumerVersion); if (!lifecycleAuthority.IsSuccess() || lifecycleAuthority.Value is null || currentConsumer is null || lifecycleAuthority.Value.StoreInstanceId != payload.StoreInstanceId || lifecycleAuthority.Value.RestoreEpoch != payload.RestoreEpoch || lifecycleAuthority.Value.DeliveryEpoch != payload.DeliveryEpoch || currentConsumer.ProjectionGeneration != payload.ProjectionGeneration || currentConsumer.CheckpointGeneration != payload.CheckpointGeneration) return Failure<BaseSubjectAcknowledgementResult>(OperationStatus.ValidationFailed, BaseSubjectRetirementErrorCodes.ContractInvalid, ErrorCategory.Validation);
        BaseInstalledSubjectRetirementPolicy? retirementPolicy = (session.Services.GetService(typeof(BaseSubjectRetirementRegistry)) as BaseSubjectRetirementRegistry)?.FindPolicy(payload.ContractId, payload.ContractVersion);
        var acknowledgement = new BaseSubjectLifecycleAcknowledgement { ConsumerId = payload.ConsumerId, ConsumerVersion = payload.ConsumerVersion, ConsumerChecksum = installed.Lifecycle.Checksum, ContractId = payload.ContractId, ContractVersion = payload.ContractVersion, SubjectId = payload.SubjectId, AuthorityEpoch = payload.AuthorityEpoch, Incarnation = payload.Incarnation, ThroughSubjectSequence = payload.ThroughSequence, Disposition = disposition, Participation = participation, RequiredBarrier = payload.Barrier, Identity = identity };
        byte[] semanticDigest = SemanticAcknowledgementDigest(evidence.Span, disposition, payload); BaseMutationRequestIdentity executionIdentity = BaseMutationRequestIdentity.Create(identity.Scope, identity.Operation, identity.IdempotencyKey, BaseMutationRequestFingerprint.Create(semanticDigest)); acknowledgement = acknowledgement with { Identity = executionIdentity }; BaseActivationGuard? effectiveGuard = activationGuard is null ? null : activationGuard with { ChildRequestFingerprint = semanticDigest.ToImmutableArray() }; var processor = new BaseSubjectRetirementAcknowledgementProcessor(new() { Acknowledgement = acknowledgement, Scope = scope, RetirementConsumerChecksum = installed.Checksum, RetirementPolicyChecksum = retirementPolicy?.Definition.PolicyChecksum ?? new string('0', 64), ObservedAtUtc = timeProvider.GetUtcNow(), DeadlineUtc = timeProvider.GetUtcNow() + installed.Definition.Limits.AcknowledgementTimeout, ActivationGuard = effectiveGuard });
        RecordMutationExecutionResult execution; try { execution = await InvokeProviderAsync(token => store.ExecuteAsync(processor, new() { AcquisitionTimeout = installed.Definition.Limits.AcknowledgementTimeout, TransactionTimeout = installed.Definition.Limits.AcknowledgementTimeout, CommitCompletionTimeout = installed.Definition.Limits.AcknowledgementTimeout, AtomicRequest = new() { Identity = executionIdentity, StructuralDigest = semanticDigest, ExpiresAt = timeProvider.GetUtcNow().AddDays(30), MaxReceiptBytes = installed.Definition.Limits.MaximumReceiptBytes } }, token), installed.Definition.Limits.AcknowledgementTimeout + installed.Definition.Limits.AcknowledgementTimeout + installed.Definition.Limits.AcknowledgementTimeout, cancellationToken).ConfigureAwait(false); } catch (TimeoutException) { return Failure<BaseSubjectAcknowledgementResult>(OperationStatus.StoreError, BaseSubjectRetirementErrorCodes.CommitIndeterminate, ErrorCategory.Store); }
        if (execution.Outcome == RecordMutationExecutionOutcome.Committed && processor.Result is not null) { await TryDispatchControlsAsync().ConfigureAwait(false); return new BaseSuccess<BaseSubjectAcknowledgementResult>(processor.Result, processor.Result.Outcome == BaseSubjectRetirementMutationOutcome.Duplicate ? OperationStatus.Ok : OperationStatus.Updated, null, null, null, null); }
        BaseError? error = execution.Error ?? execution.Processing?.Error; string code = error?.Code == "base.runtime.request.fingerprintConflict" ? BaseSubjectRetirementErrorCodes.AcknowledgementConflict : error?.Code ?? BaseSubjectRetirementErrorCodes.ProviderContractInvalid; return Failure<BaseSubjectAcknowledgementResult>(execution.Outcome == RecordMutationExecutionOutcome.Indeterminate ? OperationStatus.StoreError : OperationStatus.Conflict, code, error?.Category ?? ErrorCategory.Store);
    }

    public async ValueTask<BaseResult<BaseSubjectRetirementPage>> ReadBarriersAsync(BaseSession session, string contractId, int contractVersion, BaseSubjectRetirementBarrierState? state, BaseSubjectRetirementCursor? after, int take, CancellationToken cancellationToken)
    {
        BaseGeneratedSubjectRegistration? contract = contracts.Find(contractId, contractVersion); if (contract is null) return Failure<BaseSubjectRetirementPage>(OperationStatus.PolicyDenied, BaseSubjectRetirementErrorCodes.Unauthorized, ErrorCategory.Authorization);
        OperationContext operation = session.Operation(BaseOperationKind.SubjectRetirementInspect, "base.subjectRetirement.barriers.query"); if (!await AuthorizedAsync(session, contract, "base.subjectRetirement.barrier.inspect", operation, false, cancellationToken).ConfigureAwait(false)) return Failure<BaseSubjectRetirementPage>(OperationStatus.PolicyDenied, BaseSubjectRetirementErrorCodes.Unauthorized, ErrorCategory.Authorization); bool allScopes = session.Principal.SubjectKind is AccessSubjectKind.Admin or AccessSubjectKind.System; if (allScopes && !await AuthorizedAsync(session, contract, "base.subjectRetirement.scope.all", session.Operation(BaseOperationKind.SubjectRetirementInspect, "base.subjectRetirement.scope.all"), false, cancellationToken).ConfigureAwait(false)) return Failure<BaseSubjectRetirementPage>(OperationStatus.PolicyDenied, BaseSubjectRetirementErrorCodes.Unauthorized, ErrorCategory.Authorization);
        if (take is < 1 or > 256) return Failure<BaseSubjectRetirementPage>(OperationStatus.ValidationFailed, BaseSubjectRetirementErrorCodes.ContractInvalid, ErrorCategory.Validation);
        IRecordStore raw = stores.GetStoreForCollection(contract.Definition.ValidationPlan.PrivateCollectionId) ?? throw new InvalidOperationException(BaseSubjectRetirementErrorCodes.ProviderContractInvalid); if (raw is not IBaseSubjectRetirementStore store || raw is not IBaseSubjectLifecycleStore lifecycleStore) return Failure<BaseSubjectRetirementPage>(OperationStatus.CapabilityUnavailable, BaseSubjectRetirementErrorCodes.ProviderContractInvalid, ErrorCategory.Capability);
        BaseOwnedSubjectScopeEvidence? scope = allScopes ? null : Scope(session, contract, operation); if(scope is not null&&!ValidScope(scope))return Failure<BaseSubjectRetirementPage>(OperationStatus.PolicyDenied,BaseSubjectRetirementErrorCodes.ScopeAuthorityInvalid,ErrorCategory.Authorization); BaseSubjectLifecycleInspectionAuthority? installedInspection = allScopes ? (session.Services.GetService(typeof(BaseSubjectLifecycleInspectionAuthorityRegistry)) as BaseSubjectLifecycleInspectionAuthorityRegistry)?.Find(contractId, contractVersion) : null; if (allScopes && installedInspection is null) return Failure<BaseSubjectRetirementPage>(OperationStatus.CapabilityUnavailable, BaseSubjectRetirementErrorCodes.ProviderContractInvalid, ErrorCategory.Capability); string authorityDigest = installedInspection?.Digest ?? contract.Checksum; var scopeAuthority = new BaseSubjectScopeQueryAuthority { Mode = allScopes ? BaseSubjectScopeQueryMode.AllAuthorizedScopes : BaseSubjectScopeQueryMode.ExactScope, ExactScope = scope, InstalledAuthorityDigest = authorityDigest }; OperationResult<BaseSubjectLifecycleProviderInspection> authority; try { authority = await InvokeProviderAsync(token => lifecycleStore.InspectAsync(new() { ContractId = contractId, ContractVersion = contractVersion, ConsumerId = null, ScopeAuthority = scopeAuthority, SubjectId = null, IncludeTerminalReceipt = false, MaximumResultBytes = 4096, DeadlineUtc = timeProvider.GetUtcNow().AddSeconds(5) }, token), TimeSpan.FromSeconds(5), cancellationToken).ConfigureAwait(false); } catch (TimeoutException) { return Failure<BaseSubjectRetirementPage>(OperationStatus.StoreError, BaseSubjectRetirementErrorCodes.Timeout, ErrorCategory.Store); }
        if (!authority.IsSuccess() || authority.Value is null) return Failure<BaseSubjectRetirementPage>(authority.Status, authority.Error?.Code ?? BaseSubjectRetirementErrorCodes.ProviderContractInvalid, authority.Error?.Category ?? ErrorCategory.Store);
        byte[] binding = CursorBinding(session.ApplicationId, contract, state, scope, authority.Value.StoreInstanceId, authority.Value.RestoreEpoch); BaseSubjectRetirementBarrierKey? providerAfter = null;
        if (after is not null && !TryReadCursor(after, binding, contract.Definition.SubjectIdKind, out providerAfter)) return Failure<BaseSubjectRetirementPage>(OperationStatus.ValidationFailed, BaseSubjectRetirementErrorCodes.CursorInvalid, ErrorCategory.Validation);
        OperationResult<BaseSubjectRetirementBarrierPage> result; try { result = await InvokeProviderAsync(token => store.ReadBarriersAsync(new() { ApplicationId = session.ApplicationId, ContractId = contractId, ContractVersion = contractVersion, ScopeAuthority = scopeAuthority, State = state, After = providerAfter, Take = take, MaximumResultBytes = 1_048_576, DeadlineUtc = timeProvider.GetUtcNow().AddSeconds(30) }, token), TimeSpan.FromSeconds(30), cancellationToken).ConfigureAwait(false); } catch (TimeoutException) { return Failure<BaseSubjectRetirementPage>(OperationStatus.StoreError, BaseSubjectRetirementErrorCodes.Timeout, ErrorCategory.Store); }
        if (!result.IsSuccess() || result.Value is null) return Failure<BaseSubjectRetirementPage>(result.Status, result.Error?.Code ?? BaseSubjectRetirementErrorCodes.ProviderContractInvalid, result.Error?.Category ?? ErrorCategory.Store);
        if (!ValidateBarrierPage(_scopes, result.Value, contract, state, providerAfter, take, scope)) return Failure<BaseSubjectRetirementPage>(OperationStatus.CapabilityUnavailable, BaseSubjectRetirementErrorCodes.ProviderContractInvalid, ErrorCategory.Capability);
        BaseSubjectRetirementCursor? next = result.Value.Next is null ? null : ProtectCursor(result.Value.Next, binding);
        return new BaseSuccess<BaseSubjectRetirementPage>(new() { Barriers = [.. result.Value.Barriers.Select(static row => row.Barrier)], Next = next, CapturedBarrierGeneration = result.Value.CapturedBarrierGeneration }, OperationStatus.Ok, null, null, null, null);
    }

    private BaseSubjectRetirementCursor ProtectCursor(BaseSubjectRetirementBarrierKey key, ReadOnlySpan<byte> binding)
    {
        using var stream = new MemoryStream(); using var writer = new BinaryWriter(stream, Encoding.UTF8, true); writer.Write((byte)key.ScopeKind); writer.Write(key.ScopeIndexDigest); Write(writer, key.ContractId); writer.Write(key.ContractVersion); Write(writer, key.SubjectId.Value); writer.Write(key.AuthorityEpoch.ToArray()); writer.Write(key.Incarnation.ToArray()); writer.Flush();
        return new(Encoding.ASCII.GetBytes(tokens.Protect("hpd.base.subject-retirement.cursor.v1", 1, stream.ToArray(), binding)));
    }
    private bool TryReadCursor(BaseSubjectRetirementCursor cursor, ReadOnlySpan<byte> binding, BaseSubjectIdKind idKind, out BaseSubjectRetirementBarrierKey? key)
    {
        key = null; BaseOpaqueTokenResult value = tokens.Unprotect("hpd.base.subject-retirement.cursor.v1", 1, Encoding.ASCII.GetString(cursor.ToArray()), 65, 2048, binding); if (value.Status != BaseOpaqueTokenStatus.Valid || value.Plaintext is null) return false;
        try { using var stream = new MemoryStream(value.Plaintext, false); using var reader = new BinaryReader(stream, Encoding.UTF8, true); var kind = (BaseSubjectScopeKind)reader.ReadByte(); byte[] digest = reader.ReadBytes(32); string contractId = Read(reader); int version = reader.ReadInt32(); BaseSubjectId subjectId = BaseSubjectId.Create(Read(reader), idKind); var epoch = new BaseSubjectAuthorityEpoch(reader.ReadBytes(16)); var incarnation = new BaseSubjectIncarnation(reader.ReadBytes(24)); if (stream.Position != stream.Length || digest.Length != 32 || !Enum.IsDefined(kind)) return false; key = new() { ScopeKind = kind, ScopeIndexDigest = digest, ContractId = contractId, ContractVersion = version, SubjectId = subjectId, AuthorityEpoch = epoch, Incarnation = incarnation }; return true; } catch { return false; }
    }
    private static byte[] CursorBinding(string applicationId, BaseGeneratedSubjectRegistration contract, BaseSubjectRetirementBarrierState? state, BaseOwnedSubjectScopeEvidence? scope, string storeInstanceId, long restoreEpoch) => SHA256.HashData(Encoding.UTF8.GetBytes($"base.subjectRetirement.cursor.binding.v1\0{applicationId}\0{contract.Definition.Id}\0{contract.Definition.Version}\0{contract.Checksum}\0{(scope is null ? -1 : (int)scope.Kind)}\0{scope?.Value}\0{(state is null ? -1 : (int)state.Value)}\0{storeInstanceId}\0{restoreEpoch}"));
    private static void Write(BinaryWriter writer, string value) { byte[] bytes = Encoding.UTF8.GetBytes(value); writer.Write(bytes.Length); writer.Write(bytes); }
    private static string Read(BinaryReader reader) { int length = reader.ReadInt32(); if (length is < 1 or > 512) throw new FormatException(); byte[] bytes = reader.ReadBytes(length); if (bytes.Length != length) throw new EndOfStreamException(); return Encoding.UTF8.GetString(bytes); }

    public async ValueTask<BaseResult<BaseSubjectRetirementInspection>> InspectAsync(BaseSession session, BaseSubjectRetirementInspectionRequest request, CancellationToken cancellationToken)
    {
        BaseGeneratedSubjectRegistration? contract = contracts.Find(request.ContractId, request.ContractVersion); if (contract is null) return Failure<BaseSubjectRetirementInspection>(OperationStatus.PolicyDenied, BaseSubjectRetirementErrorCodes.Unauthorized, ErrorCategory.Authorization); OperationContext operation = session.Operation(BaseOperationKind.SubjectRetirementInspect, "base.subjectRetirement.barrier.inspect"); if (!await AuthorizedAsync(session, contract, "base.subjectRetirement.barrier.inspect", operation, false, cancellationToken).ConfigureAwait(false)) return Failure<BaseSubjectRetirementInspection>(OperationStatus.PolicyDenied, BaseSubjectRetirementErrorCodes.Unauthorized, ErrorCategory.Authorization); BaseOwnedSubjectScopeEvidence scope = Scope(session, contract, operation); if (!ValidScope(scope)) return Failure<BaseSubjectRetirementInspection>(OperationStatus.PolicyDenied, BaseSubjectRetirementErrorCodes.ScopeAuthorityInvalid, ErrorCategory.Authorization); IRecordStore? raw = stores.GetStoreForCollection(contract.Definition.ValidationPlan.PrivateCollectionId); if (raw is not IBaseSubjectRetirementStore store || raw is not IBaseSubjectLifecycleStore lifecycleStore) return Failure<BaseSubjectRetirementInspection>(OperationStatus.CapabilityUnavailable, BaseSubjectRetirementErrorCodes.ProviderContractInvalid, ErrorCategory.Capability); var scopeAuthority = new BaseSubjectScopeQueryAuthority { Mode = BaseSubjectScopeQueryMode.ExactScope, ExactScope = scope, InstalledAuthorityDigest = contract.Checksum }; OperationResult<BaseSubjectLifecycleProviderInspection> authority; OperationResult<BaseSubjectRetirementInspection> result; try { authority = await InvokeProviderAsync(token => lifecycleStore.InspectAsync(new() { ContractId = request.ContractId, ContractVersion = request.ContractVersion, ConsumerId = null, ScopeAuthority = scopeAuthority, SubjectId = request.SubjectId, IncludeTerminalReceipt = false, MaximumResultBytes = 4096, DeadlineUtc = timeProvider.GetUtcNow().AddSeconds(5) }, token), TimeSpan.FromSeconds(5), cancellationToken).ConfigureAwait(false); if (!authority.IsSuccess() || authority.Value is null) return Failure<BaseSubjectRetirementInspection>(OperationStatus.CapabilityUnavailable, BaseSubjectRetirementErrorCodes.ProviderContractInvalid, ErrorCategory.Capability); result = await InvokeProviderAsync(token => store.InspectAsync(request with { ScopeAuthority = scopeAuthority }, token), TimeSpan.FromSeconds(30), cancellationToken).ConfigureAwait(false); if (!result.IsSuccess() || result.Value is null) return Result(result); if (!ValidateInspection(result.Value, request, scope)) return Failure<BaseSubjectRetirementInspection>(OperationStatus.CapabilityUnavailable, BaseSubjectRetirementErrorCodes.ProviderContractInvalid, ErrorCategory.Capability); } catch (TimeoutException) { return Failure<BaseSubjectRetirementInspection>(OperationStatus.StoreError, BaseSubjectRetirementErrorCodes.Timeout, ErrorCategory.Store); }
        return Result(result);
    }

    public async ValueTask<BaseResult<BaseSubjectRetirementTimeoutResult>> TimeoutAsync(BaseSession session, BaseSubjectRetirementTimeoutRequest request, CancellationToken cancellationToken)
    {
        BaseGeneratedSubjectRegistration? contract = contracts.Find(request.ContractId, request.ContractVersion); BaseSubjectRetirementRegistry? registry = session.Services.GetService(typeof(BaseSubjectRetirementRegistry)) as BaseSubjectRetirementRegistry; BaseInstalledSubjectRetirementPolicy? installed = registry?.FindPolicy(request.ContractId, request.ContractVersion); if (contract is null || installed is null) return Failure<BaseSubjectRetirementTimeoutResult>(OperationStatus.PolicyDenied, BaseSubjectRetirementErrorCodes.Unauthorized, ErrorCategory.Authorization); OperationContext operation = session.Operation(BaseOperationKind.SubjectRetirementTimeout, "base.subjectRetirement.timeout.process"); if (!await AuthorizedAsync(session, contract, "base.subjectRetirement.timeout.process", operation, true, cancellationToken).ConfigureAwait(false)) return Failure<BaseSubjectRetirementTimeoutResult>(OperationStatus.PolicyDenied, BaseSubjectRetirementErrorCodes.Unauthorized, ErrorCategory.Authorization); BaseOwnedSubjectScopeEvidence scope = Scope(session, contract, operation);if(!ValidScope(scope))return Failure<BaseSubjectRetirementTimeoutResult>(OperationStatus.PolicyDenied,BaseSubjectRetirementErrorCodes.ScopeAuthorityInvalid,ErrorCategory.Authorization);if (stores.GetStoreForCollection(contract.Definition.ValidationPlan.PrivateCollectionId) is not IBaseSubjectRetirementStore store) return Failure<BaseSubjectRetirementTimeoutResult>(OperationStatus.CapabilityUnavailable, BaseSubjectRetirementErrorCodes.ProviderContractInvalid, ErrorCategory.Capability); var processor = new BaseSubjectRetirementTimeoutProcessor(new() { Request = request, Scope = scope, RetirementPolicyChecksum = installed.Definition.PolicyChecksum, ObservedAtUtc = timeProvider.GetUtcNow() }); RecordMutationExecutionResult execution = await ExecuteAsync(store, processor, request.Identity, Canonical(request), cancellationToken).ConfigureAwait(false); return Execution(execution, processor.Result);
    }

    public async ValueTask<BaseResult<BaseSubjectRetirementOverrideResult>> OverrideAsync(BaseSession session, BaseSubjectRetirementOverrideRequest request, CancellationToken cancellationToken)
    {
        BaseGeneratedSubjectRegistration? contract = contracts.Find(request.ContractId, request.ContractVersion); BaseSubjectRetirementRegistry? registry = session.Services.GetService(typeof(BaseSubjectRetirementRegistry)) as BaseSubjectRetirementRegistry; BaseInstalledSubjectRetirementPolicy? installed = registry?.FindPolicy(request.ContractId, request.ContractVersion); if (contract is null || installed is null) return Failure<BaseSubjectRetirementOverrideResult>(OperationStatus.PolicyDenied, BaseSubjectRetirementErrorCodes.Unauthorized, ErrorCategory.Authorization); OperationContext operation = session.Operation(BaseOperationKind.SubjectRetirementOverride, "base.subjectRetirement.override"); if (!await AuthorizedAsync(session, contract, "base.subjectRetirement.override", operation, true, cancellationToken).ConfigureAwait(false)) return Failure<BaseSubjectRetirementOverrideResult>(OperationStatus.PolicyDenied, BaseSubjectRetirementErrorCodes.Unauthorized, ErrorCategory.Authorization); BaseOwnedSubjectScopeEvidence scope = Scope(session, contract, operation);if(!ValidScope(scope))return Failure<BaseSubjectRetirementOverrideResult>(OperationStatus.PolicyDenied,BaseSubjectRetirementErrorCodes.ScopeAuthorityInvalid,ErrorCategory.Authorization);if (stores.GetStoreForCollection(contract.Definition.ValidationPlan.PrivateCollectionId) is not IBaseSubjectRetirementStore store) return Failure<BaseSubjectRetirementOverrideResult>(OperationStatus.CapabilityUnavailable, BaseSubjectRetirementErrorCodes.ProviderContractInvalid, ErrorCategory.Capability); var processor = new BaseSubjectRetirementOverrideProcessor(new() { Request = request, Scope = scope, RetirementPolicyChecksum = installed.Definition.PolicyChecksum, ObservedAtUtc = timeProvider.GetUtcNow() }); RecordMutationExecutionResult execution = await ExecuteAsync(store, processor, request.Identity, Canonical(request), cancellationToken).ConfigureAwait(false); return Execution(execution, processor.Result);
    }

    public async ValueTask<BaseResult<BaseSubjectFinalPurgeResult>> PurgeAsync(BaseSession session, BaseSubjectFinalPurgeRequest request, CancellationToken cancellationToken)
    {
        BaseGeneratedSubjectRegistration? contract = contracts.Find(request.ContractId, request.ContractVersion); BaseSubjectRetirementRegistry? registry = session.Services.GetService(typeof(BaseSubjectRetirementRegistry)) as BaseSubjectRetirementRegistry; BaseInstalledSubjectRetirementPolicy? installed = registry?.FindPolicy(request.ContractId, request.ContractVersion); if (contract is null || installed is null) return Failure<BaseSubjectFinalPurgeResult>(OperationStatus.PolicyDenied, BaseSubjectRetirementErrorCodes.Unauthorized, ErrorCategory.Authorization); OperationContext operation = session.Operation(BaseOperationKind.SubjectRetirementPurge, "base.subjectRetirement.purge"); if (!await AuthorizedAsync(session, contract, "base.subjectRetirement.purge", operation, true, cancellationToken).ConfigureAwait(false)) return Failure<BaseSubjectFinalPurgeResult>(OperationStatus.PolicyDenied, BaseSubjectRetirementErrorCodes.Unauthorized, ErrorCategory.Authorization); if (!await AuthorizedSourceAsync(session, contract, operation, cancellationToken).ConfigureAwait(false)) return Failure<BaseSubjectFinalPurgeResult>(OperationStatus.PolicyDenied, BaseSubjectRetirementErrorCodes.Unauthorized, ErrorCategory.Authorization); BaseOwnedSubjectScopeEvidence scope = Scope(session, contract, operation);if(!ValidScope(scope))return Failure<BaseSubjectFinalPurgeResult>(OperationStatus.PolicyDenied,BaseSubjectRetirementErrorCodes.ScopeAuthorityInvalid,ErrorCategory.Authorization);if (stores.GetStoreForCollection(contract.Definition.ValidationPlan.PrivateCollectionId) is not IBaseSubjectRetirementStore store) return Failure<BaseSubjectFinalPurgeResult>(OperationStatus.CapabilityUnavailable, BaseSubjectRetirementErrorCodes.ProviderContractInvalid, ErrorCategory.Capability); var processor = new BaseSubjectRetirementPurgeProcessor(new() { Request = request, Scope = scope, ContractChecksum = contract.Checksum, RetirementPolicyChecksum = installed.Definition.PolicyChecksum, MinimumTombstoneAge = installed.Definition.PurgeRetention.MinimumTombstoneAge, ObservedAtUtc = timeProvider.GetUtcNow(), Operation = operation }); RecordMutationExecutionResult execution = await ExecuteAsync(store, processor, request.Identity, Canonical(request), cancellationToken).ConfigureAwait(false); return Execution(execution, processor.Result);
    }

    public async ValueTask<BaseResult<BaseSubjectRetirementConsumerRemovalResult>> RemoveConsumerAsync(BaseSession session, BaseSubjectRetirementConsumerRemovalRequest request, CancellationToken cancellationToken)
    {
        BaseGeneratedSubjectRegistration? contract = contracts.Find(request.ContractId, request.ContractVersion); BaseSubjectRetirementRegistry? registry = session.Services.GetService(typeof(BaseSubjectRetirementRegistry)) as BaseSubjectRetirementRegistry; BaseInstalledSubjectRetirementPolicy? policyDefinition = registry?.FindPolicy(request.ContractId, request.ContractVersion); BaseInstalledSubjectRetirementConsumer? consumer = registry?.FindConsumer(request.ConsumerId, request.ConsumerVersion);
        if (contract is null || policyDefinition is null || consumer is null || consumer.Checksum != request.ExpectedConsumerChecksum || BaseSubjectRetirementRegistry.AcceptedSetChecksum(policyDefinition.Definition.AcceptedConsumers) != request.ExpectedAcceptedSetChecksum) return Failure<BaseSubjectRetirementConsumerRemovalResult>(OperationStatus.Conflict, BaseSubjectRetirementErrorCodes.RegistrationConflict, ErrorCategory.Conflict);
        OperationContext operation = session.Operation(BaseOperationKind.SubjectRetirementConsumerRemoval, "base.subjectRetirement.consumerRemoval"); if (!await AuthorizedAsync(session, contract, "base.subjectRetirement.consumerRemoval", operation, true, cancellationToken).ConfigureAwait(false)) return Failure<BaseSubjectRetirementConsumerRemovalResult>(OperationStatus.PolicyDenied, BaseSubjectRetirementErrorCodes.Unauthorized, ErrorCategory.Authorization);
        IRecordStore raw = stores.GetStoreForCollection(contract.Definition.ValidationPlan.PrivateCollectionId) ?? throw new InvalidOperationException(BaseSubjectRetirementErrorCodes.ProviderContractInvalid); if (raw is not IBaseSubjectAuthorityMaintenanceStore maintenance || raw is not IBaseSubjectLifecycleStore lifecycleStore) return Failure<BaseSubjectRetirementConsumerRemovalResult>(OperationStatus.CapabilityUnavailable, BaseSubjectRetirementErrorCodes.ProviderContractInvalid, ErrorCategory.Capability);
        BaseSubjectLifecycleInspectionAuthority? inspectionAuthority = (session.Services.GetService(typeof(BaseSubjectLifecycleInspectionAuthorityRegistry)) as BaseSubjectLifecycleInspectionAuthorityRegistry)?.Find(request.ContractId, request.ContractVersion); if (inspectionAuthority is null) return Failure<BaseSubjectRetirementConsumerRemovalResult>(OperationStatus.CapabilityUnavailable, BaseSubjectRetirementErrorCodes.ProviderContractInvalid, ErrorCategory.Capability);
        OperationResult<BaseSubjectLifecycleProviderInspection> inspection;try{inspection=await InvokeProviderAsync(token=>lifecycleStore.InspectAsync(new() { ContractId = request.ContractId, ContractVersion = request.ContractVersion, ConsumerId = request.ConsumerId, ScopeAuthority = new() { Mode = BaseSubjectScopeQueryMode.AllAuthorizedScopes, ExactScope = null, InstalledAuthorityDigest = inspectionAuthority.Digest }, SubjectId = null, IncludeTerminalReceipt = false, MaximumResultBytes = 1_048_576, DeadlineUtc = timeProvider.GetUtcNow().AddSeconds(30) }, token),TimeSpan.FromSeconds(30),cancellationToken).ConfigureAwait(false);}catch(TimeoutException){return Failure<BaseSubjectRetirementConsumerRemovalResult>(OperationStatus.StoreError,BaseSubjectRetirementErrorCodes.Timeout,ErrorCategory.Store);}if (!inspection.IsSuccess() || inspection.Value is null) return Failure<BaseSubjectRetirementConsumerRemovalResult>(inspection.Status, inspection.Error?.Code ?? BaseSubjectRetirementErrorCodes.ProviderContractInvalid, inspection.Error?.Category ?? ErrorCategory.Store);
        BaseSubjectLifecycleConsumerInspection? projection = inspection.Value.Consumers.SingleOrDefault(value => value.ConsumerId == request.ConsumerId && value.ConsumerVersion == request.ConsumerVersion); if (projection is null) return Failure<BaseSubjectRetirementConsumerRemovalResult>(OperationStatus.Conflict, BaseSubjectRetirementErrorCodes.RegistrationConflict, ErrorCategory.Conflict);
        long schemaGeneration = 1; if (raw is IBaseSchemaStore schema) { BaseLogicalSchema? logicalSchema = session.Services.GetService(typeof(BaseLogicalSchema)) as BaseLogicalSchema; if (logicalSchema is null) return Failure<BaseSubjectRetirementConsumerRemovalResult>(OperationStatus.CapabilityUnavailable, BaseSubjectRetirementErrorCodes.ProviderContractInvalid, ErrorCategory.Capability); OperationResult<BaseSchemaObservedState> observed;try{observed=await InvokeProviderAsync(token=>schema.InspectSchemaAsync(new() { ApplicationId = session.ApplicationId, ExpectedLogicalChecksum = logicalSchema.CanonicalChecksum, Visibility = VisibilityLevel.Admin, InspectionTimeout = TimeSpan.FromSeconds(5) }, token),TimeSpan.FromSeconds(5),cancellationToken).ConfigureAwait(false);}catch(TimeoutException){return Failure<BaseSubjectRetirementConsumerRemovalResult>(OperationStatus.StoreError,BaseSubjectRetirementErrorCodes.Timeout,ErrorCategory.Store);}if (!observed.IsSuccess() || observed.Value is null) return Failure<BaseSubjectRetirementConsumerRemovalResult>(observed.Status, BaseSubjectRetirementErrorCodes.ProviderContractInvalid, ErrorCategory.Store); schemaGeneration = observed.Value.Generation; }
        byte[] lifecycleChecksum = SHA256.HashData(Encoding.UTF8.GetBytes($"base.subjectLifecycle.removeConsumer.v1\0{request.ContractId}\0{request.ContractVersion}\0{request.ConsumerId}\0{request.ConsumerVersion}\0{projection.ProjectionGeneration}")); byte[] retirementChecksum = SHA256.HashData(Encoding.UTF8.GetBytes($"base.subjectRetirement.removeConsumer.v1\0{request.ExpectedConsumerChecksum}\0{request.ExpectedAcceptedSetChecksum}\0{request.ExpectedGraphGeneration}"));
        var execution = new BaseSubjectAuthorityMaintenanceExecutionRequest { Lifecycle = new() { Kind = BaseSubjectLifecycleMaintenanceKind.RemoveConsumer, ContractId = request.ContractId, ContractVersion = request.ContractVersion, ConsumerId = request.ConsumerId, ConsumerVersion = request.ConsumerVersion, Scope = null, RetainedFrom = null, ExpectedDeliveryEpoch = inspection.Value.DeliveryEpoch, ExpectedProjectionGeneration = projection.ProjectionGeneration, PlanChecksum = lifecycleChecksum }, Retirement = new() { Kind = BaseSubjectRetirementMaintenanceKind.RemoveConsumer, ScopeAuthority = new() { Mode = BaseSubjectScopeQueryMode.AllAuthorizedScopes, ExactScope = null, InstalledAuthorityDigest = policyDefinition.Definition.PolicyChecksum }, ExpectedGraphGeneration = request.ExpectedGraphGeneration, ExpectedBarrierControlGeneration = inspection.Value.RetirementControlGeneration, PlanChecksum = retirementChecksum }, Identity = request.Identity, CombinedPlanChecksum = new byte[32], ExpectedStoreGeneration = schemaGeneration, ExpectedSchemaGeneration = schemaGeneration, ExpectedRestoreEpoch = inspection.Value.RestoreEpoch, ExpectedScopeProtectionGeneration = inspection.Value.ScopeProtectionGeneration, ExpectedScopeProtectionKeyId = inspection.Value.ScopeProtectionKeyId, ReplacementScopeProtectionKeyId = null, PageSize = 256, OperationTimeout = TimeSpan.FromMinutes(30), CommitCompletionTimeout = TimeSpan.FromMinutes(5) }; execution = execution with { CombinedPlanChecksum = BaseSubjectAuthorityMaintenanceProcessor.PlanChecksum(execution) }; var processor = new BaseSubjectAuthorityMaintenanceProcessor(); RecordMutationExecutionResult result;try{result=await InvokeProviderAsync(token=>maintenance.ExecuteMaintenanceAsync(processor,execution,token),TimeSpan.FromMinutes(35),cancellationToken).ConfigureAwait(false);}catch(TimeoutException){return Failure<BaseSubjectRetirementConsumerRemovalResult>(OperationStatus.StoreError,BaseSubjectRetirementErrorCodes.CommitIndeterminate,ErrorCategory.Store);}if (result.Outcome != RecordMutationExecutionOutcome.Committed || processor.LifecycleResult is null) return Failure<BaseSubjectRetirementConsumerRemovalResult>(result.Outcome == RecordMutationExecutionOutcome.Indeterminate ? OperationStatus.StoreError : OperationStatus.Conflict, result.Error?.Code ?? result.Processing?.Error?.Code ?? BaseSubjectRetirementErrorCodes.ProviderContractInvalid, result.Error?.Category ?? result.Processing?.Error?.Category ?? ErrorCategory.Store);
        string published = BaseSubjectRetirementRegistry.AcceptedSetChecksum(policyDefinition.Definition.AcceptedConsumers.Where(value => value.ConsumerId != request.ConsumerId || value.ConsumerVersion != request.ConsumerVersion)); return new BaseSuccess<BaseSubjectRetirementConsumerRemovalResult>(new() { Outcome = BaseSubjectRetirementMutationOutcome.Applied, PublishedGraphGeneration = checked(request.ExpectedGraphGeneration + 1), AcceptedConsumerSetChecksum = published, ExaminedBarriers = checked((int)(processor.RetirementResult?.ExaminedCount ?? 0)), ResolvedBarriers = checked((int)(processor.RetirementResult?.ChangedCount ?? 0)) }, OperationStatus.Updated, null, null, null, null);
    }

    private async ValueTask<bool> AuthorizedAsync(BaseSession session, BaseGeneratedSubjectRegistration contract, string grantId, OperationContext operation, bool write, CancellationToken token)
    {
        if (session.Principal.SubjectKind is not (AccessSubjectKind.Admin or AccessSubjectKind.System)) return false; var resource = new CollectionDefinition { Id = grantId, Name = grantId, Kind = BaseCollectionKinds.Custom, SchemaMode = SchemaMode.Strict, UnknownFields = UnknownFieldPolicy.Reject, System = true, SystemOwnerModuleId = contract.Definition.OwningModuleId }; OperationResult<BasePolicyEvaluation> result = write ? await policy.EvaluateWriteAsync(new() { Principal = session.Principal, Operation = operation, Collection = resource, ResourceKind = PolicyResourceKind.SubjectLifecycle }, token).ConfigureAwait(false) : await policy.EvaluateReadAsync(new() { Principal = session.Principal, Operation = operation, Collection = resource, ResourceKind = PolicyResourceKind.SubjectLifecycle }, token).ConfigureAwait(false); return BaseSystemCollectionGate.HasExactSubjectLifecycleGrant(result, grantId, contract.Definition.OwningModuleId, grantId, contract.Definition.Id, contract.Definition.Version, session.Principal, operation);
    }
    private async ValueTask<bool> AuthorizedSourceAsync(BaseSession session, BaseGeneratedSubjectRegistration contract, OperationContext operation, CancellationToken token)
    {
        string sourceGrant = $"{contract.Definition.Id}.retirement.purge.source"; var resource = new CollectionDefinition { Id = contract.Definition.ValidationPlan.PrivateCollectionId, Name = contract.Definition.ValidationPlan.PrivateCollectionId, Kind = BaseCollectionKinds.Custom, SchemaMode = SchemaMode.Strict, UnknownFields = UnknownFieldPolicy.Reject, System = true, SystemOwnerModuleId = contract.Definition.OwningModuleId }; OperationResult<BasePolicyEvaluation> result = await policy.EvaluateWriteAsync(new() { Principal = session.Principal, Operation = operation with { CollectionId = contract.Definition.ValidationPlan.PrivateCollectionId }, Collection = resource, ResourceKind = PolicyResourceKind.Record }, token).ConfigureAwait(false); return BaseSystemCollectionGate.HasExactModuleSourceGrant(result, sourceGrant, contract.Definition.OwningModuleId, session.Principal, operation with { CollectionId = contract.Definition.ValidationPlan.PrivateCollectionId }, contract.Definition.ValidationPlan.PrivateCollectionId);
    }
    private static BaseOwnedSubjectScopeEvidence Scope(BaseSession session, BaseGeneratedSubjectRegistration contract, OperationContext operation) => new() { Kind = contract.Definition.Scope, Value = contract.Definition.Scope switch { BaseSubjectScopeKind.Global => null, BaseSubjectScopeKind.Tenant => operation.TenantId ?? session.Principal.CurrentTenantId, BaseSubjectScopeKind.Project => operation.ProjectId, _ => null } };
    private async ValueTask<RecordMutationExecutionResult> ExecuteAsync(IBaseSubjectRetirementStore store, IAtomicMutationProcessor processor, BaseMutationRequestIdentity identity, byte[] bytes, CancellationToken token) { try { RecordMutationExecutionResult result = await InvokeProviderAsync(inner => store.ExecuteAsync(processor, new() { AcquisitionTimeout = TimeSpan.FromSeconds(5), TransactionTimeout = TimeSpan.FromSeconds(30), CommitCompletionTimeout = TimeSpan.FromSeconds(30), AtomicRequest = new() { Identity = identity, StructuralDigest = SHA256.HashData(bytes), ExpiresAt = timeProvider.GetUtcNow().AddDays(30), MaxReceiptBytes = 1_048_576 } }, inner), TimeSpan.FromSeconds(65), token).ConfigureAwait(false); if (result.Outcome == RecordMutationExecutionOutcome.Committed) await TryDispatchControlsAsync().ConfigureAwait(false); return result; } catch (TimeoutException) { return new(RecordMutationExecutionOutcome.Indeterminate, null, new BaseError { Code = BaseSubjectRetirementErrorCodes.CommitIndeterminate, Message = Message(BaseSubjectRetirementErrorCodes.CommitIndeterminate), Category = ErrorCategory.Store }); } }
    private async ValueTask TryDispatchControlsAsync(){try{await retirementControls.ReconcileAsync(CancellationToken.None).ConfigureAwait(false);}catch(Exception exception)when(exception is not OutOfMemoryException and not StackOverflowException){}}
    private static byte[] Canonical(BaseSubjectRetirementTimeoutRequest value) => Encoding.UTF8.GetBytes($"timeout\0{value.ContractId}\0{value.ContractVersion}\0{value.SubjectId.Value}\0{value.AuthorityEpoch.ToBase64Url()}\0{value.Incarnation.ToBase64Url()}\0{value.ExpectedBarrierGeneration}\0{value.ExpectedBarrierChecksum}");
    private static byte[] Canonical(BaseSubjectRetirementOverrideRequest value) => Encoding.UTF8.GetBytes($"override\0{value.ContractId}\0{value.ContractVersion}\0{value.SubjectId.Value}\0{value.AuthorityEpoch.ToBase64Url()}\0{value.Incarnation.ToBase64Url()}\0{value.ExpectedTombstoneSequence}\0{value.ExpectedBarrierGeneration}\0{value.ExpectedBarrierChecksum}\0{value.Intent}\0{value.ChangeReference}");
    private static byte[] Canonical(BaseSubjectFinalPurgeRequest value) => Encoding.UTF8.GetBytes($"purge\0{value.ContractId}\0{value.ContractVersion}\0{value.SubjectId.Value}\0{value.AuthorityEpoch.ToBase64Url()}\0{value.Incarnation.ToBase64Url()}\0{value.ExpectedTombstoneSequence}\0{value.ExpectedPrivateRevision.Value}\0{value.ExpectedBarrierGeneration}\0{value.ExpectedBarrierChecksum}");
    private static BaseResult<T> Result<T>(OperationResult<T> result) => result.IsSuccess() && result.Value is not null ? new BaseSuccess<T>(result.Value, OperationStatus.Ok, null, null, null, null) : Failure<T>(result.Status, result.Error?.Code ?? BaseSubjectRetirementErrorCodes.ProviderContractInvalid, result.Error?.Category ?? ErrorCategory.Store);
    private static BaseResult<T> Execution<T>(RecordMutationExecutionResult execution, T? value) where T : class => execution.Outcome == RecordMutationExecutionOutcome.Committed && value is not null ? new BaseSuccess<T>(value, execution.RequestDisposition == BaseMutationRequestDisposition.Duplicate ? OperationStatus.Ok : OperationStatus.Updated, null, null, null, null) : Failure<T>(execution.Outcome == RecordMutationExecutionOutcome.Indeterminate ? OperationStatus.StoreError : OperationStatus.Conflict, execution.Error?.Code ?? execution.Processing?.Error?.Code ?? BaseSubjectRetirementErrorCodes.ProviderContractInvalid, execution.Error?.Category ?? execution.Processing?.Error?.Category ?? ErrorCategory.Store);

    private bool TryDeliveryAuthority<TSubject>(BaseSession session, BaseInstalledSubjectRetirementConsumer installed, BaseSubjectLifecycleDelivery<TSubject> delivery, BaseGeneratedSubjectRegistration contract, BaseOwnedSubjectScopeEvidence scope, out BaseSubjectLifecycleTokenPayload? authority)
    {
        byte[] binding = BaseSubjectLifecycleTokenCodec.Binding(session.ApplicationId, installed.Lifecycle.Definition, installed.Lifecycle.Checksum, contract.Checksum, scope); BaseSubjectLifecycleTokenReadStatus status = _lifecycleCodec.ReadCheckpoint(delivery.Checkpoint, binding, contract.Definition.SubjectIdKind, out authority); BaseSubjectLifecycleFact fact = delivery.Fact.Fact; return status == BaseSubjectLifecycleTokenReadStatus.Valid && authority?.Boundary is { } boundary && boundary.CommitPosition == fact.CommitPosition && boundary.SubjectId.Equals(fact.SubjectId) && boundary.AuthorityEpoch.Equals(fact.AuthorityEpoch) && boundary.Incarnation.Equals(fact.Incarnation) && boundary.SubjectSequence == fact.SubjectSequence && authority.DeliveryEpoch == fact.DeliveryEpoch;
    }
    private BaseSubjectRetirementEvidencePayload Payload(BaseInstalledSubjectRetirementConsumer installed, BaseSubjectLifecycleFact fact, BaseSubjectRequiredBarrierExpectation? barrier, DateTimeOffset issued, DateTimeOffset expires, byte[] grantDigest, string contractChecksum, BaseSubjectLifecycleTokenPayload authority)
    {
        byte[] factChecksum = FactChecksum(fact); byte[] membershipChecksum = SHA256.HashData(Encoding.UTF8.GetBytes($"base.subjectRetirement.membership.v1\0{installed.Lifecycle.Checksum}\0{authority.ProjectionGeneration}\0{Convert.ToHexStringLower(factChecksum)}")); return new(installed.Definition.Participation, installed.Definition.ConsumerId, installed.Definition.ConsumerVersion, installed.Checksum, fact.ContractId, fact.ContractVersion, contractChecksum, authority.StoreInstanceId, authority.RestoreEpoch, authority.DeliveryEpoch, authority.ProjectionGeneration, authority.CheckpointGeneration, authority.Boundary ?? throw new InvalidOperationException(BaseSubjectRetirementErrorCodes.ContractInvalid), fact.SubjectId, fact.AuthorityEpoch, fact.Incarnation, fact.SubjectSequence, factChecksum, membershipChecksum, grantDigest.ToArray(), 3, tokens.ActiveKeyId, barrier, issued, expires);
    }
    private static byte[] FactChecksum(BaseSubjectLifecycleFact fact) => SHA256.HashData(Encoding.UTF8.GetBytes($"base.subjectRetirement.fact.v1\0{fact.CommitPosition.Value}\0{fact.ContractId}\0{fact.ContractVersion}\0{fact.SubjectId.Value}\0{fact.AuthorityEpoch.ToBase64Url()}\0{fact.Incarnation.ToBase64Url()}\0{fact.SubjectSequence}\0{fact.ContractStateGeneration}\0{fact.DeliveryEpoch}\0{(int)fact.Kind}\0{(int?)fact.Created?.CurrentState}\0{(int?)fact.Transitioned?.PreviousState}\0{(int?)fact.Transitioned?.CurrentState}\0{(int?)fact.Retired?.PreviousState}"));
    private static byte[] CombinedAuthorityDigest(BasePolicyEvaluationAuthority first, BasePolicyEvaluationAuthority second) { byte[] a = first.Checksum.ToArray(); byte[] b = second.Checksum.ToArray(); byte[] combined = new byte[a.Length + b.Length]; a.CopyTo(combined, 0); b.CopyTo(combined, a.Length); return SHA256.HashData(combined); }
    private static byte[] SemanticAcknowledgementDigest(ReadOnlySpan<byte> evidence, BaseSubjectAcknowledgementDisposition disposition, BaseSubjectRetirementEvidencePayload payload) { byte[] tokenDigest = SHA256.HashData(evidence); return SHA256.HashData(Encoding.UTF8.GetBytes($"base.subjectRetirement.acknowledgement.v1\0{Convert.ToHexStringLower(tokenDigest)}\0{(int)disposition}\0{payload.ConsumerId}\0{payload.ConsumerVersion}\0{payload.ContractId}\0{payload.ContractVersion}\0{payload.SubjectId.Value}\0{payload.AuthorityEpoch.ToBase64Url()}\0{payload.Incarnation.ToBase64Url()}\0{payload.ThroughSequence}\0{Convert.ToHexStringLower(payload.GrantAuthorityDigest)}")); }
    private static BaseMutationRequestIdentity Identity(BaseInstalledSubjectRetirementConsumer installed, ReadOnlySpan<byte> token) { byte[] digest = SHA256.HashData(token); return BaseMutationRequestIdentity.Create($"subject-retirement:{installed.Definition.ConsumerId}", "subjectRetirement.acknowledge", Convert.ToHexStringLower(digest), BaseMutationRequestFingerprint.Create(digest)); }
    private static bool IdentityMatches(BaseMutationRequestIdentity identity, BaseInstalledSubjectRetirementConsumer installed, ReadOnlySpan<byte> token) { BaseMutationRequestIdentity expected = Identity(installed, token); return identity == expected; }
    private static BaseOwnedSubjectScopeEvidence Scope(BaseSession session, BaseInstalledSubjectRetirementConsumer installed) { BaseGeneratedSubjectRegistration? contract = (session.Services.GetService(typeof(BaseSubjectContractRegistry)) as BaseSubjectContractRegistry)?.Find(installed.Lifecycle.Definition.ContractId, installed.Lifecycle.Definition.ContractVersion); OperationContext operation = session.Operation(BaseOperationKind.SubjectRetirementAcknowledge, installed.Definition.ConsumerId); return new() { Kind = contract?.Definition.Scope ?? throw new InvalidOperationException(BaseSubjectRetirementErrorCodes.ContractInvalid), Value = contract.Definition.Scope switch { BaseSubjectScopeKind.Global => null, BaseSubjectScopeKind.Tenant => operation.TenantId ?? session.Principal.CurrentTenantId, BaseSubjectScopeKind.Project => operation.ProjectId, _ => null } }; }
    private static bool AudienceAllows(BaseSubjectLifecycleConsumerAudience audience, PrincipalContext principal) => principal.SubjectKind == AccessSubjectKind.System || audience == BaseSubjectLifecycleConsumerAudience.Service && principal.SubjectKind == AccessSubjectKind.ServicePrincipal;
    private static bool ValidScope(BaseOwnedSubjectScopeEvidence scope)=>scope.Kind==BaseSubjectScopeKind.Global?scope.Value is null:!string.IsNullOrEmpty(scope.Value);
    internal static bool ValidateBarrierPage(BaseSubjectScopeProtector scopes, BaseSubjectRetirementBarrierPage page, BaseGeneratedSubjectRegistration contract, BaseSubjectRetirementBarrierState? state, BaseSubjectRetirementBarrierKey? after, int take, BaseOwnedSubjectScopeEvidence? exactScope)
    {
        if (page.CapturedBarrierGeneration < 0 || page.Barriers.Length > take || page.Intervals.IsDefaultOrEmpty || page.Accounting.BarrierRows != page.Barriers.Length || page.Accounting.AcknowledgementRows < 0 || page.Accounting.ResultBytes < 0 || page.Accounting.EvidenceBytes < 0 || page.Accounting.TransientBytes < checked(page.Accounting.ResultBytes + page.Accounting.EvidenceBytes) || page.Accounting.ResultBytes > 1_048_576) return false;
        BaseSubjectRetirementBarrierKey? previous = after; long bytes = 0; int acknowledgementRows = 0; long acknowledgementBytes = 0;
        foreach (BaseSubjectRetirementBarrierRow row in page.Barriers)
        {
            BaseSubjectRetirementBarrier barrier = row.Barrier; var key = new BaseSubjectRetirementBarrierKey { ScopeKind = row.Scope.Kind, ScopeIndexDigest = row.Scope.IndexDigest.ToArray(), ContractId = barrier.ContractId, ContractVersion = barrier.ContractVersion, SubjectId = barrier.SubjectId, AuthorityEpoch = barrier.AuthorityEpoch, Incarnation = barrier.Incarnation };
            if (barrier.ContractId != contract.Definition.Id || barrier.ContractVersion != contract.Definition.Version || state is not null && barrier.State != state || barrier.TombstoneSequence <= 0 || barrier.Generation <= 0 || barrier.DeadlineUtc < barrier.CreatedAtUtc || !ValidChecksum(barrier.RequiredConsumerSetChecksum) || !ValidChecksum(barrier.BarrierChecksum) || row.Scope.IndexDigest.Length != 32 || row.Scope.ProtectedCanonicalValue.Length == 0 || exactScope is not null && !scopes.Matches(row.Scope, exactScope) || previous is not null && CompareKey(previous, key) >= 0 || !CanonicalInputs(row.AcknowledgementChecksumInputs) || barrier.BarrierChecksum != BaseSubjectRetirementRegistry.BarrierChecksum(barrier, row.AcknowledgementChecksumInputs)) return false;
            previous = key; bytes = checked(bytes + RetirementBarrierBytes(barrier)); acknowledgementRows = checked(acknowledgementRows + row.AcknowledgementChecksumInputs.Length); acknowledgementBytes = checked(acknowledgementBytes + row.AcknowledgementChecksumInputs.Sum(static value => (long)Encoding.UTF8.GetByteCount(value)));
        }
        BaseSubjectRetirementBarrierKey? through = page.Barriers.IsEmpty ? after : Key(page.Barriers[^1]);
        BaseProtectedSubjectScope? protectedScope = exactScope is null ? null : scopes.Protect(exactScope);
        if (!BaseSubjectRetirementReadIntervals.Matches(page.Intervals, contract.Definition.Id, contract.Definition.Version, state, protectedScope, after, through)) return false;
        long intervalBytes = page.Intervals.Sum(static interval => checked((long)interval.LowerInclusive.Length + interval.UpperInclusive.Length)); if (page.Accounting.AcknowledgementRows != acknowledgementRows || page.Accounting.EvidenceBytes != checked(acknowledgementBytes + intervalBytes) || page.Accounting.ResultBytes != bytes || page.Next is not null && (page.Barriers.IsEmpty || CompareKey(Key(page.Barriers[^1]), page.Next) != 0)) return false;
        return true;
    }
    private bool ValidateInspection(BaseSubjectRetirementInspection value, BaseSubjectRetirementInspectionRequest request, BaseOwnedSubjectScopeEvidence scope) => ValidateInspection(_scopes, value, request, scope);
    internal static bool ValidateInspection(BaseSubjectScopeProtector scopes, BaseSubjectRetirementInspection value, BaseSubjectRetirementInspectionRequest request, BaseOwnedSubjectScopeEvidence scope)
    {
        if (!scopes.Matches(value.Scope, scope) || value.CurrentBarrier is not null && value.TerminalSummary is not null) return false;
        if (value.CurrentBarrier is { } barrier && (barrier.ContractId != request.ContractId || barrier.ContractVersion != request.ContractVersion || !barrier.SubjectId.Equals(request.SubjectId) || !barrier.AuthorityEpoch.Equals(request.AuthorityEpoch) || !barrier.Incarnation.Equals(request.Incarnation) || barrier.Generation <= 0 || !ValidChecksum(barrier.BarrierChecksum) || !CanonicalInputs(value.AcknowledgementChecksumInputs) || barrier.BarrierChecksum != BaseSubjectRetirementRegistry.BarrierChecksum(barrier, value.AcknowledgementChecksumInputs))) return false;
        if (value.TerminalSummary is { } terminal && (terminal.ContractId != request.ContractId || terminal.ContractVersion != request.ContractVersion || !terminal.SubjectId.Equals(request.SubjectId) || !terminal.AuthorityEpoch.Equals(request.AuthorityEpoch) || !terminal.Incarnation.Equals(request.Incarnation) || !request.IncludeTerminalSummary || terminal.RetiredPosition.Value <= 0 || !ValidChecksum(terminal.TerminalReceiptChecksum))) return false;
        int rows = value.CurrentBarrier is null ? 0 : 1; long bytes = value.CurrentBarrier is null ? value.TerminalSummary is null ? 0 : 256 : RetirementBarrierBytes(value.CurrentBarrier); long evidenceBytes = value.AcknowledgementChecksumInputs.Sum(static input => (long)Encoding.UTF8.GetByteCount(input)); return value.Accounting.BarrierRows == rows && value.Accounting.AcknowledgementRows == value.AcknowledgementChecksumInputs.Length && value.Accounting.ResultBytes == bytes && value.Accounting.EvidenceBytes == evidenceBytes && value.Accounting.TransientBytes >= checked(bytes + value.Accounting.EvidenceBytes) && bytes <= request.MaximumResultBytes;
    }
    private async ValueTask<T> InvokeProviderAsync<T>(Func<CancellationToken, ValueTask<T>> invoke, TimeSpan timeout, CancellationToken cancellationToken)
    {
        return await InvokeProviderAsync(invoke, timeout, cancellationToken, _providerSlots, operationalState).ConfigureAwait(false);
    }
    internal static async ValueTask<T> InvokeProviderAsync<T>(Func<CancellationToken, ValueTask<T>> invoke, TimeSpan timeout, CancellationToken cancellationToken, SemaphoreSlim slots, BaseSubjectRetirementOperationalState state)
    { if (!await slots.WaitAsync(timeout, cancellationToken).ConfigureAwait(false)) throw new TimeoutException(); using var deadline = new CancellationTokenSource(timeout); bool release = true; Task<T>? work = null; state.Enter(); try { work = invoke(deadline.Token).AsTask(); return await work.WaitAsync(timeout, cancellationToken).ConfigureAwait(false); } catch when (work is { IsCompleted: false }) { release = false; state.Quarantine(); _ = ReleaseQuarantinedAsync(work, slots, state); throw; } finally { if (release) { state.Complete(); slots.Release(); } } }
    private static async Task ReleaseQuarantinedAsync<T>(Task<T> work, SemaphoreSlim slots, BaseSubjectRetirementOperationalState state) { try { _ = await work.ConfigureAwait(false); } catch { } finally { state.ReleaseQuarantine(); slots.Release(); } }
    public async ValueTask DisposeAsync() { long started = Stopwatch.GetTimestamp(); while (operationalState.Active + operationalState.Quarantined != 0 && Stopwatch.GetElapsedTime(started) < ShutdownDrainTimeout) await Task.Delay(10).ConfigureAwait(false); if (operationalState.Active + operationalState.Quarantined == 0) _providerSlots.Dispose(); }
    public void Dispose() { if (operationalState.Active + operationalState.Quarantined == 0) _providerSlots.Dispose(); }
    private static BaseSubjectRetirementBarrierKey Key(BaseSubjectRetirementBarrierRow row) => new() { ScopeKind = row.Scope.Kind, ScopeIndexDigest = row.Scope.IndexDigest.ToArray(), ContractId = row.Barrier.ContractId, ContractVersion = row.Barrier.ContractVersion, SubjectId = row.Barrier.SubjectId, AuthorityEpoch = row.Barrier.AuthorityEpoch, Incarnation = row.Barrier.Incarnation };
    private static int CompareKey(BaseSubjectRetirementBarrierKey left, BaseSubjectRetirementBarrierKey right) => KeyBytes(left).AsSpan().SequenceCompareTo(KeyBytes(right));
    private static byte[] KeyBytes(BaseSubjectRetirementBarrierKey key) => Encoding.UTF8.GetBytes($"{(int)key.ScopeKind:D2}\0{Convert.ToHexString(key.ScopeIndexDigest)}\0{key.ContractId}\0{key.ContractVersion:D10}\0{key.SubjectId.Value}\0{key.AuthorityEpoch.ToBase64Url()}\0{key.Incarnation.ToBase64Url()}");
    private static DateTimeOffset Min(DateTimeOffset left, DateTimeOffset right) => left <= right ? left : right;
    internal static DateTimeOffset RequiredEvidenceExpiry(DateTimeOffset issued, TimeSpan maximumCheckpointLag, DateTimeOffset barrierDeadline) =>
        Min(checked(issued + maximumCheckpointLag), Min(barrierDeadline, checked(issued.AddDays(30))));
    private static bool ProtectedScopeEquals(BaseProtectedSubjectScope left, BaseProtectedSubjectScope right) => left.Kind == right.Kind && CryptographicOperations.FixedTimeEquals(left.IndexDigest, right.IndexDigest) && CryptographicOperations.FixedTimeEquals(left.ProtectedCanonicalValue, right.ProtectedCanonicalValue);
    private static bool ValidChecksum(string value) => value.Length == 64 && value.All(static c => c is >= '0' and <= '9' or >= 'a' and <= 'f');
    private static bool CanonicalInputs(ImmutableArray<string> values) { if (values.IsDefault) return false; string? previous = null; foreach (string value in values) { if (string.IsNullOrEmpty(value) || previous is not null && string.CompareOrdinal(previous, value) >= 0) return false; previous = value; } return true; }
    private static long RetirementBarrierBytes(BaseSubjectRetirementBarrier barrier) => Encoding.UTF8.GetByteCount($"{barrier.ContractId}\0{barrier.ContractVersion}\0{barrier.SubjectId.Value}\0{barrier.AuthorityEpoch.ToBase64Url()}\0{barrier.Incarnation.ToBase64Url()}\0{barrier.TombstoneSequence}\0{barrier.RequiredConsumerSetChecksum}\0{barrier.CreatedAtUtc.UtcTicks}\0{barrier.DeadlineUtc.UtcTicks}\0{(int)barrier.State}\0{barrier.Generation}\0{barrier.BarrierChecksum}");
    private static BaseFailure<T> Failure<T>(OperationStatus status, string code, ErrorCategory category) => new(status, new BaseError { Code = code, Message = Message(code), Category = category }, null, null);
    private static string Message(string code) => code switch { BaseSubjectRetirementErrorCodes.ContractInvalid => "The subject retirement contract is invalid.", BaseSubjectRetirementErrorCodes.RegistrationConflict => "The subject retirement registration conflicts with the installed graph.", BaseSubjectRetirementErrorCodes.Unauthorized => "The subject retirement operation is not authorized.", BaseSubjectRetirementErrorCodes.ScopeAuthorityInvalid => "The subject retirement scope authority is invalid.", BaseSubjectRetirementErrorCodes.AcknowledgementConflict => "The subject retirement acknowledgement conflicts with current state.", BaseSubjectRetirementErrorCodes.SequenceInvalid => "The subject retirement sequence is invalid.", BaseSubjectRetirementErrorCodes.BarrierPending => "The subject retirement barrier is pending.", BaseSubjectRetirementErrorCodes.BarrierSatisfied => "The subject retirement barrier is already satisfied.", BaseSubjectRetirementErrorCodes.BarrierTimedOut => "The subject retirement barrier has timed out.", BaseSubjectRetirementErrorCodes.BarrierQuarantined => "The subject retirement barrier is quarantined.", BaseSubjectRetirementErrorCodes.OverrideConflict => "The subject retirement override conflicts with current state.", BaseSubjectRetirementErrorCodes.PurgeConflict => "The subject cannot be purged from its current retirement state.", BaseSubjectRetirementErrorCodes.RetentionPending => "The minimum subject retention period has not elapsed.", BaseSubjectRetirementErrorCodes.ConsumerRemovalPending => "Subject retirement consumer removal is still pending.", BaseSubjectRetirementErrorCodes.ProviderContractInvalid => "The provider cannot satisfy the subject retirement contract.", BaseSubjectRetirementErrorCodes.CapacityExceeded => "Subject retirement capacity is unavailable.", BaseSubjectRetirementErrorCodes.Timeout => "The subject retirement operation timed out.", BaseSubjectRetirementErrorCodes.CommitIndeterminate => "The subject retirement commit outcome is indeterminate.", BaseSubjectRetirementErrorCodes.MaintenanceRequired => "Subject retirement maintenance must complete before this operation.", _ => "The subject retirement operation failed." };
}
