<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><IsTestProject>false</IsTestProject><OutputType>Exe</OutputType><NoWarn>$(NoWarn);CA1515</NoWarn></PropertyGroup>
  <ItemGroup><ProjectReference Include="../../src/HPD.Payments.Extensions.OutOfProcess/HPD.Payments.Extensions.OutOfProcess.csproj" /></ItemGroup>
</Project>
