using System.Security.Cryptography;
using System.Buffers.Binary;
using System.Text;
using HPD.Agent.Audio.Authority;
using HPD.Agent.Authority;

namespace HPD.Agent.LiveAudio.Contracts.Tests.Authority;

public sealed class GlobalParticipantAllocatorFoldV1Tests
{
    [Fact] public void EmptyCompletesIdempotentlyAndQueriesNone()
    {var a=GlobalParticipantAllocatorFoldV1.Create(Journal());Assert.Throws<InvalidOperationException>(()=>a.Query(Participant(7)));var first=Assert.IsType<GlobalParticipantAllocatorFoldResultV1.Current>(a.Complete());Assert.Same(first,a.Complete());var p=a.Query(Participant(7));Assert.Equal((ushort)1,p.State);Assert.Null(p.Owner);Assert.Equal(0UL,p.RecordCount);Assert.Throws<InvalidOperationException>(()=>a.Apply(new byte[]{1}));}

    [Fact] public void InvalidIsTerminalAndDuplicateFactNeverRetries()
    {var a=GlobalParticipantAllocatorFoldV1.Create(Journal());var bad=Assert.IsType<GlobalParticipantAllocatorFoldApplyResultV1.InvalidHistory>(a.Apply(ReadOnlyMemory<byte>.Empty));Assert.Equal("record-size-invalid",bad.SafeCode.ToString());Assert.Same(bad,a.Apply(new byte[]{1}));var complete=Assert.IsType<GlobalParticipantAllocatorFoldResultV1.InvalidHistory>(a.Complete());Assert.Equal(bad.SafeCode,complete.SafeCode);Assert.Same(complete,a.Complete());Assert.Throws<InvalidOperationException>(()=>a.Query(Participant(1)));}

    [Theory][InlineData(0,"record-size-invalid")][InlineData(8193,"record-size-invalid")][InlineData(1,"record-wire-invalid")] public void RecordBoundaryAndWireCodeMatrix(int length,string code)
    {var bytes=new byte[length];if(length==1)bytes[0]=0xff;var result=Assert.IsType<GlobalParticipantAllocatorFoldApplyResultV1.InvalidHistory>(GlobalParticipantAllocatorFoldV1.Create(Journal()).Apply(bytes));Assert.Equal(code,result.SafeCode.ToString());}

    [Fact] public void CanonicalWrongJournalReachesJournalMismatch()
    {Assert.True(GlobalParticipantAllocatorCodecsV1.TryDecodeOuter(AppliedRecord(),out var outer));Assert.True(GlobalParticipantAllocatorCodecsV1.TryDecodeBody(outer!.BodyBytes.ToArray(),out var body));var x=body!;var other=GlobalParticipantAllocatorJournalId.FromValue(Id(6));var changed=new GlobalParticipantClaimRecordBodyV1(x.OperationId,x.Source,x.ParticipantId,null,x.OwnerProof,x.Outcome,new GlobalParticipantAuthorityPositionV1(other,1),x.ObservedAt);var bytes=GlobalParticipantAllocatorCodecsV1.Encode(new GlobalParticipantClaimRecordV1(outer.SourceSession,outer.SourceExpectedAuthority,GlobalParticipantAllocatorCodecsV1.Encode(changed)));Assert.Equal("journal-mismatch",Assert.IsType<GlobalParticipantAllocatorFoldApplyResultV1.InvalidHistory>(GlobalParticipantAllocatorFoldV1.Create(Journal()).Apply(bytes)).SafeCode.ToString());}

    [Fact] public void SourcePositionWithDifferentRuntimeStampReachesSourceIdentityInvalid()
    {Assert.True(GlobalParticipantAllocatorCodecsV1.TryDecodeOuter(AppliedRecord(),out var outer));Assert.True(GlobalParticipantAllocatorCodecsV1.TryDecodeBody(outer!.BodyBytes.ToArray(),out var body));var x=body!;var otherStamp=new SessionAuthorityStampV1(RuntimeGenerationId.FromValue(Id(7)),outer!.SourceSession.LiveSessionId);var source=new GlobalParticipantAllocationSourceV1(outer.SourceSession.LiveSessionId,new JournalPositionV1(otherStamp,1),x.Source.SourceOuterIntegrityHash,x.Source.SourceBodyHash);var participant=GlobalParticipantAllocatorFactIdsV1.Participant(outer.SourceSession.LiveSessionId,x.OperationId,GlobalParticipantAllocatorFactIdsV1.SourceFingerprint(source));var proof=new ParticipantIdOwnerProofV1(participant,null,1,null,GlobalParticipantAllocatorCodecsV1.EmptyIndexRoot(),GlobalParticipantAllocatorCodecsV1.CreateEmptyProofPath(),0);var changed=new GlobalParticipantClaimRecordBodyV1(x.OperationId,source,participant,null,proof,x.Outcome,x.AssignedPosition,x.ObservedAt);var bytes=GlobalParticipantAllocatorCodecsV1.Encode(new GlobalParticipantClaimRecordV1(outer.SourceSession,outer.SourceExpectedAuthority,GlobalParticipantAllocatorCodecsV1.Encode(changed)));Assert.Equal("source-identity-invalid",Assert.IsType<GlobalParticipantAllocatorFoldApplyResultV1.InvalidHistory>(GlobalParticipantAllocatorFoldV1.Create(Journal()).Apply(bytes)).SafeCode.ToString());}

    [Fact] public void CanonicalSecondRecordWithWrongPriorHeadReachesPriorHeadMismatch()
    {var (first,second)=AppliedRecords2();Assert.True(GlobalParticipantAllocatorCodecsV1.TryDecodeOuter(second,out var outer));Assert.True(GlobalParticipantAllocatorCodecsV1.TryDecodeBody(outer!.BodyBytes.ToArray(),out var body));var x=body!;var fake=new GlobalParticipantAuthorityHeadV1(new GlobalParticipantAuthorityPositionV1(Journal(),1),Hash("fake-head"));var proof=new ParticipantIdOwnerProofV1(x.ParticipantId,fake,x.OwnerProof.State,x.OwnerProof.Owner,x.OwnerProof.IndexRoot,x.OwnerProof.ProofPathBytes,x.OwnerProof.RecordCount);var changed=new GlobalParticipantClaimRecordBodyV1(x.OperationId,x.Source,x.ParticipantId,fake,proof,x.Outcome,x.AssignedPosition,x.ObservedAt);var bytes=GlobalParticipantAllocatorCodecsV1.Encode(new GlobalParticipantClaimRecordV1(outer.SourceSession,outer.SourceExpectedAuthority,GlobalParticipantAllocatorCodecsV1.Encode(changed)));var fold=GlobalParticipantAllocatorFoldV1.Create(Journal());fold.Apply(first);Assert.Equal("prior-head-mismatch",Assert.IsType<GlobalParticipantAllocatorFoldApplyResultV1.InvalidHistory>(fold.Apply(bytes)).SafeCode.ToString());}

    [Fact] public void CryptographicallyValidButStaleRootReachesProofPinMismatch()
    {var (first,second)=AppliedRecords2();Assert.True(GlobalParticipantAllocatorCodecsV1.TryDecodeOuter(second,out var outer));Assert.True(GlobalParticipantAllocatorCodecsV1.TryDecodeBody(outer!.BodyBytes.ToArray(),out var body));var x=body!;var path=x.OwnerProof.ProofPathBytes.ToArray();path[0]^=1;var root=ProofRoot(x.ParticipantId,path);var proof=new ParticipantIdOwnerProofV1(x.ParticipantId,x.PriorHead,1,null,root,path,x.OwnerProof.RecordCount);var changed=new GlobalParticipantClaimRecordBodyV1(x.OperationId,x.Source,x.ParticipantId,x.PriorHead,proof,x.Outcome,x.AssignedPosition,x.ObservedAt);var bytes=GlobalParticipantAllocatorCodecsV1.Encode(new GlobalParticipantClaimRecordV1(outer.SourceSession,outer.SourceExpectedAuthority,GlobalParticipantAllocatorCodecsV1.Encode(changed)));var fold=GlobalParticipantAllocatorFoldV1.Create(Journal());fold.Apply(first);Assert.Equal("proof-pin-mismatch",Assert.IsType<GlobalParticipantAllocatorFoldApplyResultV1.InvalidHistory>(fold.Apply(bytes)).SafeCode.ToString());}

    private static Hash256 ProofRoot(ParticipantId participant,byte[] path)
    {var current=SHA256.HashData(Encoding.UTF8.GetBytes("hpd-s1-global-participant-absent-leaf-v1\0"));var domain=Encoding.UTF8.GetBytes("hpd-s1-global-participant-owner-node-v1\0");Span<byte> id=stackalloc byte[16];participant.TryWriteBytes(id);for(var d=1;d<=128;d++){var p=new byte[domain.Length+65];domain.CopyTo(p,0);p[domain.Length]=(byte)d;var sibling=path.AsSpan((d-1)*32,32);var bit=(id[15-(d-1)/8]>>((d-1)%8))&1;if(bit==0){current.CopyTo(p,domain.Length+1);sibling.CopyTo(p.AsSpan(domain.Length+33));}else{sibling.CopyTo(p.AsSpan(domain.Length+1));current.CopyTo(p,domain.Length+33);}current=SHA256.HashData(p);}return Hash256.FromBytes(current);}

    [Fact] public void FixedNoneAndOwnerVectorsMatchManifest()
    {Assert.Equal("EACFAB8ECA64B25AC744987B7DBB9238323F2E28CB242D4A7971ED1F0B84B83C",Hex(GlobalParticipantAllocatorCodecsV1.EmptyIndexRoot()));Assert.Equal("4CD62B39BFF57A797406C17D3442ADDE19127B3D05605EC4C0329666EBAD86C3",Convert.ToHexString(SHA256.HashData(GlobalParticipantAllocatorCodecsV1.CreateEmptyProofPath())));var evidence=Convert.FromHexString("a50150000102030405060708090a0b0c0d0e0f0250101112131415161718191a1b1c1d1e1f0350202122232425262728292a2b2c2d2e2f045820303030303030303030303030303030303030303030303030303030303030303005a201a20150404142434445464748494a4b4c4d4e4f02010258205050505050505050505050505050505050505050505050505050505050505050");Assert.Equal("D27CEFDEA71D5493AAEADC212355C5DEC1B4F497B15F052DCEDD136B8F29B2DE",Convert.ToHexString(SHA256.HashData(evidence)));Assert.True(GlobalParticipantAllocatorCodecsV1.TryDecodeEvidence(evidence,out var owner));var path=Enumerable.Range(1,128).SelectMany(d=>SHA256.HashData(Encoding.UTF8.GetBytes("hpd-d0027b-owner-proof-sibling-v1\0").Concat(new[]{(byte)d}).ToArray())).ToArray();Assert.Equal("471CFA3D8E270D75DEC71EF4595EEE9B50BB4A39707E4F0301879D123DEB8121",Convert.ToHexString(SHA256.HashData(path)));var participant=ParticipantId.FromValue(StableId128.FromBytes(Convert.FromHexString("000102030405060708090A0B0C0D0E0F")));Assert.True(GlobalParticipantAllocatorCodecsV1.VerifyProof(participant,2,owner,Hash256.FromBytes(Convert.FromHexString("12855A906373E53BA6F75910B09E12351E616DA9970D07A8B7762B1CB21E6491")),path));}

    [Fact] public void PureTransitionEvaluatorCoversAppliedConflictAndRejectedWithoutAuthority()
    {var position=new GlobalParticipantAuthorityPositionV1(Journal(),1);var owner=new ParticipantIdOwnerEvidenceV1(Participant(4),LiveSessionId.FromValue(Id(2)),OperationId.FromValue(Id(3)),Hash("fingerprint"),new GlobalParticipantAuthorityHeadV1(position,Hash("record")));var applied=GlobalParticipantAllocatorFoldV1.EvaluateTransition(null,new ParticipantIdClaimOutcomeV1(1,null,null));Assert.True(applied.Valid&&applied.InsertOwnerAfterHash&&!applied.OwnershipUnchanged);var conflict=GlobalParticipantAllocatorFoldV1.EvaluateTransition(owner,new ParticipantIdClaimOutcomeV1(2,position,new BoundedAscii("participant-id-owned")));Assert.True(conflict.Valid&&!conflict.InsertOwnerAfterHash&&conflict.OwnershipUnchanged);var rejected=GlobalParticipantAllocatorFoldV1.EvaluateTransition(null,new ParticipantIdClaimOutcomeV1(3,null,new BoundedAscii("invalid-body")));Assert.True(rejected.Valid&&rejected.OwnershipUnchanged);Assert.False(GlobalParticipantAllocatorFoldV1.EvaluateTransition(owner,new ParticipantIdClaimOutcomeV1(1,null,null)).Valid);}

    [Fact] public void AppliedUpdatesRootIn128StepsAndCompletedQueriesAreStable()
    {var bytes=AppliedRecord();var caller=bytes.ToArray();var a=GlobalParticipantAllocatorFoldV1.Create(Journal());var accepted=Assert.IsType<GlobalParticipantAllocatorFoldApplyResultV1.Accepted>(a.Apply(caller));caller[0]^=0xff;var current=Assert.IsType<GlobalParticipantAllocatorFoldResultV1.Current>(a.Complete());Assert.Equal(accepted.Head,current.Snapshot.Head);Assert.NotEqual(GlobalParticipantAllocatorCodecsV1.EmptyIndexRoot(),current.Snapshot.IndexRoot);var owner=a.Query(ParticipantForRecord());Assert.Equal((ushort)2,owner.State);Assert.NotNull(owner.Owner);Assert.Equal(current.Snapshot.IndexRoot,owner.IndexRoot);var absent=a.Query(Participant(99));Assert.Equal((ushort)1,absent.State);Assert.True(GlobalParticipantAllocatorCodecsV1.VerifyProof(absent.ParticipantId,absent.State,null,absent.IndexRoot,absent.ProofPathBytes));}

    [Fact] public void ValidRejectedRecordAdvancesHeadAndLeavesOwnershipRootUnchanged()
    {var (first,second)=AppliedRecords2();Assert.True(GlobalParticipantAllocatorCodecsV1.TryDecodeOuter(second,out var outer));Assert.True(GlobalParticipantAllocatorCodecsV1.TryDecodeBody(outer!.BodyBytes.ToArray(),out var body));var x=body!;var rejected=new GlobalParticipantClaimRecordBodyV1(x.OperationId,x.Source,x.ParticipantId,x.PriorHead,x.OwnerProof,new ParticipantIdClaimOutcomeV1(3,null,new BoundedAscii("invalid-body")),x.AssignedPosition,x.ObservedAt);var bytes=GlobalParticipantAllocatorCodecsV1.Encode(new GlobalParticipantClaimRecordV1(outer.SourceSession,outer.SourceExpectedAuthority,GlobalParticipantAllocatorCodecsV1.Encode(rejected)));var fold=GlobalParticipantAllocatorFoldV1.Create(Journal());var a=Assert.IsType<GlobalParticipantAllocatorFoldApplyResultV1.Accepted>(fold.Apply(first));var b=Assert.IsType<GlobalParticipantAllocatorFoldApplyResultV1.Accepted>(fold.Apply(bytes));var final=Assert.IsType<GlobalParticipantAllocatorFoldResultV1.Current>(fold.Complete()).Snapshot;var baseline=GlobalParticipantAllocatorFoldV1.Create(Journal());baseline.Apply(first);var root=Assert.IsType<GlobalParticipantAllocatorFoldResultV1.Current>(baseline.Complete()).Snapshot.IndexRoot;Assert.Equal(root,final.IndexRoot);Assert.NotEqual(a.Head,b.Head);}

    [Fact] public void DecodedConflictAgainstEmptyOwnershipReachesOutcomeInvalid()
    {Assert.True(GlobalParticipantAllocatorCodecsV1.TryDecodeOuter(AppliedRecord(),out var outer));Assert.True(GlobalParticipantAllocatorCodecsV1.TryDecodeBody(outer!.BodyBytes.ToArray(),out var body));var x=body!;var conflict=new ParticipantIdClaimOutcomeV1(2,new GlobalParticipantAuthorityPositionV1(Journal(),1),new BoundedAscii("participant-id-owned"));var changed=new GlobalParticipantClaimRecordBodyV1(x.OperationId,x.Source,x.ParticipantId,null,x.OwnerProof,conflict,x.AssignedPosition,x.ObservedAt);var bytes=GlobalParticipantAllocatorCodecsV1.Encode(new GlobalParticipantClaimRecordV1(outer.SourceSession,outer.SourceExpectedAuthority,GlobalParticipantAllocatorCodecsV1.Encode(changed)));Assert.Equal("outcome-invalid",Assert.IsType<GlobalParticipantAllocatorFoldApplyResultV1.InvalidHistory>(GlobalParticipantAllocatorFoldV1.Create(Journal()).Apply(bytes)).SafeCode.ToString());}

    [Theory][InlineData(false,"sequence-invalid")][InlineData(true,"fact-id-duplicate")] public void ReplayAndChangedCanonicalDuplicateRespectValidationPrecedence(bool validNext,string expected)
    {var first=AppliedRecord();var duplicate=first;if(validNext){var one=GlobalParticipantAllocatorFoldV1.Create(Journal());one.Apply(first);var snap=Assert.IsType<GlobalParticipantAllocatorFoldResultV1.Current>(one.Complete()).Snapshot;Assert.True(GlobalParticipantAllocatorCodecsV1.TryDecodeOuter(first,out var outer));Assert.True(GlobalParticipantAllocatorCodecsV1.TryDecodeBody(outer!.BodyBytes.ToArray(),out var original));var x=original!;var q=snap.Query(x.ParticipantId);var proof=new ParticipantIdOwnerProofV1(x.ParticipantId,snap.Head,q.State,q.Owner,q.IndexRoot,q.ProofPathBytes,q.RecordCount);var body=new GlobalParticipantClaimRecordBodyV1(x.OperationId,x.Source,x.ParticipantId,snap.Head,proof,new ParticipantIdClaimOutcomeV1(2,x.AssignedPosition,new BoundedAscii("participant-id-owned")),new GlobalParticipantAuthorityPositionV1(Journal(),2),new MonotonicStampV1(x.ObservedAt.ClockDomainId,x.ObservedAt.BootId,12));duplicate=GlobalParticipantAllocatorCodecsV1.Encode(new GlobalParticipantClaimRecordV1(outer.SourceSession,outer.SourceExpectedAuthority,GlobalParticipantAllocatorCodecsV1.Encode(body)));}var fold=GlobalParticipantAllocatorFoldV1.Create(Journal());fold.Apply(first);Assert.Equal(expected,Assert.IsType<GlobalParticipantAllocatorFoldApplyResultV1.InvalidHistory>(fold.Apply(duplicate)).SafeCode.ToString());}

    [Fact] public void MaximumOwnerSealUsesBoundedCompactStorageAndNeverRebuildsOnQuery()
    {var owners=new Dictionary<ParticipantId,ParticipantIdOwnerEvidenceV1>(65536);var head=new GlobalParticipantAuthorityHeadV1(new GlobalParticipantAuthorityPositionV1(Journal(),1),Hash("record"));for(var i=0;i<65536;i++){var p=ParticipantFromInt(i);owners.Add(p,new ParticipantIdOwnerEvidenceV1(p,LiveSessionId.FromValue(Id(2)),OperationId.FromValue(Id(3)),Hash("fingerprint"),head));}var root=IndependentRoot(owners);var snapshot=new GlobalParticipantAllocatorCompletedFoldV1(Journal(),head,root,1,1,owners);Assert.Equal(65536,snapshot.RetainedOwnerCount);Assert.InRange(snapshot.RetainedStructuralNodeCount,65536,131071);Assert.Equal(1,snapshot.SealBuildCount);Assert.Equal(0,snapshot.QueryBuildCount);Assert.Equal(checked(256L+snapshot.RetainedStructuralNodeCount*64L+snapshot.RetainedOwnerCount*96L+snapshot.RetainedCanonicalEvidenceBytes),snapshot.ConservativeRetainedStorageUpperBoundBytes);Assert.True(snapshot.ConservativeRetainedStorageUpperBoundBytes<=81789120);for(var i=0;i<4;i++)Assert.Equal((ushort)2,snapshot.Query(ParticipantFromInt(i*21845)).State);Assert.Equal((ushort)1,snapshot.Query(ParticipantFromInt(70000)).State);Assert.Equal(0,snapshot.QueryBuildCount);}

    [Fact] public void PositionAndFoldAccept65536WhilePositionRejects65537()
    {Assert.Equal(65536UL,new GlobalParticipantAuthorityPositionV1(Journal(),65536UL).Sequence);Assert.Throws<ArgumentException>(()=>new GlobalParticipantAuthorityPositionV1(Journal(),65537UL));var fold=GlobalParticipantAllocatorFoldV1.Create(Journal());GlobalParticipantAuthorityHeadV1? head=null;for(ulong sequence=1;sequence<=65536;sequence++)head=Assert.IsType<GlobalParticipantAllocatorFoldApplyResultV1.Accepted>(fold.Apply(RejectedRecord(sequence,head))).Head;Assert.Equal(65536UL,Assert.IsType<GlobalParticipantAllocatorFoldResultV1.Current>(fold.Complete()).Snapshot.RecordCount);}

    private static byte[] RejectedRecord(ulong sequence,GlobalParticipantAuthorityHeadV1? head)
    {var session=new SessionAuthorityStampV1(RuntimeGenerationId.FromValue(Id(1)),LiveSessionId.FromValue(Id(2)));Span<byte> raw=stackalloc byte[16];BinaryPrimitives.WriteUInt64BigEndian(raw[8..],sequence);var operation=OperationId.FromValue(StableId128.FromBytes(raw));var source=new GlobalParticipantAllocationSourceV1(session.LiveSessionId,new JournalPositionV1(session,checked((long)sequence)),Hash("outer"),Hash("body"));var participant=GlobalParticipantAllocatorFactIdsV1.Participant(session.LiveSessionId,operation,GlobalParticipantAllocatorFactIdsV1.SourceFingerprint(source));var proof=new ParticipantIdOwnerProofV1(participant,head,1,null,GlobalParticipantAllocatorCodecsV1.EmptyIndexRoot(),GlobalParticipantAllocatorCodecsV1.CreateEmptyProofPath(),sequence-1);var body=new GlobalParticipantClaimRecordBodyV1(operation,source,participant,head,proof,new ParticipantIdClaimOutcomeV1(3,null,new BoundedAscii("invalid-body")),new GlobalParticipantAuthorityPositionV1(Journal(),sequence),new MonotonicStampV1(ClockDomainId.FromValue(Id(8)),BootId.FromValue(Id(9)),sequence));return GlobalParticipantAllocatorCodecsV1.Encode(new GlobalParticipantClaimRecordV1(session,ExpectedAuthorityVectorV1.Create(session,[]),GlobalParticipantAllocatorCodecsV1.Encode(body)));}


    private static Hash256 IndependentRoot(IReadOnlyDictionary<ParticipantId,ParticipantIdOwnerEvidenceV1> owners)
    {var absent=SHA256.HashData(Encoding.UTF8.GetBytes("hpd-s1-global-participant-absent-leaf-v1\0"));var node=Encoding.UTF8.GetBytes("hpd-s1-global-participant-owner-node-v1\0");var ownerDomain=Encoding.UTF8.GetBytes("hpd-s1-global-participant-owner-leaf-v1\0");var defaults=new byte[129][];defaults[0]=absent;byte[] H(int depth,byte[] l,byte[] r){var p=new byte[node.Length+65];node.CopyTo(p,0);p[node.Length]=(byte)depth;l.CopyTo(p,node.Length+1);r.CopyTo(p,node.Length+33);return SHA256.HashData(p);}for(var d=1;d<=128;d++)defaults[d]=H(d,defaults[d-1],defaults[d-1]);var leaves=owners.Select(x=>{Span<byte>b=stackalloc byte[16];x.Key.TryWriteBytes(b);var e=GlobalParticipantAllocatorCodecsV1.Encode(x.Value);var p=new byte[ownerDomain.Length+16+e.Length];ownerDomain.CopyTo(p,0);b.CopyTo(p.AsSpan(ownerDomain.Length));e.CopyTo(p,ownerDomain.Length+16);return(Key:BinaryPrimitives.ReadUInt128BigEndian(b),Hash:SHA256.HashData(p));}).OrderBy(x=>x.Key).ToArray();byte[] Lift(byte[] h,int from,int to,UInt128 key){for(var d=from+1;d<=to;d++)h=((key>>(d-1))&1)==0?H(d,h,defaults[d-1]):H(d,defaults[d-1],h);return h;}(byte[] Hash,int Bit,UInt128 Key) Build(int start,int count,int bit){if(count==1)return(leaves[start].Hash,-1,leaves[start].Key);var d=bit;while(d>=0&&(((leaves[start].Key>>d)&1)==((leaves[start+count-1].Key>>d)&1)))d--;var split=start;while(split<start+count&&((leaves[split].Key>>d)&1)==0)split++;var l=Build(start,split-start,d-1);var r=Build(split,start+count-split,d-1);return(H(d+1,Lift(l.Hash,l.Bit<0?0:l.Bit+1,d,l.Key),Lift(r.Hash,r.Bit<0?0:r.Bit+1,d,r.Key)),d,l.Key);}var root=Build(0,leaves.Length,127);return Hash256.FromBytes(Lift(root.Hash,root.Bit+1,128,root.Key));}
    private static ParticipantId ParticipantFromInt(int value){Span<byte>b=stackalloc byte[16];BinaryPrimitives.WriteUInt64BigEndian(b[8..],(ulong)value+1);return ParticipantId.FromValue(StableId128.FromBytes(b));}

    internal static byte[] AppliedRecord()
    {var session=new SessionAuthorityStampV1(RuntimeGenerationId.FromValue(Id(1)),LiveSessionId.FromValue(Id(2)));var vector=ExpectedAuthorityVectorV1.Create(session,[]);var source=new GlobalParticipantAllocationSourceV1(session.LiveSessionId,new JournalPositionV1(session,1),Hash("outer"),Hash("body"));var operation=OperationId.FromValue(Id(3));var fp=GlobalParticipantAllocatorFactIdsV1.SourceFingerprint(source);var participant=GlobalParticipantAllocatorFactIdsV1.Participant(session.LiveSessionId,operation,fp);var proof=new ParticipantIdOwnerProofV1(participant,null,1,null,GlobalParticipantAllocatorCodecsV1.EmptyIndexRoot(),GlobalParticipantAllocatorCodecsV1.CreateEmptyProofPath(),0);var body=new GlobalParticipantClaimRecordBodyV1(operation,source,participant,null,proof,new ParticipantIdClaimOutcomeV1(1,null,null),new GlobalParticipantAuthorityPositionV1(Journal(),1),new MonotonicStampV1(ClockDomainId.FromValue(Id(8)),BootId.FromValue(Id(9)),10));return GlobalParticipantAllocatorCodecsV1.Encode(new GlobalParticipantClaimRecordV1(session,vector,GlobalParticipantAllocatorCodecsV1.Encode(body)));}
    internal static ParticipantId ParticipantForRecord(){var session=new SessionAuthorityStampV1(RuntimeGenerationId.FromValue(Id(1)),LiveSessionId.FromValue(Id(2)));var source=new GlobalParticipantAllocationSourceV1(session.LiveSessionId,new JournalPositionV1(session,1),Hash("outer"),Hash("body"));return GlobalParticipantAllocatorFactIdsV1.Participant(session.LiveSessionId,OperationId.FromValue(Id(3)),GlobalParticipantAllocatorFactIdsV1.SourceFingerprint(source));}
    internal static (byte[] First,byte[] Second) AppliedRecords2()
    {var first=AppliedRecord();var f=GlobalParticipantAllocatorFoldV1.Create(Journal());Assert.IsType<GlobalParticipantAllocatorFoldApplyResultV1.Accepted>(f.Apply(first));var s=Assert.IsType<GlobalParticipantAllocatorFoldResultV1.Current>(f.Complete()).Snapshot;var session=new SessionAuthorityStampV1(RuntimeGenerationId.FromValue(Id(1)),LiveSessionId.FromValue(Id(2)));var vector=ExpectedAuthorityVectorV1.Create(session,[]);var source=new GlobalParticipantAllocationSourceV1(session.LiveSessionId,new JournalPositionV1(session,2),Hash("outer2"),Hash("body2"));var operation=OperationId.FromValue(Id(4));var participant=GlobalParticipantAllocatorFactIdsV1.Participant(session.LiveSessionId,operation,GlobalParticipantAllocatorFactIdsV1.SourceFingerprint(source));var q=s.Query(participant);var proof=new ParticipantIdOwnerProofV1(participant,s.Head,q.State,q.Owner,q.IndexRoot,q.ProofPathBytes,q.RecordCount);var body=new GlobalParticipantClaimRecordBodyV1(operation,source,participant,s.Head,proof,new ParticipantIdClaimOutcomeV1(1,null,null),new GlobalParticipantAuthorityPositionV1(Journal(),2),new MonotonicStampV1(ClockDomainId.FromValue(Id(8)),BootId.FromValue(Id(9)),11));return(first,GlobalParticipantAllocatorCodecsV1.Encode(new GlobalParticipantClaimRecordV1(session,vector,GlobalParticipantAllocatorCodecsV1.Encode(body))));}

    private static GlobalParticipantAllocatorJournalId Journal()=>GlobalParticipantAllocatorJournalId.FromValue(Id(5));
    private static ParticipantId Participant(byte n)=>ParticipantId.FromValue(Id(n));
    private static StableId128 Id(byte n)=>StableId128.FromBytes(Enumerable.Repeat(n,16).ToArray());
    private static string Hex(Hash256 hash){Span<byte>b=stackalloc byte[32];hash.TryWriteBytes(b);return Convert.ToHexString(b);}
    private static Hash256 Hash(string value)=>Hash256.FromBytes(SHA256.HashData(System.Text.Encoding.UTF8.GetBytes(value)));
}
