using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace HPD.Payments.Generators;

/// <summary>Mechanically projects explicitly reviewed HPD.Payments declarations into stable source tables.</summary>
/// <remarks>The generator copies declaration fields verbatim after syntactic validation. It does not infer capability or product semantics.</remarks>
[Generator(LanguageNames.CSharp)]
public sealed class ReviewedDeclarationGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor Malformed = new(
        "HPDPG001", "Malformed reviewed declaration",
        "Declaration '{0}' must contain projection|name|value", "HPD.Payments.Generation",
        DiagnosticSeverity.Error, isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor UnknownProjection = new(
        "HPDPG002", "Unknown projection",
        "Projection '{0}' is not a permitted mechanical projection", "HPD.Payments.Generation",
        DiagnosticSeverity.Error, isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor Duplicate = new(
        "HPDPG003", "Duplicate reviewed declaration",
        "Declaration key '{0}' occurs more than once", "HPD.Payments.Generation",
        DiagnosticSeverity.Error, isEnabledByDefault: true);

    private static readonly ImmutableHashSet<string> Permitted = ImmutableHashSet.Create(
        StringComparer.Ordinal, "serializer", "table", "visitor", "factory", "dependency",
        "compatibility", "oracle", "connector", "testvector");

    /// <summary>Registers the reviewed-declaration pipeline.</summary>
    /// <param name="context">The compiler-owned incremental initialization context.</param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var declarations = context.AdditionalTextsProvider
            .Where(static file => file.Path.EndsWith(".hpdpayments", StringComparison.Ordinal))
            .Select(static (file, cancellationToken) => new DeclarationFile(
                file.Path, file.GetText(cancellationToken)?.ToString() ?? string.Empty));

        context.RegisterSourceOutput(declarations, static (production, file) => Emit(production, file));
    }

    private static void Emit(SourceProductionContext context, DeclarationFile file)
    {
        var items = new List<Declaration>();
        var keys = new HashSet<string>(StringComparer.Ordinal);
        foreach (var raw in file.Content.Split('\n'))
        {
            var line = raw.TrimEnd('\r').Trim();
            if (line.Length == 0 || line.StartsWith('#')) continue;
            var fields = line.Split('|');
            if (fields.Length != 3 || fields.Any(static field => string.IsNullOrWhiteSpace(field)))
            {
                context.ReportDiagnostic(Diagnostic.Create(Malformed, Location.None, line));
                continue;
            }

            var projection = fields[0].Trim();
            var name = fields[1].Trim();
            var value = fields[2].Trim();
            if (!Permitted.Contains(projection))
            {
                context.ReportDiagnostic(Diagnostic.Create(UnknownProjection, Location.None, projection));
                continue;
            }

            var key = projection + "|" + name;
            if (!keys.Add(key))
            {
                context.ReportDiagnostic(Diagnostic.Create(Duplicate, Location.None, key));
                continue;
            }

            items.Add(new Declaration(projection, name, value));
        }

        items.Sort(static (left, right) =>
        {
            var kind = StringComparer.Ordinal.Compare(left.Projection, right.Projection);
            return kind != 0 ? kind : StringComparer.Ordinal.Compare(left.Name, right.Name);
        });

        var source = new StringBuilder("// <auto-generated/>\n#nullable enable\nnamespace HPD.Payments.Generated;\n\n")
            .AppendLine("/// <summary>Stable mechanical projection of explicitly reviewed declarations.</summary>")
            .AppendLine("internal static class ReviewedDeclarations")
            .AppendLine("{")
            .AppendLine("    private static readonly string[] Values =")
            .AppendLine("    [");
        foreach (var item in items)
        {
            source.Append("        \"").Append(Escape(item.Projection)).Append('|')
                .Append(Escape(item.Name)).Append('|').Append(Escape(item.Value)).AppendLine("\",");
        }

        source.AppendLine("    ];")
            .AppendLine()
            .AppendLine("    /// <summary>Gets the reviewed declarations in ordinal projection/name order.</summary>")
            .AppendLine("    internal static global::System.ReadOnlySpan<string> Items => Values;")
            .AppendLine("}");
        context.AddSource("HPD.Payments.ReviewedDeclarations.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
    }

    private static string Escape(string value) => value.Replace("\\", "\\\\", StringComparison.Ordinal)
        .Replace("\"", "\\\"", StringComparison.Ordinal);

    private sealed record DeclarationFile(string Path, string Content);
    private sealed record Declaration(string Projection, string Name, string Value);
}
