using System.Text;
using System.Linq;
using HPD.Agent.SourceGenerator.Contracts;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace HPD.Agent.SourceGenerator.SourceGeneration;

/// <summary>Generates reusable reflection-free AI input contracts for annotated partial types.</summary>
[Generator]
public sealed class AIInputContractSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var contracts = context.SyntaxProvider.ForAttributeWithMetadataName(
            "HPD.Agent.AIInputContractAttribute",
            static (node, _) => node is TypeDeclarationSyntax,
            static (attributeContext, _) => (INamedTypeSymbol)attributeContext.TargetSymbol);
        context.RegisterSourceOutput(contracts, Emit);
    }

    private static void Emit(SourceProductionContext context, INamedTypeSymbol? candidate)
    {
        if (candidate is null)
            return;
        var type = candidate;
        var location = type.Locations.FirstOrDefault();
        var analysis = AIContractAnalyzer.Analyze(type, type.Name, null, location);
        if (analysis.Contract is null)
        {
            foreach (var diagnostic in analysis.Diagnostics)
                context.ReportDiagnostic(diagnostic);
            return;
        }

        var declaration = type.DeclaringSyntaxReferences.FirstOrDefault()?.GetSyntax() as TypeDeclarationSyntax;
        if (type.ContainingType is not null ||
            type.TypeParameters.Length != 0 ||
            declaration is null ||
            !declaration.Modifiers.Any(SyntaxKind.PartialKeyword))
        {
            context.ReportDiagnostic(Diagnostic.Create(
                AIContractDiagnosticDescriptors.InvalidReusableContractDeclaration,
                location,
                type.ToDisplayString()));
            return;
        }

        var schema = AICanonicalSchemaEmitter.EmitRoot(analysis.Contract);
        var typeName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var namespaceName = type.ContainingNamespace.IsGlobalNamespace
            ? null
            : type.ContainingNamespace.ToDisplayString();
        var keyword = declaration.Keyword.ValueText;
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        if (namespaceName is not null) builder.AppendLine($"namespace {namespaceName};");
        builder.AppendLine($"partial {keyword} {type.Name}");
        builder.AppendLine("{");
        builder.AppendLine($"    private static readonly global::System.Text.Json.JsonElement s_aiInputSchema = global::System.Text.Json.JsonDocument.Parse(@\"{schema.Replace("\"", "\"\"")}\").RootElement.Clone();");
        builder.AppendLine($"    /// <summary>Gets the generated reusable AI input contract for <see cref=\"{type.Name}\"/>.</summary>");
        builder.AppendLine($"    public static global::HPD.Agent.IAIInputContract<{typeName}> AIContract {{ get; }} =");
        builder.AppendLine($"        global::HPD.Agent.AIInputContract.Create<{typeName}>(s_aiInputSchema, BindAIInputContract);");
        builder.Append(AIBindingSourceEmitter.EmitRoot(type.Name, analysis.Contract));
        builder.AppendLine("}");
        context.AddSource(type.Name + ".AIInputContract.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));
    }
}
