using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace HPD.Agent.SourceGenerator.SourceGeneration;

/// <summary>Generates the closed authority identifier family ledger and its semantic wrappers.</summary>
[Generator]
public sealed class AuthorityIdSourceGenerator : IIncrementalGenerator
{
    private static readonly HashSet<string> ValidOwners = new(
        ["S1", "S2", "S3", "S4", "S5", "S6", "S7", "S8", "S9", "S10", "S11", "AgentCore"],
        StringComparer.Ordinal);

    private static readonly HashSet<string> ValidKinds = new(
        ["authority", "capacity", "clock", "composition", "correlation", "custody", "delivery", "generation", "operation", "privacy", "projection", "provider", "qualification", "registry"],
        StringComparer.Ordinal);

    private static readonly DiagnosticDescriptor InvalidRow = new(
        "HPDA001", "Invalid authority ID family", "Authority ID manifest row is invalid: {0}",
        "HPD.Authority", DiagnosticSeverity.Error, true);

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var manifests = context.AdditionalTextsProvider
            .Where(static file => string.Equals(Path.GetFileName(file.Path), "authority-id-families-v1.txt", StringComparison.Ordinal))
            .Select(static (file, cancellationToken) => file.GetText(cancellationToken)?.ToString() ?? string.Empty)
            .Collect();

        context.RegisterSourceOutput(manifests, static (productionContext, texts) => Emit(productionContext, texts));
    }

    private static void Emit(SourceProductionContext context, ImmutableArray<string> texts)
    {
        if (texts.Length == 0)
            return;
        if (texts.Length != 1)
        {
            context.ReportDiagnostic(Diagnostic.Create(InvalidRow, Location.None, $"expected one manifest, found {texts.Length}"));
            return;
        }

        var rows = new List<Family>();
        var tokens = new HashSet<string>(StringComparer.Ordinal);
        var types = new HashSet<string>(StringComparer.Ordinal);
        foreach (var raw in texts[0].Split(new[] { '\r', '\n' }, StringSplitOptions.RemoveEmptyEntries))
        {
            var line = raw.Trim();
            if (line.Length == 0 || line[0] == '#')
                continue;
            var fields = line.Split('|');
            if (fields.Length != 5 || !ValidToken(fields[0]) || !ValidType(fields[1]) ||
                !ValidOwners.Contains(fields[2]) || !ValidOwners.Contains(fields[3]) ||
                !ValidKinds.Contains(fields[4]) || !tokens.Add(fields[0]) || !types.Add(fields[1]))
            {
                context.ReportDiagnostic(Diagnostic.Create(InvalidRow, Location.None, line));
                return;
            }
            rows.Add(new(fields[0], fields[1], fields[2], fields[3], fields[4]));
        }

        if (rows.Count != 48)
        {
            context.ReportDiagnostic(Diagnostic.Create(InvalidRow, Location.None, $"expected 48 families, found {rows.Count}"));
            return;
        }

        var source = new StringBuilder("// <auto-generated/>\n#nullable enable\nnamespace HPD.Agent.Authority;\n\n");
        foreach (var row in rows)
        {
            source.Append("/// <summary>Identifies a registered ").Append(row.Kind).Append(" value owned by ").Append(row.Owner).AppendLine(".</summary>");
            source.Append("/// <remarks>Canonical text begins with <c>").Append(row.Token).Append(":</c>. Allocation is restricted to ").Append(row.AllocatorOwner).AppendLine(" authority code.</remarks>");
            source.Append("public readonly record struct ").Append(row.Type).AppendLine("\n{");
            source.AppendLine("    private readonly StableId128 _value;");
            source.Append("    private ").Append(row.Type).AppendLine("(StableId128 value) => _value = value;");
            source.Append("    internal static ").Append(row.Type).AppendLine(" Create() => new(StableId128.CreateRandom());");
            source.Append("    internal static ").Append(row.Type).AppendLine(" FromValue(StableId128 value) => new(value);");
            source.AppendLine("    /// <summary>Writes the canonical 16-byte network-order value without exposing allocation authority.</summary>");
            source.AppendLine("    /// <param name=\"destination\">A destination containing at least 16 bytes.</param>");
            source.AppendLine("    /// <returns><see langword=\"true\"/> when this value is valid and was written; otherwise <see langword=\"false\"/>.</returns>");
            source.AppendLine("    public bool TryWriteBytes(global::System.Span<byte> destination) => _value.TryWriteBytes(destination);");
            source.AppendLine("    /// <summary>Gets whether this value is non-default and valid for an authority boundary.</summary>");
            source.AppendLine("    public bool IsValid => !_value.Equals(default);");
            source.Append("    /// <summary>Parses canonical <c>").Append(row.Token).AppendLine(":</c> text without aliases.</summary>");
            source.Append("    public static bool TryParse(string? text, out ").Append(row.Type).Append(" value) { var ok = StableId128.TryParse(text, \"").Append(row.Token).Append("\", out var parsed); value = ok ? new(parsed) : default; return ok; }").AppendLine();
            source.AppendLine("    /// <summary>Returns canonical text, or an empty string for the invalid default value.</summary>");
            source.Append("    public override string ToString() => IsValid ? _value.Format(\"").Append(row.Token).AppendLine("\") : string.Empty;");
            source.AppendLine("}\n");
        }
        source.AppendLine("internal readonly record struct AuthorityIdFamilyDescriptor(string Token, string Type, string Owner, string AllocatorOwner, string Kind);");
        source.AppendLine("internal static class AuthorityIdFamilyRegistryV1\n{\n    internal static readonly AuthorityIdFamilyDescriptor[] All =\n    [");
        foreach (var row in rows)
            source.Append("        new(\"").Append(row.Token).Append("\", \"").Append(row.Type).Append("\", \"").Append(row.Owner).Append("\", \"").Append(row.AllocatorOwner).Append("\", \"").Append(row.Kind).AppendLine("\"),");
        source.AppendLine("    ];\n}");
        context.AddSource("AuthorityIdFamiliesV1.g.cs", source.ToString());
    }

    private static bool ValidToken(string token) => token.Length is >= 2 and <= 16 && token[0] is >= 'a' and <= 'z' && token.All(static c => c is >= 'a' and <= 'z' or >= '0' and <= '9' or '-');
    private static bool ValidType(string type) =>
        type.Length > 2 &&
        type[0] is >= 'A' and <= 'Z' &&
        type.EndsWith("Id", StringComparison.Ordinal) &&
        type.All(static c => c is >= 'A' and <= 'Z' or >= 'a' and <= 'z' or >= '0' and <= '9');

    private sealed record Family(string Token, string Type, string Owner, string AllocatorOwner, string Kind);
}
