using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace HPD.Agent.SourceGenerator.SourceGeneration;

/// <summary>Generates the exact version-1 S2 per-scope governance catalog.</summary>
[Generator]
public sealed class CapacityGovernanceSourceGenerator : IIncrementalGenerator
{
    private static readonly string[] ExpectedRows =
    [
        "1|media-bytes|Participant|ParticipantId|16777216|0",
        "2|encoded-bytes|Operation|OperationId|4194304|0",
        "3|queue-items|Operation|OperationId|1024|0",
        "4|audio-samples|Participant|ParticipantId|480000|0",
        "5|buffer-nanoseconds|Participant|ParticipantId|10000000000|0",
        "6|provider-inflight|Provider|ProviderId|64|0",
        "7|output-inflight|Sink|SinkGenerationId|64|0",
        "8|subscriber-items|Subscriber|SubscriberId|256|0",
        "9|subscriber-bytes|Subscriber|SubscriberId|1048576|0",
        "10|journal-bytes|Session|SessionId|983040|65536",
        "11|copy-obligations|Custodian|CustodianDescriptorId|4032|64",
        "12|quarantine-bytes|Schema|SchemaId|983040|65536",
        "13|diagnostic-cardinality|Exporter|ExportId|1024|0",
        "14|recovery-work|Owner|OwnerSliceId|992|32",
    ];

    private static readonly DiagnosticDescriptor InvalidManifest = new(
        "HPDA004", "Invalid capacity governance manifest", "Capacity governance manifest is invalid: {0}",
        "HPD.Authority", DiagnosticSeverity.Error, true);

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var manifests = context.AdditionalTextsProvider
            .Where(static file => string.Equals(Path.GetFileName(file.Path), "authority-capacity-governance-v1.txt", StringComparison.Ordinal))
            .Select(static (file, cancellationToken) => file.GetText(cancellationToken)?.ToString() ?? string.Empty).Collect();
        context.RegisterSourceOutput(manifests, static (productionContext, texts) => Emit(productionContext, texts));
    }

    private static void Emit(SourceProductionContext context, ImmutableArray<string> texts)
    {
        if (texts.Length == 0) return;
        if (texts.Length != 1) { Fail(context, $"expected at most one manifest, found {texts.Length}"); return; }
        var rows = new List<Row>(); var ids = new HashSet<ushort>(); var tokens = new HashSet<string>(StringComparer.Ordinal);
        foreach (var raw in texts[0].Split(new[] {'\r','\n'}, StringSplitOptions.RemoveEmptyEntries))
        {
            var line = raw.Trim(); if (line.Length == 0 || line[0] == '#') continue;
            var f = line.Split('|');
            if (f.Length != 6 || !ushort.TryParse(f[0], NumberStyles.None, CultureInfo.InvariantCulture, out var id) || id == 0 ||
                !EnumName(f[2]) || !TypeName(f[3]) || !long.TryParse(f[4], NumberStyles.None, CultureInfo.InvariantCulture, out var normal) || normal <= 0 ||
                !long.TryParse(f[5], NumberStyles.None, CultureInfo.InvariantCulture, out var reserve) || reserve < 0 || normal > long.MaxValue - reserve ||
                !ids.Add(id) || !tokens.Add(f[1])) { Fail(context, line); return; }
            rows.Add(new(id,f[1],f[2],f[3],normal,reserve));
        }
        rows.Sort(static (a,b) => a.Id.CompareTo(b.Id));
        if (rows.Count != 14 || rows.Where(static (row,index) => row.Id != index + 1).Any()) { Fail(context,"expected contiguous exact set 1..14"); return; }
        var canonicalRows = rows.Select(static row => string.Join("|", row.Id.ToString(CultureInfo.InvariantCulture), row.Token,
            row.Scope, row.Identity, row.Normal.ToString(CultureInfo.InvariantCulture), row.Reserve.ToString(CultureInfo.InvariantCulture))).ToArray();
        if (!canonicalRows.SequenceEqual(ExpectedRows, StringComparer.Ordinal)) { Fail(context, "manifest differs from the accepted version-1 governance set"); return; }
        var source = new StringBuilder("// <auto-generated/>\n#nullable enable\nnamespace HPD.Agent.Authority;\n\n");
        source.AppendLine("/// <summary>Provides the immutable generated version-1 S2 capacity-governance catalog.</summary>");
        source.AppendLine("public static class CapacityGovernanceRegistryV1\n{");
        source.AppendLine("    private static readonly CapacityScopeLimitV1[] Entries =\n    [");
        foreach (var row in rows)
            source.Append("        new(new CapacityDimensionId(").Append(row.Id).Append("), CapacityScopeKindV1.").Append(row.Scope)
                .Append(", ").Append(row.Normal).Append("L, ").Append(row.Reserve).AppendLine("L),");
        source.AppendLine("    ];");
        source.AppendLine("    private static readonly global::System.Collections.ObjectModel.ReadOnlyCollection<CapacityScopeLimitV1> ReadOnlyEntries = global::System.Array.AsReadOnly(Entries);");
        source.AppendLine("    /// <summary>Gets the exact immutable catalog in dimension order.</summary>");
        source.AppendLine("    public static global::System.Collections.Generic.IReadOnlyList<CapacityScopeLimitV1> All => ReadOnlyEntries;");
        source.AppendLine("    /// <summary>Gets the sole configured limit for a registered dimension.</summary>");
        source.AppendLine("    /// <param name=\"id\">The registered capacity dimension.</param>");
        source.AppendLine("    /// <returns>The immutable scope limit for the dimension.</returns>");
        source.AppendLine("    /// <exception cref=\"global::System.ArgumentOutOfRangeException\">The dimension is invalid or unregistered.</exception>");
        source.AppendLine("    public static CapacityScopeLimitV1 Get(CapacityDimensionId id) => id.IsValid && id.Value <= Entries.Length ? Entries[id.Value - 1] : throw new global::System.ArgumentOutOfRangeException(nameof(id));");
        source.AppendLine("}");
        context.AddSource("CapacityGovernanceRegistryV1.g.cs", source.ToString());
    }

    private static bool EnumName(string value) => value.Length > 0 && value.All(static c => char.IsLetterOrDigit(c));
    private static bool TypeName(string value) => EnumName(value) && value.EndsWith("Id", StringComparison.Ordinal);
    private static void Fail(SourceProductionContext context, string value) => context.ReportDiagnostic(Diagnostic.Create(InvalidManifest, Location.None, value));
    private sealed record Row(ushort Id, string Token, string Scope, string Identity, long Normal, long Reserve);
}
