using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace HPD.Agent.SourceGenerator.SourceGeneration;

/// <summary>Generates the exact version-1 S2 capacity-dimension registry.</summary>
[Generator]
public sealed class CapacityDimensionSourceGenerator : IIncrementalGenerator
{
    private static readonly HashSet<string> Units = new(["Bytes", "Items", "Nanoseconds", "Samples", "Tokens", "Slots"], StringComparer.Ordinal);
    private static readonly HashSet<string> Conservations = new(["Resident", "Consumable", "RateWindow", "Exclusive"], StringComparer.Ordinal);
    private static readonly HashSet<string> Emergencies = new(["None", "Authority", "Privacy", "Recovery"], StringComparer.Ordinal);
    private static readonly Dictionary<string, int> ScopeOrder = new(StringComparer.Ordinal)
    {
        ["Tenant"] = 1, ["Session"] = 2, ["Participant"] = 3, ["Operation"] = 4,
        ["Provider"] = 5, ["Sink"] = 6, ["Subscriber"] = 7, ["Custodian"] = 8,
        ["Schema"] = 9, ["Exporter"] = 10, ["Owner"] = 11,
    };
    private static readonly DiagnosticDescriptor InvalidManifest = new(
        "HPDA003", "Invalid capacity dimension manifest", "Capacity dimension manifest is invalid: {0}",
        "HPD.Authority", DiagnosticSeverity.Error, true);

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var manifests = context.AdditionalTextsProvider
            .Where(static file => string.Equals(Path.GetFileName(file.Path), "authority-capacity-dimensions-v1.txt", StringComparison.Ordinal))
            .Select(static (file, cancellationToken) => file.GetText(cancellationToken)?.ToString() ?? string.Empty)
            .Collect();
        context.RegisterSourceOutput(manifests, static (productionContext, texts) => Emit(productionContext, texts));
    }

    private static void Emit(SourceProductionContext context, ImmutableArray<string> texts)
    {
        if (texts.Length == 0)
            return;
        if (texts.Length != 1)
        {
            context.ReportDiagnostic(Diagnostic.Create(InvalidManifest, Location.None, $"expected one manifest, found {texts.Length}"));
            return;
        }

        var rows = new List<Row>();
        var ids = new HashSet<ushort>();
        var tokens = new HashSet<string>(StringComparer.Ordinal);
        foreach (var raw in texts[0].Split(new[] { '\r', '\n' }, StringSplitOptions.RemoveEmptyEntries))
        {
            var line = raw.Trim();
            if (line.Length == 0 || line[0] == '#')
                continue;
            var fields = line.Split('|');
            var scopes = fields.Length == 9 ? fields[4].Split(',') : Array.Empty<string>();
            if (fields.Length != 9 ||
                !ushort.TryParse(fields[0], NumberStyles.None, CultureInfo.InvariantCulture, out var id) || id == 0 ||
                !ValidToken(fields[1]) || !Units.Contains(fields[2]) || !Conservations.Contains(fields[3]) ||
                scopes.Length == 0 || scopes.Any(value => !ScopeOrder.ContainsKey(value)) ||
                scopes.Distinct(StringComparer.Ordinal).Count() != scopes.Length ||
                !scopes.Select(value => ScopeOrder[value]).SequenceEqual(scopes.Select(value => ScopeOrder[value]).OrderBy(static value => value)) ||
                !Emergencies.Contains(fields[5]) ||
                !long.TryParse(fields[6], NumberStyles.None, CultureInfo.InvariantCulture, out var maximum) || maximum <= 0 ||
                !ushort.TryParse(fields[7], NumberStyles.None, CultureInfo.InvariantCulture, out var version) || version == 0 ||
                !EnumName(fields[8]) || !ids.Add(id) || !tokens.Add(fields[1]))
            {
                context.ReportDiagnostic(Diagnostic.Create(InvalidManifest, Location.None, line));
                return;
            }
            rows.Add(new(id, fields[1], fields[2], fields[3], scopes, fields[5], maximum, version, fields[8]));
        }

        rows.Sort(static (left, right) => left.Id.CompareTo(right.Id));
        if (rows.Count != 14 || rows.Where(static (row, index) => row.Id != index + 1).Any())
        {
            context.ReportDiagnostic(Diagnostic.Create(InvalidManifest, Location.None, "expected the contiguous exact set 1..14"));
            return;
        }

        var source = new StringBuilder("// <auto-generated/>\n#nullable enable\nnamespace HPD.Agent.Authority;\n\n");
        source.AppendLine("/// <summary>Provides the immutable generated version-1 S2 capacity-dimension registry.</summary>");
        source.AppendLine("public static class CapacityDimensionRegistryV1\n{");
        source.AppendLine("    private static readonly CapacityDimensionDescriptorV1[] Entries =\n    [");
        foreach (var row in rows)
        {
            source.Append("        new(new CapacityDimensionId(").Append(row.Id).Append("), \"").Append(row.Token)
                .Append("\", CapacityUnitV1.").Append(row.Unit).Append(", CapacityConservationV1.").Append(row.Conservation)
                .Append(", global::System.Array.AsReadOnly(new CapacityScopeKindV1[] { ");
            foreach (var scope in row.Scopes)
                source.Append("CapacityScopeKindV1.").Append(scope).Append(", ");
            source.Append("}), CapacityEmergencyClassV1.").Append(row.Emergency).Append(", ")
                .Append(row.Maximum.ToString(CultureInfo.InvariantCulture)).Append("L, ")
                .Append(row.Version.ToString(CultureInfo.InvariantCulture)).Append(", \"")
                .Append(row.SettlementEvidence).AppendLine("\"),");
        }
        source.AppendLine("    ];");
        source.AppendLine("    private static readonly global::System.Collections.ObjectModel.ReadOnlyCollection<CapacityDimensionDescriptorV1> ReadOnlyEntries = global::System.Array.AsReadOnly(Entries);");
        source.AppendLine("    /// <summary>Gets all registered descriptors in numeric identity order.</summary>");
        source.AppendLine("    public static global::System.Collections.Generic.IReadOnlyList<CapacityDimensionDescriptorV1> All => ReadOnlyEntries;");
        source.AppendLine("    /// <summary>Gets the descriptor registered for an exact dimension identity.</summary>");
        source.AppendLine("    /// <param name=\"id\">The registered dimension identity.</param>");
        source.AppendLine("    /// <returns>The immutable registered descriptor.</returns>");
        source.AppendLine("    /// <exception cref=\"global::System.ArgumentOutOfRangeException\">The identity is default or unregistered.</exception>");
        source.AppendLine("    public static CapacityDimensionDescriptorV1 Get(CapacityDimensionId id) => id.IsValid ? Entries[id.Value - 1] : throw new global::System.ArgumentOutOfRangeException(nameof(id));");
        source.AppendLine("}\n");
        source.AppendLine("/// <summary>Provides named identities for the exact version-1 capacity dimensions.</summary>");
        source.AppendLine("public static class CapacityDimensionsV1\n{");
        foreach (var row in rows)
        {
            var name = string.Concat(row.Token.Split('-').Select(static part => char.ToUpperInvariant(part[0]) + part.Substring(1)));
            source.Append("    /// <summary>Gets the registered <c>").Append(row.Token).AppendLine("</c> dimension identity.</summary>");
            source.Append("    public static CapacityDimensionId ").Append(name).Append(" { get; } = new(").Append(row.Id).AppendLine(");");
        }
        source.AppendLine("}\n");
        context.AddSource("CapacityDimensionRegistryV1.g.cs", source.ToString());
    }

    private static bool ValidToken(string value) => value.Length is >= 2 and <= 64 &&
        value[0] is >= 'a' and <= 'z' && value.All(static character => character is >= 'a' and <= 'z' or >= '0' and <= '9' or '-');

    private static bool EnumName(string value) => value.Length > 0 && value[0] is >= 'A' and <= 'Z' &&
        value.All(static character => character is >= 'A' and <= 'Z' or >= 'a' and <= 'z' or >= '0' and <= '9');

    private sealed record Row(ushort Id, string Token, string Unit, string Conservation, string[] Scopes, string Emergency, long Maximum, ushort Version, string SettlementEvidence);
}
