using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

[Generator]
public sealed class HpdPackageRegistrationSourceGenerator : IIncrementalGenerator
{
    private const string AttributeMetadataName = "HPD.Agent.Packages.HpdPackageRegistrationAttribute";
    private const string PackageInterfaceMetadataName = "HPD.Agent.Packages.IHpdPackage";

    private static readonly DiagnosticDescriptor MustImplementPackage = new(
        "HPDPKG001",
        "Package registration target must implement IHpdPackage",
        "Type '{0}' is marked with HpdPackageRegistrationAttribute but does not implement IHpdPackage",
        "HPD.PackageRegistration",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor MustHavePublicParameterlessConstructor = new(
        "HPDPKG002",
        "Package registration target must have a public parameterless constructor",
        "Type '{0}' is marked with HpdPackageRegistrationAttribute but does not have a public parameterless constructor",
        "HPD.PackageRegistration",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var packageCandidates = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeMetadataName,
                predicate: static (_, _) => true,
                transform: static (ctx, _) => GetPackageCandidate(ctx))
            .Collect();

        context.RegisterSourceOutput(packageCandidates, GeneratePackageRegistration);
    }

    private static PackageRegistrationCandidate GetPackageCandidate(GeneratorAttributeSyntaxContext context)
    {
        var type = (INamedTypeSymbol)context.TargetSymbol;
        var typeName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var displayName = type.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat);

        if (!type.AllInterfaces.Any(static candidate => candidate.ToDisplayString() == PackageInterfaceMetadataName))
        {
            return PackageRegistrationCandidate.Invalid(
                Diagnostic.Create(MustImplementPackage, type.Locations.FirstOrDefault(), displayName));
        }

        if (!HasPublicParameterlessConstructor(type))
        {
            return PackageRegistrationCandidate.Invalid(
                Diagnostic.Create(MustHavePublicParameterlessConstructor, type.Locations.FirstOrDefault(), displayName));
        }

        return PackageRegistrationCandidate.Valid(typeName);
    }

    private static bool HasPublicParameterlessConstructor(INamedTypeSymbol type)
    {
        return type.InstanceConstructors.Any(static constructor =>
            constructor.DeclaredAccessibility == Accessibility.Public &&
            constructor.Parameters.Length == 0);
    }

    private static void GeneratePackageRegistration(
        SourceProductionContext context,
        ImmutableArray<PackageRegistrationCandidate> candidates)
    {
        foreach (var diagnostic in candidates.Select(static candidate => candidate.Diagnostic).Where(static diagnostic => diagnostic is not null))
        {
            context.ReportDiagnostic(diagnostic!);
        }

        var packageTypes = candidates
            .Where(static candidate => candidate.TypeName is not null)
            .Select(static candidate => candidate.TypeName!)
            .Distinct()
            .OrderBy(static typeName => typeName)
            .ToArray();

        if (packageTypes.Length == 0)
        {
            return;
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("namespace HPD.Agent.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    internal static class HpdPackageRegistration");
        sb.AppendLine("    {");
        sb.AppendLine("#pragma warning disable CA2255");
        sb.AppendLine("        [global::System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine("        internal static void RegisterPackages()");
        sb.AppendLine("#pragma warning restore CA2255");
        sb.AppendLine("        {");

        foreach (var packageType in packageTypes)
        {
            sb.AppendLine($"            global::HPD.Agent.Packages.HpdPackageRegistry.Register<{packageType}>();");
        }

        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("HPD.Agent.Generated.HpdPackageRegistration.g.cs", sb.ToString());
    }

    private readonly record struct PackageRegistrationCandidate(
        string? TypeName,
        Diagnostic? Diagnostic)
    {
        public static PackageRegistrationCandidate Valid(string typeName) => new(typeName, null);

        public static PackageRegistrationCandidate Invalid(Diagnostic diagnostic) => new(null, diagnostic);
    }
}
