using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace HPD.Agent.SourceGenerator.SourceGeneration;

/// <summary>Generates explicit TUI permission-presentation renderer composition.</summary>
[Generator]
public sealed class PermissionPresentationRendererGenerator : IIncrementalGenerator
{
    private const string RendererAttribute =
        "HPD.Agent.TUI.Interactions.PermissionPresentationRendererAttribute";
    private const string RendererInterface =
        "HPD.Agent.TUI.Interactions.IPermissionPresentationRenderer<TPresentation>";
    private const string PresentationAttribute =
        "HPD.Agent.Permissions.PermissionPresentationAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var renderers = context.SyntaxProvider.ForAttributeWithMetadataName(
            RendererAttribute,
            static (node, _) => node is ClassDeclarationSyntax,
            static (syntaxContext, _) => Analyze((INamedTypeSymbol)syntaxContext.TargetSymbol))
            .Where(static model => model is not null)
            .Select(static (model, _) => model!);
        context.RegisterSourceOutput(
            renderers.Collect().Combine(context.CompilationProvider),
            static (production, value) => Emit(production, value.Left, value.Right.AssemblyName ?? "Application"));
    }

    private static RendererModel? Analyze(INamedTypeSymbol renderer)
    {
        var contract = renderer.AllInterfaces.FirstOrDefault(candidate =>
            candidate.IsGenericType &&
            candidate.ConstructedFrom.ToDisplayString() == RendererInterface);
        if (contract is null) return null;
        var presentation = contract.TypeArguments[0];
        var attribute = presentation.GetAttributes().FirstOrDefault(candidate =>
            candidate.AttributeClass?.ToDisplayString() == PresentationAttribute);
        var id = attribute?.ConstructorArguments.FirstOrDefault().Value as string;
        if (string.IsNullOrWhiteSpace(id)) return null;
        return new RendererModel(
            renderer.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            presentation.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            id!);
    }

    private static void Emit(
        SourceProductionContext context,
        ImmutableArray<RendererModel> renderers,
        string assemblyName)
    {
        if (renderers.IsDefaultOrEmpty) return;
        var duplicate = renderers.GroupBy(static item => item.Id, StringComparer.Ordinal)
            .FirstOrDefault(static group => group.Count() > 1);
        if (duplicate is not null)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                new DiagnosticDescriptor(
                    "HPDPR001",
                    "Duplicate permission presentation renderer",
                    "Permission presentation ID '{0}' has multiple generated renderers",
                    "HPD.Agent.TUI",
                    DiagnosticSeverity.Error,
                    true),
                Location.None,
                duplicate.Key));
            return;
        }

        var className = "GeneratedPermissionPresentationRenderers_" + Sanitize(assemblyName);
        var source = new StringBuilder()
            .AppendLine("// <auto-generated />")
            .AppendLine("namespace HPD.Agent.TUI;")
            .AppendLine($"public static class {className}")
            .AppendLine("{")
            .AppendLine("    public static global::HPD.Agent.TUI.HpdAgentTuiBuilder AddGeneratedPermissionPresentationRenderers(")
            .AppendLine("        this global::HPD.Agent.TUI.HpdAgentTuiBuilder builder)")
            .AppendLine("    {");
        foreach (var renderer in renderers.OrderBy(static item => item.Id, StringComparer.Ordinal))
        {
            source.AppendLine($"        builder.AddPermissionPresentationRenderer<{renderer.PresentationType}>(\"{Escape(renderer.Id)}\", new {renderer.RendererType}());");
        }
        source.AppendLine("        return builder;")
            .AppendLine("    }")
            .AppendLine("}");
        context.AddSource(className + ".g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
    }

    private static string Sanitize(string value) =>
        new(value.Select(static character => char.IsLetterOrDigit(character) ? character : '_').ToArray());

    private static string Escape(string value) =>
        value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private sealed record RendererModel(string RendererType, string PresentationType, string Id);
}
