using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace HPD.Agent.SourceGenerator.SourceGeneration;

/// <summary>Generates a closed provider composition from referenced manifest markers.</summary>
[Generator]
public sealed class ProviderCompositionSourceGenerator : IIncrementalGenerator
{
    private const string ManifestAttributeName = "HPD.Agent.Providers.HpdProviderManifestAttribute";
    private static readonly DiagnosticDescriptor DuplicateFamily = new(
        "HPDP010", "Duplicate provider family", "Provider '{0}' contributes client family '{1}' more than once",
        "HPD.Provider", DiagnosticSeverity.Error, true);
    private static readonly DiagnosticDescriptor KeyCollision = new(
        "HPDP011", "Provider key collision", "Provider key or alias '{0}' is claimed by both '{1}' and '{2}'",
        "HPD.Provider", DiagnosticSeverity.Error, true);

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var manifests = context.CompilationProvider.Select(static (compilation, _) =>
        {
            var builder = ImmutableArray.CreateBuilder<ManifestInfo>();
            AddManifests(compilation.Assembly, builder);
            foreach (var assembly in compilation.SourceModule.ReferencedAssemblySymbols)
                AddManifests(assembly, builder);
            return builder.Distinct(ManifestInfoComparer.Instance).OrderBy(x => x.ManifestType, StringComparer.Ordinal).ToImmutableArray();
        });

        context.RegisterSourceOutput(manifests, static (context, manifests) =>
        {
            if (manifests.IsDefaultOrEmpty)
                return;

            var invalid = false;
            foreach (var group in manifests.SelectMany(x => x.Families.Select(f => (x.ProviderKey, Family: f)))
                         .GroupBy(x => x, ProviderFamilyComparer.Instance).Where(x => x.Count() > 1))
            {
                context.ReportDiagnostic(Diagnostic.Create(DuplicateFamily, Location.None, group.Key.ProviderKey, group.Key.Family));
                invalid = true;
            }

            var claims = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
            foreach (var manifest in manifests)
                foreach (var key in manifest.Aliases.Insert(0, manifest.ProviderKey))
                {
                    if (claims.TryGetValue(key, out var existing) && !StringComparer.OrdinalIgnoreCase.Equals(existing, manifest.ProviderKey))
                    {
                        context.ReportDiagnostic(Diagnostic.Create(KeyCollision, Location.None, key, existing, manifest.ProviderKey));
                        invalid = true;
                    }
                    else claims[key] = manifest.ProviderKey;
                }
            if (invalid)
                return;

            var source = new StringBuilder();
            source.AppendLine("// <auto-generated/>");
            source.AppendLine("#nullable enable");
            source.AppendLine("namespace HPD.Agent.Providers.Generated;");
            source.AppendLine();
            source.AppendLine("/// <summary>Provides the closed provider composition generated for this assembly.</summary>");
            source.AppendLine("internal static class GeneratedProviderComposition");
            source.AppendLine("{");
            source.AppendLine("    public static global::System.Collections.Generic.IReadOnlyList<global::HPD.Agent.Providers.ProviderManifestFragment> Fragments { get; } =");
            source.AppendLine("        new global::HPD.Agent.Providers.ProviderManifestFragment[]");
            source.AppendLine("        {");
            foreach (var manifest in manifests)
                source.AppendLine($"            {manifest.ManifestType}.Fragment,");
            source.AppendLine("        };");
            source.AppendLine("    public static global::HPD.Agent.Providers.ProviderComposition Composition { get; } = global::HPD.Agent.Providers.ProviderComposition.Create(Fragments);");
            source.AppendLine("    public static global::HPD.Agent.Providers.IProviderDescriptorRegistry Descriptors => Composition.Descriptors;");
            source.AppendLine("    public static global::HPD.Agent.Providers.IProviderRuntimeRegistry Runtime => Composition.Runtime;");
            source.AppendLine("    public static global::HPD.Agent.Providers.IProviderSerializationRegistry Serialization => Composition.Serialization;");
            source.AppendLine("}");
            context.AddSource("GeneratedProviderComposition.g.cs", source.ToString());

            var services = new StringBuilder();
            services.AppendLine("// <auto-generated/>");
            services.AppendLine("#nullable enable");
            services.AppendLine("namespace Microsoft.Extensions.DependencyInjection;");
            services.AppendLine("/// <summary>Registers the source-generated provider composition for this application.</summary>");
            services.AppendLine("internal static class HpdGeneratedProviderServiceCollectionExtensions");
            services.AppendLine("{");
            services.AppendLine("    /// <summary>Adds immutable provider metadata, factories, serializers, and secret aliases.</summary>");
            services.AppendLine("    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddHpdGeneratedProviders(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
            services.AppendLine("    {");
            services.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(services);");
            services.AppendLine("        var composition = global::HPD.Agent.Providers.Generated.GeneratedProviderComposition.Composition;");
            services.AppendLine("        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddSingleton(services, composition);");
            services.AppendLine("        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddSingleton<global::HPD.Agent.Providers.IProviderDescriptorRegistry>(services, composition.Descriptors);");
            services.AppendLine("        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddSingleton<global::HPD.Agent.Providers.IProviderRuntimeRegistry>(services, composition.Runtime);");
            services.AppendLine("        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddSingleton<global::HPD.Agent.Providers.IProviderSerializationRegistry>(services, composition.Serialization);");
            services.AppendLine("        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddSingleton<global::HPD.Agent.Providers.IProviderSecretAliasRegistry>(services, composition.SecretAliases);");
            services.AppendLine("        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddSingleton<global::HPD.Agent.IAgentConfigFactory>(services, static provider => new global::HPD.Agent.AgentFactory(providerComposition: provider.GetRequiredService<global::HPD.Agent.Providers.ProviderComposition>()));");
            services.AppendLine("        return services;");
            services.AppendLine("    }");
            services.AppendLine("}");
            context.AddSource("HpdGeneratedProviderServiceCollectionExtensions.g.cs", services.ToString());
        });
    }

    private static void AddManifests(IAssemblySymbol assembly, ImmutableArray<ManifestInfo>.Builder builder)
    {
        foreach (var attribute in assembly.GetAttributes())
        {
            if (attribute.AttributeClass?.ToDisplayString() != ManifestAttributeName || attribute.ConstructorArguments.Length < 3 ||
                attribute.ConstructorArguments[0].Value is not INamedTypeSymbol type || attribute.ConstructorArguments[1].Value is not string key)
                continue;
            var families = attribute.ConstructorArguments[2].Values.Select(x => Convert.ToInt32(x.Value)).ToImmutableArray();
            var aliasesArg = attribute.NamedArguments.FirstOrDefault(x => x.Key == "Aliases").Value;
            var aliases = aliasesArg.IsNull ? ImmutableArray<string>.Empty : aliasesArg.Values.Select(x => (string)x.Value!).ToImmutableArray();
            builder.Add(new ManifestInfo(type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), key, families, aliases));
        }
    }

    private sealed record ManifestInfo(string ManifestType, string ProviderKey, ImmutableArray<int> Families, ImmutableArray<string> Aliases);
    private sealed class ManifestInfoComparer : IEqualityComparer<ManifestInfo>
    {
        public static ManifestInfoComparer Instance { get; } = new();
        public bool Equals(ManifestInfo? x, ManifestInfo? y) => x?.ManifestType == y?.ManifestType;
        public int GetHashCode(ManifestInfo obj) => StringComparer.Ordinal.GetHashCode(obj.ManifestType);
    }
    private sealed class ProviderFamilyComparer : IEqualityComparer<(string ProviderKey, int Family)>
    {
        public static ProviderFamilyComparer Instance { get; } = new();
        public bool Equals((string ProviderKey, int Family) x, (string ProviderKey, int Family) y) => x.Family == y.Family && StringComparer.OrdinalIgnoreCase.Equals(x.ProviderKey, y.ProviderKey);
        public int GetHashCode((string ProviderKey, int Family) obj) => unchecked((StringComparer.OrdinalIgnoreCase.GetHashCode(obj.ProviderKey) * 397) ^ obj.Family);
    }
}
