using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace HPD.Agent.SourceGenerator.SourceGeneration;

/// <summary>Generates a closed provider composition from referenced manifest markers.</summary>
[Generator]
public sealed class ProviderCompositionSourceGenerator : IIncrementalGenerator
{
    private const string ManifestAttributeName = "HPD.Agent.Providers.HpdProviderManifestAttribute";

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var manifests = context.CompilationProvider.Select(static (compilation, _) =>
        {
            var builder = ImmutableArray.CreateBuilder<string>();
            AddManifestTypes(compilation.Assembly, builder);
            foreach (var referencedAssembly in compilation.SourceModule.ReferencedAssemblySymbols)
                AddManifestTypes(referencedAssembly, builder);

            return builder
                .Distinct(StringComparer.Ordinal)
                .OrderBy(static value => value, StringComparer.Ordinal)
                .ToImmutableArray();
        });

        context.RegisterSourceOutput(manifests, static (productionContext, manifestTypes) =>
        {
            if (manifestTypes.IsDefaultOrEmpty)
                return;

            var source = new StringBuilder();
            source.AppendLine("// <auto-generated/>");
            source.AppendLine("#nullable enable");
            source.AppendLine("namespace HPD.Agent.Providers.Generated;");
            source.AppendLine();
            source.AppendLine("/// <summary>Provides the closed provider composition generated for this assembly.</summary>");
            source.AppendLine("internal static class GeneratedProviderComposition");
            source.AppendLine("{");
            source.AppendLine("    /// <summary>Gets all statically referenced provider manifest fragments.</summary>");
            source.AppendLine("    public static global::System.Collections.Generic.IReadOnlyList<global::HPD.Agent.Providers.ProviderManifestFragment> Fragments { get; } =");
            source.AppendLine("        new global::HPD.Agent.Providers.ProviderManifestFragment[]");
            source.AppendLine("        {");
            foreach (var manifestType in manifestTypes)
                source.AppendLine($"            {manifestType}.Fragment,");
            source.AppendLine("        };");
            source.AppendLine("}");

            productionContext.AddSource("GeneratedProviderComposition.g.cs", source.ToString());
        });
    }

    private static void AddManifestTypes(
        IAssemblySymbol assembly,
        ImmutableArray<string>.Builder builder)
    {
        foreach (var attribute in assembly.GetAttributes())
        {
            if (attribute.AttributeClass?.ToDisplayString() != ManifestAttributeName ||
                attribute.ConstructorArguments.Length != 1 ||
                attribute.ConstructorArguments[0].Value is not INamedTypeSymbol manifestType)
                continue;

            builder.Add(manifestType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
        }
    }
}
