using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace HPD.Graph.SourceGenerator;

/// <summary>
/// Source generator that creates bridge code for handlers marked with [GraphNodeHandler].
/// Generates the implementation of IGraphNodeHandler.ExecuteAsync that calls the clean user method.
/// </summary>
[Generator]
public class SocketBridgeGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax c
                    && c.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword))
                    && c.AttributeLists.Count > 0,
                transform: static (ctx, _) => (ClassDeclarationSyntax)ctx.Node)
            .Collect();

        context.RegisterSourceOutput(
            classDeclarations.Combine(context.CompilationProvider),
            (spc, pair) => Execute(pair.Right, pair.Left, spc));
    }

    private void Execute(Compilation compilation, System.Collections.Immutable.ImmutableArray<ClassDeclarationSyntax> classes, SourceProductionContext context)
    {
        foreach (var candidateClass in classes)
        {
            var model = compilation.GetSemanticModel(candidateClass.SyntaxTree);
            var classSymbol = model.GetDeclaredSymbol(candidateClass);

            if (classSymbol == null)
                continue;

            // Check if class has [GraphNodeHandler] attribute
            var attribute = classSymbol.GetAttributes()
                .FirstOrDefault(a => a.AttributeClass?.Name == "GraphNodeHandlerAttribute");

            if (attribute == null)
                continue;

            // Find the ExecuteAsync method with socket attributes
            var executeMethod = FindExecuteAsyncMethod(classSymbol);

            if (executeMethod == null)
                continue;

            // Generate bridge code
            var source = GenerateBridgeCode(classSymbol, executeMethod, attribute);
            var fileName = $"{classSymbol.Name}.Sockets.g.cs";

            context.AddSource(fileName, SourceText.From(source, Encoding.UTF8));
        }
    }

    private IMethodSymbol? FindExecuteAsyncMethod(INamedTypeSymbol classSymbol)
    {
        // Look for a method named ExecuteAsync that has parameters with [InputSocket]
        // or returns a type with properties marked with [OutputSocket]
        return classSymbol.GetMembers()
            .OfType<IMethodSymbol>()
            .FirstOrDefault(m => m.Name == "ExecuteAsync" && HasSocketAttributes(m));
    }

    private bool HasSocketAttributes(IMethodSymbol method)
    {
        // Check if any parameter has [InputSocket]
        foreach (var param in method.Parameters)
        {
            if (param.GetAttributes().Any(a => a.AttributeClass?.Name == "InputSocketAttribute"))
                return true;
        }

        // Check if return type has properties with [OutputSocket]
        if (method.ReturnType is INamedTypeSymbol returnType)
        {
            // Handle Task<T>
            if (returnType.Name == "Task" && returnType.TypeArguments.Length == 1)
            {
                var innerType = returnType.TypeArguments[0] as INamedTypeSymbol;
                if (innerType != null && HasOutputSocketProperties(innerType))
                    return true;
            }
        }

        return false;
    }

    private bool HasOutputSocketProperties(INamedTypeSymbol type)
    {
        return type.GetMembers()
            .OfType<IPropertySymbol>()
            .Any(p => p.GetAttributes().Any(a => a.AttributeClass?.Name == "OutputSocketAttribute"));
    }

    private string GenerateBridgeCode(INamedTypeSymbol classSymbol, IMethodSymbol executeMethod, AttributeData attribute)
    {
        var namespaceName = classSymbol.ContainingNamespace.ToDisplayString();
        var className = classSymbol.Name;
        var nodeName = GetNodeName(attribute, className);

        // Extract context type from attribute, first parameter, interface, or default GraphContext.
        var contextType = InferContextType(classSymbol, executeMethod, attribute);

        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {namespaceName};");
        sb.AppendLine();
        sb.AppendLine($"partial class {className} : HPD.Graph.Abstractions.Handlers.IGraphNodeHandler<{contextType}>");
        sb.AppendLine("{");

        // Generate HandlerName property if not already defined
        if (!HasHandlerNameProperty(classSymbol))
        {
            sb.AppendLine($"    public string HandlerName => \"{nodeName}\";");
            sb.AppendLine();
        }

        // Generate private field to store current node (for GetNodeConfig)
        sb.AppendLine("    private HPD.Graph.Abstractions.Graph.Node? _currentNode;");
        sb.AppendLine("    private System.IServiceProvider? _currentServices;");
        sb.AppendLine();

        // Check if handler has a nested Config class
        var configClass = FindNestedConfigClass(classSymbol);
        if (configClass != null)
        {
            // Generate GetNodeConfig helper method
            var configTypeName = configClass.ToDisplayString();
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Gets the node-specific configuration for the current node being executed.");
            sb.AppendLine("    /// Deserializes from Node.Config JSON into strongly-typed Config object.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine($"    private {configTypeName} GetNodeConfig()");
            sb.AppendLine("    {");
            sb.AppendLine("        if (_currentNode?.Config == null)");
            sb.AppendLine($"            return new {configTypeName}();");
            sb.AppendLine();
            sb.AppendLine("        var json = _currentNode.Config.Value;");
            sb.AppendLine($"        if (TryGetJsonTypeInfo<{configTypeName}>(out var jsonTypeInfo))");
            sb.AppendLine("        {");
            sb.AppendLine("            return System.Text.Json.JsonSerializer.Deserialize(json, jsonTypeInfo)");
            sb.AppendLine($"                ?? new {configTypeName}();");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine($"        var config = new {configTypeName}();");
            sb.AppendLine("        if (json.ValueKind != System.Text.Json.JsonValueKind.Object)");
            sb.AppendLine("            return config;");
            sb.AppendLine();
            var unsupportedProperties = GenerateConfigPropertyReaders(sb, configClass);
            if (unsupportedProperties.Count > 0)
            {
                sb.AppendLine($"        throw CreateMissingConfigJsonTypeInfoException(\"{configTypeName}\", \"{string.Join(", ", unsupportedProperties)}\");");
            }
            sb.AppendLine("        return config;");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        // Generate IGraphNodeHandler.ExecuteAsync implementation
        sb.AppendLine($"    async System.Threading.Tasks.Task<HPD.Graph.Abstractions.Execution.NodeExecutionResult> HPD.Graph.Abstractions.Handlers.IGraphNodeHandler<{contextType}>.ExecuteAsync(");
        sb.AppendLine($"        {contextType} context,");
        sb.AppendLine($"        HPD.Graph.Abstractions.Handlers.HandlerInputs inputs,");
        sb.AppendLine($"        System.Threading.CancellationToken ct)");
        sb.AppendLine("    {");
        sb.AppendLine("        // Store current node for GetNodeConfig access");
        sb.AppendLine("        _currentNode = context.CurrentNodeId is null ? null : context.Graph.GetNode(context.CurrentNodeId);");
        sb.AppendLine("        _currentServices = context.Services;");
        sb.AppendLine();
        sb.AppendLine("        var stopwatch = System.Diagnostics.Stopwatch.StartNew();");
        sb.AppendLine("        try");
        sb.AppendLine("        {");

        // Extract inputs from HandlerInputs
        sb.AppendLine("            // Extract inputs from HandlerInputs");
        foreach (var param in executeMethod.Parameters)
        {
            if (param.Type.Name == "CancellationToken")
                continue;

            var inputAttr = param.GetAttributes()
                .FirstOrDefault(a => a.AttributeClass?.Name == "InputSocketAttribute");

            if (inputAttr != null)
            {
                var isOptional = GetAttributeProperty<bool>(inputAttr, "Optional");
                var paramName = param.Name;
                var paramType = param.Type.ToDisplayString();

                if (isOptional || param.HasExplicitDefaultValue)
                {
                    var defaultValue = param.HasExplicitDefaultValue
                        ? FormatDefaultValue(param.ExplicitDefaultValue, param.Type)
                        : $"default({paramType})";
                    sb.AppendLine($"            var {paramName} = inputs.GetOrDefault<{paramType}>(\"{paramName}\", {defaultValue});");
                }
                else
                {
                    sb.AppendLine($"            var {paramName} = inputs.Get<{paramType}>(\"{paramName}\");");
                }
            }
        }

        sb.AppendLine();
        sb.AppendLine("            // Call user's clean method");
        var methodCall = GenerateMethodCall(executeMethod);
        sb.AppendLine($"            var result = await {methodCall};");
        sb.AppendLine();
        sb.AppendLine("            stopwatch.Stop();");
        sb.AppendLine();

        // Build outputs dictionary from result
        sb.AppendLine("            // Build outputs from result");
        sb.AppendLine("            var outputs = new System.Collections.Generic.Dictionary<string, object>();");

        var returnType = GetTaskInnerType(executeMethod.ReturnType);
        if (returnType != null && returnType is INamedTypeSymbol namedReturnType)
        {
            var outputProperties = namedReturnType.GetMembers()
                .OfType<IPropertySymbol>()
                .Where(p => p.GetAttributes().Any(a => a.AttributeClass?.Name == "OutputSocketAttribute"))
                .ToList();

            foreach (var prop in outputProperties)
            {
                sb.AppendLine($"            outputs[\"{prop.Name}\"] = result.{prop.Name}!;");
            }
        }

        sb.AppendLine();
        sb.AppendLine("            return HPD.Graph.Abstractions.Execution.NodeExecutionResult.Success.Single(");
        sb.AppendLine("                output: outputs,");
        sb.AppendLine("                duration: stopwatch.Elapsed,");
        sb.AppendLine("                metadata: new HPD.Graph.Abstractions.Execution.NodeExecutionMetadata()");
        sb.AppendLine("            );");
        sb.AppendLine("        }");
        sb.AppendLine("        catch (System.Exception ex)");
        sb.AppendLine("        {");
        sb.AppendLine("            stopwatch.Stop();");
        sb.AppendLine("            return new HPD.Graph.Abstractions.Execution.NodeExecutionResult.Failure(");
        sb.AppendLine("                Exception: ex,");
        sb.AppendLine("                Severity: IsTransientException(ex)");
        sb.AppendLine("                    ? HPD.Graph.Abstractions.Execution.ErrorSeverity.Transient");
        sb.AppendLine("                    : HPD.Graph.Abstractions.Execution.ErrorSeverity.Fatal,");
        sb.AppendLine("                IsTransient: IsTransientException(ex),");
        sb.AppendLine("                Duration: stopwatch.Elapsed");
        sb.AppendLine("            );");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Helper method to determine if exception is transient
        if (configClass != null)
        {
            sb.AppendLine("    private bool TryGetJsonTypeInfo<TConfig>(out System.Text.Json.Serialization.Metadata.JsonTypeInfo<TConfig> jsonTypeInfo)");
            sb.AppendLine("    {");
            sb.AppendLine("        if (_currentServices?.GetService(typeof(System.Collections.Generic.IEnumerable<HPD.Graph.Abstractions.Serialization.IGraphJsonTypeInfoResolverContributor>)) is System.Collections.Generic.IEnumerable<HPD.Graph.Abstractions.Serialization.IGraphJsonTypeInfoResolverContributor> contributors)");
            sb.AppendLine("        {");
            sb.AppendLine("            foreach (var contributor in contributors)");
            sb.AppendLine("            {");
            sb.AppendLine("                if (contributor.Resolver is System.Text.Json.Serialization.JsonSerializerContext contextResolver &&");
            sb.AppendLine("                    contextResolver.GetTypeInfo(typeof(TConfig)) is System.Text.Json.Serialization.Metadata.JsonTypeInfo<TConfig> contextResolved)");
            sb.AppendLine("                {");
            sb.AppendLine("                    jsonTypeInfo = contextResolved;");
            sb.AppendLine("                    return true;");
            sb.AppendLine("                }");
            sb.AppendLine();
            sb.AppendLine("                if (contributor.Resolver.GetTypeInfo(typeof(TConfig), new System.Text.Json.JsonSerializerOptions()) is System.Text.Json.Serialization.Metadata.JsonTypeInfo<TConfig> resolved)");
            sb.AppendLine("                {");
            sb.AppendLine("                    jsonTypeInfo = resolved;");
            sb.AppendLine("                    return true;");
            sb.AppendLine("                }");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        jsonTypeInfo = null!;");
            sb.AppendLine("        return false;");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    private static System.InvalidOperationException CreateMissingConfigJsonTypeInfoException(string configTypeName, string unsupportedProperties)");
            sb.AppendLine("    {");
            sb.AppendLine("        return new System.InvalidOperationException($\"Config type '{configTypeName}' contains unsupported properties ({unsupportedProperties}). Register an HPD.Graph.Abstractions.Serialization.IGraphJsonTypeInfoResolverContributor that provides JsonTypeInfo for this config type, or use only AOT-safe primitive config properties.\");");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.AppendLine("    private static bool IsTransientException(System.Exception ex)");
        sb.AppendLine("    {");
        sb.AppendLine("        // Common transient exceptions");
        sb.AppendLine("        return ex is System.IO.IOException");
        sb.AppendLine("            || ex is System.Net.Http.HttpRequestException");
        sb.AppendLine("            || ex is System.TimeoutException;");
        sb.AppendLine("    }");

        sb.AppendLine("}");

        return sb.ToString();
    }

    private string GetNodeName(AttributeData attribute, string className)
    {
        var nodeName = GetAttributeProperty<string>(attribute, "NodeName");
        if (!string.IsNullOrEmpty(nodeName))
            return nodeName;

        // Convert PascalCase to snake_case
        return ToSnakeCase(className.Replace("Handler", ""));
    }

    private string ToSnakeCase(string text)
    {
        var sb = new StringBuilder();
        for (int i = 0; i < text.Length; i++)
        {
            var c = text[i];
            if (char.IsUpper(c) && i > 0)
                sb.Append('_');
            sb.Append(char.ToLower(c));
        }
        return sb.ToString();
    }

    private T? GetAttributeProperty<T>(AttributeData attribute, string propertyName)
    {
        var namedArg = attribute.NamedArguments.FirstOrDefault(a => a.Key == propertyName);
        if (namedArg.Value.Value is T value)
            return value;
        return default;
    }

    private string InferContextType(INamedTypeSymbol classSymbol, IMethodSymbol executeMethod, AttributeData attribute)
    {
        var attributeContextType = GetAttributeType(attribute, "ContextType");
        if (attributeContextType != null)
            return attributeContextType.ToDisplayString();

        // First check if method has a parameter that looks like context
        var contextParam = executeMethod.Parameters.FirstOrDefault(p =>
            p.Name.Contains("context", System.StringComparison.OrdinalIgnoreCase));

        if (contextParam != null)
            return contextParam.Type.ToDisplayString();

        // Check if class implements IGraphNodeHandler<TContext>
        foreach (var iface in classSymbol.AllInterfaces)
        {
            if (iface.Name == "IGraphNodeHandler" && iface.TypeArguments.Length == 1)
            {
                return iface.TypeArguments[0].ToDisplayString();
            }
        }

        // Default fallback
        return "HPD.Graph.Core.Context.GraphContext";
    }

    private ITypeSymbol? GetAttributeType(AttributeData attribute, string propertyName)
    {
        var namedArg = attribute.NamedArguments.FirstOrDefault(a => a.Key == propertyName);
        return namedArg.Value.Value as ITypeSymbol;
    }

    private bool HasHandlerNameProperty(INamedTypeSymbol classSymbol)
    {
        return classSymbol.GetMembers("HandlerName")
            .OfType<IPropertySymbol>()
            .Any();
    }

    private ITypeSymbol? GetTaskInnerType(ITypeSymbol returnType)
    {
        if (returnType is INamedTypeSymbol namedType && namedType.Name == "Task" && namedType.TypeArguments.Length == 1)
        {
            return namedType.TypeArguments[0];
        }
        return null;
    }

    private string GenerateMethodCall(IMethodSymbol method)
    {
        var args = new List<string>();

        foreach (var param in method.Parameters)
        {
            if (param.Type.Name == "CancellationToken")
            {
                args.Add("ct");
            }
            else
            {
                args.Add(param.Name);
            }
        }

        return $"this.ExecuteAsync({string.Join(", ", args)})";
    }

    private string FormatDefaultValue(object? value, ITypeSymbol type)
    {
        if (value == null)
            return "null";

        if (type.SpecialType == SpecialType.System_String)
            return $"\"{value}\"";

        if (type.TypeKind == TypeKind.Enum)
            return $"{type.ToDisplayString()}.{value}";

        return value.ToString() ?? "null";
    }

    private INamedTypeSymbol? FindNestedConfigClass(INamedTypeSymbol classSymbol)
    {
        // Look for a nested class named "Config"
        return classSymbol.GetTypeMembers()
            .FirstOrDefault(t => t.Name == "Config");
    }

    private IReadOnlyList<string> GenerateConfigPropertyReaders(StringBuilder sb, INamedTypeSymbol configClass)
    {
        var unsupportedProperties = new List<string>();

        foreach (var property in configClass.GetMembers().OfType<IPropertySymbol>())
        {
            if (property.SetMethod == null || property.IsStatic)
                continue;

            var readExpression = GetJsonElementReadExpression(property.Type, "value");
            if (readExpression == null)
            {
                unsupportedProperties.Add($"{property.Name}: {property.Type.ToDisplayString()}");
                continue;
            }

            var valueName = ToCamelCase(property.Name) + "Value";
            var propertyReadExpression = readExpression.Replace("value", valueName);

            sb.AppendLine($"        if (json.TryGetProperty(\"{property.Name}\", out var {valueName}) && {valueName}.ValueKind != System.Text.Json.JsonValueKind.Null)");
            sb.AppendLine("        {");
            sb.AppendLine($"            config.{property.Name} = {propertyReadExpression};");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        return unsupportedProperties;
    }

    private string? GetJsonElementReadExpression(ITypeSymbol type, string elementName)
    {
        var nullableUnderlying = GetNullableUnderlyingType(type);
        if (nullableUnderlying != null)
        {
            return GetJsonElementReadExpression(nullableUnderlying, elementName);
        }

        if (type is IArrayTypeSymbol arrayType)
        {
            var itemExpression = GetJsonArrayItemReadExpression(arrayType.ElementType, "item");
            if (itemExpression != null)
            {
                return $"System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Select({elementName}.EnumerateArray(), static item => {itemExpression}))";
            }
        }

        if (type is INamedTypeSymbol namedType && namedType.TypeArguments.Length == 1)
        {
            var typeName = namedType.ToDisplayString();
            if (typeName.StartsWith("System.Collections.Generic.List<") ||
                typeName.StartsWith("System.Collections.Generic.IReadOnlyList<") ||
                typeName.StartsWith("System.Collections.Generic.IList<") ||
                typeName.StartsWith("System.Collections.Generic.IEnumerable<"))
            {
                var itemType = namedType.TypeArguments[0];
                var itemExpression = GetJsonArrayItemReadExpression(itemType, "item");
                if (itemExpression != null)
                {
                    return $"new System.Collections.Generic.List<{itemType.ToDisplayString()}>(System.Linq.Enumerable.Select({elementName}.EnumerateArray(), static item => {itemExpression}))";
                }
            }
        }

        if (type.SpecialType == SpecialType.System_String)
            return $"{elementName}.GetString() ?? string.Empty";
        if (type.SpecialType == SpecialType.System_Boolean)
            return $"{elementName}.GetBoolean()";
        if (type.SpecialType == SpecialType.System_Int32)
            return $"{elementName}.GetInt32()";
        if (type.SpecialType == SpecialType.System_Int64)
            return $"{elementName}.GetInt64()";
        if (type.SpecialType == SpecialType.System_Double)
            return $"{elementName}.GetDouble()";
        if (type.SpecialType == SpecialType.System_Single)
            return $"{elementName}.GetSingle()";
        if (type.SpecialType == SpecialType.System_Decimal)
            return $"{elementName}.GetDecimal()";
        if (type.SpecialType == SpecialType.System_DateTime)
            return $"{elementName}.GetDateTime()";

        if (IsType(type, "System.Guid"))
            return $"{elementName}.GetGuid()";
        if (IsType(type, "System.DateTimeOffset"))
            return $"{elementName}.GetDateTimeOffset()";

        if (type.TypeKind == TypeKind.Enum)
            return $"{elementName}.ValueKind == System.Text.Json.JsonValueKind.String ? System.Enum.Parse<{type.ToDisplayString()}>({elementName}.GetString()!, ignoreCase: true) : ({type.ToDisplayString()}){elementName}.GetInt32()";

        return null;
    }

    private string? GetJsonArrayItemReadExpression(ITypeSymbol type, string elementName)
    {
        var nullableUnderlying = GetNullableUnderlyingType(type);
        if (nullableUnderlying != null)
        {
            return GetJsonArrayItemReadExpression(nullableUnderlying, elementName);
        }

        if (type.SpecialType == SpecialType.System_String)
            return $"{elementName}.GetString() ?? string.Empty";
        if (type.SpecialType == SpecialType.System_Boolean)
            return $"{elementName}.GetBoolean()";
        if (type.SpecialType == SpecialType.System_Int32)
            return $"{elementName}.GetInt32()";
        if (type.SpecialType == SpecialType.System_Int64)
            return $"{elementName}.GetInt64()";
        if (type.SpecialType == SpecialType.System_Double)
            return $"{elementName}.GetDouble()";
        if (type.SpecialType == SpecialType.System_Single)
            return $"{elementName}.GetSingle()";
        if (type.SpecialType == SpecialType.System_Decimal)
            return $"{elementName}.GetDecimal()";
        if (type.SpecialType == SpecialType.System_DateTime)
            return $"{elementName}.GetDateTime()";

        if (IsType(type, "System.Guid"))
            return $"{elementName}.GetGuid()";
        if (IsType(type, "System.DateTimeOffset"))
            return $"{elementName}.GetDateTimeOffset()";

        if (type.TypeKind == TypeKind.Enum)
            return $"{elementName}.ValueKind == System.Text.Json.JsonValueKind.String ? System.Enum.Parse<{type.ToDisplayString()}>({elementName}.GetString()!, ignoreCase: true) : ({type.ToDisplayString()}){elementName}.GetInt32()";

        return null;
    }

    private static ITypeSymbol? GetNullableUnderlyingType(ITypeSymbol type)
    {
        return type is INamedTypeSymbol namedType &&
               namedType.ConstructedFrom.SpecialType == SpecialType.System_Nullable_T &&
               namedType.TypeArguments.Length == 1
            ? namedType.TypeArguments[0]
            : null;
    }

    private static bool IsType(ITypeSymbol type, string fullyQualifiedMetadataName)
    {
        return string.Equals(type.ToDisplayString(), fullyQualifiedMetadataName, System.StringComparison.Ordinal);
    }

    private static string ToCamelCase(string text)
    {
        if (string.IsNullOrEmpty(text))
            return text;

        return char.ToLowerInvariant(text[0]) + text.Substring(1);
    }


}
