<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>HPD.Payments.Adapters.InMemory</AssemblyName>
    <RootNamespace>HPD.Payments.Adapters_InMemory</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../HPD.Payments.Primitives/HPD.Payments.Primitives.csproj" />
    <ProjectReference Include="../HPD.Payments.Contracts/HPD.Payments.Contracts.csproj" />
    <ProjectReference Include="../HPD.Payments.Supporting/HPD.Payments.Supporting.csproj" />
    <ProjectReference Include="../HPD.Payments.Persistence/HPD.Payments.Persistence.csproj" />
  </ItemGroup>
</Project>
