using System.Security.Cryptography;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

var arguments = Arguments.Parse(args);
var parseOptions = new CSharpParseOptions(
    LanguageVersionFacts.TryParse(arguments.LanguageVersion, out var languageVersion)
        ? languageVersion
        : LanguageVersion.Latest,
    preprocessorSymbols: arguments.Defines.Split(';', StringSplitOptions.RemoveEmptyEntries));

var trees = File.ReadAllLines(arguments.SourcesFile)
    .Where(File.Exists)
    .Where(path => !Path.GetFullPath(path).Equals(Path.GetFullPath(arguments.Output), StringComparison.OrdinalIgnoreCase))
    .Select(path => CSharpSyntaxTree.ParseText(File.ReadAllText(path), parseOptions, path))
    .ToArray();
var references = File.ReadAllLines(arguments.ReferencesFile)
    .Where(File.Exists)
    .Distinct(StringComparer.OrdinalIgnoreCase)
    .Select(static path => MetadataReference.CreateFromFile(path))
    .ToArray();
var compilation = CSharpCompilation.Create(
    arguments.AssemblyName,
    trees,
    references,
    new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));
var agentEvent = compilation.GetTypeByMetadataName("HPD.Agent.AgentEvent");
if (agentEvent is null)
{
    DeleteOutput(arguments.Output);
    return 0;
}

var eventTypes = trees
    .SelectMany(static tree => tree.GetRoot().DescendantNodes().OfType<TypeDeclarationSyntax>())
    .Select(declaration => compilation.GetSemanticModel(declaration.SyntaxTree).GetDeclaredSymbol(declaration))
    .OfType<INamedTypeSymbol>()
    .Where(type => !type.IsAbstract && !type.IsGenericType && IsModuleVisible(type) && InheritsFrom(type, agentEvent))
    .Distinct(SymbolEqualityComparer.Default)
    .Where(static type => type is not null)
    .Select(static type => type!)
    .OrderBy(static type => type.ToDisplayString(), StringComparer.Ordinal)
    .ToArray();
if (eventTypes.Length == 0)
{
    DeleteOutput(arguments.Output);
    return 0;
}

var identityBytes = SHA256.HashData(Encoding.UTF8.GetBytes(arguments.AssemblyName));
var contextName = $"HpdGeneratedAgentEventJsonContext_{Convert.ToHexString(identityBytes.AsSpan(0, 6)).ToLowerInvariant()}";
var source = new StringBuilder("// <auto-generated/>\n#nullable enable\n")
    .AppendLine("namespace HPD.Agent.Serialization;")
    .AppendLine("[global::System.Text.Json.Serialization.JsonSourceGenerationOptions(")
    .AppendLine("    PropertyNamingPolicy = global::System.Text.Json.Serialization.JsonKnownNamingPolicy.CamelCase,")
    .AppendLine("    DefaultIgnoreCondition = global::System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull,")
    .AppendLine("    WriteIndented = false)]");
foreach (var eventType in eventTypes)
    source.Append("[global::System.Text.Json.Serialization.JsonSerializable(typeof(")
        .Append(eventType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
        .AppendLine("))]");
source.Append("internal partial class ").Append(contextName)
    .AppendLine(" : global::System.Text.Json.Serialization.JsonSerializerContext;");

Directory.CreateDirectory(Path.GetDirectoryName(arguments.Output)!);
var generated = source.ToString();
if (!File.Exists(arguments.Output) || !StringComparer.Ordinal.Equals(File.ReadAllText(arguments.Output), generated))
    File.WriteAllText(arguments.Output, generated, new UTF8Encoding(false));
return 0;

static bool InheritsFrom(INamedTypeSymbol type, INamedTypeSymbol expected)
{
    for (var current = type.BaseType; current is not null; current = current.BaseType)
        if (SymbolEqualityComparer.Default.Equals(current, expected))
            return true;
    return false;
}

static bool IsModuleVisible(INamedTypeSymbol type)
{
    for (var current = type; current is not null; current = current.ContainingType)
        if (current.DeclaredAccessibility is not Accessibility.Public and not Accessibility.Internal)
            return false;
    return true;
}

static void DeleteOutput(string output)
{
    if (File.Exists(output))
        File.Delete(output);
}

internal sealed record Arguments(
    string SourcesFile,
    string ReferencesFile,
    string Output,
    string AssemblyName,
    string LanguageVersion,
    string Defines)
{
    public static Arguments Parse(string[] values)
    {
        var parsed = new Dictionary<string, string>(StringComparer.Ordinal);
        for (var index = 0; index < values.Length; index += 2)
            parsed.Add(values[index], values[index + 1]);
        return new Arguments(
            parsed["--sources"],
            parsed["--references"],
            parsed["--output"],
            parsed["--assembly"],
            parsed.GetValueOrDefault("--language", "latest"),
            parsed.GetValueOrDefault("--defines", ""));
    }
}
