using Microsoft.Extensions.Logging;

namespace HPD.Base.Tests.Observability;

internal sealed record HPDBaseLogEventContract(
    string Owner,
    int Id,
    string Name,
    LogLevel Level,
    string Template,
    string[] Properties);

internal static class HPDBaseLogEventRegistry
{
    public static readonly HPDBaseLogEventContract[] Active =
    [
        new("HPD.Base.Runtime", 1001, "StoreResultMalformed", LogLevel.Error,
            "The record store returned a malformed successful result for {OperationKind}.",
            ["OperationKind"]),
        new("HPD.Base.Runtime", 1002, "StoreUnavailable", LogLevel.Warning,
            "The required record store is unavailable for {OperationKind} ({CapabilityReason}).",
            ["OperationKind", "CapabilityReason"]),
        new("HPD.Base.Runtime", 1004, "MutationEventDispatchFailed", LogLevel.Warning,
            "Mutation event dispatch degraded for {OperationKind} with {ErrorCategory} ({ErrorCode}).",
            ["OperationKind", "ErrorCategory", "ErrorCode"]),
        new("HPD.Base.Runtime", 1005, "HealthContributorFailed", LogLevel.Warning,
            "A BASE health contributor failed.",
            []),
        new("HPD.Base.Runtime", 1006, "DiagnosticContributorFailed", LogLevel.Warning,
            "A BASE diagnostic contributor failed.",
            []),
        new("HPD.Base.Runtime", 1008, "StoreFailureMalformed", LogLevel.Error,
            "The record store returned a failed result without required error details for {OperationKind}.",
            ["OperationKind"]),
        new("HPD.Base.Runtime", 1009, "StoreDependencyUnavailable", LogLevel.Warning,
            "The record store dependency is temporarily unavailable for {OperationKind} ({ErrorCode}).",
            ["OperationKind", "ErrorCode"]),
        new("HPD.Base.Runtime", 1010, "StoreDependencyFailed", LogLevel.Error,
            "The record store dependency failed for {OperationKind} ({ErrorCode}).",
            ["OperationKind", "ErrorCode"]),
        new("HPD.Base.Sqlite", 3000, "DatabaseOpenFailed", LogLevel.Error,
            "The SQLite database could not be opened ({ErrorCode}, native {NativeErrorCode}/{NativeExtendedErrorCode}).",
            ["ErrorCode", "NativeErrorCode", "NativeExtendedErrorCode"]),
        new("HPD.Base.Sqlite", 3001, "DatabaseBusy", LogLevel.Warning,
            "The SQLite database is busy; retryable: {Retryable} (native {NativeErrorCode}/{NativeExtendedErrorCode}).",
            ["Retryable", "NativeErrorCode", "NativeExtendedErrorCode"]),
        new("HPD.Base.Sqlite", 3002, "DatabaseLocked", LogLevel.Warning,
            "The SQLite database is locked; retryable: {Retryable} (native {NativeErrorCode}/{NativeExtendedErrorCode}).",
            ["Retryable", "NativeErrorCode", "NativeExtendedErrorCode"]),
        new("HPD.Base.Sqlite", 3003, "SchemaMissing", LogLevel.Error,
            "The required SQLite schema is missing ({ErrorCode}).",
            ["ErrorCode"]),
        new("HPD.Base.Sqlite", 3005, "SchemaDiagnosticWarning", LogLevel.Warning,
            "SQLite schema diagnostics reported a degraded state ({ErrorCode}).",
            ["ErrorCode"]),
        new("HPD.Base.Sqlite", 3006, "QueryPlanRejected", LogLevel.Debug,
            "SQLite rejected an unsafe or unsupported query plan ({PlanStatus}, {ErrorCode}).",
            ["PlanStatus", "ErrorCode"]),
        new("HPD.Base.Sqlite", 3008, "ProviderOperationFailed", LogLevel.Error,
            "The SQLite provider operation failed for {OperationKind} with {ErrorCategory} ({ErrorCode}, native {NativeErrorCode}/{NativeExtendedErrorCode}).",
            ["OperationKind", "ErrorCategory", "ErrorCode", "NativeErrorCode", "NativeExtendedErrorCode"]),
        new("HPD.Base.Sqlite", 3009, "AdministrationQuarantined", LogLevel.Warning,
            "SQLite administration work remains in bounded quarantine for {OperationKind}.",
            ["OperationKind"]),
        new("HPD.Base.Files", 4000, "FileProviderUnavailable", LogLevel.Warning,
            "The required file provider is unavailable for {OperationKind} ({CapabilityReason}).",
            ["OperationKind", "CapabilityReason"]),
        new("HPD.Base.Files", 4001, "FileProviderOperationFailed", LogLevel.Error,
            "The file provider operation failed for {OperationKind} with {ErrorCategory} ({ErrorCode}).",
            ["OperationKind", "ErrorCategory", "ErrorCode"]),
        new("HPD.Base.Files", 4002, "FilePolicyDenied", LogLevel.Debug,
            "File policy denied {OperationKind} ({PolicyReasonCode}).",
            ["OperationKind", "PolicyReasonCode"]),
        new("HPD.Base.Files", 4003, "FileValidationRejected", LogLevel.Debug,
            "File validation rejected {OperationKind} ({ErrorCode}).",
            ["OperationKind", "ErrorCode"]),
        new("HPD.Base.Files.AspNetCore", 4500, "DownloadResponseStreamFailed", LogLevel.Warning,
            "The file download response stream failed after provider open with {ErrorCategory} ({ErrorCode}, response started: {ResponseStarted}).",
            ["ErrorCategory", "ErrorCode", "ResponseStarted"]),
        new("HPD.Base.Realtime", 5000, "EventStreamOpenFailed", LogLevel.Warning,
            "The realtime event stream could not be opened ({ErrorCategory}, {ErrorCode}).",
            ["ErrorCategory", "ErrorCode"]),
        new("HPD.Base.Realtime", 5001, "EventProjectionFailed", LogLevel.Warning,
            "A realtime event could not be projected ({ErrorCategory}, {ErrorCode}).",
            ["ErrorCategory", "ErrorCode"]),
        new("HPD.Base.Realtime.AspNetCore", 5500, "WebSocketJoinRejectedProtocol", LogLevel.Information,
            "A realtime channel join was rejected by protocol or configuration ({ErrorCode}).",
            ["ErrorCode"]),
        new("HPD.Base.Realtime.AspNetCore", 5501, "WebSocketSendFailed", LogLevel.Warning,
            "A realtime WebSocket send failed ({ErrorCategory}, {ErrorCode}).",
            ["ErrorCategory", "ErrorCode"]),
        new("HPD.Base.Realtime.AspNetCore", 5503, "PayloadDropped", LogLevel.Information,
            "A realtime protocol payload was dropped ({ErrorCode}, {PayloadSizeBucket}).",
            ["ErrorCode", "PayloadSizeBucket"]),
        new("HPD.Base.Realtime.AspNetCore", 5504, "ProtocolMessageUnsupported", LogLevel.Debug,
            "A realtime protocol message was rejected ({ProtocolMessageKind}, {ErrorCode}).",
            ["ProtocolMessageKind", "ErrorCode"]),
        new("HPD.Base.Realtime.AspNetCore", 5505, "WebSocketReceiveFailed", LogLevel.Warning,
            "A realtime WebSocket receive or channel pump failed ({ErrorCategory}, {ErrorCode}).",
            ["ErrorCategory", "ErrorCode"]),
        new("HPD.Base.Realtime.AspNetCore", 5506, "ConnectionOpened", LogLevel.Debug,
            "A realtime WebSocket connection opened.",
            []),
        new("HPD.Base.Realtime.AspNetCore", 5508, "WebSocketJoinRejectedPolicy", LogLevel.Debug,
            "A realtime WebSocket channel join was rejected by policy ({ErrorCode}).",
            ["ErrorCode"]),
        new("HPD.Base.Realtime.AspNetCore", 5509, "WebSocketConnectionRejected", LogLevel.Information,
            "A realtime WebSocket connection was rejected ({ErrorCode}).",
            ["ErrorCode"]),
        new("HPD.Base.Realtime.AspNetCore", 5510, "ConnectionIdleTimedOut", LogLevel.Information,
            "A realtime WebSocket connection exceeded its receive-idle limit ({ErrorCode}).",
            ["ErrorCode"]),
        new("HPD.Base.Realtime.AspNetCore", 5511, "SlowConsumerTerminated", LogLevel.Information,
            "A realtime channel was terminated because its consumer was too slow ({ErrorCode}).",
            ["ErrorCode"]),
        new("HPD.Base.Auth.HPDAuth", 6000, "AuthServicesUnavailable", LogLevel.Warning,
            "Required HPD.Auth integration services are unavailable ({DiagnosticCode}).",
            ["DiagnosticCode"]),
        new("HPD.Base.Auth.HPDAuth", 6001, "GrantConfigurationMissing", LogLevel.Warning,
            "Required HPD.Auth grant configuration is unavailable ({DiagnosticCode}).",
            ["DiagnosticCode"]),
        new("HPD.Base.Auth.HPDAuth", 6002, "GrantProviderFailed", LogLevel.Warning,
            "An HPD.Auth grant provider failed ({ErrorCategory}, {ErrorCode}).",
            ["ErrorCategory", "ErrorCode"]),
        new("HPD.Base.Auth.HPDAuth", 6003, "AuthPolicyDenied", LogLevel.Debug,
            "HPD.Auth policy denied {OperationKind} ({PolicyReasonCode}).",
            ["OperationKind", "PolicyReasonCode"]),
        new("HPD.Base.Auth.HPDAuth", 6004, "PrivilegedBypassUsed", LogLevel.Debug,
            "An HPD.Auth privileged bypass was applied ({BypassKind}).",
            ["BypassKind"]),
        new("HPD.Base.Auth.HPDAuth.AspNetCore", 6502, "PrincipalEnrichmentFailed", LogLevel.Warning,
            "HPD.Auth principal enrichment failed ({ErrorCategory}, {ErrorCode}).",
            ["ErrorCategory", "ErrorCode"])
    ];
}
