using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace HPD.Agent.Bots.SourceGenerator.Generators;

/// <summary>
/// Generates {BotName}Dispatch.g.cs for each [HpdBot] class.
/// </summary>
internal static class DispatchGenerator
{
    public static void Generate(
        SourceProductionContext context,
        IReadOnlyList<BotInfo> adapters)
    {
        foreach (var adapter in adapters)
        {
            var source = BuildSource(adapter);
            context.AddSource($"{adapter.ClassName}Dispatch.g.cs",
                SourceText.From(source, Encoding.UTF8));
        }
    }

    private static string BuildSource(BotInfo adapter)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Microsoft.AspNetCore.Http;");
        sb.AppendLine("using HPD.Agent.Bots;");
        sb.AppendLine("using HPD.Agent.Bots.Contracts;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine();
        sb.AppendLine($"namespace {adapter.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"public partial class {adapter.ClassName} : IBotAdapter");
        sb.AppendLine("{");
        sb.AppendLine($"    public string Name => \"{adapter.Name}\";");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Generated transport-neutral bot dispatch entry point.</summary>");
        sb.AppendLine("    public async Task<BotAdapterResponse> HandleAsync(");
        sb.AppendLine("        BotInboundEnvelope envelope,");
        sb.AppendLine("        CancellationToken cancellationToken = default)");
        sb.AppendLine("    {");
        sb.AppendLine("        var ctx = new BotRequestContext(envelope, cancellationToken);");
        sb.AppendLine("        var bodyBytes = envelope.Body;");
        sb.AppendLine();

        if (adapter.PreDispatchMethodName is not null)
        {
            sb.AppendLine($"        var preResult = await {adapter.PreDispatchMethodName}(ctx, bodyBytes);");
            sb.AppendLine("        if (preResult is not null) return preResult;");
            sb.AppendLine();
        }

        if (adapter.BodyExtractorMethodName is not null)
        {
            sb.AppendLine($"        var (eventType, dispatchBytes) = {adapter.BodyExtractorMethodName}(ctx, bodyBytes);");
        }
        else
        {
            sb.AppendLine("        var eventType = ExtractEventType(bodyBytes);");
            sb.AppendLine("        var dispatchBytes = bodyBytes;");
        }
        sb.AppendLine();

        sb.AppendLine("        try");
        sb.AppendLine("        {");
        sb.AppendLine("            return await DispatchByTypeAsync(ctx, dispatchBytes, eventType);");
        sb.AppendLine("        }");
        sb.AppendLine("        catch (BotValidationException)      { return BotAdapterResponse.Status(400); }");
        sb.AppendLine("        catch (BotAuthenticationException)  { return BotAdapterResponse.Status(401); }");
        sb.AppendLine("        catch (BotRateLimitException)       { return BotAdapterResponse.Status(429); }");
        sb.AppendLine("        catch (BotPermissionException)      { return BotAdapterResponse.Status(403); }");
        sb.AppendLine("        catch (BotNotFoundException)        { return BotAdapterResponse.Status(404); }");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine("    /// <summary>Generated ASP.NET bridge for existing webhook endpoint mapping.</summary>");
        sb.AppendLine("    public async Task<IResult> HandleWebhookAsync(HttpContext httpContext)");
        sb.AppendLine("    {");
        sb.AppendLine("        var envelope = await CreateEnvelopeAsync(httpContext);");
        sb.AppendLine("        var response = await HandleAsync(envelope, httpContext.RequestAborted);");
        sb.AppendLine("        return new BotAdapterHttpResult(response);");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine("    private static async Task<BotInboundEnvelope> CreateEnvelopeAsync(HttpContext httpContext)");
        sb.AppendLine("    {");
        sb.AppendLine("        byte[] bodyBytes;");
        sb.AppendLine("        using (var ms = new System.IO.MemoryStream())");
        sb.AppendLine("        {");
        sb.AppendLine("            await httpContext.Request.Body.CopyToAsync(ms, httpContext.RequestAborted);");
        sb.AppendLine("            bodyBytes = ms.ToArray();");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        var headers = new Dictionary<string, string[]>(StringComparer.OrdinalIgnoreCase);");
        sb.AppendLine("        foreach (var pair in httpContext.Request.Headers)");
        sb.AppendLine("        {");
        sb.AppendLine("            var values = new string[pair.Value.Count];");
        sb.AppendLine("            for (var i = 0; i < pair.Value.Count; i++) values[i] = pair.Value[i] ?? string.Empty;");
        sb.AppendLine("            headers[pair.Key] = values;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        var query = new Dictionary<string, string[]>(StringComparer.OrdinalIgnoreCase);");
        sb.AppendLine("        foreach (var pair in httpContext.Request.Query)");
        sb.AppendLine("        {");
        sb.AppendLine("            var values = new string[pair.Value.Count];");
        sb.AppendLine("            for (var i = 0; i < pair.Value.Count; i++) values[i] = pair.Value[i] ?? string.Empty;");
        sb.AppendLine("            query[pair.Key] = values;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        return new BotInboundEnvelope");
        sb.AppendLine("        {");
        sb.AppendLine("            Method = httpContext.Request.Method,");
        sb.AppendLine("            Path = httpContext.Request.Path.Value,");
        sb.AppendLine("            Body = bodyBytes,");
        sb.AppendLine("            Headers = headers,");
        sb.AppendLine("            Query = query,");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine("    private sealed class BotAdapterHttpResult(BotAdapterResponse response) : IResult");
        sb.AppendLine("    {");
        sb.AppendLine("        public async Task ExecuteAsync(HttpContext httpContext)");
        sb.AppendLine("        {");
        sb.AppendLine("            httpContext.Response.StatusCode = response.StatusCode;");
        sb.AppendLine("            if (response.ContentType is not null)");
        sb.AppendLine("                httpContext.Response.ContentType = response.ContentType;");
        sb.AppendLine("            foreach (var header in response.Headers)");
        sb.AppendLine("                httpContext.Response.Headers[header.Key] = header.Value;");
        sb.AppendLine("            if (response.Body is { Length: > 0 })");
        sb.AppendLine("                await httpContext.Response.Body.WriteAsync(response.Body, httpContext.RequestAborted);");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();

        if (adapter.BodyExtractorMethodName is null)
        {
            sb.AppendLine("    private static string? ExtractEventType(byte[] bodyBytes)");
            sb.AppendLine("    {");
            sb.AppendLine("        try");
            sb.AppendLine("        {");
            sb.AppendLine("            using var doc = JsonDocument.Parse(bodyBytes);");
            sb.AppendLine("            var root = doc.RootElement;");
            sb.AppendLine("            if (root.TryGetProperty(\"type\", out var outerType))");
            sb.AppendLine("                return outerType.GetString();");
            sb.AppendLine("        }");
            sb.AppendLine("        catch { }");
            sb.AppendLine("        return null;");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.AppendLine("    private async Task<BotAdapterResponse> DispatchByTypeAsync(");
        sb.AppendLine("        BotRequestContext ctx, byte[] bodyBytes, string? eventType)");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (eventType)");
        sb.AppendLine("        {");

        foreach (var handler in adapter.Handlers)
        {
            foreach (var eventType in handler.EventTypes)
            {
                sb.AppendLine($"            case \"{eventType}\":");
            }
            sb.AppendLine("            {");
            sb.AppendLine($"                var payload = JsonSerializer.Deserialize(bodyBytes, {adapter.ClassName}JsonContext.Default.{handler.PayloadJsonTypeInfoProperty});");
            sb.AppendLine("                if (payload is null) return BotAdapterResponse.Ok();");
            sb.AppendLine($"                return await {handler.MethodName}(ctx, payload);");
            sb.AppendLine("            }");
        }

        sb.AppendLine("            default: return BotAdapterResponse.Ok();");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
