using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace HPD.Agent.Bots.SourceGenerator.Generators;

/// <summary>
/// Generates {BotName}Dispatch.g.cs for each [HpdBot] class.
///
/// The generated HandleWebhookAsync method:
///   1. Reads body once
///   2. Calls [HpdPreDispatch] hook if declared (adapter owns verification / challenge bypass)
///   3. Calls [HpdBodyExtractor] hook if declared, else uses default JSON "type" extraction
///   4. Dispatches to the [HpdWebhookHandler] method matching the event type
///   5. Maps known adapter exceptions to HTTP status codes
/// </summary>
internal static class DispatchGenerator
{
    public static void Generate(
        SourceProductionContext context,
        IReadOnlyList<BotInfo> adapters)
    {
        foreach (var adapter in adapters)
        {
            var source = BuildSource(adapter);
            context.AddSource($"{adapter.ClassName}Dispatch.g.cs",
                SourceText.From(source, Encoding.UTF8));
        }
    }

    private static string BuildSource(BotInfo adapter)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Microsoft.AspNetCore.Http;");
        sb.AppendLine("using Microsoft.AspNetCore.Http.Extensions;");
        sb.AppendLine("using HPD.Agent.Bots;");
        sb.AppendLine("using HPD.Agent.Bots.Contracts;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine();
        sb.AppendLine($"namespace {adapter.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"public partial class {adapter.ClassName}");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Generated webhook dispatch entry point.</summary>");
        sb.AppendLine("    public async Task<IResult> HandleWebhookAsync(HttpContext ctx)");
        sb.AppendLine("    {");
        sb.AppendLine("        var ct = ctx.RequestAborted;");
        sb.AppendLine();

        // ── Read body once ────────────────────────────────────────────────────
        sb.AppendLine("        // Read body once — reused for both pre-dispatch hook and deserialization");
        sb.AppendLine("        byte[] bodyBytes;");
        sb.AppendLine("        using (var ms = new System.IO.MemoryStream())");
        sb.AppendLine("        {");
        sb.AppendLine("            await ctx.Request.Body.CopyToAsync(ms, ct);");
        sb.AppendLine("            bodyBytes = ms.ToArray();");
        sb.AppendLine("        }");
        sb.AppendLine();

        // ── Pre-dispatch hook ─────────────────────────────────────────────────
        if (adapter.PreDispatchMethodName is not null)
        {
            sb.AppendLine($"        var preResult = await {adapter.PreDispatchMethodName}(ctx, bodyBytes);");
            sb.AppendLine("        if (preResult is not null) return preResult;");
            sb.AppendLine();
        }

        // ── Body extraction ───────────────────────────────────────────────────
        if (adapter.BodyExtractorMethodName is not null)
        {
            sb.AppendLine($"        var (eventType, dispatchBytes) = {adapter.BodyExtractorMethodName}(ctx, bodyBytes);");
        }
        else
        {
            sb.AppendLine("        var eventType = ExtractEventType(bodyBytes);");
            sb.AppendLine("        var dispatchBytes = bodyBytes;");
        }
        sb.AppendLine();

        // ── Exception wrapper + dispatch ──────────────────────────────────────
        sb.AppendLine("        try");
        sb.AppendLine("        {");
        sb.AppendLine("            return await DispatchByTypeAsync(ctx, dispatchBytes, eventType, ct);");
        sb.AppendLine("        }");
        sb.AppendLine("        catch (BotValidationException)      { return Results.BadRequest(); }");
        sb.AppendLine("        catch (BotAuthenticationException)  { return Results.Unauthorized(); }");
        sb.AppendLine("        catch (BotRateLimitException)       { return Results.StatusCode(429); }");
        sb.AppendLine("        catch (BotPermissionException)      { return Results.Forbid(); }");
        sb.AppendLine("        catch (BotNotFoundException)        { return Results.NotFound(); }");
        sb.AppendLine("    }");
        sb.AppendLine();

        // ── Default ExtractEventType helper (only when no body extractor) ─────
        if (adapter.BodyExtractorMethodName is null)
        {
            sb.AppendLine("    private static string? ExtractEventType(byte[] bodyBytes)");
            sb.AppendLine("    {");
            sb.AppendLine("        try");
            sb.AppendLine("        {");
            sb.AppendLine("            using var doc = JsonDocument.Parse(bodyBytes);");
            sb.AppendLine("            var root = doc.RootElement;");
            sb.AppendLine("            if (root.TryGetProperty(\"type\", out var outerType))");
            sb.AppendLine("            {");
            sb.AppendLine("                return outerType.GetString();");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("        catch { }");
            sb.AppendLine("        return null;");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        // ── Switch dispatch ───────────────────────────────────────────────────
        sb.AppendLine("    private async Task<IResult> DispatchByTypeAsync(");
        sb.AppendLine("        HttpContext ctx, byte[] bodyBytes, string? eventType, CancellationToken ct)");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (eventType)");
        sb.AppendLine("        {");

        foreach (var handler in adapter.Handlers)
        {
            foreach (var eventType in handler.EventTypes)
            {
                sb.AppendLine($"            case \"{eventType}\":");
            }
            sb.AppendLine("            {");
            sb.AppendLine($"                var payload = JsonSerializer.Deserialize(bodyBytes, {adapter.ClassName}JsonContext.Default.{handler.PayloadJsonTypeInfoProperty});");
            sb.AppendLine($"                if (payload is null) return Results.Ok();");
            sb.AppendLine($"                return await {handler.MethodName}(ctx, payload);");
            sb.AppendLine("            }");
        }

        sb.AppendLine("            default: return Results.Ok(); // unknown event types → ACK and ignore");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
