<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>HPD-ML-Core</PackageId>
    <TargetFramework>net11.0</TargetFramework>
    <TargetFrameworks></TargetFrameworks>
    <LangVersion>preview</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);SYSLIB5001</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../HPD.ML.Abstractions/HPD.ML.Abstractions.csproj" />
    <ProjectReference Include="../../../shared/src/HPD-Events/HPD-Events.csproj" />
    <ProjectReference Include="../../../../../../../../HPD-Math-Framework/Helium/src/Helium.Algebra/Helium.Algebra.csproj" />
  </ItemGroup>

</Project>
