<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <TargetFrameworks></TargetFrameworks>
    <RootNamespace>HPD.Base.Studio</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishAot>true</PublishAot>
    <IsAotCompatible>true</IsAotCompatible>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
  </PropertyGroup>

  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <PackageId>HPD.Base.Studio</PackageId>
    <Description>HPD BASE Studio module package for HPD AI Platform.</Description>
    <PackageTags>base;dbase;data;storage;realtime;studio;svelte</PackageTags>
    <StudioBaseModuleRoot>$(MSBuildThisFileDirectory)..\..\..\..\typescript\hpd-ai-studio\modules\hpd-base-studio\</StudioBaseModuleRoot>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\HPD-AI.Platform\HPD-AI.Platform.csproj" />
    <ProjectReference Include="..\HPD.Base\HPD.Base.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="$(StudioBaseModuleRoot)**\*" Exclude="$(StudioBaseModuleRoot)node_modules\**\*;$(StudioBaseModuleRoot)dist\**\*;$(StudioBaseModuleRoot).DS_Store" Pack="true" PackagePath="clientapp-modules\hpd-base-studio\%(RecursiveDir)%(Filename)%(Extension)" />
    <EmbeddedResource Include="$(StudioBaseModuleRoot)dist\base.js" LogicalName="HPD.Base.Studio.Assets.base.js" />
    <None Include="$(StudioBaseModuleRoot)dist\base.js" Pack="true" PackagePath="studio-assets\base\6c6d65420bde4c64faaaea95ec0a74b36c719d66c0edd2eec1aa7d7f461873e5.js" />
  </ItemGroup>

</Project>
