using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("HPD.Base.AspNetCore")]
[assembly: InternalsVisibleTo("HPD.Base.Testing")]
[assembly: InternalsVisibleTo("HPD.Base.Tests")]
[assembly: InternalsVisibleTo("HPD.Base.Studio")]
[assembly: InternalsVisibleTo("HPD.Base.Studio.Tests")]
[assembly: InternalsVisibleTo("HPD.Base.AspNetCore.Tests")]
[assembly: InternalsVisibleTo("HPD.Base.Auth.Tests")]
[assembly: InternalsVisibleTo("HPD.Base.Realtime")]
[assembly: InternalsVisibleTo("HPD.Base.Sqlite")]
[assembly: InternalsVisibleTo("HPD.Base.Sqlite.Tests")]
[assembly: InternalsVisibleTo("HPD.Base.Vector.Tests")]
[assembly: InternalsVisibleTo("HPD.Base.InMemory.Vector.AotSmoke")]
[assembly: InternalsVisibleTo("HPD.Base.AotSmoke")]
[assembly: InternalsVisibleTo("HPD.Base.Sqlite.AotSmoke")]
