<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <PublishAot>false</PublishAot>
    <PackAsTool>false</PackAsTool>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
</Project>
