using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace HPD.Agent.Bots.SourceGenerator.Generators;

/// <summary>
/// Generates {BotName}Registration.g.cs for each [HpdBot] class.
/// Emits AddXxxBot() and MapXxxWebhook() extension methods.
/// </summary>
internal static class RegistrationGenerator
{
    public static void Generate(
        SourceProductionContext context,
        IReadOnlyList<BotInfo> adapters)
    {
        foreach (var adapter in adapters)
        {
            var source = BuildSource(adapter);
            context.AddSource($"{adapter.ClassName}Registration.g.cs",
                SourceText.From(source, Encoding.UTF8));
        }
    }

    private static string BuildSource(BotInfo adapter)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using Microsoft.AspNetCore.Builder;");
        sb.AppendLine("using Microsoft.AspNetCore.Http;");
        sb.AppendLine("using Microsoft.AspNetCore.Routing;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection.Extensions;");
        sb.AppendLine("using Microsoft.Extensions.Options;");
        sb.AppendLine("using HPD.Agent.Bots;");
        sb.AppendLine("using HPD.Agent.Bots.Session;");
        sb.AppendLine("using HPD.Agent.Bots.Streaming;");
        sb.AppendLine();

        var adapterName = adapter.Name; // e.g. "slack"
        var className   = adapter.ClassName; // e.g. "SlackBot"
        var configName  = $"{className}Config";
        // Capitalised for method names: "Slack"
        var pascal = char.ToUpper(adapterName[0]) + adapterName.Substring(1);

        sb.AppendLine($"namespace {adapter.Namespace};");
        sb.AppendLine();

        // ── DI extensions ──────────────────────────────────────────────────────
        sb.AppendLine($"public static partial class {className}ServiceCollectionExtensions");
        sb.AppendLine("{");
        sb.AppendLine($"    /// <summary>Registers the {pascal} adapter and its configuration.</summary>");
        sb.AppendLine($"    public static IServiceCollection Add{pascal}Bot(");
        sb.AppendLine($"        this IServiceCollection services,");
        sb.AppendLine($"        Action<{configName}> configure)");
        sb.AppendLine("    {");

        if (adapter.SocketTransportTypeFqn is not null && !string.IsNullOrEmpty(adapter.SocketConfigProperty))
        {
            // configure is called once upfront to read the config property for the socket check.
            // services.Configure(configure) stores the delegate and calls it again at options
            // resolution time — this is identical to the no-socket path and is expected behaviour.
            // Using services.Configure(configure) (not Options.Create) means IOptions<T>,
            // IOptionsMonitor<T>, and IOptionsSnapshot<T> all resolve correctly.
            sb.AppendLine($"        var _cfg = new {configName}();");
            sb.AppendLine($"        configure(_cfg);");
            sb.AppendLine($"        services.Configure<{configName}>(configure);");
            sb.AppendLine($"        if (_cfg.{adapter.SocketConfigProperty} is not null)");
            sb.AppendLine($"            services.AddHostedService<{adapter.SocketTransportTypeFqn}>();");
        }
        else
        {
            sb.AppendLine($"        services.Configure(configure);");
        }

        if (adapter.Streaming is not null)
        {
            sb.AppendLine($"        services.Configure<BotStreamingOptions>(\"{adapterName}\", options =>");
            sb.AppendLine("        {");
            sb.AppendLine($"            options.Strategy = StreamingStrategy.{adapter.Streaming.Strategy};");
            sb.AppendLine($"            options.DebounceMs = {adapter.Streaming.DebounceMs};");
            sb.AppendLine("        });");
        }

        sb.AppendLine($"        services.TryAddSingleton<{className}>();");
        sb.AppendLine("        services.TryAddEnumerable(ServiceDescriptor.Singleton<HPD.Agent.Bots.AspNetCore.IBotRegistryProvider, HPD.Agent.Bots.Generated.GeneratedBotRegistryProvider>());");
        sb.AppendLine($"        services.TryAddSingleton<HPD.Agent.Bots.Session.PlatformSessionMapper>();");
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        // ── Endpoint extensions ───────────────────────────────────────────────
        sb.AppendLine($"public static partial class {className}EndpointRouteBuilderExtensions");
        sb.AppendLine("{");
        sb.AppendLine($"    /// <summary>Maps the {pascal} webhook endpoint and wires up the adapter.</summary>");
        sb.AppendLine($"    public static IEndpointConventionBuilder Map{pascal}Webhook(");
        sb.AppendLine($"        this IEndpointRouteBuilder app,");
        sb.AppendLine($"        string path = \"/webhooks/{adapterName}\")");
        sb.AppendLine("    {");
        sb.AppendLine($"        var adapter = app.ServiceProvider.GetRequiredService<{className}>();");
        if (adapter.WebhookMethods.Count > 0)
        {
            var methods = string.Join(", ", adapter.WebhookMethods.Select(m => $"\"{m}\""));
            sb.AppendLine($"        return app.MapMethods(path, [{methods}], (HttpContext ctx) => adapter.HandleWebhookAsync(ctx));");
        }
        else
        {
            sb.AppendLine($"        return app.MapPost(path, (HttpContext ctx) => adapter.HandleWebhookAsync(ctx));");
        }
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
