using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace HPD.Agent.Bots.SourceGenerator.Generators;

/// <summary>
/// Generates Format(...) and Parse(string) methods for records marked with [ThreadId].
/// </summary>
internal static class ThreadIdGenerator
{
    public static void Generate(
        SourceProductionContext context,
        IReadOnlyList<ThreadIdInfo> threadIds)
    {
        foreach (var threadId in threadIds)
        {
            var source = BuildSource(threadId);
            context.AddSource($"{threadId.RecordName}ThreadId.g.cs",
                SourceText.From(source, Encoding.UTF8));
        }
    }

    public static IReadOnlyList<string> GetSlots(string format)
    {
        var slots = new List<string>();
        foreach (var segment in ParseFormat(format))
        {
            if (segment.IsSlot)
                slots.Add(segment.Value);
        }

        return slots;
    }

    private static string BuildSource(ThreadIdInfo threadId)
    {
        var segments = ParseFormat(threadId.Format).ToList();
        var slotProperties = threadId.Slots
            .Select(slot => FindProperty(threadId, slot))
            .Where(property => property is not null)
            .Select(property => property!)
            .ToList();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine();
        sb.AppendLine($"namespace {threadId.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"public partial record {threadId.RecordName}");
        sb.AppendLine("{");
        AppendFormatMethod(sb, segments, slotProperties);
        sb.AppendLine();
        AppendParseMethod(sb, threadId, segments, slotProperties);
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void AppendFormatMethod(
        StringBuilder sb,
        IReadOnlyList<FormatSegment> segments,
        IReadOnlyList<ThreadIdPropertyInfo> slotProperties)
    {
        var parameters = string.Join(", ", slotProperties.Select(property =>
        {
            var parameter = ToParameterName(property.Name);
            var suffix = property.HasExplicitDefaultValue && property.ExplicitDefaultValue is not null
                ? $" = {property.ExplicitDefaultValue}"
                : "";
            return $"{property.TypeFqn} {parameter}{suffix}";
        }));

        sb.AppendLine($"    public static string Format({parameters})");
        sb.Append("        => $\"");
        foreach (var segment in segments)
        {
            if (segment.IsSlot)
                sb.Append('{').Append(ToParameterName(segment.Value)).Append('}');
            else
                sb.Append(EscapeInterpolatedStringLiteral(segment.Value));
        }
        sb.AppendLine("\";");
    }

    private static void AppendParseMethod(
        StringBuilder sb,
        ThreadIdInfo threadId,
        IReadOnlyList<FormatSegment> segments,
        IReadOnlyList<ThreadIdPropertyInfo> slotProperties)
    {
        sb.AppendLine($"    public static {threadId.RecordName} Parse(string value)");
        sb.AppendLine("    {");
        sb.AppendLine("        ArgumentNullException.ThrowIfNull(value);");
        sb.AppendLine("        var position = 0;");

        for (var i = 0; i < segments.Count; i++)
        {
            var segment = segments[i];
            if (!segment.IsSlot)
            {
                if (segment.Value.Length == 0) continue;
                sb.AppendLine($"        if (!value.AsSpan(position).StartsWith(\"{EscapeStringLiteral(segment.Value)}\", StringComparison.Ordinal))");
                sb.AppendLine($"            throw new FormatException($\"Value '{{value}}' does not match thread id format '{EscapeInterpolatedStringLiteral(threadId.Format)}'.\");");
                sb.AppendLine($"        position += {segment.Value.Length};");
                continue;
            }

            var property = FindProperty(threadId, segment.Value)!;
            var nextLiteral = segments.Skip(i + 1).FirstOrDefault(s => !s.IsSlot && s.Value.Length > 0);
            var variable = ToParameterName(property.Name);

            if (nextLiteral is null)
            {
                sb.AppendLine($"        var {variable}Text = value.Substring(position);");
                sb.AppendLine("        position = value.Length;");
            }
            else
            {
                sb.AppendLine($"        var {variable}End = value.IndexOf(\"{EscapeStringLiteral(nextLiteral.Value)}\", position, StringComparison.Ordinal);");
                sb.AppendLine($"        if ({variable}End < 0)");
                sb.AppendLine($"            throw new FormatException($\"Value '{{value}}' does not match thread id format '{EscapeInterpolatedStringLiteral(threadId.Format)}'.\");");
                sb.AppendLine($"        var {variable}Text = value.Substring(position, {variable}End - position);");
                sb.AppendLine($"        position = {variable}End;");
            }

            sb.AppendLine($"        var {variable} = {ConvertFromString(property, variable + "Text")};");
        }

        sb.AppendLine("        if (position != value.Length)");
        sb.AppendLine($"            throw new FormatException($\"Value '{{value}}' does not match thread id format '{EscapeInterpolatedStringLiteral(threadId.Format)}'.\");");
        sb.AppendLine();
        sb.AppendLine($"        return new {threadId.RecordName}(");
        for (var i = 0; i < slotProperties.Count; i++)
        {
            var property = slotProperties[i];
            var suffix = i == slotProperties.Count - 1 ? "" : ",";
            sb.AppendLine($"            {property.Name}: {ToParameterName(property.Name)}{suffix}");
        }
        sb.AppendLine("        );");
        sb.AppendLine("    }");
    }

    private static string ConvertFromString(ThreadIdPropertyInfo property, string valueExpression)
        => property.TypeFqn switch
        {
            "string" or "global::System.String" => valueExpression,
            _ => $"({property.TypeFqn})System.ComponentModel.TypeDescriptor.GetConverter(typeof({property.TypeFqn})).ConvertFromInvariantString({valueExpression})!",
        };

    private static ThreadIdPropertyInfo? FindProperty(ThreadIdInfo threadId, string slot)
        => threadId.Properties.FirstOrDefault(p => string.Equals(p.Name, slot, StringComparison.OrdinalIgnoreCase));

    private static IEnumerable<FormatSegment> ParseFormat(string format)
    {
        var index = 0;
        while (index < format.Length)
        {
            var open = format.IndexOf('{', index);
            if (open < 0)
            {
                yield return new FormatSegment(IsSlot: false, format.Substring(index));
                yield break;
            }

            if (open > index)
                yield return new FormatSegment(IsSlot: false, format.Substring(index, open - index));

            var close = format.IndexOf('}', open + 1);
            if (close < 0)
            {
                yield return new FormatSegment(IsSlot: false, format.Substring(open));
                yield break;
            }

            yield return new FormatSegment(IsSlot: true, format.Substring(open + 1, close - open - 1));
            index = close + 1;
        }
    }

    private static string ToParameterName(string propertyName)
        => propertyName.Length == 0
            ? propertyName
            : char.ToLowerInvariant(propertyName[0]) + propertyName.Substring(1);

    private static string EscapeInterpolatedStringLiteral(string value)
        => value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("{", "{{")
            .Replace("}", "}}");

    private static string EscapeStringLiteral(string value)
        => value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"");

    private sealed record FormatSegment(bool IsSlot, string Value);
}
