<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Rhodium.Core\Rhodium.Core.csproj" />
    <ProjectReference Include="..\..\src\Rhodium.Connectivity\Rhodium.Connectivity.csproj" />
    <ProjectReference Include="..\..\src\Rhodium.Simulation\Rhodium.Simulation.csproj" />
  </ItemGroup>

</Project>
