<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>HPD.Payments.Extensions.OutOfProcess</AssemblyName>
    <RootNamespace>HPD.Payments.Extensions_OutOfProcess</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../HPD.Payments.Primitives/HPD.Payments.Primitives.csproj" />
    <ProjectReference Include="../HPD.Payments.Contracts/HPD.Payments.Contracts.csproj" />
    <ProjectReference Include="../HPD.Payments.Supporting/HPD.Payments.Supporting.csproj" />
    <ProjectReference Include="../HPD.Payments.Serialization/HPD.Payments.Serialization.csproj" />
  </ItemGroup>
</Project>
