using System.Text.Json;
using System.Text.Json.Serialization;
using HPD.Agent;
using HPD.Agent.Security;
using HPD.Agent.ToolHarness.Coding;
using HPD.Agent.ToolHarness.Coding.Debugging;
using HPD.Environment.Contracts;
using HPD.Events;
using HPDOS.ToolHarnesses.Middleware;

[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    WriteIndented = false)]
[JsonSerializable(typeof(AgentWorkspace))]
[JsonSerializable(typeof(AgentWorkspaceRoot))]
[JsonSerializable(typeof(LanguageServerOptions))]
[JsonSerializable(typeof(EnvironmentContextConfig))]
[JsonSerializable(typeof(IReadOnlyList<AgentWorkspaceRoot>), TypeInfoPropertyName = "AgentWorkspaceRootReadOnlyList")]
[JsonSerializable(typeof(List<AgentWorkspaceRoot>), TypeInfoPropertyName = "AgentWorkspaceRootList")]

[JsonSerializable(typeof(ContentAddress))]
[JsonSerializable(typeof(ExecuteCommandPermissionPlan))]
[JsonSerializable(typeof(SimpleCommandPermissionPlan))]
[JsonSerializable(typeof(SegmentedCommandPermissionPlan))]
[JsonSerializable(typeof(NonRunCommandPermissionPlan))]
[JsonSerializable(typeof(ReviewOnlyCommandPermissionPlan))]
[JsonSerializable(typeof(UntrustedCommandPermissionPlan))]
[JsonSerializable(typeof(ExecuteCommandPermissionChoice))]
[JsonSerializable(typeof(AllowOnceChoice))]
[JsonSerializable(typeof(PersistRuleChoice))]
[JsonSerializable(typeof(DenyChoice))]
[JsonSerializable(typeof(FeedbackChoice))]
[JsonSerializable(typeof(ExecuteCommandPermissionRuleProposal))]
[JsonSerializable(typeof(ExactAllowRuleProposal))]
[JsonSerializable(typeof(PrefixAllowRuleProposal))]
[JsonSerializable(typeof(SegmentRuleBundleProposal))]
[JsonSerializable(typeof(AskRuleProposal))]
[JsonSerializable(typeof(DenyRuleProposal))]
[JsonSerializable(typeof(ExecuteCommandPermissionRule))]
[JsonSerializable(typeof(ExecuteCommandInactivePermissionRule))]
[JsonSerializable(typeof(ExecuteCommandPermissionRuleLifecycleIssue))]
[JsonSerializable(typeof(ExecuteCommandPermissionRuleLifecycleOperationResult))]
[JsonSerializable(typeof(ExecuteCommandPermissionRuleLifecycleAuditRecord))]
[JsonSerializable(typeof(ExecuteCommandPermissionRuleLifecycleOperation))]
[JsonSerializable(typeof(ExecuteCommandPermissionRuleLifecycleAction))]
[JsonSerializable(typeof(ExecuteCommandPermissionStateData))]
[JsonSerializable(typeof(ExecuteCommandBatchPermissionStateData))]
[JsonSerializable(typeof(ExecuteCommandPermissionDecision))]
[JsonSerializable(typeof(DebugPermissionStateData))]
[JsonSerializable(typeof(DebugPermissionDecision))]
[JsonSerializable(typeof(Dictionary<string, DebugPermissionDecision>))]
[JsonSerializable(typeof(ExecuteCommandPermissionAuditDetails))]
[JsonSerializable(typeof(ExecuteCommandSubcommandPlan))]
[JsonSerializable(typeof(ExecuteCommandShellScope))]
[JsonSerializable(typeof(ExecuteCommandPermissionWorkspaceScope))]
[JsonSerializable(typeof(ProcessIsolationPolicy))]
[JsonSerializable(typeof(FilesystemAccessPolicy))]
[JsonSerializable(typeof(PathAccessRule))]
[JsonSerializable(typeof(NetworkEgressPolicy))]
[JsonSerializable(typeof(ProcessInteractivePolicy))]
[JsonSerializable(typeof(AgentSandboxRuntime))]
[JsonSerializable(typeof(AgentSandboxConfiguration))]
[JsonSerializable(typeof(AgentSandboxPathGrant))]
[JsonSerializable(typeof(ExecuteCommandFilesystemEffect))]
[JsonSerializable(typeof(ExecuteCommandNetworkEffect))]
[JsonSerializable(typeof(ExecuteCommandRedirectionPlan))]
[JsonSerializable(typeof(ExecuteCommandCategory))]
[JsonSerializable(typeof(ExecuteCommandStreamKind))]
[JsonSerializable(typeof(ExecuteCommandCompletionKind))]
[JsonSerializable(typeof(ExecuteCommandPermissionBehavior))]
[JsonSerializable(typeof(ExecuteCommandPermissionMatchKind))]
[JsonSerializable(typeof(ExecuteCommandAnalysisTrustLevel))]
[JsonSerializable(typeof(ExecuteCommandPermissionRisk))]
[JsonSerializable(typeof(ExecuteCommandUnsupportedShellFeature))]
[JsonSerializable(typeof(ExecuteCommandPolicyReadiness))]
[JsonSerializable(typeof(ExecuteCommandShellFamily))]
[JsonSerializable(typeof(AgentSandboxPathAccess))]
[JsonSerializable(typeof(ExecuteCommandFilesystemOperation))]
[JsonSerializable(typeof(ExecuteCommandNetworkOperation))]
[JsonSerializable(typeof(ExecuteCommandRedirectionKind))]

[JsonSerializable(typeof(FileWriteMode))]
[JsonSerializable(typeof(CodingFileMutationKind))]
[JsonSerializable(typeof(FileMutationSnapshot))]
[JsonSerializable(typeof(FileMutationTextEdit))]
[JsonSerializable(typeof(FileMutationRange))]
[JsonSerializable(typeof(FileMutationHunk))]
[JsonSerializable(typeof(FileMutationDiffStat))]
[JsonSerializable(typeof(FileMutationNote))]
[JsonSerializable(typeof(FileEditAppliedReplacement))]
[JsonSerializable(typeof(FileEditNormalizationNote))]
[JsonSerializable(typeof(IReadOnlyList<FileMutationTextEdit>), TypeInfoPropertyName = "FileMutationTextEditReadOnlyList")]
[JsonSerializable(typeof(List<FileMutationTextEdit>), TypeInfoPropertyName = "FileMutationTextEditList")]
[JsonSerializable(typeof(IReadOnlyList<FileMutationHunk>), TypeInfoPropertyName = "FileMutationHunkReadOnlyList")]
[JsonSerializable(typeof(List<FileMutationHunk>), TypeInfoPropertyName = "FileMutationHunkList")]
[JsonSerializable(typeof(IReadOnlyList<FileMutationNote>), TypeInfoPropertyName = "FileMutationNoteReadOnlyList")]
[JsonSerializable(typeof(List<FileMutationNote>), TypeInfoPropertyName = "FileMutationNoteList")]
[JsonSerializable(typeof(IReadOnlyList<FileEditAppliedReplacement>), TypeInfoPropertyName = "FileEditAppliedReplacementReadOnlyList")]
[JsonSerializable(typeof(List<FileEditAppliedReplacement>), TypeInfoPropertyName = "FileEditAppliedReplacementList")]
[JsonSerializable(typeof(IReadOnlyList<FileEditNormalizationNote>), TypeInfoPropertyName = "FileEditNormalizationNoteReadOnlyList")]
[JsonSerializable(typeof(List<FileEditNormalizationNote>), TypeInfoPropertyName = "FileEditNormalizationNoteList")]
[JsonSerializable(typeof(IReadOnlyList<FileMutationRange>), TypeInfoPropertyName = "FileMutationRangeReadOnlyList")]
[JsonSerializable(typeof(List<FileMutationRange>), TypeInfoPropertyName = "FileMutationRangeList")]
[JsonSerializable(typeof(IReadOnlyList<string>), TypeInfoPropertyName = "StringReadOnlyList")]
[JsonSerializable(typeof(List<string>), TypeInfoPropertyName = "StringList")]
[JsonSerializable(typeof(DebugOperation))]
[JsonSerializable(typeof(DebugExecutionPlanMetadata))]
[JsonSerializable(typeof(DebugExecutionActivationMetadata))]
[JsonSerializable(typeof(DebugProjectEvaluationMetadata))]
[JsonSerializable(typeof(DebugExceptionFilterMetadata))]
[JsonSerializable(typeof(IReadOnlyList<DebugExceptionFilterMetadata>), TypeInfoPropertyName = "DebugExceptionFilterMetadataReadOnlyList")]
[JsonSerializable(typeof(DebugCapabilitySummaryMetadata))]
[JsonSerializable(typeof(DebugModuleMetadata))]
[JsonSerializable(typeof(IReadOnlyList<DebugModuleMetadata>), TypeInfoPropertyName = "DebugModuleMetadataReadOnlyList")]
[JsonSerializable(typeof(DebugModulePageMetadata))]
[JsonSerializable(typeof(DebugLaunchNoticeMetadata))]
[JsonSerializable(typeof(IReadOnlyList<DebugLaunchNoticeMetadata>), TypeInfoPropertyName = "DebugLaunchNoticeMetadataReadOnlyList")]
[JsonSerializable(typeof(DebugBreakpointCounts))]
[JsonSerializable(typeof(DebugTerminalRecordMetadata))]

[JsonSerializable(typeof(DebugBreakpointSelectionEventItem))]
[JsonSerializable(typeof(IReadOnlyList<DebugBreakpointSelectionEventItem>), TypeInfoPropertyName = "DebugBreakpointSelectionEventItemReadOnlyList")]
[JsonSerializable(typeof(DebugBreakpointSelectionDelta))]
[JsonSerializable(typeof(IReadOnlyList<DebugBreakpointSelectionDelta>), TypeInfoPropertyName = "DebugBreakpointSelectionDeltaReadOnlyList")]
[JsonSerializable(typeof(DebugSourcePreview))]
[JsonSerializable(typeof(IReadOnlyList<DebugSourcePreview>), TypeInfoPropertyName = "DebugSourcePreviewReadOnlyList")]
[JsonSerializable(typeof(DebugSourcePreviewHunk))]
[JsonSerializable(typeof(IReadOnlyList<DebugSourcePreviewHunk>), TypeInfoPropertyName = "DebugSourcePreviewHunkReadOnlyList")]
[JsonSerializable(typeof(LanguageServerStatusSnapshot))]
[JsonSerializable(typeof(IReadOnlyList<LanguageServerStatusSnapshot>), TypeInfoPropertyName = "LanguageServerStatusSnapshotReadOnlyList")]
[JsonSerializable(typeof(List<LanguageServerStatusSnapshot>), TypeInfoPropertyName = "LanguageServerStatusSnapshotList")]
[JsonSerializable(typeof(LanguageServerDiagnosticSummary))]
[JsonSerializable(typeof(IReadOnlyList<LanguageServerDiagnosticSummary>), TypeInfoPropertyName = "LanguageServerDiagnosticSummaryReadOnlyList")]
[JsonSerializable(typeof(List<LanguageServerDiagnosticSummary>), TypeInfoPropertyName = "LanguageServerDiagnosticSummaryList")]
[JsonSerializable(typeof(LanguageServerDiagnosticSource))]
[JsonSerializable(typeof(LanguageServerDiagnosticSeverity))]
[JsonSerializable(typeof(LanguageServerWatchedFileChangeKind))]

// Common event fields
[JsonSerializable(typeof(EventChannel))]
[JsonSerializable(typeof(EventKind))]
[JsonSerializable(typeof(EventDirection))]
[JsonSerializable(typeof(DateTimeOffset))]
public partial class CodingToolHarnessJsonContext : JsonSerializerContext
{
}
