using System.Text.Json;
using System.Text.Json.Serialization;
using HPD.Agent;
using HPD.Agent.ToolHarness.Coding;
using HPD.Agent.ToolHarness.Coding.Debugging;
using HPD.Environment.Contracts;
using HPD.Events;
using HPDOS.ToolHarnesses.Middleware;

[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    WriteIndented = false)]
[JsonSerializable(typeof(AgentEvent))]
[JsonSerializable(typeof(AgentWorkspace))]
[JsonSerializable(typeof(AgentWorkspaceRoot))]
[JsonSerializable(typeof(IReadOnlyList<AgentWorkspaceRoot>), TypeInfoPropertyName = "AgentWorkspaceRootReadOnlyList")]
[JsonSerializable(typeof(List<AgentWorkspaceRoot>), TypeInfoPropertyName = "AgentWorkspaceRootList")]

// ExecuteCommand events
[JsonSerializable(typeof(ExecuteCommandEvent))]
[JsonSerializable(typeof(ExecuteCommandProcessStartedEvent))]
[JsonSerializable(typeof(ExecuteCommandOutputChunkEvent))]
[JsonSerializable(typeof(ExecuteCommandProgressEvent))]
[JsonSerializable(typeof(ExecuteCommandProcessExitedEvent))]
[JsonSerializable(typeof(ExecuteCommandAutoBackgroundedEvent))]
[JsonSerializable(typeof(ExecuteCommandPermissionRequestEvent))]
[JsonSerializable(typeof(ExecuteCommandPermissionResponseEvent))]
[JsonSerializable(typeof(ExecuteCommandSandboxCapabilityRequestEvent))]
[JsonSerializable(typeof(ExecuteCommandSandboxCapabilityResponseEvent))]
[JsonSerializable(typeof(ExecuteCommandPermissionRulePersistedEvent))]
[JsonSerializable(typeof(ExecuteCommandPermissionPlan))]
[JsonSerializable(typeof(SimpleCommandPermissionPlan))]
[JsonSerializable(typeof(SegmentedCommandPermissionPlan))]
[JsonSerializable(typeof(NonRunCommandPermissionPlan))]
[JsonSerializable(typeof(ReviewOnlyCommandPermissionPlan))]
[JsonSerializable(typeof(UntrustedCommandPermissionPlan))]
[JsonSerializable(typeof(ExecuteCommandPermissionChoice))]
[JsonSerializable(typeof(AllowOnceChoice))]
[JsonSerializable(typeof(PersistRuleChoice))]
[JsonSerializable(typeof(DenyChoice))]
[JsonSerializable(typeof(FeedbackChoice))]
[JsonSerializable(typeof(ExecuteCommandPermissionRuleProposal))]
[JsonSerializable(typeof(ExactAllowRuleProposal))]
[JsonSerializable(typeof(PrefixAllowRuleProposal))]
[JsonSerializable(typeof(SegmentRuleBundleProposal))]
[JsonSerializable(typeof(AskRuleProposal))]
[JsonSerializable(typeof(DenyRuleProposal))]
[JsonSerializable(typeof(ExecuteCommandPermissionRule))]
[JsonSerializable(typeof(ExecuteCommandInactivePermissionRule))]
[JsonSerializable(typeof(ExecuteCommandPermissionRuleLifecycleIssue))]
[JsonSerializable(typeof(ExecuteCommandPermissionRuleLifecycleOperationResult))]
[JsonSerializable(typeof(ExecuteCommandPermissionRuleLifecycleAuditRecord))]
[JsonSerializable(typeof(ExecuteCommandPermissionRuleLifecycleOperation))]
[JsonSerializable(typeof(ExecuteCommandPermissionRuleLifecycleAction))]
[JsonSerializable(typeof(ExecuteCommandPermissionStateData))]
[JsonSerializable(typeof(ExecuteCommandBatchPermissionStateData))]
[JsonSerializable(typeof(ExecuteCommandPermissionDecision))]
[JsonSerializable(typeof(DebugPermissionStateData))]
[JsonSerializable(typeof(DebugPermissionDecision))]
[JsonSerializable(typeof(Dictionary<string, DebugPermissionDecision>))]
[JsonSerializable(typeof(ExecuteCommandPermissionAuditDetails))]
[JsonSerializable(typeof(ExecuteCommandSubcommandPlan))]
[JsonSerializable(typeof(ExecuteCommandShellScope))]
[JsonSerializable(typeof(ExecuteCommandPermissionWorkspaceScope))]
[JsonSerializable(typeof(ProcessIsolationPolicy))]
[JsonSerializable(typeof(FilesystemAccessPolicy))]
[JsonSerializable(typeof(PathAccessRule))]
[JsonSerializable(typeof(NetworkEgressPolicy))]
[JsonSerializable(typeof(ProcessInteractivePolicy))]
[JsonSerializable(typeof(ExecuteCommandSandboxAmendment))]
[JsonSerializable(typeof(AllowReadPathAmendment))]
[JsonSerializable(typeof(AllowWritePathAmendment))]
[JsonSerializable(typeof(AllowNetworkDomainAmendment))]
[JsonSerializable(typeof(AllowNetworkModeAmendment))]
[JsonSerializable(typeof(AllowPtyAmendment))]
[JsonSerializable(typeof(AllowLocalBindingAmendment))]
[JsonSerializable(typeof(AgentProcessSandboxPolicy))]
[JsonSerializable(typeof(AgentProcessPathGrant))]
[JsonSerializable(typeof(AgentProcessNetworkGrant))]
[JsonSerializable(typeof(AgentProcessInteractiveGrant))]
[JsonSerializable(typeof(ExecuteCommandFilesystemEffect))]
[JsonSerializable(typeof(ExecuteCommandNetworkEffect))]
[JsonSerializable(typeof(ExecuteCommandRedirectionPlan))]
[JsonSerializable(typeof(ExecuteCommandCategory))]
[JsonSerializable(typeof(ExecuteCommandStreamKind))]
[JsonSerializable(typeof(ExecuteCommandCompletionKind))]
[JsonSerializable(typeof(ExecuteCommandPermissionBehavior))]
[JsonSerializable(typeof(ExecuteCommandSandboxCapabilityKind))]
[JsonSerializable(typeof(ExecuteCommandPermissionMatchKind))]
[JsonSerializable(typeof(ExecuteCommandAnalysisTrustLevel))]
[JsonSerializable(typeof(ExecuteCommandPermissionRisk))]
[JsonSerializable(typeof(ExecuteCommandUnsupportedShellFeature))]
[JsonSerializable(typeof(ExecuteCommandPolicyReadiness))]
[JsonSerializable(typeof(ExecuteCommandShellFamily))]
[JsonSerializable(typeof(AgentProcessIsolationMode))]
[JsonSerializable(typeof(AgentProcessPathGrantKind))]
[JsonSerializable(typeof(ExecuteCommandNetworkMode))]
[JsonSerializable(typeof(ExecuteCommandFilesystemOperation))]
[JsonSerializable(typeof(ExecuteCommandNetworkOperation))]
[JsonSerializable(typeof(ExecuteCommandRedirectionKind))]

// File mutation events
[JsonSerializable(typeof(FileMutationAppliedEvent))]
[JsonSerializable(typeof(FileEditAppliedEvent))]
[JsonSerializable(typeof(FileWriteAppliedEvent))]
[JsonSerializable(typeof(FileWriteMode))]
[JsonSerializable(typeof(CodingFileMutationKind))]
[JsonSerializable(typeof(FileMutationSnapshot))]
[JsonSerializable(typeof(FileMutationTextEdit))]
[JsonSerializable(typeof(FileMutationRange))]
[JsonSerializable(typeof(FileMutationHunk))]
[JsonSerializable(typeof(FileMutationDiffStat))]
[JsonSerializable(typeof(FileMutationNote))]
[JsonSerializable(typeof(FileEditAppliedReplacement))]
[JsonSerializable(typeof(FileEditNormalizationNote))]
[JsonSerializable(typeof(IReadOnlyList<FileMutationTextEdit>), TypeInfoPropertyName = "FileMutationTextEditReadOnlyList")]
[JsonSerializable(typeof(List<FileMutationTextEdit>), TypeInfoPropertyName = "FileMutationTextEditList")]
[JsonSerializable(typeof(IReadOnlyList<FileMutationHunk>), TypeInfoPropertyName = "FileMutationHunkReadOnlyList")]
[JsonSerializable(typeof(List<FileMutationHunk>), TypeInfoPropertyName = "FileMutationHunkList")]
[JsonSerializable(typeof(IReadOnlyList<FileMutationNote>), TypeInfoPropertyName = "FileMutationNoteReadOnlyList")]
[JsonSerializable(typeof(List<FileMutationNote>), TypeInfoPropertyName = "FileMutationNoteList")]
[JsonSerializable(typeof(IReadOnlyList<FileEditAppliedReplacement>), TypeInfoPropertyName = "FileEditAppliedReplacementReadOnlyList")]
[JsonSerializable(typeof(List<FileEditAppliedReplacement>), TypeInfoPropertyName = "FileEditAppliedReplacementList")]
[JsonSerializable(typeof(IReadOnlyList<FileEditNormalizationNote>), TypeInfoPropertyName = "FileEditNormalizationNoteReadOnlyList")]
[JsonSerializable(typeof(List<FileEditNormalizationNote>), TypeInfoPropertyName = "FileEditNormalizationNoteList")]
[JsonSerializable(typeof(IReadOnlyList<FileMutationRange>), TypeInfoPropertyName = "FileMutationRangeReadOnlyList")]
[JsonSerializable(typeof(List<FileMutationRange>), TypeInfoPropertyName = "FileMutationRangeList")]
[JsonSerializable(typeof(IReadOnlyList<string>), TypeInfoPropertyName = "StringReadOnlyList")]
[JsonSerializable(typeof(List<string>), TypeInfoPropertyName = "StringList")]
[JsonSerializable(typeof(DebugOperation))]
[JsonSerializable(typeof(DebugExecutionPlanMetadata))]
[JsonSerializable(typeof(DebugExecutionActivationMetadata))]
[JsonSerializable(typeof(DebugProjectEvaluationMetadata))]
[JsonSerializable(typeof(DebugExceptionFilterMetadata))]
[JsonSerializable(typeof(IReadOnlyList<DebugExceptionFilterMetadata>), TypeInfoPropertyName = "DebugExceptionFilterMetadataReadOnlyList")]
[JsonSerializable(typeof(DebugCapabilitySummaryMetadata))]
[JsonSerializable(typeof(DebugLaunchNoticeMetadata))]
[JsonSerializable(typeof(IReadOnlyList<DebugLaunchNoticeMetadata>), TypeInfoPropertyName = "DebugLaunchNoticeMetadataReadOnlyList")]
[JsonSerializable(typeof(DebugBreakpointCounts))]
[JsonSerializable(typeof(DebugTerminalRecordMetadata))]

// Language server events
[JsonSerializable(typeof(LanguageServerEvent))]
[JsonSerializable(typeof(LanguageServerDocumentOpenedEvent))]
[JsonSerializable(typeof(LanguageServerDocumentChangedEvent))]
[JsonSerializable(typeof(LanguageServerDocumentClosedEvent))]
[JsonSerializable(typeof(LanguageServerDocumentSavedEvent))]
[JsonSerializable(typeof(LanguageServerWatchedFileChangedEvent))]
[JsonSerializable(typeof(LanguageServerDiagnosticsReceivedEvent))]
[JsonSerializable(typeof(LanguageServerStatusSnapshotEvent))]
[JsonSerializable(typeof(DebugLifecycleEvent))]
[JsonSerializable(typeof(DebugTreeStartedEvent))]
[JsonSerializable(typeof(DebugExecutionPlannedEvent))]
[JsonSerializable(typeof(DebugExecutionActivatingEvent))]
[JsonSerializable(typeof(DebugHostProcessStartedEvent))]
[JsonSerializable(typeof(DebugHostReadyEvent))]
[JsonSerializable(typeof(DebugHostProcessExitedEvent))]
[JsonSerializable(typeof(DebugExecutionActivationFailedEvent))]
[JsonSerializable(typeof(DebugOwnedResourceCleanupFailedEvent))]
[JsonSerializable(typeof(DebugTerminalRecordRetainedEvent))]
[JsonSerializable(typeof(DebugTerminalRecordEvictedEvent))]
[JsonSerializable(typeof(DebugSessionStateChangedEvent))]
[JsonSerializable(typeof(DebugSessionExitedEvent))]
[JsonSerializable(typeof(DebugSessionTerminatedEvent))]
[JsonSerializable(typeof(DebugTreeFaultedEvent))]
[JsonSerializable(typeof(DebugSessionFailedEvent))]
[JsonSerializable(typeof(DebugTreeTerminatedEvent))]
[JsonSerializable(typeof(DebugSessionSummaryEvent))]
[JsonSerializable(typeof(DebugRestartTransitionEvent))]
[JsonSerializable(typeof(DebugChildSessionStartedEvent))]
[JsonSerializable(typeof(DebugBreakpointChangedEvent))]
[JsonSerializable(typeof(DebugRunInTerminalRequestEvent))]
[JsonSerializable(typeof(DebugRunInTerminalResponseEvent))]
[JsonSerializable(typeof(DebugSessionStoppedEvent))]
[JsonSerializable(typeof(DebugSessionContinuedEvent))]
[JsonSerializable(typeof(DebugProcessChangedEvent))]
[JsonSerializable(typeof(DebugThreadChangedEvent))]
[JsonSerializable(typeof(DebugModuleChangedEvent))]
[JsonSerializable(typeof(DebugLoadedSourceChangedEvent))]
[JsonSerializable(typeof(DebugCapabilitiesChangedEvent))]
[JsonSerializable(typeof(DebugStateInvalidatedEvent))]
[JsonSerializable(typeof(DebugMemoryChangedEvent))]
[JsonSerializable(typeof(DebugOutputAvailableEvent))]
[JsonSerializable(typeof(DebugProgressStartedEvent))]
[JsonSerializable(typeof(DebugProgressUpdatedEvent))]
[JsonSerializable(typeof(DebugProgressCompletedEvent))]
[JsonSerializable(typeof(LanguageServerStatusSnapshot))]
[JsonSerializable(typeof(IReadOnlyList<LanguageServerStatusSnapshot>), TypeInfoPropertyName = "LanguageServerStatusSnapshotReadOnlyList")]
[JsonSerializable(typeof(List<LanguageServerStatusSnapshot>), TypeInfoPropertyName = "LanguageServerStatusSnapshotList")]
[JsonSerializable(typeof(LanguageServerDiagnosticSummary))]
[JsonSerializable(typeof(IReadOnlyList<LanguageServerDiagnosticSummary>), TypeInfoPropertyName = "LanguageServerDiagnosticSummaryReadOnlyList")]
[JsonSerializable(typeof(List<LanguageServerDiagnosticSummary>), TypeInfoPropertyName = "LanguageServerDiagnosticSummaryList")]
[JsonSerializable(typeof(LanguageServerDiagnosticSource))]
[JsonSerializable(typeof(LanguageServerDiagnosticSeverity))]
[JsonSerializable(typeof(LanguageServerWatchedFileChangeKind))]

// Common event fields
[JsonSerializable(typeof(EventChannel))]
[JsonSerializable(typeof(EventKind))]
[JsonSerializable(typeof(EventDirection))]
[JsonSerializable(typeof(DateTimeOffset))]
public partial class CodingToolHarnessJsonContext : JsonSerializerContext
{
}
