import { gatewayJsonSemanticEqual, type GatewayJsonArray, type GatewayJsonNode, type GatewayJsonObject } from './authored-json.ts';

export interface GatewayNavigatorEntry { readonly key:string; readonly family:'route'|'upstream'|'destination'|'definition'|'listener'|'policy'|'transform'; readonly identity:string; readonly pointer:string; readonly diagnosticCount:number; readonly changed:boolean; readonly referenceTargets:readonly string[]; readonly usedBy:readonly string[]; readonly usedByTruncated:number; readonly unresolved:boolean; readonly orphan:boolean; }
export interface GatewayNavigatorProjection { readonly entries:readonly GatewayNavigatorEntry[]; readonly truncatedCount:number; }
export interface GatewaySemanticDifference { readonly pointer:string; readonly kind:'added'|'removed'|'changed'; }
export interface GatewaySemanticDiff { readonly differences:readonly GatewaySemanticDifference[]; readonly truncatedCount:number; }

export function projectGatewayNavigator(graph:GatewayJsonObject,baseline:GatewayJsonObject|null=null,diagnosticPaths:readonly string[]=[]):GatewayNavigatorProjection{
  const drafts=collectDrafts(graph);
  const listeners=new Map<string,string[]>(); for(const draft of drafts.filter(value=>value.family==='route'))for(const target of draft.targets.filter(value=>value.startsWith('listener:'))){const identity=target.slice(9);const used=listeners.get(identity)??[];used.push(draft.key);listeners.set(identity,used);}
  for(const [identity,usedBy] of listeners)drafts.push({key:`listener:${identity}`,family:'listener',identity,pointer:'',targets:[],node:null,syntheticUsedBy:usedBy});
  drafts.sort((a,b)=>ordinal(a.key,b.key)); const known=new Set(drafts.map(value=>value.key)); const reverse=new Map<string,string[]>();
  for(const draft of drafts)for(const target of draft.targets){const used=reverse.get(target)??[];used.push(draft.key);reverse.set(target,used);}
  const baselineByKey=baseline===null?new Map<string,GatewayJsonNode|null>():new Map(collectDrafts(baseline).map(value=>[value.key,value.node]));
  const entries=drafts.slice(0,50_000).map(draft=>{const used=[...(draft.syntheticUsedBy??[]),...(reverse.get(draft.key)??[])].sort(ordinal);const unresolved=draft.targets.some(target=>!known.has(target));const orphan=(draft.family==='upstream'||draft.family==='definition')&&used.length===0;const prior=baselineByKey.get(draft.key);const changed=baseline!==null&&(prior===undefined?true:draft.node===null||prior===null?!Object.is(prior,draft.node):!gatewayJsonSemanticEqual(draft.node,prior));return Object.freeze({key:draft.key,family:draft.family,identity:draft.identity,pointer:draft.pointer,diagnosticCount:diagnosticPaths.filter(value=>value===draft.pointer||value.startsWith(`${draft.pointer}/`)).length,changed,referenceTargets:Object.freeze([...draft.targets].sort(ordinal)),usedBy:Object.freeze(used.slice(0,256)),usedByTruncated:Math.max(0,used.length-256),unresolved,orphan});});
  return Object.freeze({entries:Object.freeze(entries),truncatedCount:Math.max(0,drafts.length-entries.length)});
}

export function searchGatewayNavigator(projection:GatewayNavigatorProjection,query:string):readonly GatewayNavigatorEntry[]{const value=query.normalize('NFC');return Object.freeze(projection.entries.filter(entry=>entry.key.includes(value)||entry.identity.includes(value)||entry.pointer.includes(value)).slice(0,256));}
export function diffGatewayDocuments(current:GatewayJsonObject,baseline:GatewayJsonObject):GatewaySemanticDiff{const output:GatewaySemanticDifference[]=[];let truncated=0;const add=(pointer:string,kind:GatewaySemanticDifference['kind'])=>{if(output.length<4096)output.push(Object.freeze({pointer,kind}));else truncated++;};const walk=(left:GatewayJsonNode|undefined,right:GatewayJsonNode|undefined,path:string):void=>{if(left===undefined){add(path,'removed');return;}if(right===undefined){add(path,'added');return;}if(left.kind==='object'&&right.kind==='object'){const l=objectMap(left),r=objectMap(right),keys=[...new Set([...l.keys(),...r.keys()])].sort(ordinal);for(const key of keys)walk(l.get(key),r.get(key),`${path}/${escapePointer(key)}`);return;}if(left.kind==='array'&&right.kind==='array'){const count=Math.max(left.items.length,right.items.length);for(let i=0;i<count;i++)walk(left.items[i],right.items[i],`${path}/${i}`);return;}if(!gatewayJsonSemanticEqual(left,right))add(path,'changed');};walk(current,baseline,'');return Object.freeze({differences:Object.freeze(output),truncatedCount:truncated});}

interface Draft{key:string;family:GatewayNavigatorEntry['family'];identity:string;pointer:string;targets:string[];node:GatewayJsonNode|null;syntheticUsedBy?:string[]}
function collectDrafts(graph:GatewayJsonObject):Draft[]{const output:Draft[]=[];const root=objectMap(graph);collectResources(array(root.get('routes')),'route','/routes',output);collectResources(array(root.get('upstreams')),'upstream','/upstreams',output,(item,index)=>collectDestinations(item,`/upstreams/${index}`,output));const definitions=object(root.get('definitions'));if(definitions)for(const entry of definitions.entries){const values=array(entry.value);values?.items.forEach((item,index)=>{const identity=idOf(item)??`${index}`;output.push({key:`definition:${entry.name}:${identity}`,family:'definition',identity,pointer:`/definitions/${escapePointer(entry.name)}/${index}`,targets:references(item),node:item});});}return output;}
function collectResources(values:GatewayJsonArray|null,family:'route'|'upstream',base:string,output:Draft[],after?:(item:GatewayJsonNode,index:number)=>void):void{values?.items.forEach((item,index)=>{const identity=idOf(item)??`${index}`;output.push({key:`${family}:${identity}`,family,identity,pointer:`${base}/${index}`,targets:references(item),node:item});after?.(item,index);});}
function collectDestinations(input:GatewayJsonNode,base:string,output:Draft[]):void{if(input.kind!=='object')return;const source=objectMap(input).get('endpoints');if(source?.kind!=='object'||stringValue(objectMap(source).get('kind'))!=='static')return;const destinations=array(objectMap(source).get('destinations'));destinations?.items.forEach((item,index)=>{const identity=idOf(item)??`${index}`;output.push({key:`destination:${idOf(input)??base}:${identity}`,family:'destination',identity,pointer:`${base}/endpoints/destinations/${index}`,targets:references(item),node:item});});}
const definitionFamilies=Object.freeze(['authorization','cors','trafficAdmission','requestTimeout','outputCache','telemetry','inspection','credentialDisposition'] as const);
function references(node:GatewayJsonNode):string[]{const result:string[]=[];if(node.kind!=='object')return result;const root=objectMap(node);const upstream=identityValue(root.get('upstream'));if(upstream!==null)result.push(`upstream:${upstream}`);const listener=identityValue(root.get('listener'));if(listener!==null)result.push(`listener:${listener}`);const declarations=object(root.get('declarations'));if(declarations)collectDefinitionBindings(declarations,result);const defaults=object(root.get('rootDefaults'));if(defaults)collectDefinitionBindings(defaults,result);return [...new Set(result)];}
function collectDefinitionBindings(container:GatewayJsonObject,result:string[]):void{const map=objectMap(container);for(const family of definitionFamilies){const binding=object(map.get(family));if(binding===null)continue;const identity=identityValue(objectMap(binding).get('definition'));if(identity!==null)result.push(`definition:${family}:${identity}`);}}
function identityValue(node:GatewayJsonNode|undefined):string|null{if(node?.kind!=='object')return null;return stringValue(objectMap(node).get('value'));}
function idOf(node:GatewayJsonNode):string|null{if(node.kind!=='object')return null;const id=objectMap(node).get('id');if(id?.kind==='string')return id.value;if(id?.kind==='object')return stringValue(objectMap(id).get('value'));return null;}
function stringValue(node:GatewayJsonNode|undefined):string|null{return node?.kind==='string'?node.value:null;}
function object(node:GatewayJsonNode|undefined):GatewayJsonObject|null{return node?.kind==='object'?node:null;}
function array(node:GatewayJsonNode|undefined):GatewayJsonArray|null{return node?.kind==='array'?node:null;}
function objectMap(node:GatewayJsonObject):Map<string,GatewayJsonNode>{return new Map(node.entries.map(entry=>[entry.name,entry.value]));}
function escapePointer(value:string):string{return value.replaceAll('~','~0').replaceAll('/','~1');}
function ordinal(left:string,right:string):number{const l=[...left],r=[...right],length=Math.min(l.length,r.length);for(let i=0;i<length;i++){const a=l[i]!.codePointAt(0)!,b=r[i]!.codePointAt(0)!;if(a!==b)return a-b;}return l.length-r.length;}
