<script lang="ts">
  import { onMount } from 'svelte';
  import { requireGatewayRuntimeContext } from './runtime-context.ts';
  import type { GatewayStudioController, GatewayStudioSnapshot } from './state.ts';
  import type { GatewayManagedWorkflowController, GatewayManagedWorkflowSnapshot } from './managed-workflows.ts';
  import type { GatewayOperationsController } from './operations.ts';
  import type { GatewayObservabilityLink } from './observability-links.ts';
  import { projectGatewayDiscovery, summarizeGatewayDiscovery } from './discovery-projection.ts';
  const context=requireGatewayRuntimeContext();
  const studio:GatewayStudioController=context.controller;
  const managedController:GatewayManagedWorkflowController=context.workflows;
  const operations:GatewayOperationsController=context.operations;
  const links:readonly GatewayObservabilityLink[]=context.observabilityLinks;
  let snapshot:GatewayStudioSnapshot=$state(studio.snapshot());
  let managed:GatewayManagedWorkflowSnapshot=$state(managedController.snapshot());
  let exportFailure=$state(false);
  onMount(()=>{const first=studio.subscribe(value=>snapshot=value);const second=managedController.subscribe(value=>managed=value);return()=>{first();second();};});
  function download(){const bundle=operations.createDiagnosticBundle();if(bundle===null){exportFailure=true;return;}exportFailure=false;const blob=new Blob([bundle.bytes as BlobPart],{type:'application/json'});const href=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=href;anchor.download=bundle.filename;anchor.rel='noopener noreferrer';anchor.click();URL.revokeObjectURL(href);}
  function requireValue<T>(value:T|undefined):T{if(value===undefined)throw new Error('Gateway diagnostic context is unavailable.');return value;}
  const status=$derived(snapshot.observation?.status);
  const node=$derived(status?.node??undefined);
  const effective=$derived(snapshot.observation?.effective.state==='value'?snapshot.observation.effective.value:undefined);
  const effectiveRecords=$derived(effective?.routes.flatMap(route=>route.contributions)??[]);
  const desired=$derived(snapshot.observation?.desired.state==='value'?snapshot.observation.desired.value:undefined);
  const activeIdentity=$derived(node?.publication.state==='ActiveAcknowledged'?node.publication.active??undefined:undefined);
  const active=$derived(activeIdentity?.candidateId);
  const alignment=$derived(!desired||!activeIdentity||!effective?'Incomplete':desired.candidateId===activeIdentity.candidateId&&activeIdentity.candidateId===effective.candidateId&&activeIdentity.applicationId===effective.applicationId&&hashEqual(activeIdentity.symbolicPlanIdentity,effective.symbolicPlanIdentity)?'Aligned':'Diverged');
  const discovery=$derived(projectGatewayDiscovery(node?.upstreams??[],effective));
  const discoverySummary=$derived(summarizeGatewayDiscovery(discovery));
  const admission=$derived(node?.trafficAdmission.profiles??[]);
  const appliedAdmission=$derived(effective?.routes.filter(route=>route.trafficAdmission!=null).map(route=>({routeId:route.routeId,plan:route.trafficAdmission!}))??[]);
  function hash(value:{readonly algorithm?:string;readonly value?:string}):string{return value.value?`${value.algorithm??'hash'}:${value.value}`:'Not recorded';}
  function hashEqual(left:{readonly algorithm?:string;readonly value?:string},right:{readonly algorithm?:string;readonly value?:string}):boolean{return Boolean(left.algorithm&&left.value&&right.algorithm&&right.value&&left.algorithm===right.algorithm&&left.value===right.value);}
</script>

<main class="min-h-0 p-4 sm:p-6 lg:p-8"><div class="mx-auto grid w-full max-w-[110rem] gap-5">
 <header><p class="studio-label">HPD Gateway Studio · Diagnose</p><h1 class="text-3xl font-extrabold">Outcome-first diagnosis</h1><p class="mt-2 max-w-3xl text-sm text-studio-muted">Gateway lifecycle conclusions first; bounded provenance and external operator links remain explicitly separate.</p></header>
 {#if !snapshot.context}<section class="studio-panel p-5" role="status"><h2 class="font-bold">Explicit target required</h2><p class="text-sm text-studio-muted">Choose a namespace and target on Overview. Diagnose performs no discovery.</p></section>
 {:else if !snapshot.observation}<section class="studio-panel p-5" role="status"><h2 class="font-bold">No target observation</h2><p class="text-sm text-studio-muted">{snapshot.failureCode??'Refresh target truth to diagnose this context.'}</p></section>
 {:else}
  <section class="studio-panel grid gap-4 p-5"><div class="flex flex-wrap items-start justify-between gap-3"><div><p class="studio-label">Serving verdict</p><h2 class="text-2xl font-extrabold">{snapshot.verdict}</h2></div><span class="studio-badge studio-badge-warning">Alignment: {alignment}</span></div>
   {#if node?.publication.state==='PublicationIndeterminate'}<p class="rounded-studio bg-studio-danger-muted p-3 font-semibold text-studio-danger" role="alert">Native exchange began, but exact acknowledgement was not observed. Serving generation remains unknown; use controlled restart or replay procedures.</p>{/if}
   {#if node?.host.state==='RestartRequired'}<p class="rounded-studio bg-studio-warning-muted p-3 font-semibold text-studio-warning" role="alert">Desired hosting identity differs from the running host. Restart is required.</p>{/if}
   <dl class="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><div><dt class="studio-label">Desired</dt><dd class="studio-text-safe font-mono text-sm">{desired?.candidateId??'Not observed'}</dd></div><div><dt class="studio-label">Delivery</dt><dd>{status?.management.latestNodeOutcome??'NotAttempted'}</dd></div><div><dt class="studio-label">Active</dt><dd class="studio-text-safe font-mono text-sm">{active??'Not acknowledged'}</dd></div><div><dt class="studio-label">Effective</dt><dd class="studio-text-safe font-mono text-sm">{effective?.candidateId??'Not observed'}</dd></div></dl>
  </section>
  <section class="studio-panel grid gap-3 p-5"><h2 class="text-lg font-bold">Readiness and conditions</h2><p class="text-sm">Serving: <strong>{node?.readiness.serving??'Not observed'}</strong> · {node?.readiness.reasons.map(reason=>reason.code).join(', ')||'No reason code'}</p><p class="text-xs text-studio-muted">Observed {status?.observedAt??'time unavailable'} · source snapshot {node?.snapshotSequence??'unavailable'} · truncation {status?.isTruncated||node?.detailsTruncated?'present':'none'}</p><div class="grid gap-2 md:grid-cols-2 xl:grid-cols-3">{#each node?.conditions??[] as condition}<article class="rounded-studio border border-studio-line p-3"><p class="studio-label">{condition.type}</p><p class="font-bold">{condition.value}</p><p class="studio-text-safe text-xs text-studio-muted">{condition.reasonCode}</p><dl class="mt-2 grid gap-1 text-xs"><div><dt class="studio-label">Observed at</dt><dd>{condition.lastTransitionAt}</dd></div><div><dt class="studio-label">Source</dt><dd class="studio-text-safe font-mono">snapshot {condition.observedSnapshotSequence}</dd></div><div><dt class="studio-label">Truncation</dt><dd>{status?.isTruncated||node?.detailsTruncated?'Status details truncated':'Complete retained status'}</dd></div></dl></article>{/each}</div></section>
  <section class="studio-panel grid gap-3 p-5" aria-labelledby="diagnose-discovery-heading"><div><h2 id="diagnose-discovery-heading" class="text-lg font-bold">Discovery and native membership</h2><p class="text-sm text-studio-muted">{discoverySummary.total} applied Upstreams · {discoverySummary.fresh} fresh · {discoverySummary.degraded} degraded · {discoverySummary.unavailable} unavailable · {discoverySummary.failed} failed · {discoverySummary.indeterminate} unresolved.</p></div><div class="grid gap-2">{#each discovery as upstream (upstream.upstreamId)}<article class="rounded-studio border border-studio-line p-3"><div class="flex flex-wrap items-start justify-between gap-2"><strong class="studio-text-safe">{upstream.upstreamId}</strong><span class="studio-badge">{upstream.state}</span></div><dl class="mt-2 grid gap-2 text-xs sm:grid-cols-2 xl:grid-cols-4"><div><dt class="studio-label">Query</dt><dd class="studio-text-safe">{upstream.profile??'Static'} · {upstream.service??'Not required'}{upstream.endpoint?` / ${upstream.endpoint}`:''}</dd></div><div><dt class="studio-label">Generation</dt><dd class="studio-text-safe font-mono">{upstream.membershipGeneration??'static'}</dd></div><div><dt class="studio-label">Membership identity</dt><dd class="studio-text-safe font-mono">{upstream.membershipIdentity??'Not observed'}</dd></div><div><dt class="studio-label">Correlation</dt><dd>{upstream.correlation}</dd></div><div><dt class="studio-label">Applied / effective</dt><dd>{upstream.appliedDestinationCount} / {upstream.effectiveDestinationCount??'unknown'}</dd></div><div><dt class="studio-label">Native / available</dt><dd>{upstream.nativeDestinationCount} / {upstream.availableDestinationCount}</dd></div><div><dt class="studio-label">Eligibility</dt><dd>{upstream.eligibility}</dd></div><div><dt class="studio-label">Applied at</dt><dd>{upstream.appliedAt??'Not observed'}</dd></div></dl><p class="studio-text-safe mt-2 text-xs">{upstream.safeDiagnostic}</p>{#if upstream.reasons.length}<p class="studio-text-safe mt-1 text-xs text-studio-muted">Reasons: {upstream.reasons.join(', ')}</p>{/if}</article>{/each}</div></section>
  <section class="studio-panel grid gap-3 p-5" aria-labelledby="diagnose-admission-heading"><div><h2 id="diagnose-admission-heading" class="text-lg font-bold">Traffic admission truth</h2><p class="text-sm text-studio-muted">Applied Route plans are distinct from bounded request-time authority observations. No partition value or provider address is retained.</p></div><div class="grid gap-2 md:grid-cols-2">{#each admission as profile (profile.profile)}<article class="rounded-studio border border-studio-line p-3"><div class="flex flex-wrap justify-between gap-2"><strong class="studio-text-safe">{profile.profile}</strong><span class="studio-badge">{profile.state}</span></div><p class="studio-text-safe mt-1 text-xs">{profile.scope} · {profile.authorityId} · {hash(profile.behaviorIdentity)}</p><p class="mt-2 text-xs">Acquired {profile.acquired} · rejected {profile.rejected} · infrastructure {profile.infrastructureFailures} · bypass {profile.degradedBypasses} · fallback {profile.localFallbacks}</p>{#if profile.safeDiagnosticCode}<p class="studio-text-safe mt-1 text-xs text-studio-muted">{profile.safeDiagnosticCode}</p>{/if}</article>{/each}</div><div class="grid gap-2">{#each appliedAdmission as item (item.routeId)}<article class="rounded-studio border border-studio-line p-3"><strong class="studio-text-safe">Route {item.routeId}</strong><p class="studio-text-safe mt-1 font-mono text-xs">Plan {hash(item.plan.planIdentity)}</p>{#each item.plan.entries as entry}<div class="mt-2 rounded-studio border border-studio-line p-2 text-xs"><p class="studio-text-safe">#{entry.order} {entry.profile} · {entry.scope} · {entry.kind}{entry.rateAlgorithm?`/${entry.rateAlgorithm}`:''} · {entry.partition} · {entry.failureDisposition}</p><p class="studio-text-safe mt-1">Authority {entry.authorityId} · behavior {hash(entry.behaviorIdentity)}</p><p class="studio-text-safe mt-1">{#if entry.permitLimit!=null}Limit {entry.permitLimit} · window {entry.windowMilliseconds} ms{/if}{#if entry.segmentsPerWindow!=null} · {entry.segmentsPerWindow} segments{/if}{#if entry.tokenLimit!=null}Tokens {entry.tokenLimit} · refill {entry.tokensPerPeriod}/{entry.replenishmentPeriodMilliseconds} ms{/if}{#if entry.concurrencyPermitLimit!=null}Concurrency {entry.concurrencyPermitLimit} · queue {entry.queueLimit}{/if}</p>{#if entry.partitionProjectorId}<p class="studio-text-safe mt-1">Projector {entry.partitionProjectorId} · {hash(entry.partitionProjectorIdentity!)}</p>{/if}{#if entry.providerId}<p class="studio-text-safe mt-1">Provider {entry.providerId} · {hash(entry.providerBehaviorIdentity!)} · timeout {entry.operationTimeoutMilliseconds} ms · capacity {entry.maximumConcurrentInvocations}</p>{/if}{#if entry.localFallbackProfile}<p class="studio-text-safe mt-1">Fallback {entry.localFallbackProfile} · {hash(entry.localFallbackIdentity!)}</p>{/if}</div>{/each}</article>{/each}</div></section>
  <section class="studio-panel grid gap-3 p-5"><div class="flex flex-wrap items-start justify-between gap-3"><div><h2 class="text-lg font-bold">Applied runtime provenance</h2><p class="text-sm text-studio-muted">{effectiveRecords.length} retained contribution records across {effective?.routes.length??0} applied Routes and {effective?.upstreams.length??0} applied Upstreams{effective?.isTruncated?' · source truncated':''}.</p><p class="studio-text-safe mt-1 text-xs text-studio-muted">Application {effective?.applicationId??'not observed'} · plan {effective?hash(effective.symbolicPlanIdentity):'not observed'} · applied {effective?.appliedAt??'not observed'}</p></div><button class="studio-button studio-button-sm" onclick={download}>Download safe diagnostic observation</button></div>{#if exportFailure}<p class="text-sm font-semibold text-studio-danger" role="alert">The bounded diagnostic envelope could not be produced.</p>{/if}<div class="grid gap-2">{#each effectiveRecords as record}<article class="rounded-studio border border-studio-line p-3"><div class="flex flex-wrap justify-between gap-2"><strong>{record.targetId}</strong><span class="studio-badge">{record.family}</span></div><dl class="mt-2 grid gap-1 text-xs sm:grid-cols-2"><div><dt class="studio-label">Native seam</dt><dd class="studio-text-safe">{record.nativeProjection.owner} · {record.nativeProjection.seam}</dd></div><div><dt class="studio-label">Effective hash</dt><dd class="studio-text-safe font-mono">{hash(record.effectiveContentHash)}</dd></div><div><dt class="studio-label">Composition</dt><dd>{record.composition}</dd></div><div><dt class="studio-label">Compiler</dt><dd class="studio-text-safe">{record.compilerPackage} {record.compilerVersion}</dd></div></dl>{#each record.contributions as contribution}<div class="mt-2 rounded-studio border border-studio-line p-2 text-xs"><p class="studio-text-safe font-semibold">#{contribution.deterministicOrder} · {contribution.scope} · {contribution.sourceKind} · {contribution.disposition}</p><p class="studio-text-safe">Source: {contribution.sourceIdentity}</p><p class="studio-text-safe">Definition: {contribution.definition?.value??'None'}</p><p class="studio-text-safe font-mono">Content: {hash(contribution.contentHash)}</p></div>{/each}</article>{/each}</div></section>
  <section class="studio-panel grid gap-3 p-5"><h2 class="text-lg font-bold">Retained activation evidence</h2><p class="text-sm">{managed.activationIntents.length} intents · {managed.activationOutcomes.length} outcomes{managed.stale?' · stale':''}</p></section>
 {/if}
 {#if links.length}<section class="studio-panel grid gap-3 p-5"><h2 class="text-lg font-bold">External observability</h2><p class="text-sm text-studio-muted">Configured by the host; not Gateway-observed telemetry.</p><div class="flex flex-wrap gap-2">{#each links as link}<a class="studio-button studio-button-sm" href={link.href} target="_blank" rel="noopener noreferrer">{link.label} · External</a>{/each}</div></section>{/if}
</div></main>
