<script lang="ts">
  import {onMount} from 'svelte';
  import {gatewayDeclarationEditorContract} from '@hpd/gateway-client';
  import {useStudioModuleContext} from '@hpd-research/hpd-studio-core';
  import type {GatewayDeclarationController,GatewayDeclarationSnapshot} from './declaration-state.ts';
  import {diffGatewayDocuments,projectGatewayNavigator,searchGatewayNavigator} from './declaration-projections.ts';
  import type {GatewayStudioController,GatewayStudioSnapshot} from './state.ts';
  import type {GatewayQuickRouteCoordinator} from './quick-route.ts';
  const context=useStudioModuleContext();
  const declaration=requireValue(context.get<GatewayDeclarationController>('gateway-declaration-controller'));
  const overview=requireValue(context.get<GatewayStudioController>('gateway-controller'));
  const quick=requireValue(context.get<GatewayQuickRouteCoordinator>('gateway-quick-route-coordinator'));
  let authored:GatewayDeclarationSnapshot=$state(declaration.snapshot());
  let remote:GatewayStudioSnapshot=$state(overview.snapshot());
  let raw=$state(declaration.snapshot().document.utf8Text);let tab=$state<'visual'|'raw'|'truth'>('visual');let search=$state('');let proposal=$state(declaration.snapshot().document.utf8Text);let proposalStatus=$state('');let viewportWidth=$state(0);
  onMount(()=>{const resize=()=>viewportWidth=globalThis.innerWidth;resize();globalThis.addEventListener('resize',resize);const a=declaration.subscribe(next=>{authored=next;if(raw!==next.document.utf8Text)raw=next.document.utf8Text;});const b=overview.subscribe(next=>remote=next);return()=>{globalThis.removeEventListener('resize',resize);a();b();};});
  const navigator=$derived(authored.document.compatibleGraph?projectGatewayNavigator(authored.document.compatibleGraph,authored.baseline?.graph??null,authored.document.diagnostics.map(value=>value.path)):null);
  const results=$derived(navigator?searchGatewayNavigator(navigator,search):[]);
  const diff=$derived(authored.document.compatibleGraph&&authored.baseline?diffGatewayDocuments(authored.document.compatibleGraph,authored.baseline.graph):null);
  const canMutate=$derived(remote.authentication.isAuthenticated&&viewportWidth>=720);
  function edit(){declaration.replaceRaw(raw);}
  async function validate(){await declaration.validate();}
  async function runProposal(){const value=quick.create(proposal);if(!value){proposalStatus='Proposal is not locally compatible or host capabilities are unavailable.';return;}proposalStatus=await quick.validateAndCommit(value)?'Validated proposal committed atomically.':'Proposal was rejected or became stale.';}
  function requireValue<T>(value:T|undefined):T{if(value===undefined)throw new Error('Gateway Configure context is unavailable.');return value;}
</script>
<main class="min-h-0 p-4 sm:p-6 lg:p-8">
 <div class="mx-auto grid w-full max-w-[110rem] gap-4">
  <header class="flex flex-wrap items-start justify-between gap-4"><div><p class="studio-label">HPD Gateway Studio · Configure</p><h1 class="text-3xl font-extrabold">One complete candidate</h1><p class="mt-2 max-w-3xl text-sm text-studio-muted">Raw, visual, Quick Route, navigation, and validation are projections of generation {authored.document.editGeneration.toString()}. Nothing here submits or activates.</p></div><span class="studio-badge studio-badge-warning">{authored.document.state}</span></header>
  {#if !canMutate}<section class="studio-panel border-studio-warning-soft bg-studio-warning-muted p-4" role="status"><h2 class="font-bold">Safe read-only presentation</h2><p class="text-sm">Sign in and use a viewport at least 720 CSS pixels wide to edit. The authored candidate remains intact.</p></section>{/if}
  <section class="studio-panel grid gap-3 p-4" aria-label="Candidate status"><div class="grid gap-2 sm:grid-cols-2 xl:grid-cols-4"><div><p class="studio-label">Authored source</p><p class="studio-text-safe font-mono text-xs">{authored.document.sourceSha256}</p></div><div><p class="studio-label">Validation identity</p><p class="studio-text-safe font-mono text-xs">{authored.document.validation?.contentHashValue??'Not server validated'}</p></div><div><p class="studio-label">Host capabilities</p><p class="font-semibold">{remote.observation?.hostCapabilities.state??'Not observed'}</p></div><div><p class="studio-label">Changes</p><p class="font-semibold">{diff?.differences.length??0}{diff?.truncatedCount?' + truncated':''}</p></div></div><div class="flex flex-wrap gap-2"><button class="studio-button studio-button-sm" type="button" disabled={!canMutate||authored.document.compatibleGraph===null} onclick={()=>declaration.captureBaseline()}>Capture local baseline</button><button class="studio-button studio-button-sm" type="button" disabled={!canMutate||authored.document.compatibleGraph===null} onclick={validate}>Validate candidate</button><button class="studio-button studio-button-sm" type="button" disabled={!canMutate} onclick={()=>declaration.reset()}>New local candidate</button></div></section>
  <nav class="flex gap-2" aria-label="Configure views">{#each ['visual','raw','truth'] as view}<button class="studio-button studio-button-sm" aria-pressed={tab===view} onclick={()=>tab=view as typeof tab}>{view==='visual'?'Visual':view==='raw'?'Authored raw':'Read-only truth'}</button>{/each}</nav>
  {#if tab==='raw'}<section class="studio-panel grid gap-3 p-4"><label class="grid gap-2 font-bold" for="gateway-raw">Exact authored JSON</label><textarea id="gateway-raw" class="studio-focus-ring min-h-[32rem] rounded-studio border border-studio-line bg-studio-panel-raised p-3 font-mono text-sm" bind:value={raw} oninput={edit} disabled={!canMutate} spellcheck="false"></textarea>{#each authored.document.diagnostics as diagnostic}<p class="text-sm text-studio-danger" role="alert">{diagnostic.path||'/'} · {diagnostic.code}</p>{/each}</section>
  {:else if tab==='truth'}<section class="grid gap-3 lg:grid-cols-2"><article class="studio-panel p-4"><p class="studio-label">Desired · read-only</p><pre class="studio-text-safe mt-2 overflow-auto text-xs">{JSON.stringify(remote.observation?.desired??{state:'not-observed'},null,2)}</pre></article><article class="studio-panel p-4"><p class="studio-label">Effective · read-only</p><pre class="studio-text-safe mt-2 overflow-auto text-xs">{JSON.stringify(remote.observation?.effective??{state:'not-observed'},null,2)}</pre></article><article class="studio-panel p-4"><p class="studio-label">Selected revision</p><p>Unavailable in Slice 6.</p></article><article class="studio-panel p-4"><p class="studio-label">Native</p><p>Unavailable: no bounded native-raw operation exists.</p></article></section>
  {:else}<div class="grid gap-4 xl:grid-cols-[18rem_minmax(0,1fr)_22rem]"><aside class="studio-panel grid content-start gap-3 p-4"><h2 class="font-bold">Local document navigator</h2><input class="studio-focus-ring rounded-studio border border-studio-line bg-studio-panel-raised p-2" placeholder="Local document search" bind:value={search}/><ul class="grid gap-1">{#each results as entry}<li class="studio-text-safe rounded-studio border border-studio-line p-2 text-xs"><strong>{entry.identity}</strong><br/>{entry.family} · used by {entry.usedBy.length}{entry.unresolved?' · unresolved':''}{entry.orphan?' · orphan':''}</li>{/each}</ul></aside><section class="studio-panel p-4"><h2 class="font-bold">Generated visual fields</h2><p class="mt-1 text-sm text-studio-muted">{gatewayDeclarationEditorContract.fields.filter(value=>value.disposition==='editable').length} released behavior fields are represented. Structural seams remain navigation-only.</p><div class="mt-4 grid gap-3 sm:grid-cols-2">{#each ['identity','match','endpoint','policies','reliability','security','transport','metadata','advanced'] as group}<article class="rounded-studio border border-studio-line p-3"><h3 class="font-semibold capitalize">{group}</h3><p class="text-xs text-studio-muted">{gatewayDeclarationEditorContract.fields.filter(value=>value.presentationGroup===group&&value.disposition==='editable').length} editable occurrences</p></article>{/each}</div><p class="mt-4 text-sm">Use Authored raw for complete lossless editing. Visual controls never hide or discard unknown data.</p></section><aside class="studio-panel grid content-start gap-3 p-4"><h2 class="font-bold">Quick Route transaction</h2><ol class="list-decimal pl-5 text-sm"><li>Request match</li><li>Upstream and destination</li><li>Optional installed policies</li><li>Proposed transaction diff</li><li>Authoritative validation</li></ol><label class="grid gap-1 text-sm font-semibold">Complete proposed candidate<textarea class="studio-focus-ring min-h-48 rounded-studio border border-studio-line bg-studio-panel-raised p-2 font-mono text-xs" bind:value={proposal} disabled={!canMutate}></textarea></label><button class="studio-button" type="button" disabled={!canMutate} onclick={runProposal}>Validate and atomically apply</button>{#if proposalStatus}<p class="text-sm" role="status">{proposalStatus}</p>{/if}</aside></div>{/if}
 </div>
</main>
