<script lang="ts">
  import {onMount} from 'svelte';
  import {useStudioModuleContext} from '@hpd-research/hpd-studio-core';
  import type {GatewayDeclarationController,GatewayDeclarationSnapshot} from './declaration-state.ts';
  import {diffGatewayDocuments,projectGatewayNavigator,searchGatewayNavigator} from './declaration-projections.ts';
  import type {GatewayStudioController,GatewayStudioSnapshot} from './state.ts';
  import {buildGatewayQuickRoute,type GatewayQuickRouteCoordinator,type GatewayQuickRouteInput} from './quick-route.ts';
  import {projectGatewayVisualFields,visualFieldNode,type GatewayVisualField} from './visual-fields.ts';
  import {applyGatewayStructureAction,projectGatewayStructureActions,type GatewayStructureAction} from './structural-editor.ts';
  const context=useStudioModuleContext();const declaration=requireValue(context.get<GatewayDeclarationController>('gateway-declaration-controller'));const overview=requireValue(context.get<GatewayStudioController>('gateway-controller'));const quick=requireValue(context.get<GatewayQuickRouteCoordinator>('gateway-quick-route-coordinator'));
  let authored:GatewayDeclarationSnapshot=$state(declaration.snapshot());let remote:GatewayStudioSnapshot=$state(overview.snapshot());let raw=$state(declaration.snapshot().document.utf8Text);let tab=$state<'visual'|'raw'|'truth'>('visual');let search=$state('');let proposalStatus=$state('');let viewportWidth=$state(0);let quickStep=$state(1);
  let routeId=$state('route-1'),path=$state('/api/{**catch-all}'),methods=$state('GET'),hosts=$state(''),listenerId=$state(''),upstreamId=$state('upstream-1'),destinationId=$state('destination-1'),destinationAddress=$state('https://localhost:7001'),authorizationPolicy=$state(''),corsPolicy=$state(''),trafficAdmissionPolicy=$state(''),outputCachePolicy=$state('');
  onMount(()=>{const resize=()=>viewportWidth=globalThis.innerWidth;resize();globalThis.addEventListener('resize',resize);const a=declaration.subscribe(next=>{authored=next;if(raw!==next.document.utf8Text)raw=next.document.utf8Text;});const b=overview.subscribe(next=>remote=next);return()=>{globalThis.removeEventListener('resize',resize);a();b();};});
  const navigator=$derived(authored.document.compatibleGraph?projectGatewayNavigator(authored.document.compatibleGraph,authored.baseline?.graph??null,authored.document.diagnostics.map(value=>value.path)):null);const results=$derived(navigator?searchGatewayNavigator(navigator,search):[]);const diff=$derived(authored.document.compatibleGraph&&authored.baseline?diffGatewayDocuments(authored.document.compatibleGraph,authored.baseline.graph):null);const canMutate=$derived(remote.authentication.isAuthenticated&&viewportWidth>=720);const capabilities=$derived(remote.observation?.hostCapabilities.value??null);const fields=$derived(authored.document.compatibleGraph?projectGatewayVisualFields(authored.document.compatibleGraph,capabilities):[]);const structureActions=$derived(authored.document.compatibleGraph?projectGatewayStructureActions(authored.document.compatibleGraph):[]);const quickPreview=$derived(buildPreview());
  function edit(){declaration.replaceRaw(raw);}async function validate(){await declaration.validate();}
  function changeField(field:GatewayVisualField,event:Event){const target=event.currentTarget as HTMLInputElement|HTMLSelectElement;const node=visualFieldNode(field,target.value,target instanceof HTMLInputElement&&target.type==='checkbox'?target.checked:undefined);if(node!==null)declaration.setAtPointer(field.pointer,node);}
  function omitField(field:GatewayVisualField){if(!field.required)declaration.removeAtPointer(field.pointer);}
  function applyStructure(action:GatewayStructureAction){applyGatewayStructureAction(declaration,action);}
  function input():GatewayQuickRouteInput{return{routeId,path,methods:split(methods),hosts:split(hosts),listenerId,upstreamId,destinationId,destinationAddress,authorizationPolicy,corsPolicy,trafficAdmissionPolicy,outputCachePolicy};}
  function buildPreview(){return buildGatewayQuickRoute(declaration,input());}
  async function runProposal(){const built=buildGatewayQuickRoute(declaration,input());if(!built){proposalStatus='The guided transaction is incomplete, collides, or cannot preserve the current document.';return;}const value=quick.create(built.proposedUtf8);if(!value){proposalStatus='Proposal is not locally compatible or host capabilities are unavailable.';return;}proposalStatus=await quick.validateAndCommit(value)?'Validated Route, Upstream, and destination committed atomically.':'Proposal was rejected or became stale.';}
  function split(value:string):string[]{return value.split(',').map(item=>item.trim()).filter(Boolean).slice(0,64);}function requireValue<T>(value:T|undefined):T{if(value===undefined)throw new Error('Gateway Configure context is unavailable.');return value;}
</script>
<main class="min-h-0 p-4 sm:p-6 lg:p-8"><div class="mx-auto grid w-full max-w-[110rem] gap-4">
 <header class="flex flex-wrap items-start justify-between gap-4"><div><p class="studio-label">HPD Gateway Studio · Configure</p><h1 class="text-3xl font-extrabold">One complete candidate</h1><p class="mt-2 max-w-3xl text-sm text-studio-muted">Raw, visual, Quick Route, navigation, and validation are projections of generation {authored.document.editGeneration.toString()}. Nothing here submits or activates.</p></div><span class="studio-badge studio-badge-warning">{authored.document.state}</span></header>
 {#if !canMutate}<section class="studio-panel border-studio-warning-soft bg-studio-warning-muted p-4" role="status"><h2 class="font-bold">Safe read-only presentation</h2><p class="text-sm">Sign in and use a viewport at least 720 CSS pixels wide to edit.</p></section>{/if}
 <section class="studio-panel grid gap-3 p-4"><div class="grid gap-2 sm:grid-cols-2 xl:grid-cols-4"><div><p class="studio-label">Authored source</p><p class="studio-text-safe font-mono text-xs">{authored.document.sourceSha256}</p></div><div><p class="studio-label">Validation identity</p><p class="studio-text-safe font-mono text-xs">{authored.document.validation?.contentHashValue??'Not server validated'}</p></div><div><p class="studio-label">Host capabilities</p><p class="font-semibold">{remote.observation?.hostCapabilities.state??'Not observed'}</p></div><div><p class="studio-label">Changes</p><p class="font-semibold">{diff?.differences.length??0}</p></div></div><div class="flex flex-wrap gap-2"><button class="studio-button studio-button-sm" disabled={!canMutate||authored.document.compatibleGraph===null} onclick={()=>declaration.captureBaseline()}>Capture local baseline</button><button class="studio-button studio-button-sm" disabled={!canMutate||authored.document.compatibleGraph===null} onclick={validate}>Validate candidate</button><button class="studio-button studio-button-sm" disabled={!canMutate} onclick={()=>declaration.reset()}>New local candidate</button></div></section>
 <nav class="flex gap-2" aria-label="Configure views">{#each ['visual','raw','truth'] as view}<button class="studio-button studio-button-sm" aria-pressed={tab===view} onclick={()=>tab=view as typeof tab}>{view==='visual'?'Visual':view==='raw'?'Authored raw':'Read-only truth'}</button>{/each}</nav>
 {#if tab==='raw'}<section class="studio-panel grid gap-3 p-4"><label class="grid gap-2 font-bold" for="gateway-raw">Exact authored JSON</label><textarea id="gateway-raw" class="studio-focus-ring min-h-[32rem] rounded-studio border border-studio-line bg-studio-panel-raised p-3 font-mono text-sm" bind:value={raw} oninput={edit} disabled={!canMutate} spellcheck="false"></textarea>{#each authored.document.diagnostics as diagnostic}<p class="text-sm text-studio-danger" role="alert">{diagnostic.path||'/'} · {diagnostic.code}</p>{/each}</section>
 {:else if tab==='truth'}<section class="grid gap-3 lg:grid-cols-2"><article class="studio-panel p-4"><p class="studio-label">Desired · read-only</p><pre class="studio-text-safe mt-2 overflow-auto text-xs">{JSON.stringify(remote.observation?.desired??{state:'not-observed'},null,2)}</pre></article><article class="studio-panel p-4"><p class="studio-label">Effective · read-only</p><pre class="studio-text-safe mt-2 overflow-auto text-xs">{JSON.stringify(remote.observation?.effective??{state:'not-observed'},null,2)}</pre></article></section>
 {:else}<div class="grid gap-4 xl:grid-cols-[18rem_minmax(0,1fr)_24rem]">
  <aside class="studio-panel grid content-start gap-3 p-4"><h2 class="font-bold">Document navigator</h2><input class="studio-focus-ring rounded-studio border border-studio-line bg-studio-panel-raised p-2" placeholder="Local document search" bind:value={search}/><ul class="grid gap-1">{#each results as entry}<li class="studio-text-safe rounded-studio border border-studio-line p-2 text-xs"><strong>{entry.identity}</strong><br/>{entry.family} · used by {entry.usedBy.length}{entry.unresolved?' · unresolved':''}{entry.orphan?' · orphan':''}</li>{/each}</ul></aside>
  <section class="studio-panel grid content-start gap-4 p-4"><div><h2 class="font-bold">Generated visual editor</h2><p class="text-sm text-studio-muted">{fields.length} concrete fields resolved from the active schema branch. Changes update the one authored document.</p></div><fieldset class="grid gap-2 rounded-studio border border-studio-line p-3"><legend class="px-1 font-semibold">Structure</legend><p class="text-xs text-studio-muted">Schema-derived additions and union transitions make absent behavior reachable without replacing the candidate.</p><div class="flex flex-wrap gap-2">{#each structureActions as action}<button class="studio-button studio-button-sm" disabled={!canMutate} onclick={()=>applyStructure(action)}>{action.label}</button>{/each}</div></fieldset>{#each ['identity','match','endpoint','policies','reliability','security','transport','metadata','advanced'] as group}{#if fields.some(field=>field.group===group)}<fieldset class="grid gap-3 rounded-studio border border-studio-line p-3"><legend class="px-1 font-semibold capitalize">{group}</legend>{#each fields.filter(field=>field.group===group) as field}<div class="grid gap-1 text-sm"><label class="font-semibold" for={field.key}>{field.label} {field.required?'· required':''}</label><span class="studio-text-safe text-xs text-studio-muted">{field.pointer} · {field.inheritance==='none'?'local':field.inheritance} · omitted: {field.omitted} · capability: {field.capabilityState}</span>{#if field.valueKind==='boolean'}<input id={field.key} type="checkbox" checked={field.value==='true'} onchange={(event)=>changeField(field,event)} disabled={!canMutate}/>{:else if field.enumValues.length||field.capabilityOptions.length}<select id={field.key} class="studio-focus-ring rounded-studio border border-studio-line bg-studio-panel-raised p-2" value={field.value} onchange={(event)=>changeField(field,event)} disabled={!canMutate}><option value="" disabled>Select value</option>{#each [...new Set([...field.enumValues,...field.capabilityOptions])] as option}<option value={option}>{option}</option>{/each}</select>{:else}<input id={field.key} class="studio-focus-ring rounded-studio border border-studio-line bg-studio-panel-raised p-2" value={field.value} inputmode={field.valueKind==='integer'?'numeric':'text'} onchange={(event)=>changeField(field,event)} disabled={!canMutate}/>{/if}{#if field.present&&!field.required}<button class="studio-button studio-button-sm justify-self-start" disabled={!canMutate} onclick={()=>omitField(field)}>Use inherited / omitted value</button>{/if}</div>{/each}</fieldset>{/if}{/each}</section>
  <aside class="studio-panel grid content-start gap-3 p-4"><h2 class="font-bold">Quick Route</h2><p class="text-xs text-studio-muted">Step {quickStep} of 5. One provisional transaction; no server mutation.</p><div class="flex gap-1">{#each [1,2,3,4,5] as step}<button class="studio-button studio-button-sm" aria-pressed={quickStep===step} onclick={()=>quickStep=step}>{step}</button>{/each}</div>
   {#if quickStep===1}<label class="grid gap-1">Route ID<input bind:value={routeId}/></label><label class="grid gap-1">Path<input bind:value={path}/></label><label class="grid gap-1">Methods, comma-separated<input bind:value={methods}/></label><label class="grid gap-1">Hosts, comma-separated<input bind:value={hosts}/></label><label class="grid gap-1">Listener (optional)<select bind:value={listenerId}><option value="">No listener</option>{#each capabilities?.capabilities.listeners??[] as listener}<option value={listener.id}>{listener.id}</option>{/each}</select></label>
   {:else if quickStep===2}<label class="grid gap-1">Upstream ID<input bind:value={upstreamId}/></label><label class="grid gap-1">Destination ID<input bind:value={destinationId}/></label><label class="grid gap-1">Destination address<input bind:value={destinationAddress}/></label>
   {:else if quickStep===3}<label class="grid gap-1">Authorization policy<select bind:value={authorizationPolicy}><option value="">None</option>{#each capabilities?.capabilities.authorizationPolicies??[] as option}<option>{option}</option>{/each}</select></label><label class="grid gap-1">CORS policy<select bind:value={corsPolicy}><option value="">None</option>{#each capabilities?.capabilities.corsPolicies??[] as option}<option>{option}</option>{/each}</select></label><label class="grid gap-1">Admission policy<select bind:value={trafficAdmissionPolicy}><option value="">None</option>{#each capabilities?.capabilities.trafficAdmissionPolicies??[] as option}<option>{option}</option>{/each}</select></label><label class="grid gap-1">Output Cache policy<select bind:value={outputCachePolicy}><option value="">None</option>{#each capabilities?.capabilities.outputCacheProfiles??[] as option}<option value={option.name}>{option.name}@{option.version}</option>{/each}</select></label>
   {:else if quickStep===4}<h3 class="font-semibold">Proposed transaction diff</h3>{#if quickPreview}<ul class="text-xs">{#each quickPreview.changedPointers as pointer}<li class="studio-text-safe">{pointer}</li>{/each}</ul>{:else}<p class="text-sm text-studio-danger">The proposal is incomplete or conflicts with the document.</p>{/if}
   {:else}<p class="text-sm">Authoritative validation will bind the proposal to the current edit, principal, and capability generations before one atomic local commit.</p><button class="studio-button" disabled={!canMutate||quickPreview===null} onclick={runProposal}>Validate and atomically apply</button>{#if proposalStatus}<p class="text-sm" role="status">{proposalStatus}</p>{/if}{/if}
  </aside>
 </div>{/if}
</div></main>
