import type { GatewayClient } from '@hpd/gateway-client';
import { createGatewayDeclarationController, type GatewayDeclarationController, type GatewayServerValidationEvidence } from './declaration-state.ts';
import { framedSha256, lengthFrame, sha256Segments, uint64 } from './sha256.ts';

const encoder=new TextEncoder();
export interface GatewayQuickRouteProposalV1{readonly contractVersion:1;readonly baseEditGeneration:bigint;readonly baseSourceSha256:string;readonly principalGeneration:bigint;readonly capabilitySnapshotAlgorithm:string;readonly capabilitySnapshotValue:string;readonly proposedUtf8:string;readonly proposedSourceSha256:string;readonly proposalId:string;}
export interface GatewayQuickRouteCoordinator{create(proposedUtf8:string):GatewayQuickRouteProposalV1|null;validateAndCommit(proposal:GatewayQuickRouteProposalV1):Promise<boolean>;cancel():void;dispose():void;}
interface Options{readonly declaration:GatewayDeclarationController;readonly client:GatewayClient;readonly principalGeneration:()=>bigint;readonly capabilityIdentity:()=>Readonly<{algorithm:string;value:string}>|null;}
export function createGatewayQuickRouteCoordinator(options:Options):GatewayQuickRouteCoordinator{let current:string|null=null;let generation=0;let disposed=false;return Object.freeze({
  create(proposedUtf8:string){if(disposed||encoder.encode(proposedUtf8).byteLength>4*1024*1024)return null;const base=options.declaration.snapshot().document,capability=options.capabilityIdentity();if(base.compatibleGraph===null||capability===null)return null;const probe=createGatewayDeclarationController();const candidate=probe.replaceRaw(proposedUtf8);probe.dispose();if(candidate.compatibleGraph===null||candidate.state!=='LocallyValidNotServerValidated')return null;const principal=options.principalGeneration();const source=framedSha256('hpd.gateway.authored-source.v1\0',encoder.encode(proposedUtf8));const id=proposalIdentity(base.editGeneration,base.sourceSha256,principal,capability.algorithm,capability.value,proposedUtf8);current=id;generation++;return Object.freeze({contractVersion:1,baseEditGeneration:base.editGeneration,baseSourceSha256:base.sourceSha256,principalGeneration:principal,capabilitySnapshotAlgorithm:capability.algorithm,capabilitySnapshotValue:capability.value,proposedUtf8,proposedSourceSha256:source,proposalId:id});},
  async validateAndCommit(proposal:GatewayQuickRouteProposalV1){if(disposed||current!==proposal.proposalId)return false;const callGeneration=++generation;const identity=options.capabilityIdentity();if(identity===null||identity.algorithm!==proposal.capabilitySnapshotAlgorithm||identity.value!==proposal.capabilitySnapshotValue||options.principalGeneration()!==proposal.principalGeneration)return false;const probe=createGatewayDeclarationController({client:options.client,hostCapabilityIdentity:options.capabilityIdentity});probe.replaceRaw(proposal.proposedUtf8);const valid=await probe.validate();const evidence=probe.snapshot().document.validation;probe.dispose();if(!valid||evidence===null||disposed||callGeneration!==generation||current!==proposal.proposalId)return false;if(options.principalGeneration()!==proposal.principalGeneration)return false;const after=options.capabilityIdentity();if(after===null||after.algorithm!==proposal.capabilitySnapshotAlgorithm||after.value!==proposal.capabilitySnapshotValue)return false;if(framedSha256('hpd.gateway.authored-source.v1\0',encoder.encode(proposal.proposedUtf8))!==proposal.proposedSourceSha256)return false;const transferred:GatewayServerValidationEvidence=Object.freeze({...evidence});const committed=options.declaration.commitValidatedProposal(proposal.baseEditGeneration,proposal.baseSourceSha256,proposal.proposedUtf8,transferred,proposal.proposalId);if(committed)current=null;return committed;},
  cancel(){generation++;current=null;},dispose(){if(!disposed){disposed=true;generation++;current=null;}}
});}
function proposalIdentity(base:bigint,source:string,principal:bigint,algorithm:string,value:string,proposed:string):string{return sha256Segments(encoder.encode('hpd.gateway.quick-route-proposal.v1\0'),uint64(base),lengthFrame(encoder.encode(source)),uint64(principal),lengthFrame(encoder.encode(algorithm)),lengthFrame(encoder.encode(value)),lengthFrame(encoder.encode(proposed)));}
