import {gatewayRuntimeSchemas} from '@hpd/gateway-client';
import type {GatewayDeclarationController} from './declaration-state.ts';
import type {GatewayJsonNode,GatewayJsonObject} from './authored-json.ts';

type Schema=Readonly<Record<string,unknown>>;const schemas=gatewayRuntimeSchemas as unknown as Readonly<Record<string,Schema>>;const root=schemas.HPD_Gateway_Abstractions_GatewayConfiguration;
export interface GatewayStructureAction{readonly key:string;readonly kind:'add-container'|'append-item'|'select-union'|'remove-container'|'remove-item';readonly pointer:string;readonly label:string;readonly value:GatewayJsonNode|null;}
export function projectGatewayStructureActions(graph:GatewayJsonObject):readonly GatewayStructureAction[]{if(root===undefined)return Object.freeze([]);const output:GatewayStructureAction[]=[];walk(graph,root,'',output,0);output.sort((a,b)=>ordinal(a.key,b.key));return Object.freeze(output.slice(0,4096));}
export function applyGatewayStructureAction(controller:GatewayDeclarationController,action:GatewayStructureAction):boolean{return action.kind==='remove-container'||action.kind==='remove-item'?controller.removeAtPointer(action.pointer):action.kind==='append-item'?controller.appendAtPointer(action.pointer,action.value!):controller.setAtPointer(action.pointer,action.value!);}

function walk(node:GatewayJsonNode,schemaValue:Schema,path:string,output:GatewayStructureAction[],depth:number):void{if(depth>64||output.length>=4096)return;const schema=resolve(schemaValue);if(schema===null)return;const choices=unionChoices(schema);if(choices.length){if(node.kind!=='object')return;const discriminator=record(schema.discriminator)&&typeof schema.discriminator.propertyName==='string'?schema.discriminator.propertyName:'kind';const active=node.entries.find(entry=>entry.name===discriminator)?.value;for(const choice of choices)if(active?.kind!=='string'||active.value!==choice.tag)output.push(action('select-union',path,`Use ${choice.tag} branch`,template(choice.schema,depth+1,choice.tag,discriminator)));const selected=active?.kind==='string'?choices.find(choice=>choice.tag===active.value):undefined;if(selected)walk(node,selected.schema,path,output,depth+1);return;}
  if(node.kind==='array'){if(record(schema.items))output.push(action('append-item',path,`Add ${singular(path)}`,template(schema.items as Schema,depth+1)));if(record(schema.items))node.items.forEach((item,index)=>{output.push(action('remove-item',`${path}/${index}`,`Remove ${singular(path)} ${index+1}`,null));walk(item,schema.items as Schema,`${path}/${index}`,output,depth+1);});return;}
  if(node.kind!=='object')return;const properties=record(schema.properties)?schema.properties as Record<string,Schema>:{};const required=new Set(array(schema.required).filter((value):value is string=>typeof value==='string'));for(const [name,childSchema] of Object.entries(properties)){const next=`${path}/${escapePointer(name)}`;const child=node.entries.find(entry=>entry.name===name)?.value;if(child!==undefined){const resolvedChild=resolve(childSchema);const childTypes=resolvedChild===null?[]:array(resolvedChild.type);if(!required.has(name)&&(childTypes.includes('object')||childTypes.includes('array')||unionChoices(resolvedChild??{}).length))output.push(action('remove-container',next,`Remove ${name}`,null));walk(child,childSchema,next,output,depth+1);continue;}const resolved=resolve(childSchema);if(resolved===null)continue;const branches=unionChoices(resolved);if(branches.length){const discriminator=record(resolved.discriminator)&&typeof resolved.discriminator.propertyName==='string'?resolved.discriminator.propertyName:'kind';for(const branch of branches)output.push(action('select-union',next,`Add ${name}: ${branch.tag}`,template(branch.schema,depth+1,branch.tag,discriminator)));continue;}const types=array(resolved.type);if(types.includes('object')||types.includes('array'))output.push(action('add-container',next,`Add ${name}`,template(resolved,depth+1)));}}
function template(source:Schema,depth:number,unionTag?:string,discriminator='kind',hint='value'):GatewayJsonNode{if(depth>64)return Object.freeze({kind:'object',entries:Object.freeze([])});const schema=resolve(source)??source;const choices=unionChoices(schema);if(choices.length){const chosen=unionTag===undefined?choices[0]!:choices.find(value=>value.tag===unionTag)??choices[0]!;return template(chosen.schema,depth+1,chosen.tag,discriminator,hint);}const types=array(schema.type);if(types.includes('object')||record(schema.properties)){const properties=record(schema.properties)?schema.properties as Record<string,Schema>:{};const required=new Set(array(schema.required).filter((value):value is string=>typeof value==='string'));const entries:{name:string;value:GatewayJsonNode}[]=[];if(unionTag!==undefined)entries.push({name:discriminator,value:Object.freeze({kind:'string',value:unionTag})});for(const name of [...required].sort(ordinal)){if(name===discriminator&&unionTag!==undefined)continue;const child=properties[name];if(record(child))entries.push({name,value:template(child,depth+1,undefined,'kind',name)});}return Object.freeze({kind:'object',entries:Object.freeze(entries.map(entry=>Object.freeze(entry)))});}if(types.includes('array'))return Object.freeze({kind:'array',items:Object.freeze([])});const constant=schema.const??array(schema.enum)[0];if(typeof constant==='string')return Object.freeze({kind:'string',value:constant});if(typeof constant==='boolean')return Object.freeze({kind:'boolean',value:constant});if(typeof constant==='number')return Object.freeze({kind:'number',lexeme:String(constant)});if(types.includes('integer'))return Object.freeze({kind:'number',lexeme:'0'});if(types.includes('boolean'))return Object.freeze({kind:'boolean',value:false});if(types.includes('null')&&!types.includes('string'))return Object.freeze({kind:'null'});return Object.freeze({kind:'string',value:typeof schema.format==='string'&&schema.format==='uri'?'https://example.invalid':`new-${hint}`});}
function unionChoices(schema:Schema):readonly {tag:string;schema:Schema}[]{if(!record(schema.discriminator)||!record(schema.discriminator.mapping))return[];const result:{tag:string;schema:Schema}[]=[];for(const [tag,reference]of Object.entries(schema.discriminator.mapping))if(typeof reference==='string'){const value=resolveReference(reference);if(value)result.push({tag,schema:value});}return result.sort((a,b)=>ordinal(a.tag,b.tag));}
function resolve(schema:Schema):Schema|null{return typeof schema.$ref==='string'?resolveReference(schema.$ref):schema;}
function resolveReference(reference:string):Schema|null{const prefix='#/components/schemas/';return reference.startsWith(prefix)?schemas[reference.slice(prefix.length)]??null:null;}
function action(kind:GatewayStructureAction['kind'],pointer:string,label:string,value:GatewayJsonNode|null):GatewayStructureAction{return Object.freeze({key:`${kind}:${pointer}:${label}`,kind,pointer,label,value});}
function singular(pointer:string):string{const value=pointer.split('/').at(-1)??'item';return value.endsWith('ies')?`${value.slice(0,-3)}y`:value.endsWith('s')?value.slice(0,-1):value;}
function array(value:unknown):readonly unknown[]{return Array.isArray(value)?value:value===undefined?[]:[value];}function record(value:unknown):value is Record<string,unknown>{return typeof value==='object'&&value!==null&&!Array.isArray(value);}function escapePointer(value:string):string{return value.replaceAll('~','~0').replaceAll('/','~1');}function ordinal(a:string,b:string):number{return a<b?-1:a>b?1:0;}
