namespace HPD.Agent.Authority;

internal sealed class GraphParticipantReservationFoldV2
{
    private readonly SessionAuthorityStampV1 _session;
    private readonly GraphParticipantReservationFoldV1 _v1;
    private readonly Dictionary<JournalFactId,byte[]> _facts=new(65_536);
    private readonly Dictionary<OperationId,(AuthorityFactEnvelopeV1 Command,AuthorityFactEnvelopeV1? Fact,GraphParticipantReservationV1? Reservation,BoundedAscii? Code)> _operations=new(65_536);
    private readonly HashSet<OperationId> _v1Commands=[];
    private readonly HashSet<OperationId> _v1Facts=[];
    private InvalidHistory? _invalid;private bool _completed;private long _through;private ulong _records,_bytes;private JournalPositionV1? _appliedSingleton,_appliedPredecessor,_v1Applied;
    private GraphParticipantReservationFoldV2(SessionAuthorityStampV1 session){_session=session;_v1=GraphParticipantReservationFoldV1.Create(session);}
    internal static GraphParticipantReservationFoldV2 Create(SessionAuthorityStampV1 session){if(!session.IsValid)throw new ArgumentException("A valid session is required.",nameof(session));return new(session);}

    internal ApplyResultV1 Apply(AuthorityFactEnvelopeV1 envelope)
    {
        ArgumentNullException.ThrowIfNull(envelope);if(_invalid is not null)return _invalid;if(_completed)return Fail("safe-code-invalid");
        if(_v1.Apply(envelope) is GraphParticipantReservationFoldV1.InvalidHistory v1Invalid)return Fail(v1Invalid.SafeCode.ToString());
        if(envelope.Position.Session!=_session)return Fail("session-mismatch");var exact=envelope.PayloadBytes.ToArray();if(_facts.ContainsKey(envelope.FactId))return Fail("duplicate-changed");if(envelope.Position.Sequence!=_through+1)return Fail("position-invalid");var length=AuthorityCanonicalCborV1.GetEnvelopeEncodedLength(envelope);if(_records==65_536||length>8192||_bytes>536_870_912UL-length)return Fail("record-wire-invalid");_facts.Add(envelope.FactId,exact);_through++;_records++;_bytes+=length;
        var v1c=GraphParticipantBindingPayloadRegistrationsV1.ReservationCommand;var v1f=GraphParticipantBindingPayloadRegistrationsV1.ReservationFact;
        if(envelope.PayloadSchema==v1c.Schema)
        {if(!GraphParticipantBindingCodecsV1.TryDecodeReservationCommand(exact,out var o)||o is null||!GraphParticipantBindingCodecsV1.TryDecodeReservationCommandBody(o.BodyBytes.ToArray(),out var b)||b is null||GraphParticipantBindingFactIdsV1.ReservationCommand(_session,b.OperationId)!=envelope.FactId)return Fail("record-wire-invalid");if(_operations.ContainsKey(b.OperationId))return Fail("cross-version-operation-conflict");_v1Commands.Add(b.OperationId);return new Accepted();}
        if(envelope.PayloadSchema==v1f.Schema)
        {if(!GraphParticipantBindingCodecsV1.TryDecodeReservationFact(exact,out var o)||o is null||!GraphParticipantBindingCodecsV1.TryDecodeReservationFactBody(o.BodyBytes.ToArray(),out var b)||b is null||GraphParticipantBindingFactIdsV1.ReservationFact(b.CommandPosition)!=envelope.FactId)return Fail("record-wire-invalid");_v1Facts.Add(b.OperationId);if(b.Outcome==1){if(_appliedSingleton is not null||_v1Applied is not null)return Fail("singleton-duplicate");_v1Applied=envelope.Position;}return new Accepted();}
        var commandSchema=GraphParticipantReservationPayloadRegistrationsV2.ReservationCommand;var factSchema=GraphParticipantReservationPayloadRegistrationsV2.ReservationFact;if(envelope.PayloadSchema!=commandSchema.Schema&&envelope.PayloadSchema!=factSchema.Schema)return new Accepted();
        var registration=envelope.PayloadSchema==commandSchema.Schema?commandSchema:factSchema;if(envelope.ThreadScope is not null||envelope.Owner!=OwnerSliceId.S1||envelope.PayloadHash!=AuthorityPayloadHashV1.Compute(registration.SchemaToken,envelope.PayloadSchema,exact))return Fail("record-wire-invalid");
        if(envelope.PayloadSchema==commandSchema.Schema)
        {if(!GraphParticipantReservationCodecsV2.TryDecodeReservationCommand(exact,out var outer)||outer is null||!GraphParticipantReservationCodecsV2.TryDecodeReservationCommandBody(outer.BodyBytes.ToArray(),out var body)||body is null)return Fail("record-wire-invalid");if(outer.Session!=_session||outer.ExpectedAuthority.Session!=_session)return Fail("session-mismatch");if(GraphParticipantReservationFactIdsV2.ReservationCommand(_session,body.OperationId)!=envelope.FactId)return Fail("fact-id-mismatch");if(_operations.ContainsKey(body.OperationId))return Fail("duplicate-changed");if(_v1Commands.Contains(body.OperationId))return Fail("cross-version-operation-conflict");_operations.Add(body.OperationId,(envelope,null,null,null));return new Accepted();}
        if(!GraphParticipantReservationCodecsV2.TryDecodeReservationFact(exact,out var factOuter)||factOuter is null||!GraphParticipantReservationCodecsV2.TryDecodeReservationFactBody(factOuter.BodyBytes.ToArray(),out var fact)||fact is null)return Fail("record-wire-invalid");if(factOuter.Session!=_session||factOuter.ExpectedAuthority.Session!=_session||fact.CommandPosition.Session!=_session)return Fail("session-mismatch");if(!_operations.TryGetValue(fact.OperationId,out var entry)||entry.Command.Position!=fact.CommandPosition||entry.Fact is not null||GraphParticipantReservationFactIdsV2.ReservationFact(fact.CommandPosition)!=envelope.FactId)return Fail("command-fact-join-invalid");
        if(envelope.Correlation!=entry.Command.Correlation||envelope.ObservedAt!=entry.Command.ObservedAt||!GraphParticipantReservationCodecsV2.TryDecodeReservationCommand(entry.Command.PayloadMemory,out var storedOuter)||storedOuter is null||!GraphParticipantReservationCodecsV2.TryDecodeReservationCommandBody(storedOuter.BodyBytes.ToArray(),out var stored)||stored is null||factOuter.ExpectedAuthority!=storedOuter.ExpectedAuthority||fact.RuntimeGeneration!=stored.RuntimeGeneration||fact.GraphGeneration!=stored.GraphGeneration||fact.ParticipantPlanFingerprint!=stored.ParticipantPlanFingerprint||fact.AllocationCarrierFingerprint!=stored.AllocationCarrierFingerprint||fact.ObservedAt!=stored.ObservedAt)return Fail("command-fact-join-invalid");
        var current=_appliedSingleton??_v1Applied;var code=fact.SafeCode?.ToString();var predecessorValid=code switch{"participant-already-reserved"=>current is not null?fact.ActualPredecessor==current:fact.ActualPredecessor==stored.ExpectedReservationFact,"reservation-predecessor-conflict"=>fact.ActualPredecessor==current&&stored.ExpectedReservationFact!=current,_=>fact.ActualPredecessor==stored.ExpectedReservationFact&&fact.ActualPredecessor==current};if(!predecessorValid)return Fail("command-fact-join-invalid");
        var earliest=EarliestFor(stored.ExpectedReservationFact);var isLeader=earliest?.Position==entry.Command.Position;
        if((fact.Outcome==1||code=="participant-id-collision")&&!isLeader)return Fail("election-invalid");
        if(code=="participant-already-reserved"&&current is null&&isLeader)return Fail("election-invalid");
        if(fact.Outcome==1)
        {if(fact.Reservation is null||fact.SafeCode is not null||current is not null||fact.Reservation.ParticipantFactoryKey!=stored.ParticipantFactoryKey||!fact.Reservation.OrderedTopologyNodeKeys.SequenceEqual(stored.OrderedTopologyNodeKeys))return Fail("singleton-duplicate");_appliedSingleton=envelope.Position;_appliedPredecessor=fact.ActualPredecessor;_operations[fact.OperationId]=(entry.Command,envelope,fact.Reservation,null);}
        else if(fact.Outcome==2&&fact.Reservation is null&&code is "participant-id-collision" or "participant-already-reserved" or "reservation-predecessor-conflict")_operations[fact.OperationId]=(entry.Command,envelope,null,fact.SafeCode);else return Fail("outcome-invalid");return new Accepted();
    }

    internal Completed Complete(){if(_v1Commands.Except(_v1Facts).Any())throw new InvalidOperationException("cross-version-command-incomplete");_v1.Complete();_completed=true;return new(_session,_through,_records,_bytes,_appliedSingleton,_appliedPredecessor);}
    internal QueryResultV1 Query(OperationId operationId){if(!_completed||_invalid is not null||!operationId.IsValid)throw new InvalidOperationException("Only a valid completed history is queryable.");if(!_operations.TryGetValue(operationId,out var x))return new NotFound();if(x.Fact is null)return new CommandOnly(x.Command);return x.Reservation is not null?new AppliedReservation(x.Command,x.Fact,x.Reservation):new RejectedReservation(x.Command,x.Fact,x.Code!.Value);}
    internal ElectionResultV2 Elect(OperationId operationId)
    {if(!_completed||_invalid is not null||!operationId.IsValid)throw new InvalidOperationException("Only a valid completed history is electable.");if(!_operations.TryGetValue(operationId,out var target)||target.Fact is not null)return new NoCommand();var current=_appliedSingleton??_v1Applied;if(current is not null)return new BlockedByApplied(target.Command,current.Value);if(!GraphParticipantReservationCodecsV2.TryDecodeReservationCommand(target.Command.PayloadMemory,out var outer)||outer is null||!GraphParticipantReservationCodecsV2.TryDecodeReservationCommandBody(outer.BodyBytes.ToArray(),out var body)||body is null)return new PredecessorConflict(target.Command,current);if(body.ExpectedReservationFact!=current)return new PredecessorConflict(target.Command,current);var eligible=_operations.Values.Where(x=>x.Fact is null).Select(x=>x.Command).Where(x=>{if(!GraphParticipantReservationCodecsV2.TryDecodeReservationCommand(x.PayloadMemory,out var o)||o is null||!GraphParticipantReservationCodecsV2.TryDecodeReservationCommandBody(o.BodyBytes.ToArray(),out var b)||b is null)return false;return b.ExpectedReservationFact==current;}).OrderBy(x=>x.Position.Sequence).First();return eligible.Position==target.Command.Position?new Leader(target.Command):new Follower(target.Command,eligible);}
    private AuthorityFactEnvelopeV1? EarliestFor(JournalPositionV1? predecessor)=>_operations.Values.Where(x=>x.Fact is null).Select(x=>x.Command).Where(x=>{if(!GraphParticipantReservationCodecsV2.TryDecodeReservationCommand(x.PayloadMemory,out var o)||o is null||!GraphParticipantReservationCodecsV2.TryDecodeReservationCommandBody(o.BodyBytes.ToArray(),out var b)||b is null)return false;return b.ExpectedReservationFact==predecessor;}).OrderBy(x=>x.Position.Sequence).FirstOrDefault();
    private InvalidHistory Fail(string code)=>_invalid??=new(new BoundedAscii(code));
    internal abstract record ApplyResultV1;internal sealed record Accepted:ApplyResultV1;internal sealed record InvalidHistory(BoundedAscii SafeCode):ApplyResultV1;internal sealed record Completed(SessionAuthorityStampV1 Session,long SnapshotThrough,ulong RecordCount,ulong TotalCanonicalBytes,JournalPositionV1? AppliedReservationFact,JournalPositionV1? AppliedReservationPredecessor);internal abstract record QueryResultV1;internal sealed record NotFound:QueryResultV1;internal sealed record CommandOnly(AuthorityFactEnvelopeV1 Command):QueryResultV1;internal sealed record AppliedReservation(AuthorityFactEnvelopeV1 Command,AuthorityFactEnvelopeV1 Fact,GraphParticipantReservationV1 Reservation):QueryResultV1;internal sealed record RejectedReservation(AuthorityFactEnvelopeV1 Command,AuthorityFactEnvelopeV1 Fact,BoundedAscii SafeCode):QueryResultV1;
    internal abstract record ElectionResultV2;internal sealed record Leader(AuthorityFactEnvelopeV1 Command) : ElectionResultV2;internal sealed record Follower(AuthorityFactEnvelopeV1 Command, AuthorityFactEnvelopeV1 LeaderCommand) : ElectionResultV2;internal sealed record BlockedByApplied(AuthorityFactEnvelopeV1 Command, JournalPositionV1 AppliedFact) : ElectionResultV2;internal sealed record PredecessorConflict(AuthorityFactEnvelopeV1 Command, JournalPositionV1? ActualPredecessor) : ElectionResultV2;internal sealed record NoCommand : ElectionResultV2;
}
