// <auto-generated/>
#nullable enable
namespace HPD.Payments.Generated;

/// <summary>Stable mechanical projection of explicitly reviewed declarations.</summary>
internal static class ReviewedDeclarations
{
    private static readonly string[] Values =
    [
        "compatibility|WireRevision|rev-1",
        "connector|SimulatorConnector|authorize",
        "dependency|AgreementDependency|ScopedIdentity",
        "factory|PersistenceFactory|Agreement",
        "oracle|AgreementOracle|AGR-001",
        "serializer|AuthorityJsonContext|HPD.Payments.Contracts.Agreement.AgreementCommand",
        "table|AuthorityTable|Agreement",
        "testvector|AgreementReplay|duplicate-request",
        "visitor|ResultVisitor|Accepted",
    ];

    /// <summary>Gets the reviewed declarations in ordinal projection/name order.</summary>
    internal static global::System.ReadOnlySpan<string> Items => Values;
}
