namespace HPD.Agent.MCP;

/// <summary>
/// Registration info for an MCP server defined via [MCPServer] attribute.
/// Generated by source generator, consumed at agent build time.
/// ParentHarness is used at runtime to stamp ParentContainer on the MCP tools/container,
/// wiring them into the parent harness's collapse/expand lifecycle.
/// </summary>
public class MCPServerRegistration
{
    public string Name { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;

    /// <summary>
    /// Name of the harness class that owns this MCP server.
    /// Stamped as ParentContainer on runtime AIFunctions so ToolVisibilityManager
    /// can hide/show them based on the parent harness's expansion state.
    /// </summary>
    public string ParentHarness { get; set; } = string.Empty;

    /// <summary>
    /// When true, MCP tools sit behind their own MCP_* container nested inside the
    /// parent harness. When false, tools appear directly under the parent harness.
    /// </summary>
    public bool CollapseWithinHarness { get; set; }

    /// <summary>
    /// Path to mcp.json manifest (FromManifest mode).
    /// Null for inline config mode.
    /// </summary>
    public string? FromManifest { get; set; }

    /// <summary>
    /// Server name to look up in manifest (FromManifest mode).
    /// </summary>
    public string? ManifestServerName { get; set; }

    /// <summary>
    /// Attribute override for RequiresPermission (null = use value from config).
    /// </summary>
    public bool? RequiresPermissionOverride { get; set; }

    /// <summary>
    /// Provider for static [MCPServer] methods.
    /// Exactly one of StaticConfigProvider or InstanceConfigProvider is set.
    /// </summary>
    public Func<MCPServerConfig?>? StaticConfigProvider { get; set; }

    /// <summary>
    /// Provider for instance [MCPServer] methods.
    /// Receives the harness instance as object, returns config.
    /// Exactly one of StaticConfigProvider or InstanceConfigProvider is set.
    /// </summary>
    public Func<object, MCPServerConfig?>? InstanceConfigProvider { get; set; }
}
