using HPD.Agent.Authority;

namespace HPD.Agent.Tests.Authority;

public sealed class PrivacyCopyLifecycleV1Tests
{
    [Fact]
    public void Copy_is_reserved_before_escape_with_exact_frontier_and_retry()
    {var f=new Fixture();var state=PrivacyCopyLifecycleV1.Create();var operation=OperationId.Create();var command=new PrivacyCopyCommandV1.Reserve(operation,0,f.Reservation(0));var applied=Assert.IsType<PrivacyCopyResultV1.Applied>(PrivacyCopyLifecycleV1.Apply(state,command,8,32));Assert.Single(applied.State.Copies);Assert.IsType<PrivacyCopyResultV1.Duplicate>(PrivacyCopyLifecycleV1.Apply(applied.State,command,8,32));Assert.Equal("copy-frontier-conflict",Assert.IsType<PrivacyCopyResultV1.Rejected>(PrivacyCopyLifecycleV1.Apply(applied.State,new PrivacyCopyCommandV1.Reserve(OperationId.Create(),1,f.Reservation(0)),8,32)).SafeCode.ToString());}
    [Fact]
    public void Fence_closes_registration_and_one_receipt_settles_only_one_copy()
    {var f=new Fixture();var state=Reserved(f,2);state=Applied(state,new PrivacyCopyCommandV1.Fence(OperationId.Create(),2,DeletionId.Create()));state=Applied(state,new PrivacyCopyCommandV1.CloseRegistration(OperationId.Create(),3));var first=state.Copies.Keys.First();state=Applied(state,new PrivacyCopyCommandV1.AdmitReceipt(OperationId.Create(),4,first,CopyTerminalEvidenceV1.Deleted));state=Applied(state,new PrivacyCopyCommandV1.FoldTerminal(OperationId.Create(),5));Assert.Equal(PrivacyDeletionOutcomeV1.Unknown,state.Deletion!.Outcome);}
    [Fact]
    public void Hold_blocks_destruction_and_does_not_grant_other_authority()
    {var f=new Fixture();var state=Reserved(f,1);var copy=state.Copies.Keys.Single();state=Applied(state,new PrivacyCopyCommandV1.SetHold(OperationId.Create(),1,copy,true));state=Applied(state,new PrivacyCopyCommandV1.Fence(OperationId.Create(),2,DeletionId.Create()));state=Applied(state,new PrivacyCopyCommandV1.CloseRegistration(OperationId.Create(),3));Assert.Equal("copy-held",Assert.IsType<PrivacyCopyResultV1.Rejected>(PrivacyCopyLifecycleV1.Apply(state,new PrivacyCopyCommandV1.AdmitReceipt(OperationId.Create(),4,copy,CopyTerminalEvidenceV1.Deleted),8,32)).SafeCode.ToString());state=Applied(state,new PrivacyCopyCommandV1.FoldTerminal(OperationId.Create(),4));Assert.Equal(PrivacyDeletionOutcomeV1.Held,state.Deletion!.Outcome);}
    [Fact]
    public void Transfer_is_nonterminal_and_unknown_never_becomes_completed()
    {var f=new Fixture();var state=Reserved(f,1);var copy=state.Copies.Keys.Single();state=Applied(state,new PrivacyCopyCommandV1.Fence(OperationId.Create(),1,DeletionId.Create()));state=Applied(state,new PrivacyCopyCommandV1.CloseRegistration(OperationId.Create(),2));Assert.Equal("copy-transfer-nonterminal",Assert.IsType<PrivacyCopyResultV1.Rejected>(PrivacyCopyLifecycleV1.Apply(state,new PrivacyCopyCommandV1.AdmitReceipt(OperationId.Create(),3,copy,CopyTerminalEvidenceV1.Transferred),8,32)).SafeCode.ToString());state=Applied(state,new PrivacyCopyCommandV1.FoldTerminal(OperationId.Create(),3));Assert.Equal(PrivacyDeletionOutcomeV1.Unknown,state.Deletion!.Outcome);}
    [Fact]
    public void Completed_requires_terminal_receipts_then_minimal_tombstone()
    {var f=new Fixture();var state=Reserved(f,1);var copy=state.Copies.Keys.Single();state=Applied(state,new PrivacyCopyCommandV1.Fence(OperationId.Create(),1,DeletionId.Create()));state=Applied(state,new PrivacyCopyCommandV1.CloseRegistration(OperationId.Create(),2));state=Applied(state,new PrivacyCopyCommandV1.AdmitReceipt(OperationId.Create(),3,copy,CopyTerminalEvidenceV1.CryptoErased));state=Applied(state,new PrivacyCopyCommandV1.FoldTerminal(OperationId.Create(),4));Assert.Equal(PrivacyDeletionOutcomeV1.Completed,state.Deletion!.Outcome);state=Applied(state,new PrivacyCopyCommandV1.CommitTombstone(OperationId.Create(),5));Assert.True(state.Deletion!.TombstoneCommitted);Assert.Equal(PrivacyDeletionOutcomeV1.CompletedWithMinimalTombstone,state.Deletion.Outcome);}
    [Fact]
    public void Late_copy_reopens_terminal_and_creates_repair_revision()
    {var f=new Fixture();var state=Reserved(f,1);var copy=state.Copies.Keys.Single();state=Applied(state,new PrivacyCopyCommandV1.Fence(OperationId.Create(),1,DeletionId.Create()));state=Applied(state,new PrivacyCopyCommandV1.CloseRegistration(OperationId.Create(),2));state=Applied(state,new PrivacyCopyCommandV1.AdmitReceipt(OperationId.Create(),3,copy,CopyTerminalEvidenceV1.Deleted));state=Applied(state,new PrivacyCopyCommandV1.FoldTerminal(OperationId.Create(),4));state=Applied(state,new PrivacyCopyCommandV1.Reserve(OperationId.Create(),5,f.Reservation(1)),8,32);Assert.Equal(PrivacyDeletionOutcomeV1.Open,state.Deletion!.Outcome);Assert.False(state.Deletion.RegistrationClosed);Assert.Equal(1UL,state.Deletion.RepairRevision);}
    private static PrivacyCopyStateV1 Reserved(Fixture f,int count){var state=PrivacyCopyLifecycleV1.Create();for(var i=0;i<count;i++)state=Applied(state,new PrivacyCopyCommandV1.Reserve(OperationId.Create(),state.Revision,f.Reservation((ulong)i)));return state;}
    private static PrivacyCopyStateV1 Applied(PrivacyCopyStateV1 state,PrivacyCopyCommandV1 command,ushort maxCopies=8,ushort maxReceipts=32)=>Assert.IsType<PrivacyCopyResultV1.Applied>(PrivacyCopyLifecycleV1.Apply(state,command,maxCopies,maxReceipts)).State;
    private sealed class Fixture
    {private readonly SessionAuthorityStampV1 _session=new(RuntimeGenerationId.Create(),LiveSessionId.Create());internal CopyReservationV1 Reservation(ulong frontier){var position=new JournalPositionV1(_session,1);return new(CopyId.Create(),new FactRangeV1(position,position),CustodianDescriptorId.Create(),[],DataClassificationV1.Confidential,PurposeId.Create(),AudienceId.Create(),new ResidencyRuleV1([new BoundedAscii("us")],false),AuthorizationId.Create(),new RetentionIntervalV1(new UtcInstant(10),new UtcInstant(20),RetentionBasisV1.Purpose),ExpectedAuthorityVectorV1.Create(_session,[]),OperationId.Create(),frontier);}}
}
