#!/usr/bin/env python3
"""Compile the pinned Unicode 17 UCD into the portable BASE text analyzer tables."""

from pathlib import Path
import sys


def escaped(values: list[int]) -> str:
    return "".join(f"\\U{value:08X}" for value in values)


def read_unicode_data(path: Path):
    rows, compatibility, pending = {}, set(), None
    for raw in path.read_text(encoding="utf-8").splitlines():
        p = raw.split(";")
        cp, name, category, ccc = int(p[0], 16), p[1], p[2], int(p[3])
        decomp = p[5].split()
        if decomp and decomp[0].startswith("<"):
            compatibility.add(cp)
            decomp = decomp[1:]
        mapping = [int(x, 16) for x in decomp]
        if name.endswith(", First>"):
            pending = (cp, category, ccc, mapping)
            continue
        if name.endswith(", Last>"):
            start, cat, combining, mapped = pending
            for value in range(start, cp + 1): rows[value] = (cat, combining, mapped)
            pending = None
            continue
        rows[cp] = (category, ccc, mapping)
    return rows, compatibility


def main() -> None:
    ucd, casefold, exclusions, target = map(Path, sys.argv[1:5])
    rows, compatibility = read_unicode_data(ucd)
    excluded = set()
    for raw in exclusions.read_text(encoding="utf-8").splitlines():
        body = raw.split("#", 1)[0].strip()
        if body: excluded.add(int(body, 16))

    folds, statuses = {}, {}
    for raw in casefold.read_text(encoding="utf-8").splitlines():
        body = raw.split("#", 1)[0].strip()
        if not body: continue
        left, status, right, *_ = [part.strip() for part in body.split(";")]
        if status not in {"C", "F"}: continue
        scalar = int(left, 16)
        if statuses.get(scalar) == "F" and status == "C": continue
        folds[scalar] = [int(value, 16) for value in right.split()]
        statuses[scalar] = status

    decompositions = {cp: value[2] for cp, value in rows.items() if value[2]}
    combining = {cp: value[1] for cp, value in rows.items() if value[1]}
    compositions = {}
    for cp, (_, _, mapping) in rows.items():
        if cp in excluded or len(mapping) != 2 or rows.get(mapping[0], (None, 1, None))[1] != 0: continue
        if cp in compatibility: continue
        compositions[(mapping[0], mapping[1])] = cp

    accepted = {"Lu": 1, "Ll": 1, "Lt": 1, "Lm": 1, "Lo": 1, "Nd": 1, "Mn": 2, "Mc": 2, "Me": 2, "Pc": 3}
    category_points = sorted((cp, accepted[value[0]]) for cp, value in rows.items() if value[0] in accepted)
    ranges = []
    for cp, kind in category_points:
        if ranges and ranges[-1][1] + 1 == cp and ranges[-1][2] == kind: ranges[-1] = (ranges[-1][0], cp, kind)
        else: ranges.append((cp, cp, kind))

    lines = ["// <auto-generated />", "#nullable enable", "namespace HPD.Base;", "", "internal static class BaseTextUnicode17", "{"]
    lines += ["    internal static string Fold(int scalar) => scalar switch", "    {"]
    lines += [f'        0x{cp:X} => "{escaped(value)}",' for cp, value in sorted(folds.items())]
    lines += ["        _ => char.ConvertFromUtf32(scalar),", "    };"]
    lines += ["    internal static string? Decomposition(int scalar) => scalar switch", "    {"]
    lines += [f'        0x{cp:X} => "{escaped(value)}",' for cp, value in sorted(decompositions.items())]
    lines += ["        _ => null,", "    };"]
    lines += ["    internal static byte CombiningClass(int scalar) => scalar switch", "    {"]
    lines += [f"        0x{cp:X} => {value}," for cp, value in sorted(combining.items())]
    lines += ["        _ => 0,", "    };"]
    lines += ["    internal static int Compose(int first, int second) => ((long)first << 21 | (uint)second) switch", "    {"]
    lines += [f"        ((long)0x{first:X} << 21 | 0x{second:X}) => 0x{value:X}," for (first, second), value in sorted(compositions.items())]
    lines += ["        _ => 0,", "    };"]
    flat = ", ".join(f"0x{start:X}, 0x{end:X}, {kind}" for start, end, kind in ranges)
    lines += [f"    private static readonly int[] Categories = [{flat}];", "    internal static byte TokenCategory(int scalar)", "    {", "        int low = 0, high = Categories.Length / 3 - 1;", "        while (low <= high) { int middle = low + ((high - low) >> 1); int offset = middle * 3; if (scalar < Categories[offset]) high = middle - 1; else if (scalar > Categories[offset + 1]) low = middle + 1; else return (byte)Categories[offset + 2]; }", "        return 0;", "    }", "}", ""]
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text("\n".join(lines), encoding="utf-8", newline="\n")


if __name__ == "__main__": main()
