<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>HPD.Payments.Profiles.Embedded</AssemblyName>
    <RootNamespace>HPD.Payments.Profiles_Embedded</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../HPD.Payments.Runtime/HPD.Payments.Runtime.csproj" />
    <ProjectReference Include="../HPD.Payments.Serialization/HPD.Payments.Serialization.csproj" />
    <ProjectReference Include="../HPD.Payments.Adapters.InMemory/HPD.Payments.Adapters.InMemory.csproj" />
    <ProjectReference Include="../HPD.Payments.Adapters.Sqlite/HPD.Payments.Adapters.Sqlite.csproj" />
    <ProjectReference Include="../HPD.Payments.Connectors.Simulator/HPD.Payments.Connectors.Simulator.csproj" />
  </ItemGroup>
</Project>
