import { describe,expect,it } from 'vitest';
import { createGatewayDeclarationController,initialGatewayDocument } from '../src/declaration-state.ts';
import { createGatewayQuickRouteCoordinator } from '../src/quick-route.ts';

describe('atomic Quick Route proposal',()=>{
  it('creates a deterministic proposal and transfers exact validation evidence in one generation',async()=>{const declaration=createGatewayDeclarationController();let principal=7n;const capability={algorithm:'sha-256',value:'b'.repeat(64)};const coordinator=createGatewayQuickRouteCoordinator({declaration,client:client(),principalGeneration:()=>principal,capabilityIdentity:()=>capability});const proposed=initialGatewayDocument+' ';const first=coordinator.create(proposed)!;const second=coordinator.create(proposed)!;expect(first.proposalId).toBe(second.proposalId);expect(await coordinator.validateAndCommit(second)).toBe(true);const document=declaration.snapshot().document;expect(document.editGeneration).toBe(1n);expect(document.utf8Text).toBe(proposed);expect(document.state).toBe('ServerValid');expect(document.validation?.transferredFromProposalId).toBe(second.proposalId);expect(principal).toBe(7n);});
  it('never commits after concurrent edits, principal/capability drift, cancellation, or disposal',async()=>{let release!:()=>void;const wait=new Promise<void>(resolve=>{release=resolve;});const delayed=client(wait);let principal=1n;let capability={algorithm:'sha-256',value:'b'.repeat(64)};const declaration=createGatewayDeclarationController();const coordinator=createGatewayQuickRouteCoordinator({declaration,client:delayed,principalGeneration:()=>principal,capabilityIdentity:()=>capability});const proposal=coordinator.create(initialGatewayDocument+' ')!;const pending=coordinator.validateAndCommit(proposal);declaration.replaceRaw(initialGatewayDocument+'  ');release();expect(await pending).toBe(false);expect(declaration.snapshot().document.utf8Text).toBe(initialGatewayDocument+'  ');const p2=coordinator.create(initialGatewayDocument+'   ')!;principal=2n;expect(await coordinator.validateAndCommit(p2)).toBe(false);principal=1n;const p3=coordinator.create(initialGatewayDocument+'   ')!;capability={algorithm:'sha-256',value:'c'.repeat(64)};expect(await coordinator.validateAndCommit(p3)).toBe(false);coordinator.cancel();expect(await coordinator.validateAndCommit(p3)).toBe(false);coordinator.dispose();expect(coordinator.create(initialGatewayDocument)).toBeNull();});
});
function client(wait:Promise<void>=Promise.resolve()){return{validate:async()=>{await wait;return{ok:true,status:200,value:{canonicalizationVersion:'1',contentHashAlgorithm:'sha-256',contentHashValue:'a'.repeat(64),correlationId:'c',diagnostics:[],hostCapabilitySnapshotAlgorithm:'sha-256',hostCapabilitySnapshotValue:'b'.repeat(64),isValid:true,observedAt:'2026-01-01T00:00:00Z',schemaVersion:'1.0'},headers:{}};}} as any;}
