<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Rhodium.Kernel\Rhodium.Kernel.csproj" />
    <ProjectReference Include="..\Rhodium.Primitives\Rhodium.Primitives.csproj" />
    <ProjectReference Include="..\Rhodium.Tensor\Rhodium.Tensor.csproj" />
    <ProjectReference Include="..\Rhodium.Control\Rhodium.Control.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Rhodium.Platform.Tests" />
    <InternalsVisibleTo Include="Rhodium.Connectivity" />
  </ItemGroup>

</Project>
