<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>HPD-ML-TimeSeries</PackageId>
    <TargetFramework>net11.0</TargetFramework>
    <TargetFrameworks></TargetFrameworks>
    <LangVersion>preview</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);SYSLIB5001</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="HPD.ML.TimeSeries.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../HPD.ML.Core/HPD.ML.Core.csproj" />
  </ItemGroup>

</Project>
