using System.Text.Json.Serialization;
using HPD.Agent;
using HPD.Agent.Audio;
using HPD.Agent.Audio.Output;
using HPD.Agent.Audio.Policies;
using HPD.Agent.ClientTools;
using HPD.Agent.Hosting.Data;
using HPD.Agent.Middleware;
using HPD.Agent.Providers;
using HPD.Agent.StructuredOutput;
using HPD.Events;

namespace HPD.Agent.Hosting.Serialization;

/// <summary>
/// Source-generated JSON serialization context for all HPD-Agent hosting DTOs.
/// Enables Native AOT compilation by eliminating runtime reflection.
///
/// Used by:
/// - ErrorResponses (in AspNetCore) for HTTP error responses during data access operations
/// - SseEventHandler streaming for agent events (via chain in AspNetCore JsonOptionsSetup)
/// - Minimal API endpoints that return these DTOs
/// </summary>
[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    WriteIndented = false)]
// Session DTOs
[JsonSerializable(typeof(SessionDto))]
[JsonSerializable(typeof(SessionDto[]))]
[JsonSerializable(typeof(List<SessionDto>))]
// Thread DTOs
[JsonSerializable(typeof(ThreadDto))]
[JsonSerializable(typeof(ThreadDto[]))]
[JsonSerializable(typeof(List<ThreadDto>))]
[JsonSerializable(typeof(ThreadExecutionDto))]
[JsonSerializable(typeof(ThreadExecutionDto[]))]
[JsonSerializable(typeof(List<ThreadExecutionDto>))]
[JsonSerializable(typeof(ThreadExecutionErrorDto))]
[JsonSerializable(typeof(ThreadExecutionOperationDto))]
[JsonSerializable(typeof(List<ThreadExecutionOperationDto>))]
// Thread event DTOs
[JsonSerializable(typeof(ProviderUsageMeasurement))]
[JsonSerializable(typeof(MessageTurnUsageSummary))]
[JsonSerializable(typeof(ProviderReportedMonetaryObservation))]
// Content DTOs
[JsonSerializable(typeof(ContentDto))]
[JsonSerializable(typeof(ContentDto[]))]
[JsonSerializable(typeof(List<ContentDto>))]
// Request DTOs
[JsonSerializable(typeof(CreateSessionRequest))]
[JsonSerializable(typeof(UpdateSessionRequest))]
[JsonSerializable(typeof(SearchSessionsRequest))]
[JsonSerializable(typeof(CreateThreadRequest))]
[JsonSerializable(typeof(UpdateThreadRequest))]
[JsonSerializable(typeof(ForkThreadRequest))]
[JsonSerializable(typeof(StreamTextRequest))]
[JsonSerializable(typeof(ContextUsageRequest))]
[JsonSerializable(typeof(ThreadContextUsage))]
// Run config DTO graph used by StreamTextRequest
[JsonSerializable(typeof(AgentRunConfig))]
[JsonSerializable(typeof(CollapsingRunPolicy))]
[JsonSerializable(typeof(ContainerRecoveryHistoryMode))]
[JsonSerializable(typeof(CompactionConfig))]
[JsonSerializable(typeof(CompactionRunPolicy))]
[JsonSerializable(typeof(AutomaticCompactionPolicy))]
[JsonSerializable(typeof(ThreadCompactionRequest))]
[JsonSerializable(typeof(CompactThreadInputEvent))]
[JsonSerializable(typeof(CompactionTrigger))]
[JsonSerializable(typeof(TurnCountCompactionTrigger))]
[JsonSerializable(typeof(InputTokenCompactionTrigger))]
[JsonSerializable(typeof(ContextPercentageCompactionTrigger))]
[JsonSerializable(typeof(CompactionPoint))]
[JsonSerializable(typeof(CompactAtCurrentHead))]
[JsonSerializable(typeof(CompactAtMessage))]
[JsonSerializable(typeof(CompactAtTurn))]
[JsonSerializable(typeof(CompactionPreservation))]
[JsonSerializable(typeof(PreserveNoPreviousHistory))]
[JsonSerializable(typeof(PreservePreviousTurns))]
[JsonSerializable(typeof(PreservePreviousUserMessages))]
[JsonSerializable(typeof(PreviousHistoryLimit))]
[JsonSerializable(typeof(PreviousItemCountLimit))]
[JsonSerializable(typeof(PreviousTokenBudgetLimit))]
[JsonSerializable(typeof(CompactionStrategy))]
[JsonSerializable(typeof(RemovalCompaction))]
[JsonSerializable(typeof(SummarizingCompaction))]
[JsonSerializable(typeof(CompactionSpecification))]
[JsonSerializable(typeof(ThreadForkCompaction))]
[JsonSerializable(typeof(InheritThreadForkCompaction))]
[JsonSerializable(typeof(DisableThreadForkCompaction))]
[JsonSerializable(typeof(ApplyThreadForkCompaction))]
[JsonSerializable(typeof(ThreadJournalCursor))]
[JsonSerializable(typeof(CompactionCommitMode))]
[JsonSerializable(typeof(AgentModelTransportMode))]
[JsonSerializable(typeof(AgentSecurityRunConfig))]
[JsonSerializable(typeof(AgentSandboxRunConfig))]
[JsonSerializable(typeof(AgentApprovalPolicy))]
[JsonSerializable(typeof(AgentSandboxPolicy))]
[JsonSerializable(typeof(AgentSandboxEscapePolicy))]
[JsonSerializable(typeof(HPD.Agent.Security.AgentSandboxConfiguration))]
[JsonSerializable(typeof(HPD.Agent.Security.AgentSandboxPathGrant))]
[JsonSerializable(typeof(HPD.Agent.Security.AgentSandboxPathAccess))]
[JsonSerializable(typeof(AgentClientsConfig))]
[JsonSerializable(typeof(AgentProviderBackendProfile))]
[JsonSerializable(typeof(AgentProviderFamilyDefault))]
[JsonSerializable(typeof(ProviderReference))]
[JsonSerializable(typeof(ProviderAuthentication))]
[JsonSerializable(typeof(ApiKeyProviderAuthentication))]
[JsonSerializable(typeof(OAuthProviderAuthentication))]
[JsonSerializable(typeof(ExternalIdentityProviderAuthentication))]
[JsonSerializable(typeof(AnonymousProviderAuthentication))]
[JsonSerializable(typeof(ProviderAccountOperationRequest))]
[JsonSerializable(typeof(BeginProviderAuthorizationHostRequest))]
[JsonSerializable(typeof(CompleteProviderAuthorizationRequest))]
[JsonSerializable(typeof(ProviderDeviceAuthorizationOperationRequest))]
[JsonSerializable(typeof(ProviderAuthorizationChallenge))]
[JsonSerializable(typeof(BrowserAuthorizationChallenge))]
[JsonSerializable(typeof(DeviceAuthorizationChallenge))]
[JsonSerializable(typeof(ProviderAuthorizationResponse))]
[JsonSerializable(typeof(BrowserAuthorizationResponse))]
[JsonSerializable(typeof(DeviceAuthorizationPresentationResponse))]
[JsonSerializable(typeof(ProviderDeviceAuthorizationStatus))]
[JsonSerializable(typeof(ProviderAuthorizationStatus))]
[JsonSerializable(typeof(ProviderDisconnectResult))]
[JsonSerializable(typeof(ProviderRevocationResult))]
[JsonSerializable(typeof(ProviderClientConfig))]
[JsonSerializable(typeof(AudioRunConfig))]
[JsonSerializable(typeof(ChatClientConfig))]
[JsonSerializable(typeof(RealtimeClientConfig))]
[JsonSerializable(typeof(ImageGenerationClientConfig))]
[JsonSerializable(typeof(EmbeddingsClientConfig))]
[JsonSerializable(typeof(TextToSpeechClientConfig))]
[JsonSerializable(typeof(SpeechToTextClientConfig))]
[JsonSerializable(typeof(HostedFilesClientConfig))]
[JsonSerializable(typeof(VoiceActivityClientConfig))]
[JsonSerializable(typeof(EndOfTurnClientConfig))]
[JsonSerializable(typeof(RealtimeAudioFormatRunConfig))]
[JsonSerializable(typeof(RealtimeTranscriptionRunConfig))]
[JsonSerializable(typeof(UploadStrategy))]
[JsonSerializable(typeof(CompactionContinuation))]
[JsonSerializable(typeof(StructuredOutputOptions))]
[JsonSerializable(typeof(AgentClientInput))]
[JsonSerializable(typeof(ClientToolDefinition))]
[JsonSerializable(typeof(IToolResultContent))]
[JsonSerializable(typeof(IReadOnlyList<IToolResultContent>))]
[JsonSerializable(typeof(List<IToolResultContent>))]
[JsonSerializable(typeof(TextContent))]
[JsonSerializable(typeof(BinaryContent))]
[JsonSerializable(typeof(JsonContent))]
[JsonSerializable(typeof(ClientToolInvokeOutcomeKind))]
[JsonSerializable(typeof(ClientToolOperationOutcomeState))]
[JsonSerializable(typeof(ClientToolOperationOutcomeEvent))]
[JsonSerializable(typeof(ClientAppProviderReference))]
[JsonSerializable(typeof(ClientAppProviderReference[]))]
[JsonSerializable(typeof(List<ClientAppProviderReference>))]
[JsonSerializable(typeof(ClientProviderSelector))]
[JsonSerializable(typeof(ClientToolHarnessSelector))]
[JsonSerializable(typeof(IReadOnlyList<ClientToolHarnessSelector>))]
[JsonSerializable(typeof(ClientAppProviderBindingPolicy))]
[JsonSerializable(typeof(ClientAppProviderDescriptor))]
[JsonSerializable(typeof(ClientToolProviderIdentity))]
[JsonSerializable(typeof(ClientToolProviderRuntimeIdentity))]
[JsonSerializable(typeof(ClientToolProviderContext))]
[JsonSerializable(typeof(ClientToolProviderReadiness))]
[JsonSerializable(typeof(ClientToolProviderConnectionState))]
[JsonSerializable(typeof(ClientToolProviderBindingLeaseStatus))]
[JsonSerializable(typeof(ClientToolProviderManifest))]
[JsonSerializable(typeof(ClientToolProviderSnapshot))]
[JsonSerializable(typeof(ClientToolProviderConnectionRegistration))]
[JsonSerializable(typeof(ClientToolProviderBindingScope))]
[JsonSerializable(typeof(ClientToolProviderBindingLease))]
[JsonSerializable(typeof(ClientToolProviderBindingResult))]
[JsonSerializable(typeof(ClientToolProviderQuery))]
[JsonSerializable(typeof(ClientToolProviderHelloMessage))]
[JsonSerializable(typeof(ClientToolProviderWelcomeMessage))]
[JsonSerializable(typeof(ClientToolProviderManifestMessage))]
[JsonSerializable(typeof(ClientToolProviderHeartbeatMessage))]
[JsonSerializable(typeof(ClientToolProviderReleaseMessage))]
[JsonSerializable(typeof(ClientToolProviderErrorMessage))]
[JsonSerializable(typeof(ClientToolProviderInvokeToolMessage))]
[JsonSerializable(typeof(ClientToolProviderInvokeOutcomeMessage))]
[JsonSerializable(typeof(ClientToolProviderOperationOutcomeMessage))]
[JsonSerializable(typeof(ClientToolProviderToolBinding))]
[JsonSerializable(typeof(ClientToolProviderInvocationRequest))]
[JsonSerializable(typeof(ClientToolProviderOperationDescriptor))]
[JsonSerializable(typeof(AudioInputMode))]
[JsonSerializable(typeof(AudioOutputMode))]
[JsonSerializable(typeof(AssistantOutputSynthesisMode))]
[JsonSerializable(typeof(AssistantAudioArtifactCapturePolicy))]
[JsonSerializable(typeof(TextToSpeechPacingOptions))]
[JsonSerializable(typeof(TextToSpeechFirstSegmentOptions))]
[JsonSerializable(typeof(TextToSpeechContinuationOptions))]
[JsonSerializable(typeof(TextToSpeechBoundaryOptions))]
[JsonSerializable(typeof(TextToSpeechFilteringOptions))]
[JsonSerializable(typeof(TextToSpeechPacingMode))]
[JsonSerializable(typeof(TextToSpeechEmojiPolicy))]
[JsonSerializable(typeof(ProgressiveTextToSpeechRouteMode))]
[JsonSerializable(typeof(PushTextInputAggregationMode))]
// Note: Agent input/output events are covered by AgentEventJsonContext.
[JsonSerializable(typeof(AgentRespondResult))]
[JsonSerializable(typeof(ClientToolContentDto))]
[JsonSerializable(typeof(ClientToolContentDto[]))]
[JsonSerializable(typeof(List<ClientToolContentDto>))]
// Agent DTOs — AgentConfig is covered by HPDJsonContext in the chain
[JsonSerializable(typeof(AgentSummaryDto))]
[JsonSerializable(typeof(AgentSummaryDto[]))]
[JsonSerializable(typeof(List<AgentSummaryDto>))]
[JsonSerializable(typeof(StoredAgentDto))]
[JsonSerializable(typeof(CreateAgentRequest))]
[JsonSerializable(typeof(UpdateAgentRequest))]
// ReasoningOptions — used by AgentRunConfig when events are serialized through AgentEventJsonContext.
[JsonSerializable(typeof(HPD.Agent.ReasoningOptions))]
[JsonSerializable(typeof(HPD.Agent.ReasoningEffort))]
[JsonSerializable(typeof(HPD.Agent.ReasoningOutput))]
// Primitive collections used in responses
[JsonSerializable(typeof(string[]))]
[JsonSerializable(typeof(List<string>))]
[JsonSerializable(typeof(Dictionary<string, object>))]
[JsonSerializable(typeof(Dictionary<string, object?>))]
[JsonSerializable(typeof(Dictionary<string, string>))]
[JsonSerializable(typeof(Dictionary<string, bool>))]
[JsonSerializable(typeof(Dictionary<string, string[]>))]
public partial class HPDAgentApiJsonSerializerContext : JsonSerializerContext
{
}
