using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace HPD.Agent.Harness.Coding.SourceGenerator.Generators;

internal static class RegistryGenerator
{
    public static void Generate(
        SourceProductionContext context,
        IReadOnlyList<LanguageServerProviderInfo> providers)
    {
        if (providers.Count == 0)
            return;

        context.AddSource(
            "LanguageServerRegistry.g.cs",
            SourceText.From(BuildSource(providers), Encoding.UTF8));
    }

    private static string BuildSource(IReadOnlyList<LanguageServerProviderInfo> providers)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using HPDOS.Harneses.Middleware;");
        sb.AppendLine();
        sb.AppendLine("namespace HPDOS.Harneses.Middleware.Generated;");
        sb.AppendLine();
        sb.AppendLine("internal sealed class GeneratedLanguageServerRegistryProvider : ILanguageServerRegistryProvider");
        sb.AppendLine("{");
        sb.AppendLine("    public IEnumerable<LanguageServerDefinition> GetAll() => LanguageServerRegistry.All;");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("internal static class LanguageServerRegistry");
        sb.AppendLine("{");
        sb.AppendLine("    public static readonly LanguageServerDefinition[] All =");
        sb.AppendLine("    [");

        foreach (var provider in providers)
        {
            sb.AppendLine("        new LanguageServerDefinition");
            sb.AppendLine("        {");
            sb.AppendLine($"            Id = \"{Escape(provider.Id)}\",");
            sb.AppendLine($"            Extensions = [{FormatStringList(provider.Extensions)}],");
            sb.AppendLine($"            LanguageIds = new Dictionary<string, string>(System.StringComparer.Ordinal) {{ {FormatDictionary(provider.LanguageIds)} }},");
            sb.AppendLine($"            Provider = {FormatProvider(provider)},");
            if (provider.DisabledByDefault)
                sb.AppendLine("            EnabledByDefault = false,");
            if (provider.Experimental)
                sb.AppendLine("            Experimental = true,");
            sb.AppendLine("        },");
        }

        sb.AppendLine("    ];");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string FormatProvider(LanguageServerProviderInfo provider)
    {
        if (provider.ImplementsProvider)
            return $"new {provider.FullyQualifiedTypeName}()";

        return $"new StaticCommandLanguageServerProvider([{FormatStringList(provider.RootMarkers)}], \"{Escape(provider.Executable ?? string.Empty)}\", [{FormatStringList(provider.Arguments)}], [{FormatStringList(provider.ExcludeRootMarkers)}])";
    }

    private static string FormatStringList(IReadOnlyList<string> values)
        => string.Join(", ", values.Select(value => $"\"{Escape(value)}\""));

    private static string FormatDictionary(IReadOnlyDictionary<string, string> values)
        => string.Join(", ", values.Select(pair => $"[\"{Escape(pair.Key)}\"] = \"{Escape(pair.Value)}\""));

    private static string Escape(string value)
        => value.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
