<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>preview</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Rhodium.Primitives\Rhodium.Primitives.csproj" />
    <ProjectReference Include="..\Rhodium.Tensor\Rhodium.Tensor.csproj" />
    <ProjectReference Include="..\Rhodium.Kernel\Rhodium.Kernel.csproj" />
  </ItemGroup>

</Project>
