using HPD.Agent.Hosting.Lifecycle;

namespace HPD.Agent.Bots.Session;

/// <summary>
/// Resolves an inbound platform message to an HPD <c>sessionId</c> + <c>branchId</c>.
/// Operates in-process against <see cref="SessionManager"/> — no HTTP.
/// </summary>
/// <remarks>
/// <para>
/// <see cref="ResolveAsync"/> searches the session repository by <c>metadata["platformKey"]</c>.
/// On a miss it delegates to <see cref="SessionManager.CreateSessionAsync"/> — the same
/// method that creates the session, the default "main" branch, and persists both atomically.
/// </para>
/// <para>
/// The mapper never bypasses <see cref="SessionManager"/>. All session creation goes
/// through the manager so that concurrency locks remain consistent.
/// </para>
/// <para>
/// <b>Performance note (open question §5):</b> <see cref="ResolveAsync"/> currently does
/// <c>ListSessionIdsAsync</c> + load-each — O(n) over all sessions. Acceptable for low-volume
/// deployments but degrades at scale. A future iteration can add an in-memory
/// <c>ConcurrentDictionary</c> cache or a secondary index in the workspace-backed repository.
/// </para>
/// </remarks>
public sealed class PlatformSessionMapper
{
    private const string PlatformKeyMetadataField = "platformKey";
    private const string PlatformKeyAliasesMetadataField = "platformKeyAliases";

    private readonly SessionManager _manager;

    /// <summary>
    /// Initialises the mapper with the session manager for the target agent.
    /// </summary>
    public PlatformSessionMapper(SessionManager manager)
    {
        _manager = manager ?? throw new ArgumentNullException(nameof(manager));
    }

    /// <summary>
    /// Finds the existing session for <paramref name="platformKey"/>, or creates a new one.
    /// </summary>
    /// <param name="platformKey">
    /// Opaque platform-specific key (e.g. <c>"slack:C123:1234567890.000100"</c>).
    /// Generated by the adapter's <c>[ThreadId]</c> record.
    /// </param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>
    /// The <c>sessionId</c> and <c>branchId</c> ("main") for this platform key.
    /// </returns>
    public async Task<(string SessionId, string BranchId)> ResolveAsync(
        string platformKey,
        CancellationToken ct = default)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(platformKey);

        // Search existing sessions for a matching platformKey in metadata
        var sessionIds = await _manager.Repository.ListSessionIdsAsync(ct);
        foreach (var sessionId in sessionIds)
        {
            var session = await _manager.Repository.LoadSessionAsync(sessionId, ct);
            if (session?.Metadata != null && MetadataContainsPlatformKey(session.Metadata, platformKey))
            {
                // Return the first branch (always "main" for adapter-created sessions)
                var branchIds = await _manager.Repository.ListBranchIdsAsync(sessionId, ct);
                var branchId  = branchIds.Count > 0 ? branchIds[0] : "main";
                return (sessionId, branchId);
            }
        }

        // No match — create a new session via the manager (atomically creates session + "main" branch)
        var metadata = new Dictionary<string, object>
        {
            [PlatformKeyMetadataField] = platformKey,
        };

        return await _manager.CreateSessionAsync(metadata: metadata, ct: ct);
    }

    /// <summary>
    /// Associates an additional platform key with an existing session.
    /// </summary>
    /// <remarks>
    /// Use this when a platform creates a new thread/channel identity after the
    /// initial inbound message, but future messages in that thread should keep
    /// routing to the same HPD session and branch.
    /// </remarks>
    public async Task BindThreadAsync(
        string platformKey,
        string sessionId,
        string branchId,
        CancellationToken ct = default)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(platformKey);
        ArgumentException.ThrowIfNullOrWhiteSpace(sessionId);
        ArgumentException.ThrowIfNullOrWhiteSpace(branchId);

        var session = await _manager.Repository.LoadSessionAsync(sessionId, ct)
            ?? throw new InvalidOperationException($"Session '{sessionId}' was not found.");

        if (MetadataContainsPlatformKey(session.Metadata, platformKey))
            return;

        var aliases = GetPlatformKeyAliases(session.Metadata).ToList();
        aliases.Add(platformKey);
        session.Metadata[PlatformKeyAliasesMetadataField] = aliases.Distinct(StringComparer.Ordinal).ToArray();

        await _manager.Repository.SaveSessionAsync(session, ct);
    }

    /// <summary>
    /// Resets the session for <paramref name="platformKey"/> — deletes the existing session
    /// (if any) and creates a fresh one.
    /// </summary>
    /// <remarks>
    /// Use this when the user explicitly starts a new conversation (e.g. a "reset" slash command).
    /// </remarks>
    public async Task<(string SessionId, string BranchId)> ResetAsync(
        string platformKey,
        CancellationToken ct = default)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(platformKey);

        // Find and delete existing session
        var sessionIds = await _manager.Repository.ListSessionIdsAsync(ct);
        foreach (var sessionId in sessionIds)
        {
            var session = await _manager.Repository.LoadSessionAsync(sessionId, ct);
            if (session?.Metadata != null && MetadataContainsPlatformKey(session.Metadata, platformKey))
            {
                await _manager.Repository.DeleteSessionAsync(sessionId, ct);
                _manager.RemoveSession(sessionId);
                break;
            }
        }

        // Create fresh session
        var metadata = new Dictionary<string, object>
        {
            [PlatformKeyMetadataField] = platformKey,
        };

        return await _manager.CreateSessionAsync(metadata: metadata, ct: ct);
    }

    private static bool MetadataContainsPlatformKey(
        IReadOnlyDictionary<string, object> metadata,
        string platformKey)
    {
        if (metadata.TryGetValue(PlatformKeyMetadataField, out var primary) &&
            MetadataValueContains(primary, platformKey))
        {
            return true;
        }

        return metadata.TryGetValue(PlatformKeyAliasesMetadataField, out var aliases) &&
            MetadataValueContains(aliases, platformKey);
    }

    private static IEnumerable<string> GetPlatformKeyAliases(
        IReadOnlyDictionary<string, object> metadata)
    {
        if (!metadata.TryGetValue(PlatformKeyAliasesMetadataField, out var aliases))
            return [];

        return aliases switch
        {
            string value => [value],
            IEnumerable<string> values => values,
            System.Text.Json.JsonElement { ValueKind: System.Text.Json.JsonValueKind.Array } element =>
                element.EnumerateArray()
                    .Where(item => item.ValueKind == System.Text.Json.JsonValueKind.String)
                    .Select(item => item.GetString()!)
                    .Where(value => !string.IsNullOrWhiteSpace(value)),
            _ => [],
        };
    }

    private static bool MetadataValueContains(object value, string platformKey)
        => value switch
        {
            string stored => stored == platformKey,
            IEnumerable<string> values => values.Contains(platformKey, StringComparer.Ordinal),
            System.Text.Json.JsonElement { ValueKind: System.Text.Json.JsonValueKind.String } element =>
                element.GetString() == platformKey,
            System.Text.Json.JsonElement { ValueKind: System.Text.Json.JsonValueKind.Array } element =>
                element.EnumerateArray().Any(item =>
                    item.ValueKind == System.Text.Json.JsonValueKind.String &&
                    item.GetString() == platformKey),
            _ => false,
        };
}
