<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Rhodium.Kernel\Rhodium.Kernel.csproj" />
    <ProjectReference Include="..\Rhodium.Primitives\Rhodium.Primitives.csproj" />
    <ProjectReference Include="..\Rhodium.Tensor\Rhodium.Tensor.csproj" />
    <ProjectReference Include="..\Rhodium.Control\Rhodium.Control.csproj" />
    <ProjectReference Include="..\Rhodium.Indicators\Rhodium.Indicators.csproj" />
    <ProjectReference Include="..\Rhodium.Generators\Rhodium.Generators.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\Rhodium.Analyzers\Rhodium.Analyzers.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>preview</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Rhodium.Platform.Tests" />
    <InternalsVisibleTo Include="Rhodium.Connectivity" />
    <InternalsVisibleTo Include="Rhodium.Simulation" />
  </ItemGroup>

</Project>
