<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>false</IsTestProject>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup><ProjectReference Include="../../src/HPD.Payments.Generators/HPD.Payments.Generators.csproj" /></ItemGroup>
  <ItemGroup>
    <Reference Include="Microsoft.CodeAnalysis" HintPath="$(MSBuildSDKsPath)/../Roslyn/bincore/Microsoft.CodeAnalysis.dll" Private="true" />
    <Reference Include="Microsoft.CodeAnalysis.CSharp" HintPath="$(MSBuildSDKsPath)/../Roslyn/bincore/Microsoft.CodeAnalysis.CSharp.dll" Private="true" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Baselines/**/*.cs" />
    <None Include="Baselines/**" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
