using System.Text.Json;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using Microsoft.Extensions.DependencyInjection;

namespace HPD.Base.AspNetCore;

internal static class SubjectRetirementEndpoints
{
    private const int MaximumBodyBytes=16*1024;

    internal static void MapApplication(IEndpointRouteBuilder endpoints)
    {
        BaseSubjectRetirementRegistry? registry=endpoints.ServiceProvider.GetService<BaseSubjectRetirementRegistry>();
        if(registry is null||registry.Consumers.Count==0)return;
        endpoints.MapPost("/subject-retirement/acknowledgements",(RequestDelegate)Acknowledge)
            .WithHPDBaseEndpoint("base.subjectRetirement.acknowledge",HPDBaseEndpointAudience.Application,
                HPDBaseEndpointOperation.SubjectRetirementAcknowledge,HPDBaseCapabilities.SubjectRetirementAcknowledge)
            .WithName("base.subjectRetirement.acknowledge");
    }

    internal static void MapControlPlane(IEndpointRouteBuilder endpoints,Action<IEndpointConventionBuilder,HPDBaseEndpointDescriptor> convention)
    {
        BaseSubjectRetirementRegistry? registry=endpoints.ServiceProvider.GetService<BaseSubjectRetirementRegistry>();
        if(registry is null||registry.Policies.Count==0)return;
        Map("/subject-retirement/barriers/query","base.subjectRetirement.barriers.query",HPDBaseEndpointOperation.SubjectRetirementBarrierQuery,HPDBaseCapabilities.SubjectRetirementBarrierInspect,QueryBarriers);
        Map("/subject-retirement/timeouts/process","base.subjectRetirement.timeouts.process",HPDBaseEndpointOperation.SubjectRetirementTimeoutProcess,HPDBaseCapabilities.SubjectRetirementTimeoutProcess,ProcessTimeout);
        Map("/subject-retirement/overrides","base.subjectRetirement.overrides.create",HPDBaseEndpointOperation.SubjectRetirementOverride,HPDBaseCapabilities.SubjectRetirementOverride,Override);
        Map("/subject-retirement/purge","base.subjectRetirement.purge",HPDBaseEndpointOperation.SubjectRetirementPurge,HPDBaseCapabilities.SubjectRetirementPurge,Purge);
        Map("/subject-retirement/consumers/remove","base.subjectRetirement.consumers.remove",HPDBaseEndpointOperation.SubjectRetirementConsumerRemoval,HPDBaseCapabilities.SubjectRetirementConsumerRemoval,RemoveConsumer);
        void Map(string route,string id,HPDBaseEndpointOperation operation,string capability,RequestDelegate handler)=>endpoints.MapPost(route,handler).WithHPDBaseEndpoint(id,HPDBaseEndpointAudience.ControlPlane,operation,capability,convention).WithName(id);
    }

    private static async Task QueryBarriers(HttpContext context)
    {
        (PrincipalContext? principal,JsonDocument? document)=await ReadControlAsync(context).ConfigureAwait(false);if(principal is null||document is null)return;using(document){try{JsonElement root=document.RootElement;Allowed(root,["contractId","contractVersion","state","cursor","take","projectId"],["contractId","contractVersion","state","cursor","take","projectId"]);BaseSession session=Session(context,principal,Optional(root,"projectId"));string contractId=RequiredString(root,"contractId");int version=root.GetProperty("contractVersion").GetInt32();BaseSubjectRetirementBarrierState? state=ParseState(root.GetProperty("state"));BaseSubjectRetirementCursor? cursor=root.GetProperty("cursor").ValueKind==JsonValueKind.Null?null:new(Decode(RequiredString(root,"cursor"),8192));BaseResult<BaseSubjectRetirementPage> result=await session.SubjectRetirements.ReadBarriersAsync(contractId,version,state,cursor,root.GetProperty("take").GetInt32(),context.RequestAborted).ConfigureAwait(false);if(result is BaseFailure<BaseSubjectRetirementPage> failure){await Problem(context,failure.Status,failure.Error.Code).ConfigureAwait(false);return;}await WriteBarrierPage(context,((BaseSuccess<BaseSubjectRetirementPage>)result).Value).ConfigureAwait(false);}catch(Exception error)when(error is JsonException or ArgumentException or FormatException or KeyNotFoundException){await Problem(context,OperationStatus.ValidationFailed,BaseSubjectRetirementErrorCodes.ContractInvalid).ConfigureAwait(false);}}
    }

    private static Task ProcessTimeout(HttpContext context)=>ExecuteControlMutation(context,async(session,root,contract)=>await session.SubjectRetirements.ProcessTimeoutAsync(new(){ContractId=contract.Definition.Id,ContractVersion=contract.Definition.Version,SubjectId=Subject(root,contract),AuthorityEpoch=BaseSubjectAuthorityEpoch.Parse(RequiredString(root,"authorityEpoch")),Incarnation=BaseSubjectIncarnation.Parse(RequiredString(root,"incarnation")),ExpectedBarrierGeneration=root.GetProperty("expectedBarrierGeneration").GetInt64(),ExpectedBarrierChecksum=RequiredString(root,"expectedBarrierChecksum"),Identity=Identity(context,root.GetProperty("identity"))},context.RequestAborted).ConfigureAwait(false),["contractId","contractVersion","subjectId","authorityEpoch","incarnation","expectedBarrierGeneration","expectedBarrierChecksum","identity","projectId"]);
    private static Task Override(HttpContext context)=>ExecuteControlMutation(context,async(session,root,contract)=>await session.SubjectRetirements.OverrideAsync(new(){ContractId=contract.Definition.Id,ContractVersion=contract.Definition.Version,SubjectId=Subject(root,contract),AuthorityEpoch=BaseSubjectAuthorityEpoch.Parse(RequiredString(root,"authorityEpoch")),Incarnation=BaseSubjectIncarnation.Parse(RequiredString(root,"incarnation")),ExpectedTombstoneSequence=root.GetProperty("expectedTombstoneSequence").GetInt64(),ExpectedBarrierGeneration=root.GetProperty("expectedBarrierGeneration").GetInt64(),ExpectedBarrierChecksum=RequiredString(root,"expectedBarrierChecksum"),Intent=RequiredString(root,"intent"),ChangeReference=RequiredString(root,"changeReference"),Identity=Identity(context,root.GetProperty("identity"))},context.RequestAborted).ConfigureAwait(false),["contractId","contractVersion","subjectId","authorityEpoch","incarnation","expectedTombstoneSequence","expectedBarrierGeneration","expectedBarrierChecksum","intent","changeReference","identity","projectId"]);
    private static Task Purge(HttpContext context)=>ExecuteControlMutation(context,async(session,root,contract)=>await session.SubjectRetirements.PurgeAsync(new(){ContractId=contract.Definition.Id,ContractVersion=contract.Definition.Version,SubjectId=Subject(root,contract),AuthorityEpoch=BaseSubjectAuthorityEpoch.Parse(RequiredString(root,"authorityEpoch")),Incarnation=BaseSubjectIncarnation.Parse(RequiredString(root,"incarnation")),ExpectedTombstoneSequence=root.GetProperty("expectedTombstoneSequence").GetInt64(),ExpectedPrivateRevision=new RevisionToken(RequiredString(root,"expectedPrivateRevision")),ExpectedBarrierGeneration=root.GetProperty("expectedBarrierGeneration").GetInt64(),ExpectedBarrierChecksum=RequiredString(root,"expectedBarrierChecksum"),Identity=Identity(context,root.GetProperty("identity"))},context.RequestAborted).ConfigureAwait(false),["contractId","contractVersion","subjectId","authorityEpoch","incarnation","expectedTombstoneSequence","expectedPrivateRevision","expectedBarrierGeneration","expectedBarrierChecksum","identity","projectId"]);
    private static Task RemoveConsumer(HttpContext context)=>ExecuteControlMutation(context,async(session,root,contract)=>await session.SubjectRetirements.RemoveConsumerAsync(new(){ContractId=contract.Definition.Id,ContractVersion=contract.Definition.Version,ConsumerId=RequiredString(root,"consumerId"),ConsumerVersion=root.GetProperty("consumerVersion").GetInt32(),ExpectedConsumerChecksum=RequiredString(root,"expectedConsumerChecksum"),ExpectedAcceptedSetChecksum=RequiredString(root,"expectedAcceptedSetChecksum"),ExpectedGraphGeneration=root.GetProperty("expectedGraphGeneration").GetInt64(),Identity=Identity(context,root.GetProperty("identity"))},context.RequestAborted).ConfigureAwait(false),["contractId","contractVersion","consumerId","consumerVersion","expectedConsumerChecksum","expectedAcceptedSetChecksum","expectedGraphGeneration","identity","projectId"]);

    private static async Task ExecuteControlMutation<T>(HttpContext context,Func<BaseSession,JsonElement,BaseGeneratedSubjectRegistration,ValueTask<BaseResult<T>>> execute,string[] fields)
    {
        (PrincipalContext? principal,JsonDocument? document)=await ReadControlAsync(context).ConfigureAwait(false);if(principal is null||document is null)return;using(document){try{JsonElement root=document.RootElement;Allowed(root,fields,fields);BaseGeneratedSubjectRegistration contract=Contract(context,root);BaseResult<T> result=await execute(Session(context,principal,Optional(root,"projectId")),root,contract).ConfigureAwait(false);if(result is BaseFailure<T> failure){await Problem(context,failure.Status,failure.Error.Code).ConfigureAwait(false);return;}await WriteControlResult(context,((BaseSuccess<T>)result).Value!).ConfigureAwait(false);}catch(Exception error)when(error is JsonException or ArgumentException or FormatException or KeyNotFoundException or InvalidOperationException){await Problem(context,OperationStatus.ValidationFailed,BaseSubjectRetirementErrorCodes.ContractInvalid).ConfigureAwait(false);}}
    }

    private static async ValueTask<(PrincipalContext?,JsonDocument?)> ReadControlAsync(HttpContext context)
    {
        PrincipalContext principal=await context.RequestServices.GetRequiredService<IBaseHttpPrincipalContextFactory>().CreateAsync(context,context.RequestAborted).ConfigureAwait(false);if(principal.AuthenticationState is not(PrincipalAuthenticationState.Admin or PrincipalAuthenticationState.System)){await Problem(context,OperationStatus.PolicyDenied,BaseSubjectRetirementErrorCodes.Unauthorized).ConfigureAwait(false);return(null,null);}try{if(context.Request.ContentLength is>MaximumBodyBytes)throw new InvalidDataException();var bounded=new LimitedRequestBodyStream(context.Request.Body,MaximumBodyBytes);JsonDocument document=await JsonDocument.ParseAsync(bounded,new(){AllowTrailingCommas=false,CommentHandling=JsonCommentHandling.Disallow,MaxDepth=6},context.RequestAborted).ConfigureAwait(false);return(principal,document);}catch(Exception error)when(error is JsonException or InvalidDataException){await Problem(context,OperationStatus.ValidationFailed,BaseSubjectRetirementErrorCodes.ContractInvalid).ConfigureAwait(false);return(null,null);}
    }
    private static BaseSession Session(HttpContext context,PrincipalContext principal,string? projectId)=>context.RequestServices.GetRequiredService<IBaseSessionFactory>().For(principal,options=>options.ProjectId=projectId);
    private static BaseGeneratedSubjectRegistration Contract(HttpContext context,JsonElement root){string id=RequiredString(root,"contractId");int version=root.GetProperty("contractVersion").GetInt32();return context.RequestServices.GetRequiredService<BaseSubjectContractRegistry>().Find(id,version)??throw new JsonException();}
    private static BaseSubjectId Subject(JsonElement root,BaseGeneratedSubjectRegistration contract)=>BaseSubjectId.Create(RequiredString(root,"subjectId"),contract.Definition.SubjectIdKind,contract.Definition.MaximumSubjectIdUtf8Bytes);
    private static BaseMutationRequestIdentity Identity(HttpContext context,JsonElement value){Exact(value,["scope","operation","idempotencyKey","fingerprint"]);byte[] fingerprint=Convert.FromBase64String(RequiredString(value,"fingerprint"));BaseMutationRequestIdentity identity=BaseMutationRequestIdentity.Create(RequiredString(value,"scope"),RequiredString(value,"operation"),RequiredString(value,"idempotencyKey"),BaseMutationRequestFingerprint.Create(fingerprint));if(!context.Request.Headers.TryGetValue(BaseHttpHeaders.IdempotencyKey,out var header)||header.Count!=1||header[0]!=identity.IdempotencyKey)throw new JsonException();return identity;}
    private static string RequiredString(JsonElement value,string name)=>value.GetProperty(name).GetString()??throw new JsonException();
    private static string? Optional(JsonElement value,string name)=>value.TryGetProperty(name,out JsonElement item)&&item.ValueKind!=JsonValueKind.Null?item.GetString():null;
    private static BaseSubjectRetirementBarrierState? ParseState(JsonElement value){if(value.ValueKind==JsonValueKind.Null)return null;return value.GetString() switch{"pending"=>BaseSubjectRetirementBarrierState.Pending,"satisfied"=>BaseSubjectRetirementBarrierState.Satisfied,"timedOut"=>BaseSubjectRetirementBarrierState.TimedOut,"quarantined"=>BaseSubjectRetirementBarrierState.Quarantined,"overridden"=>BaseSubjectRetirementBarrierState.Overridden,_=>throw new JsonException()};}
    private static void Allowed(JsonElement value,string[] names,string[] required){if(value.ValueKind!=JsonValueKind.Object)throw new JsonException();var seen=new HashSet<string>(StringComparer.Ordinal);foreach(JsonProperty property in value.EnumerateObject())if(!seen.Add(property.Name)||!names.Contains(property.Name,StringComparer.Ordinal))throw new JsonException();foreach(string name in required)if(!seen.Contains(name))throw new JsonException();}
    private static async Task WriteBarrierPage(HttpContext context,BaseSubjectRetirementPage page){context.Response.StatusCode=200;context.Response.ContentType="application/json; charset=utf-8";await using var writer=new Utf8JsonWriter(context.Response.BodyWriter);writer.WriteStartObject();writer.WritePropertyName("barriers");writer.WriteStartArray();foreach(BaseSubjectRetirementBarrier barrier in page.Barriers){writer.WriteStartObject();WriteBarrier(writer,barrier);writer.WriteEndObject();}writer.WriteEndArray();if(page.Next is null)writer.WriteNull("cursor");else writer.WriteString("cursor",Encode(page.Next.ToArray()));writer.WriteString("capturedBarrierGeneration",page.CapturedBarrierGeneration.ToString(System.Globalization.CultureInfo.InvariantCulture));writer.WriteEndObject();await writer.FlushAsync(context.RequestAborted).ConfigureAwait(false);}
    private static async Task WriteControlResult<T>(HttpContext context,T value){context.Response.StatusCode=200;context.Response.ContentType="application/json; charset=utf-8";await using var writer=new Utf8JsonWriter(context.Response.BodyWriter);writer.WriteStartObject();switch(value){case BaseSubjectRetirementTimeoutResult result:WriteOutcome(writer,result.Outcome);writer.WriteString("state",State(result.State));writer.WriteString("generation",result.Generation.ToString(System.Globalization.CultureInfo.InvariantCulture));writer.WriteString("barrierChecksum",result.BarrierChecksum);break;case BaseSubjectRetirementOverrideResult result:WriteOutcome(writer,result.Outcome);writer.WriteString("generation",result.Generation.ToString(System.Globalization.CultureInfo.InvariantCulture));writer.WriteString("barrierChecksum",result.BarrierChecksum);break;case BaseSubjectFinalPurgeResult result:WriteOutcome(writer,result.Outcome);writer.WriteString("retiredSubjectSequence",result.RetiredSubjectSequence.ToString(System.Globalization.CultureInfo.InvariantCulture));writer.WriteString("retiredPosition",result.RetiredPosition.Value.ToString(System.Globalization.CultureInfo.InvariantCulture));writer.WriteString("terminalReceiptChecksum",result.TerminalReceiptChecksum);break;case BaseSubjectRetirementConsumerRemovalResult result:WriteOutcome(writer,result.Outcome);writer.WriteString("publishedGraphGeneration",result.PublishedGraphGeneration.ToString(System.Globalization.CultureInfo.InvariantCulture));writer.WriteString("acceptedConsumerSetChecksum",result.AcceptedConsumerSetChecksum);writer.WriteNumber("examinedBarriers",result.ExaminedBarriers);writer.WriteNumber("resolvedBarriers",result.ResolvedBarriers);break;default:throw new InvalidOperationException();}writer.WriteEndObject();await writer.FlushAsync(context.RequestAborted).ConfigureAwait(false);}
    private static void WriteBarrier(Utf8JsonWriter writer,BaseSubjectRetirementBarrier value){writer.WriteString("contractId",value.ContractId);writer.WriteNumber("contractVersion",value.ContractVersion);writer.WriteString("subjectId",value.SubjectId.Value);writer.WriteString("authorityEpoch",value.AuthorityEpoch.ToBase64Url());writer.WriteString("incarnation",value.Incarnation.ToBase64Url());writer.WriteString("tombstoneSequence",value.TombstoneSequence.ToString(System.Globalization.CultureInfo.InvariantCulture));writer.WriteString("requiredConsumerSetChecksum",value.RequiredConsumerSetChecksum);writer.WriteString("createdAtUtc",value.CreatedAtUtc);writer.WriteString("deadlineUtc",value.DeadlineUtc);writer.WriteString("state",State(value.State));writer.WriteString("generation",value.Generation.ToString(System.Globalization.CultureInfo.InvariantCulture));writer.WriteString("barrierChecksum",value.BarrierChecksum);}
    private static void WriteOutcome(Utf8JsonWriter writer,BaseSubjectRetirementMutationOutcome value)=>writer.WriteString("outcome",value switch{BaseSubjectRetirementMutationOutcome.Applied=>"applied",BaseSubjectRetirementMutationOutcome.Duplicate=>"duplicate",_=>"obsolete"});
    private static string State(BaseSubjectRetirementBarrierState value)=>value switch{BaseSubjectRetirementBarrierState.Pending=>"pending",BaseSubjectRetirementBarrierState.Satisfied=>"satisfied",BaseSubjectRetirementBarrierState.TimedOut=>"timedOut",BaseSubjectRetirementBarrierState.Quarantined=>"quarantined",_=>"overridden"};

    private static async Task Acknowledge(HttpContext context)
    {
        PrincipalContext principal=await context.RequestServices.GetRequiredService<IBaseHttpPrincipalContextFactory>().CreateAsync(context,context.RequestAborted).ConfigureAwait(false);
        if(principal.AuthenticationState is not(PrincipalAuthenticationState.Service or PrincipalAuthenticationState.System)){await Problem(context,OperationStatus.PolicyDenied,BaseSubjectRetirementErrorCodes.Unauthorized).ConfigureAwait(false);return;}
        WireRequest? request=await ReadRequest(context).ConfigureAwait(false);if(request is null)return;
        BaseSubjectRetirementRegistry registry=context.RequestServices.GetRequiredService<BaseSubjectRetirementRegistry>();
        BaseInstalledSubjectRetirementConsumer? installed=registry.FindConsumer(request.ConsumerId,request.ConsumerVersion);
        if(installed is null||!AudienceAllows(installed.Definition.Audience,principal.AuthenticationState)
            ||(installed.Definition.Participation==BaseSubjectRetirementParticipation.AdvisoryAcknowledgement?"advisory":"required")!=request.Participation)
        {await Problem(context,OperationStatus.PolicyDenied,BaseSubjectRetirementErrorCodes.Unauthorized).ConfigureAwait(false);return;}
        BaseMutationRequestIdentity identity;
        try{byte[] fingerprint=Convert.FromBase64String(request.Identity.Fingerprint);identity=BaseMutationRequestIdentity.Create(request.Identity.Scope,request.Identity.Operation,request.Identity.IdempotencyKey,BaseMutationRequestFingerprint.Create(fingerprint));}
        catch(Exception error)when(error is ArgumentException or FormatException){await Problem(context,OperationStatus.ValidationFailed,BaseSubjectRetirementErrorCodes.ContractInvalid).ConfigureAwait(false);return;}
        if(!context.Request.Headers.TryGetValue(BaseHttpHeaders.IdempotencyKey,out var header)||header.Count!=1||header[0]!=identity.IdempotencyKey)
        {await Problem(context,OperationStatus.ValidationFailed,BaseSubjectRetirementErrorCodes.ContractInvalid).ConfigureAwait(false);return;}
        byte[] evidence;try{evidence=Decode(request.Evidence);}catch(FormatException){await Problem(context,OperationStatus.ValidationFailed,BaseSubjectRetirementErrorCodes.ContractInvalid).ConfigureAwait(false);return;}
        BaseSession session=context.RequestServices.GetRequiredService<IBaseSessionFactory>().For(principal,options=>options.ProjectId=request.ProjectId);
        IBaseSubjectRetirementRuntime runtime=context.RequestServices.GetRequiredService<IBaseSubjectRetirementRuntime>();
        BaseResult<BaseSubjectAcknowledgementResult> result=await runtime.AcknowledgeAsync(session,installed,evidence,installed.Definition.Participation,
            request.Disposition=="completed"?BaseSubjectAcknowledgementDisposition.Completed:BaseSubjectAcknowledgementDisposition.RetainedByPolicy,identity,context.RequestAborted).ConfigureAwait(false);
        if(result is BaseFailure<BaseSubjectAcknowledgementResult> failure){await Problem(context,failure.Status,failure.Error.Code).ConfigureAwait(false);return;}
        BaseSubjectAcknowledgementResult value=((BaseSuccess<BaseSubjectAcknowledgementResult>)result).Value;context.Response.StatusCode=StatusCodes.Status200OK;context.Response.ContentType="application/json; charset=utf-8";
        await using var writer=new Utf8JsonWriter(context.Response.BodyWriter);writer.WriteStartObject();writer.WriteString("outcome",value.Outcome switch{BaseSubjectRetirementMutationOutcome.Applied=>"applied",BaseSubjectRetirementMutationOutcome.Duplicate=>"duplicate",_=>"obsolete"});writer.WriteString("throughSubjectSequence",value.ThroughSubjectSequence.ToString(System.Globalization.CultureInfo.InvariantCulture));if(value.BarrierState is { } state){writer.WriteString("barrierState",state.ToString()[..1].ToLowerInvariant()+state.ToString()[1..]);writer.WriteString("barrierGeneration",value.BarrierGeneration!.Value.ToString(System.Globalization.CultureInfo.InvariantCulture));writer.WriteString("barrierChecksum",value.BarrierChecksum);}writer.WriteEndObject();await writer.FlushAsync(context.RequestAborted).ConfigureAwait(false);
    }

    private static async ValueTask<WireRequest?> ReadRequest(HttpContext context)
    {
        try{if(context.Request.ContentLength is>MaximumBodyBytes)throw new InvalidDataException();await using var bounded=new LimitedRequestBodyStream(context.Request.Body,MaximumBodyBytes);using JsonDocument document=await JsonDocument.ParseAsync(bounded,new(){AllowTrailingCommas=false,CommentHandling=JsonCommentHandling.Disallow,MaxDepth=5},context.RequestAborted).ConfigureAwait(false);JsonElement root=document.RootElement;if(root.ValueKind!=JsonValueKind.Object)throw new JsonException();Exact(root,["consumerId","consumerVersion","participation","evidence","disposition","identity","projectId"]);JsonElement id=root.GetProperty("identity");Exact(id,["scope","operation","idempotencyKey","fingerprint"]);string participation=root.GetProperty("participation").GetString()??throw new JsonException();string disposition=root.GetProperty("disposition").GetString()??throw new JsonException();string? project=root.GetProperty("projectId").ValueKind==JsonValueKind.Null?null:root.GetProperty("projectId").GetString();if(participation is not("advisory" or "required")||disposition is not("completed" or "retainedByPolicy")||project is{Length:<1 or>256})throw new JsonException();return new(root.GetProperty("consumerId").GetString()??throw new JsonException(),root.GetProperty("consumerVersion").GetInt32(),participation,root.GetProperty("evidence").GetString()??throw new JsonException(),disposition,project,new(id.GetProperty("scope").GetString()??throw new JsonException(),id.GetProperty("operation").GetString()??throw new JsonException(),id.GetProperty("idempotencyKey").GetString()??throw new JsonException(),id.GetProperty("fingerprint").GetString()??throw new JsonException()));}
        catch(Exception error)when(error is JsonException or InvalidDataException or KeyNotFoundException){await Problem(context,OperationStatus.ValidationFailed,BaseSubjectRetirementErrorCodes.ContractInvalid).ConfigureAwait(false);return null;}
    }
    private static void Exact(JsonElement value,string[] names){if(value.ValueKind!=JsonValueKind.Object)throw new JsonException();var seen=new HashSet<string>(StringComparer.Ordinal);foreach(JsonProperty property in value.EnumerateObject())if(!seen.Add(property.Name)||!names.Contains(property.Name,StringComparer.Ordinal))throw new JsonException();if(seen.Count!=names.Length)throw new JsonException();}
    private static byte[] Decode(string value)=>Decode(value,2048);
    private static byte[] Decode(string value,int maximumBytes){string padded=value.Replace('-','+').Replace('_','/').PadRight(value.Length+(4-value.Length%4)%4,'=');byte[] bytes=Convert.FromBase64String(padded);if(bytes.Length<1||bytes.Length>maximumBytes||Convert.ToBase64String(bytes).TrimEnd('=').Replace('+','-').Replace('/','_')!=value)throw new FormatException();return bytes;}
    private static string Encode(byte[] value)=>Convert.ToBase64String(value).TrimEnd('=').Replace('+','-').Replace('/','_');
    private static bool AudienceAllows(BaseSubjectLifecycleConsumerAudience audience,PrincipalAuthenticationState principal)=>audience==BaseSubjectLifecycleConsumerAudience.System?principal==PrincipalAuthenticationState.System:principal is PrincipalAuthenticationState.Service or PrincipalAuthenticationState.System;
    private static async Task Problem(HttpContext context,OperationStatus status,string code){context.Response.StatusCode=status switch{OperationStatus.ValidationFailed=>400,OperationStatus.PolicyDenied=>403,OperationStatus.Conflict=>409,OperationStatus.CapabilityUnavailable=>424,_=>500};context.Response.ContentType="application/problem+json";await using var writer=new Utf8JsonWriter(context.Response.BodyWriter);writer.WriteStartObject();writer.WriteString("title","Subject retirement operation failed.");writer.WriteNumber("status",context.Response.StatusCode);writer.WriteString("code",code);writer.WriteEndObject();await writer.FlushAsync(context.RequestAborted).ConfigureAwait(false);}
    private sealed record WireRequest(string ConsumerId,int ConsumerVersion,string Participation,string Evidence,string Disposition,string? ProjectId,WireIdentity Identity);
    private sealed record WireIdentity(string Scope,string Operation,string IdempotencyKey,string Fingerprint);
}
