<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>HPD-ML-DeepLearning</PackageId>
    <TargetFramework>net11.0</TargetFramework>
    <TargetFrameworks></TargetFrameworks>
    <LangVersion>preview</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);SYSLIB5001</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="HPD.ML.DeepLearning.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../HPD.ML.Core/HPD.ML.Core.csproj" />
    <ProjectReference Include="../HPD.ML.Backends.Abstractions/HPD.ML.Backends.Abstractions.csproj" />
    <ProjectReference Include="../../../../../../../../HPD-Math-Framework/Helium/src/Helium.Train/Helium.Train.csproj" />
  </ItemGroup>

</Project>
