using System.Text.Json;
using Microsoft.Extensions.AI;
using HPD.Agent.Middleware;
using HPD.Agent.Secrets;

namespace HPD.Agent;

/// <summary>
/// Factory for creating toolharness instances without reflection.
/// Contains direct delegate references to generated registration code.
/// Generated by HPDToolSourceGenerator per assembly.
/// </summary>
/// <remarks>
/// <para><b>Design Philosophy:</b></para>
/// <para>
/// This record is the key to eliminating reflection in hot paths:
/// </para>
/// <list type="bullet">
/// <item>CreateInstance: Direct constructor call (no Activator.CreateInstance!)</item>
/// <item>CreateFunctions: Direct delegate to generated CreateToolHarness method</item>
/// <item>GetReferencedToolHarnesses: Direct delegate to generated GetReferencedToolHarnesses method</item>
/// <item>GetReferencedFunctions: Direct delegate to generated GetReferencedFunctions method</item>
/// </list>
///
/// <para>
/// The source generator creates a ToolHarnessRegistry.g.cs file that initializes
/// an array of ToolHarnessFactory records with these delegates, enabling AOT-compatible
/// toolharness instantiation and function creation.
/// </para>
/// </remarks>
public record ToolHarnessFactory(
    // ========== EXISTING FIELDS ==========

    /// <summary>
    /// ToolHarness name (e.g., "MathToolHarness", "SearchToolHarness").
    /// Always the class name (CustomName support removed).
    /// </summary>
    string Name,

    /// <summary>
    /// ToolHarness type (for type checking and compatibility)
    /// </summary>
    Type ToolHarnessType,

    /// <summary>
    /// Direct constructor call delegate - AOT-safe, no Activator.CreateInstance
    /// Example: () => new MathToolHarness()
    /// </summary>
    Func<object> CreateInstance,

    /// <summary>
    /// Direct delegate to generated CreateToolHarness method.
    /// Example: (instance, ctx, serialization) => MathToolHarnessRegistration.CreateToolHarness((MathToolHarness)instance, ctx, serialization)
    /// </summary>
    Func<object, IToolMetadata?, HPDToolSerializationOptions?, List<AIFunction>> CreateFunctions,

    /// <summary>
    /// Direct delegate to generated GetReferencedToolHarnesses method.
    /// Returns toolharness names that this toolharness's skills depend on.
    /// </summary>
    Func<string[]> GetReferencedToolHarnesses,

    /// <summary>
    /// Direct delegate to generated GetReferencedFunctions method.
    /// Returns map of toolharness name -> function names for selective registration.
    /// </summary>
    Func<Dictionary<string, string[]>> GetReferencedFunctions,

    // ========== NEW: COLLAPSING METADATA (from [Collapse] attribute) ==========

    /// <summary>
    /// Whether this toolharness has a description (from [Collapse("description")]).
    /// Description presence = collapsible (functions hidden behind container).
    /// </summary>
    bool HasDescription = false,

    /// <summary>
    /// Description from [Collapse] attribute (if present).
    /// Used for the container function description when collapsed.
    /// </summary>
    string? Description = null,

    /// <summary>
    /// Instructions returned as FUNCTION RESULT when container is expanded.
    /// From [Collapse(FunctionResult = "...")] or method reference.
    /// </summary>
    string? FunctionResult = null,

    /// <summary>
    /// Instructions injected into SYSTEM PROMPT while expanded.
    /// From [Collapse(SystemPrompt = "...")] or method reference.
    /// </summary>
    string? SystemPrompt = null,

    // ========== NEW: SECRETS-BASED INSTANTIATION ==========

    /// <summary>
    /// Delegate to create a toolharness instance from an ISecretResolver.
    /// Generated when the toolharness has a constructor whose only parameter is ISecretResolver.
    /// Example: secrets => new StripeToolHarness(secrets)
    /// Null if toolharness has no ISecretResolver-only constructor.
    /// </summary>
    Func<ISecretResolver, object>? CreateWithSecrets = null,

    // ========== NEW: CONFIG-BASED INSTANTIATION ==========

    /// <summary>
    /// Type of the config constructor parameter, if detected.
    /// Example: typeof(SearchToolHarnessConfig) for SearchToolHarness(SearchToolHarnessConfig config).
    /// Null if toolharness has no config constructor.
    /// </summary>
    Type? ConfigType = null,

    /// <summary>
    /// Delegate to create a toolharness instance from JSON config.
    /// Example: json => new SearchToolHarness(json.Deserialize&lt;SearchToolHarnessConfig&gt;()!)
    /// Null if toolharness has no config constructor.
    /// </summary>
    Func<JsonElement, object>? CreateFromConfig = null,

    // ========== NEW: METADATA DESERIALIZATION ==========

    /// <summary>
    /// Metadata type from [AIFunction&lt;TMetadata&gt;] on toolharness methods.
    /// Used to deserialize ToolHarnessReference.Metadata at resolution time.
    /// Example: typeof(SearchContext) for [AIFunction&lt;SearchContext&gt;].
    /// Null if toolharness methods don't use typed metadata.
    /// </summary>
    Type? MetadataType = null,

    /// <summary>
    /// Delegate to deserialize typed metadata from JSON without reflection.
    /// Generated when toolharness functions use [AIFunction&lt;TMetadata&gt;].
    /// </summary>
    Func<JsonElement, IToolMetadata?>? DeserializeMetadata = null,

    // ========== NEW: SELECTIVE FUNCTION REGISTRATION ==========

    /// <summary>
    /// All function names in this toolharness for selective registration.
    /// Example: new[] { "WebSearch", "ImageSearch", "NewsSearch" }
    /// Used to validate ToolHarnessReference.Functions at resolution time.
    /// </summary>
    string[]? FunctionNames = null,

    // ========== NEW: MCP SERVER SUPPORT ==========

    /// <summary>
    /// Whether this toolharness has [McpServer] methods.
    /// When true, the generated Registration class has a static MCPServers property
    /// containing McpServerSource descriptors that AgentBuilder processes at build time.
    /// </summary>
    bool HasMcpServers = false,

    /// <summary>
    /// Delegate to collect MCP server registrations from [McpServer] methods.
    /// Null when the toolharness has no MCP servers.
    /// </summary>
    Action<object, Action<McpServerSource>>? CollectMcpServers = null,

    // ========== NEW: OPENAPI SOURCE SUPPORT ==========

    /// <summary>
    /// Delegate to collect OpenAPI source registrations from [OpenApi] methods.
    /// Null when toolharness has no [OpenApi] methods.
    ///
    /// Signature: (instance, collector) where collector is Action&lt;string, object, string&gt;:
    ///   - string: source name (Prefix ?? method name)
    ///   - object: OpenApiConfig returned by the [OpenApi] method (cast to OpenApiConfig in HPD-Agent.OpenApi)
    ///   - string: parent toolharness name
    ///
    /// Config is passed as object to avoid ToolHarnessFactory taking a dependency on HPD-Agent.OpenApi.
    /// Cast to OpenApiConfig happens inside OpenApiLoader.LoadAllAsync.
    /// ISecretResolver is available via constructor injection — no threading through this delegate.
    /// </summary>
    Action<object, Action<string, object, string>>? CollectOpenApiSources = null,

    // ========== HARNESS-SCOPED MIDDLEWARE (015) ==========

    /// <summary>
    /// AOT-safe factory delegates for middleware declared in <c>[Collapse(Middlewares = [...])]</c>
    /// that have a public parameterless constructor.
    /// Each delegate is a direct constructor call — <c>static () =&gt; new ConcreteType()</c> — emitted by
    /// <c>HPDToolSourceGenerator</c> into <c>ToolHarnessRegistry.g.cs</c>.
    /// Null when the toolharness declares no parameterless-constructor scoped middlewares.
    /// Instances are created at container expansion time and live for the duration of that expansion.
    /// </summary>
    IReadOnlyList<Func<IAgentMiddleware>>? CollapseMiddlewareFactories = null,

    /// <summary>
    /// AOT-safe config-constructor factory delegates for middleware declared in
    /// <c>[Collapse(Middlewares = [...])]</c> that have a single-parameter config constructor.
    /// Each entry carries the middleware's simple type name (for matching against
    /// <c>ToolHarnessReference.MiddlewareConfigs</c> keys) and a delegate that accepts a
    /// <c>JsonElement</c> and returns an instantiated middleware.
    /// Emitted by <c>HPDToolSourceGenerator</c> into <c>ToolHarnessRegistry.g.cs</c>.
    /// Null when the toolharness declares no config-constructor scoped middlewares.
    /// </summary>
    IReadOnlyList<CollapseMiddlewareConfigFactory>? CollapseMiddlewareConfigFactories = null
);

/// <summary>
/// Entry for a config-constructor toolharness-scoped middleware factory .
/// Carries the middleware's simple type name for matching against
/// <c>ToolHarnessReference.MiddlewareConfigs</c> map keys, and the factory delegate.
/// </summary>
/// <param name="MiddlewareTypeName">
/// Simple (unqualified) class name of the middleware type, e.g. <c>"DbRateLimitMiddleware"</c>.
/// Used to match entries in <c>ToolHarnessReference.MiddlewareConfigs</c>.
/// </param>
/// <param name="Factory">
/// AOT-safe direct constructor delegate — e.g.
/// <c>static json => new DbRateLimitMiddleware(json.Deserialize&lt;DbRateLimitConfig&gt;()!)</c>.
/// </param>
public record CollapseMiddlewareConfigFactory(
    string MiddlewareTypeName,
    Func<System.Text.Json.JsonElement, IAgentMiddleware> Factory
);
