[global]
type=global
user_agent=HPD-Audio-PBX-Qualification

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060
external_media_address=10.0.0.192
external_signaling_address=10.0.0.192

[hpd-anonymous]
type=endpoint
context=from-hpd
disallow=all
allow=ulaw
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes

[hpd-anonymous]
type=identify
endpoint=hpd-anonymous
match=0.0.0.0/0
